- Documentation/install.md
Now that we merged necessary PRs in lokomotive, we can skip several steps in the installation instructions.
> Documentation: remove unnecessary instructions

- Documentation/architecture/k8s.svg
- Documentation/install.md
- deploy/ds-gadget.yaml
- gadget-ds/files/gadget-node-install.sh
This eliminates the manual "inspektor-gadget install" step.
> Run install script on gadget pod startup by default

- Documentation/install.md
The KVM platform is maybe the most accessible option to try Inspektor Gadget because it does not require an AWS account.
> docs: Mention Lokomotive on libvirt as supported platform

- .github/workflows/inspektor-gadget.yml
When pushing a tag starting with 'v', this should automatically create a release. The release has `draft=true`, so it can be tested before it is announced.
> GitHub Actions: prepare releases

- README.md
Incorrect - `inspektor-gadget deploy | kubectl apply -f`
Correct - `kubectl gadget deploy | kubectl apply -f`
Correct - `kubectl-gadget deploy | kubectl apply -f`
Signed-off-by: Imran Pochi <imran@kinvolk.io>
> Correct name of the inspecktor-gadget binary in installation step

- Documentation/demo-bindsnoop.md
- README.md
- cmd/inspektor-gadget/cmd/bcck8s.go
- gadget-ds/bcc.Dockerfile
- gadget-ds/files/bcck8s/bcc-wrapper.sh
```
$ inspektor-gadget tcpbind --label run=nginx-app
Node numbers: 0 = ip-10-0-1-49 1 = ip-10-0-15-182 2 = ip-10-0-19-78
[ 1] Tracing binds ... Hit Ctrl-C to end
[ 1]   PID COMM         IP ADDR            PORT   OPTS IF
[ 2] Tracing binds ... Hit Ctrl-C to end
[ 2]   PID COMM         IP ADDR            PORT   OPTS IF
[ 0] Tracing binds ... Hit Ctrl-C to end
[ 0]   PID COMM         IP ADDR            PORT   OPTS IF
[ 1]  6991 nginx        4  0.0.0.0            80 ...R.  0
```
The nginx line is printed when starting nginx:
```
$ kubectl run --image=nginx nginx-app --port=80
kubectl run --generator=deployment/apps.v1 is DEPRECATED and will be removed in a future version. Use kubectl run --generator=run-pod/v1 or kubectl create instead.
deployment.apps/nginx-app created
```
Fixes …
> Add gadget bindsnoop

- Documentation/demo-network-policy.md
- Documentation/examples/disable-psp-demo.yaml
- Makefile
- README.md
- cmd/inspektor-gadget/cmd/bcck8s.go
- cmd/inspektor-gadget/cmd/networkpolicyadvisor.go
- cmd/networkpolicyadvisor/main.go
- gadget-ds/files/bcck8s/bcc-wrapper.sh
- gadget-ds/gadget.Dockerfile
- go.mod
- go.sum
- pkg/networkpolicy/networkpolicy.go
- pkg/networkpolicy/types/event.go
This uses https://github.com/weaveworks/tcptracer-bpf to know about new connections in the selected namespaces:
```
$ inspektor-gadget network-policy monitor --namespaces demo --output ./networktrace.log
```
While `inspektor-gadget` is running, I deploy a microservice application ([kubernetes-manifests.yaml](https://github.com/GoogleCloudPlatform/microservices-demo/blob/master/release/kubernetes-manifests.yaml)): 
```
kubectl apply -f kubernetes-manifests.yaml -n demo
```
When the microservice application runs, `inspektor-gadget` starts to detect TCP connections:
```
{"type":"connect","remote_kind":"svc","port":3550,"local_pod_namespace":"demo","local_pod_name":"frontend-788f7bdc86-mtc6r","local_pod_owner":"frontend","local_pod_labels":{"app":"frontend","pod-template-hash":"788f7bdc86"},"r …
```
> Add Network Policy Advisor gadget

- tools/image-tag
If the current branch is master the tag should be "latest", otherwise the
deployment will fail because there is not such "master" tag.
> tools: Fix image tag generation

- cmd/inspektor-gadget/cmd/bcck8s.go
0549db2e37f3 ("Filter first bcc tool lines and annotate nodes") introduced a way
to skip printing the first line of the bcc tools as it is printed once per node.
That commit had a bug and was partially reverted by
6a0116f077d3 ("Workaround for the output disappearing"). This commit fixes the
logic in the original commit by using a pointer receiver notation in the Write()
method of postProcess.
Fixes https://github.com/kinvolk/inspektor-gadget/issues/33.
> Fix first line print logic

- pkg/networkpolicy/networkpolicy.go
Sort policies by name so they are easier to understand by users. It also fixes
a random failure in one test because the order of the generated policies was
not always the same.
> pkg/networkpolicy: sort policies by name

- cmd/kubectl-gadget/deploy.go
- gadget-container/gadgettracermanager/main.go
- gadget-container/ocihookgadget/main.go
- pkg/gadgettracermanager/containerutils/containerutils.go
- pkg/gadgettracermanager/gadgettracermanager.go
- pkg/gadgettracermanager/initialcontainers/initialcontainers.go
The Gadget Tracer Manager currently only finds out about new containers via the OCI PreStart hook. If a container was started before Inspektor Gadget is deployed, then it will not be found and gadgets won't be able to get events for that container.
This patch adds support to find out about those containers.
Functions from ocihookgadget to read cgroup paths and cgroup ids are moved to a new package pkg/gadgettracermanager/containerutils.
> Find containers started before Inspektor Gadget

- cmd/kubectl-gadget/deploy.go
- gadget-container/cleanup.sh
- gadget-container/gadget-from-local-bin.Dockerfile
- gadget-container/gadget.Dockerfile
Add a cleanup script using the preStop hook to remove all the files installed
in the host by Inspektor Gadget.
> Cleanup installed files

- .github/workflows/inspektor-gadget.yml
- Documentation/install.md
- gadget-container/Makefile
- gadget-container/gadget-from-local-bin.Dockerfile
Also, add a build smoke-test to check that `gadget-from-local-bin.Dockerfile` is still buildable.
> Fix minikube dev image

- pkg/gadgettracermanager/initialcontainers/initialcontainers.go
There is no point of checking the pid of containers that are not running yet, or that have terminated. This causes unnecessary errors.
> Initial containers: only check pid of running containers

- gadget-container/gadgets/networkpolicyadvisor/main.go
The Network Policy Advisor receives TCP connection tuples with IP
addresses from the BPF program. In order to match them with Kubernetes
pods and services, it needs to make two API calls to the kube-apiserver
to get the IP of the pods and the IP of the services.
Before this patch, the kube-apiserver was called for each new TCP
connection. This takes too much CPU and it is sometimes unable to handle
the connections fast enough.
With this patch, it uses a ticker and it can only call the API server
maximum every second and it caches the result for a batch of TCP
connections. It takes care of making the API calls after receiving the
TCP connection to avoid the race of evaluating a connection from a new
pod based on a old cache of the pod IPs.
> networkpolicyadvisor: batch events to reduce api calls

- cmd/kubectl-gadget/traceloop.go
- cmd/kubectl-gadget/utils.go
- gadget-container/gadget.Dockerfile
```
-A, --all-namespaces     if present, list the traces across all namespaces.
-f, --full               show all fields without truncating
-n, --namespace string   only show traces in the specified namespace.
--no-headers         don't print headers.
```
> traceloop list: add presentation options: namespace filters, headers

- Documentation/install.md
- cmd/kubectl-gadget/deploy.go
- gadget-container/cleanup.sh
- gadget-container/entrypoint.sh
- pkg/gadgettracermanager/containerutils/containerutils.go
Improve runc hooks mode support
- Rename the option to 'runc-hooks-mode'
- Make 'auto' mode detect the config if possible
- Add a 'flatcar_edge' mode
- Add some documentation
- Clean up changes in /etc/ls.so.preload when uninstalling IG
The target of this PR is to add changes to https://github.com/kinvolk/inspektor-gadget/pull/58, not directly the master branch.
> Improve runc hooks mode

- cmd/kubectl-gadget/bcck8s.go
- cmd/kubectl-gadget/bcck8s_test.go
The postProcessor is a class that wraps an io.Writer object to add a prefix
to all the lines that are printed to the terminal, it's used to print the
node number before each line.
The current logic instroduces in some cases a line break making it difficult to
read. The following is a snippet of the opensnoop gadget:
...
[ 0] 19651  sh                  3   0 /etc/passwd
[ 0] 19651  sh                  3   0
[ 0] /etc/passwd
...
This problem happens because the Write() function doesn't receive a full string
in all the cases, for instance in the last example it received something like:
Write("19651  sh                  3   0 /etc/passwd\n")
Write("19651  sh                  3   0")
Write("/etc/passwd\n")
This commit fixes the logic by taking that case into consideration, avoiding
to print …
> cmd/inspektor-gadget: Fix terminal output

- .github/workflows/inspektor-gadget.yml
- .gitignore
- Makefile
- cmd/kubectl-gadget/bcck8s.go
- cmd/kubectl-gadget/traceloop.go
- gadget-container/gadgettracermanager/main.go
- Add kubectl-gadget executables to .gitignore
- traceloop list: improve duration display in status
- bcc gadgets: check --label flag before using it
Extract some commits originally added in https://github.com/kinvolk/inspektor-gadget/pull/76 to make that review easier.
> Miscellaneous fixes

- cmd/kubectl-gadget/bcck8s.go
- gadget-container/gadgets/networkpolicyadvisor/main.go
- pkg/k8sutil/client.go
- bcck8s: Add line break after printing the nodes names
- gadgets/networkpolicyadvisor: Use k8sutil to create k8s client set
> Two small fixes

- gadget-container/gadget-from-local-bin.Dockerfile
- gadget-container/gadget.Dockerfile
traceloop includes the fix "Don't print an error on empty reads"
bcc includes filtering by mount namespace
> gadget container: update dependencies (bcc and traceloop)

- gadget-container/entrypoint.sh
- gadget-container/ocihookgadget/main.go
- gadget-container/ocihookgadget/runc-hook-poststop.sh
- gadget-container/ocihookgadget/runc-hook-prestart.sh
- pkg/gadgettracermanager/initialcontainers/initialcontainers.go
There are 2 locations where IG fetches the list of pods from the API
server:
- the oci hooks
- during initialisation of the gadgettracermanager
In both cases, IG does not need to get all the pods but only the local
pods. Use a field selector to filter pods.
> Only fetch local pods

- Documentation/install.md
- README.md
To be merged once https://github.com/kubernetes-sigs/krew-index/pull/628 is merged.
> Docs: Add krew install instructions

- pkg/k8sutil/client.go
Symptoms from integration tests:
```
--- FAIL: TestTraceloop (89.38s)
--- FAIL: TestTraceloop/Check_traceloop_list (5.01s)
traceloop_test.go:101: Command: sleep 5 ; $KUBECTL_GADGET traceloop list -n test-traceloop --no-headers | grep multiplication | awk '{print $1" "$6}'
make: *** [integration-tests] Error 1
traceloop_test.go:105: Command returned:
time="2020-06-03T02:11:36Z" level=fatal msg="Error in creating setting up Kubernetes client: \"unable to load in-cluster configuration, KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT must be defined\"" args="[]" command="kubectl-gadget traceloop list"
```
> Fix kubeconfig sources

- cmd/kubectl-gadget/deploy.go
- gadget-container/gadget-from-local-bin.Dockerfile
- gadget-container/gadget.Dockerfile
- gadget-container/gadgets/bcck8s/bcc-wrapper.sh
- pkg/gadgettracermanager/containerutils/containerutils.go
- pkg/gadgettracermanager/k8s/k8s.go
This PR fixes some problems I found while experimenting with containerd on Ubuntu 20.04. 
- Kernel headers missing
- containerd runtime not considered
- Bad handling of wrong cgroupsv2 path
> Fixes for containerd and Ubuntu

- .github/workflows/inspektor-gadget.yml
- integration/Dockerfile
- integration/Makefile
- integration/gadget-integration-tests-job.yaml
Then, Kubernetes distributions will be able to run the tests from Inspektor Gadget with the following commands, without installing kubectl-gadget or recompiling:
```
wget https://github.com/kinvolk/inspektor-gadget/releases/download/v0.2.0/gadget-integration-tests-job.yaml
kubectl apply -f gadget-integration-tests-job.yaml
kubectl logs -n gadget-test -l job-name=gadget-test
```
> Build and publish container image for integration tests

- cmd/kubectl-gadget/bcck8s.go
- pkg/gadgettracermanager/gadgettracermanager.go
Symptoms:
```
kubectl gadget execsnoop --namespace test
[E0] 2020/06/08 10:35:35 rpc error: code = Unknown desc = tracer id "20200608123534-52fdfc072182" already exists
```
> Fix non-random tracer id

- gadget-container/entrypoint.sh
- gadget-container/gadget-from-local-bin.Dockerfile
- gadget-container/gadget.Dockerfile
Ubuntu has /usr/src with the kernel headers but on Flatcar Container Linux, this directory does not exist and the kernel headers are located in /lib/modules/$(uname -r) directly.
Attempting to mount /usr/src from the host would cause Docker to attempt to create that directory but this does not work when the host /usr is read-only.
This patch adds access to /usr/src with a symbolic link, so it works both for Linux distributions with and without /usr/src.
----
Symptoms from a GitHub action (https://github.com/kinvolk/inspektor-gadget/pull/109#issuecomment-640650397):
```
[E0] xz: (stdin): Read error: No such device
[E0] tar: Unexpected EOF in archive
[E0] tar: Unexpected EOF in archive
[E0] tar: Error is not recoverable: exiting now
[E0] rmmod: ERROR: Module kheaders is not currently loaded …
```
> Add access to /usr/src without direct bind-mount

- cmd/kubectl-gadget/bcck8s.go
The current description for tcpconnect seems wrong: "Suggest Kubernetes Network Policies", that's not what the bcc tcpconnect tool does.
The one for opensnoop looks weird compared to the others: "Trace files" vs "Trace IPv4 and IPv6 bind() system calls".
This change fixes tcpconnect to match the description from the bcc tools and the opensnoop one to be more similar to the bindsnoop one.
> Fix short descs for opensnoop and tcpconnect

- gadget-container/entrypoint.sh
- gadget-container/ocihookgadget/main.go
- gadget-container/ocihookgadget/runc-hook-poststop.sh
- gadget-container/ocihookgadget/runc-hook-prestart.sh
The parameter is not needed anymore after 068c46f90270eaf0f4aec3ba867754479abbeb1d.
> ocihookgadget: Remove unused node parameter

- .github/workflows/inspektor-gadget.yml
Upgrade `manusa/actions-setup-minikube` to the latest version.
Removes the following warnings caused by [CVE-2020-15228](https://github.com/actions/toolkit/security/advisories/GHSA-mfwh-5m23-j46w):
```
Warning: The `set-env` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
Warning: The `add-path` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
```
Relates to:
- https://github.com/manusa/actions-setup-minikube/issues/22
- …
> chore: Upgrade actions-setup-minikube to v2.0.1

- .github/workflows/inspektor-gadget.yml
- .gitignore
- .krew.yaml
Use the [krew-release-bot](https://github.com/rajatjindal/krew-release-bot) to automate the plugin update process. 
The main difference is that the releases created are not draft anymore, so pushing a tag to the repo will create a release and update it on the krew-index automatically.
> Automate krew plugin version update

- pkg/gadgets/networkpolicy/networkpolicy.go
Symptoms:
```
pkg/gadgets/networkpolicy/networkpolicy.go:143:21: conversion from uint16 to string yields a string of one rune, not a string of digits (did you mean fmt.Sprint(x)?)
```
See:
https://github.com/golang/go/issues/32479
Signed-off-by: Alban Crequy <alban@kinvolk.io>
> Fix string conversion error

- pkg/gadgettracermanager/gadgettracermanager.go
Somehow I managed to break this in a previous commit some months ago.
It was probably not detected before because it doesn't affect the
pod informer mechanism that uses the K8s api server to get the list
of pods.
Deploy Inspektor Gadget using `--runc-hooks-mode` different to `auto` or `podinformer` in a cluster with some existing pods and check that those are correctly added to the list of containers in the gadget tracer manager by executing `gadgettracermanager -dump` in the gadget pod.
> gadget tracer manager: fix logic to get existing containers

- .github/workflows/inspektor-gadget.yml
Previous version doesn't work with Ubuntu 20.04.2 that is now being
used.
It has been failing since a while but we haven't noticed it -> https://github.com/kinvolk/inspektor-gadget/actions?query=branch%3Amaster+
> GHA: Update actions-setup-minikube to 2.4.2

- gadget-local.Dockerfile
- gadget.Dockerfile
This PR changes the directory where `bcc-wrapper.sh` is installed because gadgets are looking for it in `/opt/bcck8s/` while it is being installed in `/opt/`. For instance, networkpolicyadvisor and bcck8s in the following two lines (there are others):
https://github.com/kinvolk/inspektor-gadget/blob/0c92eed86b8f30c7533c4899d7203546de7aff41/cmd/kubectl-gadget/bcck8s.go#L332
https://github.com/kinvolk/inspektor-gadget/blob/0c92eed86b8f30c7533c4899d7203546de7aff41/cmd/kubectl-gadget/networkpolicyadvisor.go#L149
This issue prevents users to properly gadgets with the following error:
```
Node numbers: 0 = blanquicet
[E0] /bin/sh: 1: exec: /opt/bcck8s/bcc-wrapper.sh: not found
```
> gadget-dockerfiles: Change bcc-wrapper.sh installation directory

- go.mod
This PR updates pretty module to version 0.2.1 because it is required by ebpf version 0.4.0 which was introduced in 320f8f01
(Implement support for Node Resource Interface).
Current compilation error:
```
$ make gadget-container-local
...
mkdir -p bin
GO111MODULE=on CGO_ENABLED=1 GOOS=linux go build \
-o bin/ocihookgadget \
./hooks/oci/main.go
go: github.com/kr/pretty@v0.2.1: missing go.sum entry; to add it:
go mod download github.com/kr/pretty
make[1]: *** [Makefile:29: ocihookgadget] Error 1
```
After debugging, it was possible to find that ebpf v0.4.0 is asking for pretty v0.2.1:
```
$ make gadget-container-local
...
mkdir -p bin
GO111MODULE=on CGO_ENABLED=1 GOOS=linux go build \
-o bin/ocihookgadget \
./hooks/oci/main.go
go: github.com/cilium/ebpf@v0.4.0 requires …
```
> Update go.mod with newer pretty version required by ebpf

- cmd/kubectl-gadget/deploy.go
- gadget-container/gadgettracermanager/main.go
This PR implements liveness probe for the GadgetTracerManager using the [grpc_health_v1 package](https://pkg.go.dev/google.golang.org/grpc/health/grpc_health_v1).
Given that Kubernetes does not support gRPC probes, a gRPC client is called by command to check if the container is alive and healthy. The client was actually developed inside the GadgetTracerManager itself and can be launched by using parameter `-liveness`. It will return 0 if status [SERVING](https://pkg.go.dev/google.golang.org/grpc@v1.33.2/health/grpc_health_v1#HealthCheckResponse_SERVING) is received from server and 1 otherwise. Notice that server and client use the service created by default with empty string name ("") and status [SERVING](https://pkg.go.dev/google.golang.org/grpc@v1.33.2/health/grpc_health_v1#HealthCheckRe …
> gadget-container: Add liveness probe

- gadget-local.Dockerfile
- gadget.Dockerfile
Currently, the BCC container image used for InspektorGadget is based on kinvolk/bcc@5fed2a9 (v0.14.0) but changes introduced in torvalds/linux@97e4910232fa1f81e806aa60c25a0450276d99a2 (v5.12) make BCC-based gadgets to start complaining about macros redefinition when compiling BPF programs.
Issue was already solved in BCC upstream with iovisor/bcc#3391. Therefore, this commit updates the BCC container image to be used by InspektorGadget to one based on kinvolk/bcc@4e8e8c6 (v0.20.0) which includes the fix.
This commit fixes issue #182.
Please notice that the size of the final InspektorGadget container image is passing from ~180MB to ~320MB. This increment is coming from BCC upstream where container image size passed from ~110MB (v0.14.0) to ~250MB (v0.20.0). Check container registries:
- …
> Update BCC container image

- .dockerignore
- gadget.Dockerfile
- Cache go modules in a Docker layer to avoid downloading them at each
build
- Only copy necessary files in the build context
This patch uses the ideas from the following article:
https://medium.com/@pliutau/docker-and-go-modules-4265894f9fc
-----
- Compile everything: `make`
- Test
- Make some changes in some Go code of the gadget container.
- Recompile: `make`. Thanks to this patch, the Go modules will not be downloaded again.
- Make some changes unrelated to the gadget container (e.g. `docs/install.md`).
- Recompile: `make`. Thanks to this patch, the gadget container will not be recompiled.
> Dockerfile: faster builds

- docs/CONTRIBUTING.md
- gadget-local.Dockerfile
- gadget.Dockerfile
Add new section in `docs/CONTRIBUTING.md` to describe how to update BCC from upstream.
I also put the building notes in a separate section because they are actually related to both, client and image compilation.
> Describe how to update BCC on gadget container image

- .krew.yaml
- tools/image-tag
The default branch name was `master` and I renamed it to `main`. This PR adjusts the code to this new name.
For more background, see:
https://github.com/github/renaming#renaming-existing-branches
> Update branch name to main

- Makefile
Unfortunately, minikube-cache and minikube-image have bugs in older
versions. And new versions of minikube don't support all eBPF
features. So we have to keep "docker-save|docker-load" for now.
> Makefile: workaround minikube cache issues

- .github/workflows/inspektor-gadget.yml
Installing libbpf-dev used to take 20 seconds. Additionally, this causes
unnecessary network traffic to Ubuntu package repositories and PPA
repositories. This patch optimizes that by using the GitHub action
cache.
After this patch, checking the cache takes less than 1 second and
installing from the cache takes 1 second.
Technique inspired from:
https://stackoverflow.com/questions/59269850/caching-apt-packages-in-github-actions-workflow
-----
Using the technique from the documentation:
https://github.com/actions/cache/blob/main/examples.md#go---modules
This is useful for building the kubectl plugin ("make kubectl-gadget")
and the unit tests ("make test"): those are built directly on the Ubuntu
host.
Before this patch:
- make kubectl-gadget: 2m 42s (test 1) and 2m 18s (test 2)
- make test: …
> GitHub action: cache Go mods and deb packages

- .github/workflows/inspektor-gadget.yml
- Makefile
https://github.com/kinvolk/inspektor-gadget/pull/164/commits/2ef22b70e5af388ea9f1c396962be729e73418ab broke the pushing of the `latest` tag of the container image. It happened because it defined `IMAGE_TAG` on github actions, then `tools/image-tag` returned here https://github.com/kinvolk/inspektor-gadget/blob/b1dac15b475b3d4fe572a3f3087e345491bb9607/tools/image-tag#L10 without running the conditional to set IMAGE_TAG to latest when the branch is main. 
This commit fixes that problem taking into consideration that case directly in the github actions workflow. 
Please note that `tools/image-tag` can't be used directly in GHA because the repo is in "detached HEAD" status when it's run and hence it'll always return `HEAD`.
> GHA: Fix pushing latest container image

- .github/workflows/inspektor-gadget.yml
Without this patch, the step "Build gadget container" takes 4m 10s.
With this patch, it takes as little as 11s if there was no changes and
all the layers were cached.
Inspired by:
https://evilmartians.com/chronicles/build-images-on-github-actions-with-docker-layer-caching#building-a-single-stage-dockerfile
> GitHub action: cache Docker layers

- pkg/gadgettracermanager/gadgettracermanager.go
- pkg/gadgettracermanager/k8s/k8s.go
Sometimes, the container runtime says the pid of the container is zero:
```
Skip pod kube-system/gadget-prm95: cannot find cgroup path: cannot parse cgroup: open /proc/0/cgroup: no such file or directory
```
In this case, don't try to read /proc/0/cgroup but return an error message early.
The OCI Container Runtime specification says that the pid is required when the state of the container is 'created' or 'running' but not when it is 'creating' or 'stopped'.
Double "limit":
```
failed to increase limit memlock limit: %w
```
Typo reported by @marga-kinvolk
> Fix a couple of error messages

- go.mod
- go.sum
cilium/ebpf commit [f7c00a7b0e39](https://github.com/cilium/ebpf/commit/f7c00a7b0e39904bf62aa83910b55dd6c82fd834) ("btf: Add support for BTF_KIND_FLOAT") fixes support for Linux 5.13.
This is necessary for the new gadgets coming up:
- Seccomp Policy Advisor
- Process Collector
> go.mod: update cilium/ebpf to include fix for Linux 5.13

- cmd/kubectl-gadget/bcck8s.go
- cmd/kubectl-gadget/bcck8s_test.go
- gadget.Dockerfile
This PR extends the gadgets to print information about the pod & container where the event happened. 
The gadget tracer manager creates an eBPF map where it saves all the details of the container. The different gadgets then perform a lookup in this map to get the information about the container and print it. This PR also changes how the node name is printed, now the full name (instead of just an integer is printed). 
Example of the output for the execsnoop gadget
```
$ ./kubectl-gadget-linux-amd64 execsnoop 
NODE             NAMESPACE        PODNAME          CONTAINERNAME   PCOMM            PID    PPID   RET ARGS
127.0.0.1        default          pod2             pod2            ping             227616 53305    0 /bin/ping 8.8.8.8
127.0.0.1        default          pod2             pod2 …
```
> Extend gadgets to print container & pod information

- pkg/gadgettracermanager/gadgettracermanager.go
- pkg/gadgettracermanager/gadgettracermanager_test.go
GadgetTracerManager is refactored so it's possible to create an instance
that will not do any privileged operations like using BPF maps.
Then, it's possible to add unit tests.
> refactor gadgettracermanager and add unit tests

- pkg/controllers/trace_controller.go
- pkg/controllers/trace_controller_test.go
- pkg/gadgets/biolatency/gadget.go
- pkg/gadgets/interface.go
- pkg/gadgets/networkpolicy/gadget.go
- pkg/gadgettracermanager/gadgettracermanager.go
- pkg/gadgettracermanager/gadgettracermanager_test.go
Before this patch, the process gadgettracermanager started two main independent components:
1. GadgetTracerManager, the gRPC server
2. TraceReconciler, a Controller Manager for the Trace custom resource
The TraceReconciler calls methods on TraceFactory and Trace interfaces.  But sometimes, a Trace needs to do a lookup on the GadgetTracerManager to match a mntns and a container.
This patch passes a GadgetTracerManager reference to the Trace.Operation() method, so it can do lookups. The reference is not passed directly but via a Resolver interface, so it limits the API exposed to gadgets.
The seccomp PR #208 will use this.
```
make test
```
> New Resolver interface for gadgets to call back the GadgetTracerManager

- gadget-container/gadgettracermanager/controller.go
- pkg/gadgets/helpers.go
- pkg/gadgets/process-collector/gadget.go
- pkg/gadgets/process-collector/tracer/bpf/Makefile
- pkg/gadgets/process-collector/tracer/bpf/process-collector.c
- pkg/gadgets/process-collector/tracer/embed-ebpf.go
- pkg/gadgets/process-collector/tracer/embed-none.go
- pkg/gadgets/process-collector/tracer/tracer.go
- pkg/resources/samples/trace-process-collector.yaml
Add a new gadget that gather the list of all processes enriched with container metadata.
This is implemented with BPF iterators, a new feature of Linux 5.8. For an introduction to BPF iterators, see:
https://devconfcz2021.sched.com/event/gmK5/ebpf-iterators
process-collector can optionally use filters as prepared by the Gadget Tracer Manager in the same way as other bcc tools such as opensnoop or execsnoop:
```
apiVersion: gadget.kinvolk.io/v1alpha1
kind: Trace
metadata:
name: process-collector
namespace: gadget
spec:
node: minikube
gadget: process-collector
filter:
namespace: default
labels:
role: demo
runMode: Manual
outputMode: Status
```
Implementation details:
- The BPF program is compiled twice: one time with the filter and one time without. The Go program selects the right one to …
> New gadget: process collector

- cmd/kubectl-gadget/bcck8s.go
- cmd/kubectl-gadget/bcck8s_test.go
- gadget.Dockerfile
Add a `--json` flag to enable the json mode on BCC-based gadgets.
BCC implementation is done here -> https://github.com/kinvolk/bcc/pull/2. 
TODO:
> Support json output for BCC based gadgets

- cmd/kubectl-gadget/deploy.go
Liveness probes are great for a production environment but they make it
complicated to debug an issue. This commit adds a parameter to disable
them.
> cmd/kubectl-gadget: add option to disable liveness probe

- .github/workflows/inspektor-gadget.yml
Comments in yaml strings are not removed, so the paths were not valid.
See example of mistaken cache handling:
https://github.com/kinvolk/inspektor-gadget/runs/3235399299?check_suite_focus=true
```
Received 22 of 22 (100.0%), 0.0 MBs/sec
Cache Size: ~0 MB (22 B)
/usr/bin/tar --use-compress-program zstd -d -xf /home/runner/work/_temp/db306363-4ac2-4195-8a9a-86767fdeeebd/cache.tzst -P -C /home/runner/work/inspektor-gadget/inspektor-gadget
Cache restored successfully
Cache restored from key: Linux-f0c82c52096f1cb0197fae8668e8e32debc2d25f7dbbc9523abc34da004b1b8d
Cache deb packages
```
```
Post job cleanup.
Cache hit occurred on the primary key Linux-f0c82c52096f1cb0197fae8668e8e32debc2d25f7dbbc9523abc34da004b1b8d, not saving cache.
Complete job
```
After this patch, the cache works in the …
> GitHub Action: fix cache on external dependencies

- cmd/kubectl-gadget/bcck8s.go
- cmd/kubectl-gadget/deploy.go
- cmd/kubectl-gadget/utils.go
- gadget-container/entrypoint.sh
- gadget.Dockerfile
This PR allows to use the libbpf-based tools from BCC when BTF is available in the host. The entrypoint script of the gadget container checks if BTF is available and then it creates symlinks to the right tools to be used (standard/python vs libbpf-based). It doesn't change anything from the user POV, the tools continue to work the same. 
This PR is rather small as most of the changes needed to make it work are in the BCC repo: https://github.com/kinvolk/bcc/pull/5. 
TODO:
> Use bcc libbpf-tools

- cmd/kubectl-gadget/bcck8s.go
https://github.com/kinvolk/inspektor-gadget/pull/207 extended the tools to print some extra information about the container and pod names. This feature is not supported by profile, hence when that tool is used the `--containersmap` shouldn't be passed to the tool. 
Reported in https://github.com/kinvolk/inspektor-gadget/pull/217#issuecomment-896172487
> cmd/kubectl-gadget: do not pass --containersmap to profile

- cmd/kubectl-gadget/collector.go
- cmd/kubectl-gadget/deploy.go
- cmd/kubectl-gadget/utils.go
This implements `kubectl gadget process-collector`.
The basic output:
```
$ ./kubectl-gadget-linux-amd64 process-collector --namespace kube-system -l k8s-app=gadget
NAMESPACE      POD             CONTAINER    COMM               PID
kube-system    gadget-xrl8g    gadget       entrypoint.sh      563921
kube-system    gadget-xrl8g    gadget       gadgettracerman    563946
kube-system    gadget-xrl8g    gadget       sleep              563947
```
With the threads:
```
$ ./kubectl-gadget-linux-amd64 process-collector --namespace kube-system -l k8s-app=gadget --threads
NAMESPACE      POD             CONTAINER    COMM               TGID      PID
kube-system    gadget-xrl8g    gadget       entrypoint.sh      563921    563921
kube-system    gadget-xrl8g    gadget       gadgettracerman    563946 …
```
> kubectl-gadget process-collector: implement client side

- gadget-container/Makefile
In case of compilation errors in one of the ebpf programs, the makefile was continuing the build instead of stopping. This patch replaces `;` by `&&` in the shell command line to make sure compilations errors are not ignored.
> gadget-container/Makefile: stop in case of errors

- gadget-container/entrypoint.sh
- gadget.Dockerfile
This PR is an experiment that uses https://github.com/aquasecurity/btfhub to run CO-RE based tools in systems without `CONFIG_DEBUG_INFO_BTF=y`.
The entrypoint script tries to download the BTF file for the current kernel, if it's successful it creates an ELF file with a .BTF section containing the BTF debug info and stores it at `/boot/vmlinux-$(uname -r)`
I created a test cluster in ubuntu focal (using kubeadm) and tried to run some of the tools. 
```
$ cat /boot/config-$(uname -r) | grep BTF
CONFIG_VIDEO_SONY_BTF_MPX=m
$ kubectl -n kube-system logs $PODNAME 
OS detected: "Ubuntu 20.04.1 LTS"
Kernel detected: 5.4.0-80-generic
bcc detected: 0.21.0-1
Gadget image: docker.io/kinvolk/gadget:mauricio-btf-hub-poc
Deployment options:
INSPEKTOR_GADGET_OPTION_TRACELOOP_LOGLEVEL=info,json …
```
> Use btfhub

- pkg/gadgets/interface.go
- pkg/gadgettracermanager/gadgettracermanager.go
- pkg/gadgettracermanager/pubsub/pubsub.go
- pkg/gadgettracermanager/pubsub/pubsub_test.go
GadgetTracerManager's pubsub provides a synchronous publish subscribe mechanism for gadgets to be informed of container creation and deletion. It needs to be synchronous so that gadgets have time to attach their tracer before the container is started.
Examples of possible gadgets that would need this:
- a gadget that listens on the network traffic of containers. It needs to have access to the netns of the container before it is started.
- a gadget that installs uprobes on programs of containers. It needs to have access to the mntns of the container before it is started.
The methods to add/remove containers and tracers can be called concurrently from different threads and they read/update the
'containers' and 'tracers' maps respectively. This patch makes use of the existing mutex to …
> GadgetTracerManager: add pubsub in preparation for future network and uprobe gadgets

- gadget-container/entrypoint.sh
This commit fixes the URL used to fetch the files from the btfhub repo.
I forgot to push before merging https://github.com/kinvolk/inspektor-gadget/pull/221. This PR fixes that. 
ref https://github.com/kinvolk/inspektor-gadget/pull/221#issuecomment-901019312
> Fix btfhub URL

- cmd/kubectl-gadget/deploy.go
We're hitting an issue (#230) when using CO-RE based tools. Let's set
the default to "standard" until we found out the reason of that issue.
> cmd: set default of "tools-mode" to standard

- cmd/kubectl-gadget/collector.go
Initialise Process slices so that we get an empty JSON instead of null.
I tested this by intentionally omitting `-A` option and with a pod that is not in the `default` namespace so that the `process-collector` doesn't find any match and `status.output` is empty.  
Before this commit:
```
$ ./kubectl-gadget-linux-amd64 process-collector -p mypod -j
null
```
After this commit:
```
$ ./kubectl-gadget-linux-amd64 process-collector -p mypod -j
[]
```
Please notice that there is an ongoing discussion to improve user experience in this kind of cases.
> kubectl-gadget process-collector: Improve output for empty case

- pkg/gadgets/seccomp/gadget.go
- pkg/gadgets/socket-collector/gadget.go
To check if a map is empty, don't use ==nil but use len() instead. See
https://play.golang.org/p/7znzMaS5LUK
> seccomp & socket-collector: fix nil-dereference and other errors

- pkg/gadgets/interface.go
- pkg/gadgettracermanager/gadgettracermanager.go
- pkg/gadgettracermanager/gadgettracermanager_test.go
This PR adds function `GetContainersBySelector` to GadgetTracerManager to be able to retrieve all the containers that match the parameters defined by the `ContainerSelector` data structure. 
This function will be used together with PR #239 to run gadgets on a subset of containers defined by user through filters. Check  gadget socket-collector for an example of usage in coming PRs. 
Check new tests added to `TestContainer`: 
```
$ go test ./pkg/gadgettracermanager/
ok      github.com/kinvolk/inspektor-gadget/pkg/gadgettracermanager     0.011s
```
>  gadgettracermanager: Add helper function to get containers by selectors 

- pkg/gadgets/socket-collector/tracer/tools.go
When trying to use the socket-collector package, I had an error with
bpf2go:
```
cannot find package "." in:
/home/alban/go/src/github.com/kinvolk/inspektor-gadget/vendor/github.com/cilium/ebpf/cmd/bpf2go
```
See:
https://github.com/golang/go/issues/29516#issuecomment-454159127
> socket-collector: fix access to bpf2go

- cmd/kubectl-gadget/collector.go
- cmd/kubectl-gadget/dns.go
- cmd/kubectl-gadget/utils/trace.go
- gadget-container/gadgettracermanager/controller.go
- pkg/api/v1alpha1/trace_types.go
- pkg/gadgets/dns/gadget.go
- pkg/gadgets/dns/tracer/bpf/Makefile
- pkg/gadgets/dns/tracer/bpf/dns-common.h
- pkg/gadgets/dns/tracer/bpf/dns.c
- pkg/gadgets/dns/tracer/embed-ebpf.go
- pkg/gadgets/dns/tracer/embed-none.go
- pkg/gadgets/dns/tracer/tracer.go
- pkg/gadgets/dns/tracer/tracer_test.go
- pkg/gadgets/dns/types/dns.go
- pkg/gadgettracermanager/containerutils/containerutils.go
- pkg/resources/crd/bases/gadget.kinvolk.io_traces.yaml
- pkg/resources/samples/trace-dns.yaml
This PR implements:
* Streams in the Gadget Tracer Manager. Gadgets can now easily publish a stream of events consumable by kubectl-gadget or other clients
* A new DNS gadget in the gadget pod.
* Refactoring the client-side code to help writing new gadgets client-side.
* "kubectl gadget dns" itself.
```
$ kubectl gadget dns --namespace default
default/normal-pod-ks8hs: DNS request to kinvolk.io.
default/normal-pod-ks8hs: DNS request to kinvolk.io.
default/normal-pod-ks8hs: DNS request to kinvolk.io.
default/normal-pod-ks8hs: DNS request to kinvolk.io.
```
```
$ kubectl exec -ti normal-pod-ks8hs -- wget kinvolk.io
```
Tested on Minikube with the docker driver.
The internals can also be tested manually with:
```
$ kubectl apply -f pkg/resources/samples/trace-dns.yaml
$ kubectl annotate -n …
```
> New DNS gadget

- Makefile
- cmd/kubectl-gadget/deploy.go
- gadget-container/entrypoint.sh
- gadget-container/gadgettracermanager/main.go
- go.mod
- go.sum
- pkg/gadgettracermanager/gadgettracermanager.go
- pkg/gadgettracermanager/gadgettracermanager_test.go
- pkg/gadgettracermanager/k8s/k8s.go
- pkg/runcfanotify/runcfanotify.go
This hook gets new container creation events in a synchronous way thanks to fanotify's FAN_OPEN_EXEC_PERM and FAN_ACCESS_PERM features which work in a synchronous way. 
* Use fanotify_mark FAN_OPEN_EXEC_PERM on the runc binary and parse its command line parameters, in particular the --bundle and --pid-file parameters.
* Before letting runc executing, use fanotify_mark FAN_ACCESS_PERM on the pid file to notice when `containerd-shim` reads the file.
* Let `runc create` resume.
* Before letting `containerd-shim` read the file, add the container in the Gadget Tracer Manager
* Let `containerd-shim` resume and start the container
```
kubectl gadget deploy --hook-mode=fanotify
```
Tested on:
* Minikube with the docker driver and Linux 5.12.6-300.fc34.x86_64.
* AKS with Linux 5.4.0-1055-azure
I …
> New hook mode: runcfanotify

- cmd/kubectl-gadget/collector.go
- pkg/gadgets/socket-collector/gadget.go
- pkg/gadgets/socket-collector/tracer/tracer.go
- pkg/gadgets/socket-collector/types/socket-collector.go
- pkg/types/types.go
This PR implements the client side of socket-collector gadget introduced by PR kinvolk/inspektor-gadget#227.
Sockets are sorted in the following decreasing order:
- Node
- Namespace
- Pod
- Protocol
- Status
- Local Address
- Remote Address
- Local Port
- Remote Port
Notice that it is not yet possible to filter by labels or only by namespace.
Output in columns:
```
$ kubectl gadget socket-collector -n demo -p mypod
NODE      NAMESPACE    POD      PROTOCOL    LOCAL               REMOTE              STATUS
mynode    demo         mypod    TCP         10.0.0.187:44928    10.0.0.191:27017    ESTABLISHED
mynode    demo         mypod    TCP         0.0.0.0:8081        0.0.0.0:0           LISTEN
```
In JSON format:
```
$ kubectl gadget socket-collector -n demo -p mypod -j
[
{
"node": "mynode", …
```
> kubectl-gadget socket-collector: Implement client side

- cmd/kubectl-gadget/utils/trace.go
- pkg/gadgets/socket-collector/gadget.go
- pkg/gadgets/socket-collector/tracer/tracer.go
This commit improves the filtering for the socket-collector gadget introduced by PR #227. It is now possible to filter by namespace (or use -A for all-namespaces) and labels.
Some examples with the output in columns:
```
$ kubectl gadget socket-collector -n default
NODE      NAMESPACE    POD         PROTOCOL    LOCAL               REMOTE              STATUS
mynode    default      my-pod      TCP         10.0.0.187:44928    10.0.0.191:27017    ESTABLISHED
mynode    default      my-pod      TCP         0.0.0.0:8081        0.0.0.0:0           LISTEN
mynode    default      my-pod-2    TCP         127.0.0.1:51962     127.0.0.1:2379      ESTABLISHED
```
```
$ kubectl gadget socket-collector -n demo
NODE      NAMESPACE    POD       PROTOCOL    LOCAL            REMOTE           STATUS
mynode …
```
> socket-collector: Improve filtering

- .github/workflows/inspektor-gadget.yml
- .gitignore
- .krew.yaml
- Makefile
- docs/CONTRIBUTING.md
- integration/Makefile
- tests.mk
In order to support the two new platforms, this patch avoids hardcoding
amd64 in different places.
Some changes in the Makefile:
* kubectl-gadget-all: build for all platforms
* kubectl-gadget: build for the host platform only
Other targets are updated to avoid hard coding the platform.
Fixes https://github.com/kinvolk/inspektor-gadget/issues/241
In order to validate this PR, reviewers should:
- fork this repository
- set up GitHub Secrets in the forked repository (see [Github Actions](https://github.com/kinvolk/inspektor-gadget/blob/main/docs/CONTRIBUTING.md#github-actions))
- push a git tag on the forked repository
- and check that krew manifest is correct
- download the generated kubectl-gadget and check that it works on the arm64 harware
I don't have the hardware, so this is not …
> Add support for arm64 on linux and darwin

- gadget.Dockerfile
Update BCC to fix issue with opensnoop on recent kernels 
Fixes https://github.com/kinvolk/inspektor-gadget/issues/244
Local fix https://github.com/kinvolk/bcc/pull/7
Upstream fix https://github.com/iovisor/bcc/pull/3607
> Fix opensnoop on kernels supporting kfunc

- .gitignore
After latest changes on Makefile introduced in PR #255, when 'make kubectl-gadget' is executed, the kubectl-gadget-$(GOHOSTOS)-$(GOHOSTARCH) is renamed as kubectl-gadget. Therefore, this commit updates the .gitignore file accordantly.
> Updates .gitignore after latest changes on Makefile

- go.mod
- go.sum
Update cilium/ebpf library to include
https://github.com/cilium/ebpf/commit/429c5ea93f7af2e85fbd6cfe8d78d7d9a0168a0a
that fixes programs using bpf_probe_read_{kern,user}() in kernels without
that support by replacing those calls by bpf_probe_read().
--- 
I hit this issue when running the seccomp policy advisor in a 5.4 kernel.
> go.mod: update cilium/ebpf

- pkg/gadgets/biolatency/gadget.go
- pkg/gadgets/dns/gadget.go
- pkg/gadgets/networkpolicy/gadget.go
- pkg/gadgets/process-collector/gadget.go
- pkg/gadgets/seccomp/gadget.go
After refactoring Operations() in the TraceFactory interface, this code
is no longer needed.
This is a follow up to https://github.com/kinvolk/inspektor-gadget/pull/256
> gadgets: cleanup dead code

- gadget-container/cleanup.sh
- gadget-container/entrypoint.sh
- gadget-container/gadgettracermanager/main.go
- pkg/gadgettracermanager/gadgettracermanager.go
Some changes to remove the different pinned eBPF objects when removing the gadget container. For more details please check each commit message.
> Remove pinned eBPF objects

- pkg/gadgets/dns/tracer/tracer.go
The perf file descriptor seems to be closed while we are still reading
on it. This patch does not fully resolved the issue, but at least the
error management should prevent gadget-tracer-manager from crashing.
Symptoms:
```
time="2021-09-14T13:44:20Z" level=error msg="Error while reading from perf event reader: bad file descriptor"
panic: runtime error: index out of range [0] with length 0
goroutine 379 [running]:
github.com/kinvolk/inspektor-gadget/pkg/gadgets/dns/tracer.parseDNSEvent(0x0, 0x0, 0x0, 0x2e, 0xc000886f58, 0x1, 0x1)
/gadget/pkg/gadgets/dns/tracer/tracer.go:198 +0x24c
github.com/kinvolk/inspektor-gadget/pkg/gadgets/dns/tracer.(*Tracer).listen(0xc00000f440, 0xc00033c820, 0xc0005d1840)
/gadget/pkg/gadgets/dns/tracer/tracer.go:225 +0x179
created by …
```
> dns gadget: stop on error on perf ring buffer

- README.md
- docs/CONTRIBUTING.md
- docs/install.md
Add instruction for installation in minikube.
An ideal solution would be to have https://github.com/kubernetes/minikube/issues/8556 merged first but it's having some issues. I propose to add these instructions in the meanwhile.
Ref https://github.com/kinvolk/inspektor-gadget/issues/115.
> Docs: Include instructions for minikube

- pkg/runcfanotify/runcfanotify.go
The go-fanotify package has an inconsistent API: data.Close() and
data.File() cannot be used together because one is closing the file with
unix.Close() and the other is using os.NewFile() so it will be closed by
the os.File's finalizer once the garbage collector frees it.
Since we need the os.File to be able to use ioutil.ReadAll(), let's be
consistent and never call data.Close().
cc @iaguis @rata who helped to debug this.
> runcfanotify: fix fd double close

- README.md
- cmd/kubectl-gadget/collector.go
- docs/gadgets/process-collector.md
- docs/gadgets/socket-collector.md
- pkg/gadgets/process-collector/gadget.go
- pkg/gadgets/socket-collector/gadget.go
"Collect processes" and "Collect sockets" doesn't really help clarify what these gadgets do. Reword this to "Gather information" about either running processes or network sockets, so that we actually provide some additional info in the short description.
> Improve collector descriptions

- .krew.yaml
- docs/CONTRIBUTING.md
`Documentation` folder is now named `docs`.
> docs: Update links to docs folder

- Makefile
If `kubectl-gadget-$(GOHOSTOS)-$(GOHOSTARCH)` does not exist, then `make integration-tests` will fail. Therefore, it needs to be added as dependency.
This PR also starts using `kubectl-gadget` instead of `kubectl-gadget-$(GOHOSTOS)-$(GOHOSTARCH)` to prevent user from keeping both binaries.
Tests were done without having compiled the CLI.
Before this PR:
```
$ make integration-tests
KUBECTL_GADGET="/kinvolk/src/inspektor-gadget/kubectl-gadget-linux-amd64" \
go test ./integration/... \
-integration \
-image blanquicet/gadget:latest
--- FAIL: TestTraceloop (0.13s)
--- FAIL: TestTraceloop/Deploy_Inspektor_Gadget (0.08s)
traceloop_test.go:115: Command: $KUBECTL_GADGET deploy $GADGET_IMAGE_FLAG | kubectl apply -f -
traceloop_test.go:119: Command returned:
/bin/sh: 1: …
```
> makefile: Ensure CLI is compiled before launching the integration-tests

- gadget.Dockerfile
Update to include BCC v0.22
Important things for us are:
- https://github.com/iovisor/bcc/pull/3607
- https://github.com/iovisor/bcc/pull/3596 (https://github.com/kinvolk/inspektor-gadget/pull/169)
> Update BCC version

- .github/workflows/inspektor-gadget.yml
Check for any uncommitted changes and fail the GitHub Action if any is
found.
This is to avoid mistakes like in the previous release where a version
with the "-dirty" suffix was reported:
```
$ ./kubectl-gadget version
v0.3.0-dirty
```
This was because "bin/" was forgotten from .gitignore. With this patch,
we will no longer forget entries in .gitignore.
Fixes https://github.com/kinvolk/inspektor-gadget/issues/301
> GitHub Action: check for any uncommitted changes

- cmd/kubectl-gadget/utils/trace.go
This PR fixes #251.
Before this PR:
```
$ ./kubectl-gadget socket-collector -n default -p my-pod --node non-existent-node
FATA[0000] Error getting traces from all nodes           args="[]" command="kubectl-gadget socket-collector"
$ ./kubectl-gadget process-collector -A --node non-existent-node
FATA[0000] Error getting traces from all nodes           args="[]" command="kubectl-gadget process-collector"
$ ./kubectl-gadget dns -A --node non-existent-node
NODE             NAMESPACE        POD                            TYPE      NAME
FATA[0000] Error getting traces from all nodes           args="[]" command="kubectl-gadget dns"
```
After this PR:
```
$ ./kubectl-gadget socket-collector -n default -p my-pod --node non-existent-node
FATA[0000] Invalid filter: Node "non-existent-node" does not …
```
> kubectl-gadget: Manage filtering by non-exisitent node

- pkg/container-collection/container-collection.go
- pkg/container-collection/interface.go
- pkg/container-collection/match.go
- pkg/container-collection/match_test.go
- pkg/gadgets/interface.go
- pkg/gadgettracermanager/gadgettracermanager.go
- pkg/gadgettracermanager/gadgettracermanager_test.go
- pkg/gadgettracermanager/pubsub/pubsub.go
- pkg/gadgettracermanager/pubsub/pubsub_test.go
Abstracting the set of containers in gadget-tracer-manager, so it can be reused in local-gadget (https://github.com/kinvolk/inspektor-gadget/pull/245).
This includes the helper function ContainerSelectorMatches. Some unit tests were moved accordingly.
No changes, this is just refactoring code.
`make test` and `make local-gadget-tests` in the local-gadget branch.
> New pkg: container-collection

- pkg/gadgettracermanager/gadgettracermanager.go
While debugging some issue on https://github.com/kinvolk/inspektor-gadget/pull/272, I wanted to print all go routine stacks to see if a go routine was stuck.
For debugging, the dump command will now print all go routine stacks:
```
gadgettracermanager -dump
```
```
kubectl exec -ti -n kube-system $(kubectl get pod -n kube-system -l k8s-app=gadget -o name) -- gadgettracermanager -dump | less
```
I tested that I can print the stacks.
> gadgettracermanager: add command to dump stacks

- cmd/kubectl-gadget/networkpolicyadvisor.go
- pkg/gadgets/networkpolicy/advisor/advisor.go
- pkg/gadgets/networkpolicy/advisor/advisor_test.go
- pkg/gadgets/networkpolicy/gadget.go
This is to avoid linking too many packages in the kubectl-gadget CLI tool.
Internal imports before this patch:
```
cmd/kubectl-gadget
cmd/kubectl-gadget/utils
pkg/api/v1alpha1
pkg/factory
pkg/k8sutil
pkg/types
pkg/gadgets/dns/types
pkg/gadgets/networkpolicy
pkg/gadgets
pkg/container-collection
pkg/gadgettracermanager/api
pkg/gadgettracermanager/containerutils
pkg/gadgettracermanager/pubsub
pkg/runcfanotify
pkg/gadgets/networkpolicy/types
pkg/gadgets/socket-collector/types
pkg/resources
```
Internal imports after this patch:
```
cmd/kubectl-gadget
cmd/kubectl-gadget/utils
pkg/api/v1alpha1
pkg/factory
pkg/k8sutil
pkg/types
pkg/gadgets/dns/types
pkg/gadgets/networkpolicy/advisor
pkg/gadgets/networkpolicy/types
pkg/gadgets/socket-collector/types
pkg/resources
```
> Network Policy Advisor: move advisor in separate package

- README.md
- cmd/kubectl-gadget/bcck8s.go
- docs/guides/biotop.md
This change introduces a new command to execute `biotop` gadget. The gadget doesn't support namespace, containername or podname parameters. It traces disk usage per node.
`kubectl gadget biotop --all-namespaces`
Executed the following commands:
```
Invalid commands:
kubectl gadget biotop # FATA[0000] biotop only works with --all-namespaces
kubectl gadget biotop --namespace default # FATA[0000] biotop only works with --all-namespaces
kubectl gadget biotop --containername container FATA[0000] biotop doesn't support --containername or --podname
kubectl gadget biotop --podname podname FATA[0000] biotop doesn't support --containername or --podname
Valid commands:
kubectl gadget biotop --all-namespaces
kubectl gadget biotop --all-namespaces --node minikube
```
> Add support of biotop gadget

- docs/gadgets/seccomp.md
- pkg/gadgets/seccomp/gadget.go
- pkg/gadgets/seccomp/syscalls.go
- pkg/gadgets/seccomp/syscalls_none.go
- pkg/gadgets/seccomp/tracer/tracer.go
- pkg/resources/samples/trace-seccomp.yaml
This patch updates the seccomp gadget to subscribe to container termination events (using `pkg/gadgettracermanager/pubsub`) and to save a Seccomp Profile with a unique name when it happens.
This allows to capture syscalls on short-lived pods. See discussion in https://github.com/kinvolk/inspektor-gadget/issues/265
The new Seccomp Profile resource will have:
* some annotations to identify where it is coming from.
* the labels copied from the Trace custom resource. This will be useful for implementing the kubectl-gadget CLI, to be able to delete all Seccomp Profiles coming from the same Trace resource.
See commands below.
Tested with the following commands:
```
$ kubectl apply -f ./pkg/resources/samples/trace-seccomp.yaml
$ kubectl annotate -n gadget trace/seccomp …
```
> seccomp: generate SeccompProfile for terminated pods

- Makefile
* don't fail when pv is not installed. pv is nice to display a progress bar, but it is not critical.
* fix dep on kubectl-gadget: uses kubectl-gadget instead of kubectl-gadget-linux-amd64
```
make minikube-install
```
Tested both with and without pv installed.
cc @joaquimrocha
> Makefile fixes on the minikube-install target

- gadget.Dockerfile
It fixes traces not being shown in an AKS cluster
I'm not 100% sure why the old version wasn't working, I think it's something that was fixed by this commit -> https://github.com/kinvolk/traceloop/commit/6f4efc6fca46d92c75f4ec4e6c6e1d829bdeaddf. 
Fixes https://github.com/kinvolk/inspektor-gadget/issues/248. 
Notes to reviewers: Please be sure that you are able to reproduce the issue in https://github.com/kinvolk/inspektor-gadget/issues/248 and that this PR actually fixes it.
> Update traceloop binary

- docs/guides/bindsnoop.md
Two fixes for the bindsnoop guide:
- docs: Add node about podinformer hook in bindsnoop guide
- docs: Remove --generators from bindsnoop guide
> docs: bindsnoop fixes

- docs/guides/dns.md
This PR implements a very simple guide about the dns gadget. 
Fixes https://github.com/kinvolk/inspektor-gadget/issues/282
> docs: Create initial dns guide

- Makefile
I have race conditions where the gadget namespace is not fully deleted
after the "kubectl delete -f". So the "kubectl apply" does not need to
create the namespace, but then the deletion terminates soon after.
Similarly, there are sometimes two gadgets pod: one in the terminating
state, and one in the creating state.
Additionally, it seems that "kubectl delete --wait" does not always
work. So I am adding an explicit "kubectl wait".
@ashu8912
> Makefile: minikube-install: wait for uninstall before new installation

- docs/gadgets/seccomp.md
- pkg/gadgets/seccomp/gadget.go
- pkg/resources/samples/trace-seccomp.yaml
SeccompProfiles can be created via 2 code paths:
- upon pod termination
- with the "generate" operation
Before this patch, the SeccompProfiles resources were only annotated
with the first code path. This patch prepares annotations for both
scenarios.
Fixes https://github.com/kinvolk/inspektor-gadget/issues/341
cc @ashu8912 
```
kubectl apply -f https://github.com/jetstack/cert-manager/releases/download/v1.6.0/cert-manager.yaml
kubectl --namespace cert-manager wait --for condition=ready pod -l app.kubernetes.io/instance=cert-manager
kubectl apply -f https://raw.githubusercontent.com/kubernetes-sigs/security-profiles-operator/master/deploy/operator.yaml
make minikube-install
kubectl apply -f …
```
> seccomp gadget: add labels and annotations to SeccompProfiles

- cmd/kubectl-gadget/deploy.go
- gadget-container/entrypoint.sh
- gadget-container/gadgettracermanager/main.go
- pkg/container-collection/container-collection.go
- pkg/container-collection/options.go
- pkg/gadgettracermanager/gadgettracermanager.go
- pkg/gadgettracermanager/gadgettracermanager_test.go
- pkg/gadgettracermanager/k8s/k8s.go
This commit implements a mechanism that uses a pod informer as backup
for other hooks. If a container is detected by the pod informer and it
hasn't been added to the container list then it print a warning message
to notify the main hook is having issues.
Fixes https://github.com/kinvolk/inspektor-gadget/issues/336
TODO:
> Implement pod informer fallback

- docs/_index.md
- docs/custom-resources.md
Document what the Trace resources are for and how to use them in basic situations. Also add a link to this page to the main index, together with other top items.
This is a "human friendly" doc. #257 contains the spec for the resource.
> Add documentation about our CRD

- gadget-container/entrypoint.sh
BTFHub is now using LFS and now the URL needs a "archive" prefix.
> Update URL for BTFHub

- .github/workflows/inspektor-gadget.yml
It's not needed right now, so let's disable it.
Similar to https://github.com/kinvolk/traceloop/pull/63
> GHA: Remove daily cron job

- cmd/kubectl-gadget/collector.go
- cmd/kubectl-gadget/dns.go
- cmd/kubectl-gadget/utils/trace.go
Hi.
Jose and I are working on adding CLI to `biolatency` and `seccomp` gadget.
To do so, we need to modify the `utils.trace` API.
For the moment, I added several functions to this API:
1. `CreateTrace()` which creates a trace according to the given parameter.
2. `SetTraceOperation()` which updates the operation of an existing trace.
3. `PrintTraceOutput()` which prints the output of a trace.
4. `DeleteTrace()` which deletes a trace created by CreateTrace().
I also updated the following gadgets to this new API:
1. `process-collector`
2. `socket-collector`
3. `dns`
Code was tested and seems fine:
```bash
francis@machine:~/Codes/kinvolk/inspektor-gadget$ kubectl create ns demo                                        francis/utils-trace-new-api % u=
namespace/demo created …
```
> Modify utils.trace API and convert some gadgets to it.

- cmd/kubectl-gadget/deploy.go
IPC_LOCK allows to bypass RLIMIT_MEMLOCK. Some gadgets (BCC python-based)
are not bumping their rlimit lock and hence they are failing.
Related to https://github.com/kinvolk/inspektor-gadget/pull/381.
How to reproduce:
```
$ ./kubectl-gadget deploy | kubectl apply -f -
$ ./kubectl-gadget execsnoop
NODE             NAMESPACE        POD              CONTAINER        PCOMM            PID    PPID   RET ARGS
mmap: Operation not permitted
... 
```
Tested in 5.11.0-38-generic.
> cmd: Add IPC_LOCK capability to gadget container

- .github/workflows/inspektor-gadget.yml
- .gitignore
- Makefile
- cmd/local-gadget/main.go
- docs/local-gadget.md
- go.mod
- go.sum
- pkg/container-collection/options.go
- pkg/gadget-collection/gadget-collection.go
- pkg/local-gadget-manager/local-gadget-manager.go
- pkg/local-gadget-manager/local-gadget-manager_test.go
- pkg/runcfanotify/runcfanotify.go
This patch makes the gadgets from Inspektor Gadget available on a Linux
machine without Kubernetes:
- kubectl-gadget: Inspektor Gadget on Kubernetes
- local-gadget: Inspektor Gadget on a single Linux machine
local-gadget can be executed without parameters and it will start a
shell with auto completion. Type "help" to get the list of commands.
Commands are implemented with cobra.
local-gadget uses the runc fanotify package to know when containers
based on runc are started or stopped. Notably it works with docker
containers.
Possible use cases:
- Faster development cycle of gadgets: they no longer need to be
deployed on Kubernetes and the compilation of a single binary is
faster than the build of the gadget container.
- Easier to write gadget tests: we can test whether a BPF program is …
> New command: local-gadget

- .github/workflows/inspektor-gadget.yml
When forking the inspektor-gadget repository for testing the release process, we don't want to mistakenly publish a release to krew-index. This patch detects the fork and skip the krew-index update in that case.
Tested via:
https://github.com/alban/inspektor-gadget/runs/4224664726?check_suite_focus=true
> GHA: don't update krew on forks

- README.md
- docs/guides/biolatency.md
- docs/requirements.md
This PR implements a simple guide about the biolatency gadget. It could be still improved by using additional flags of the `stress` tool and when we will have the possibility to use the different options that the BCC biolatency script offers.
Fixes #309
> docs: Create initial biolatency guide

- pkg/gadgettracermanager/gadgettracermanager.go
- pkg/local-gadget-manager/local-gadget-manager.go
While gadgettracermanager increased the memlock rlimit, local-gadget was
not doing it and this leads to this error:
```
{"err":"failed to create BPF collection: program bpf_prog1: load
program: RLIMIT_MEMLOCK may be too low: operation not
permitted","notice":"failed to attach
tracer","node":"local","namespace":"default","pod":"shell01"}
```
This patch increases the memlock rlimit for local-gadget using the
provided function from cilium/ebpf and use the same code pattern in
gadgettracermanager.
Note that recent kernels don't require the memlock rlimit to be
increased when the process has CAP_IPC_LOCK (Linux >= 5.11). But it has
been found necessary for Linux 5.10.
cc @tormath1
> local-gadget: remove memlock rlimit

- cmd/kubectl-gadget/biolatency.go
- cmd/kubectl-gadget/utils/trace.go
Hi.
In this commit, I added waiting for the trace to be in a given by user initial state once it is created.
The advantage of doing so is that we give a "ready to use" trace to the user and also print trace warnings and errors during its creation rather than waiting for the user to use a `stop` operation.
It fixes #391.
Best regards.
> utils: trace: Wait for given initial state after creating the trace.

- docs/guides/biotop.md
- docs/guides/process-collector.md
- docs/guides/socket-collector.md
After PR https://github.com/kinvolk/inspektor-gadget/pull/333, the user can get the output in JSON format using the `--output json` or `-o json` instead of `--json`. Update the guides accordingly.
> docs: Update guides to use `-o json` instead of `--json`

- cmd/kubectl-gadget/seccompadvisor.go
- cmd/kubectl-gadget/utils/trace.go
- docs/examples/seccomp/trace-external.yaml
- docs/guides/seccomp.md
- pkg/gadgets/seccomp/gadget.go
Hi.
In this PR, I added a CLI for the seccomp gadget:
1. `start`: Run the trace and start monitoring syscalls
2. `stop`: Output the previously captured syscalls on standard output.
3. `list`: List the existing seccomp trace (_i.e._, the ones created with `monitor` which were not `report`ed for the moment).
<details>
<summary>Here is an example of how to use it</summary>
```bash
francis@machine:~/Codes/kinvolk/inspektor-gadget$ kubectl apply -f docs/examples/seccomp/basic.yamlnamespace/seccomp-demo created
configmap/app-script created
service/hello-python-service created
francis@machine:~/Codes/kinvolk/inspektor-gadget$ kubectl apply -f docs/examples/seccomp/unconfined.yaml
pod/hello-python created
francis@machine:~/Codes/kinvolk/inspektor-gadget$ ./kubectl-gadget seccomp-advisor monitor …
```
> Add cli for seccomp.

- cmd/kubectl-gadget/utils/flags.go
- cmd/kubectl-gadget/utils/trace.go
This PR moves into a common place for the BCC (previously not covered) and non-BCC gadgets the node existence verification.
As discussed in the comments, this check will be removed when we will support the addition/deletion of nodes.
The gadget does not notify any error and remains blocked just doing nothing.
```
$ ./kubectl-gadget opensnoop -A --node non-existent-node
^C
Terminating...
```
The gadget finishes immediately with the following error:
```
$ ./kubectl-gadget opensnoop -A --node non-existent-node
Error: invalid filter: node "non-existent-node" does not exist
```
> kubectl-gadget/bcc: Manage filtering by non-existent node

- cmd/kubectl-gadget/collector.go
- cmd/local-gadget/main.go
- docs/gadgets/process-collector.md
- docs/gadgets/socket-collector.md
- pkg/gadgets/process-collector/gadget.go
- pkg/gadgets/socket-collector/gadget.go
- pkg/local-gadget-manager/local-gadget-manager_test.go
`Start` is not an appropriate operation name for the gadgets that generate a snapshot because they are not actually being started but just executed. In fact, after the `Start` operation they do not go in `Started` but `Completed` so they do not even need to be stopped.
For these reasons, the operation name was changed from `Start` to `Collect`.
https://github.com/kinvolk/inspektor-gadget/pull/357 unblocked this implementation and made it quite straightforward.
Nothing changes from the user's point of view.
- I tested the socket-collector with the local-gadget.
- I re-run the socket and process collector guides to ensure they were still working correctly.
> collectors: Change operation from Start to Collect

- .dockerignore
- .github/workflows/inspektor-gadget.yml
- Makefile
- docs/CONTRIBUTING.md
- docs/requirements.md
- gadget-container/entrypoint.sh
- gadget.Dockerfile
- tools/btfgen.sh
- tools/getbtfhub.sh
BTFGen[0] allows to generate small BTF files with only the information
needed by a set of eBPF objects. This commit makes use of that tool
together with BTFHub[1] to create a set of BTF files needed by Inspektor
Gadget. These files are around 800KB and are included in the gadget
container. At container startup time, the entrypoint script checks if
there's a file for the running kernel, if yes it's installed on the
system.
[0]: https://github.com/kinvolk/btfgen
[1]: https://github.com/aquasecurity/btfhub
TODO:
> Use BTFGen

- docs/examples/seccomp/confined.yaml
- docs/examples/seccomp/unconfined.yaml
- docs/guides/seccomp.md
- pkg/gadgets/seccomp/tracer/bpf/seccomp.c
As discussed in issue https://github.com/kinvolk/inspektor-gadget/issues/267, the policies generated by the seccomp-advisor gadget are not enough to get the pod to run successfully. As a workaround, it is necessary to set `allowPrivilegeEscalation` to `false` to make them work. However, it does not always work.
This PR fixes a bug in the way we collect the syscalls performed by `runc`. It was previously relying on the fact that the `seccomp()` will be called but it is not always true. Actually, it is false in most cases. 
Consider we want to record only the syscalls executed by `runc` after the seccomp profile is actually installed. However, if we are running the seccomp-advisor gadget, it's very probably that the pod does not have a seccomp profile yet, so `seccomp()` will not be called. …
> seccomp: Record runc syscalls only after the profile are installed

- cmd/kubectl-gadget/seccompadvisor.go
- docs/examples/seccomp/confined.yaml
- docs/guides/seccomp.md
- pkg/gadgets/seccomp/gadget.go
- pkg/gadgets/seccomp/gadget_test.go
- pkg/gadgets/seccomp/syscalls.go
- pkg/gadgets/seccomp/syscalls_none.go
This PR aligns the name of the profiles generated on-demand and at pod termination. Now, both generations use the following logic to name the profiles:
```golang
if traceSpecOutput != "" {
name = Generated using traceSpecOutput as prefix, e.g myprofile-5t6g9
if traceSpecOutput contains namespace {
namespace = Retrieved from traceSpecOutput. Syntax: namespace/prefix-name
} else {
namespace = Fallback to trace's namespace
}
} else {
name = Use podname (or podname-X if needed) as name, e.g mypod, mypod-2, ...
namespace = Fallback to trace's namespace
}
```
Why do we generate names in some cases and use a counter in others?
- Generated names are used when we are generating profiles for different pods thus it would have no sense to use a counter in this case.
- The counter is used because the …
> seccomp: Align namespace and naming convention of the generated profiles

- pkg/gadgets/dns/tracer/tracer.go
- pkg/gadgets/socket-collector/tracer/tracer.go
- pkg/netnsenter/netnsenter.go
We used the same code pattern to enter a network namespace, execute some
code and return to the orginal network namespace. This patch factorizes
the code in a common package netnsenter.
This same code pattern will be used in a couple places more in the
tracepkt gadget, so it is time to factorize.
-----
Tracepkt gadget: https://github.com/kinvolk/inspektor-gadget/pull/427
> New pkg: netnsenter

- cmd/kubectl-gadget/utils/trace.go
The return code when the user presses Ctrl + C should be 0 instead
of 1.
TODO:
> cmd: Fix return code when SIGINT

- cmd/gen-doc/gadget.template
- docs/gadgets/biolatency.md
- docs/gadgets/dns.md
- docs/gadgets/network-policy-advisor.md
- docs/gadgets/process-collector.md
- docs/gadgets/seccomp.md
- docs/gadgets/socket-collector.md
- docs/gadgets/traceloop.md
Hi.
Jose notified me I forgot to modify #447 to add syntax highlighting to generated documentation.
Thus, this commit fixes the previous one.
Best regards.
> docs: Add syntax highlighting for generated documentation.

- Makefile
- README.md
- cmd/kubectl-gadget/deploy.go
- cmd/kubectl-gadget/undeploy.go
- cmd/kubectl-gadget/utils/trace.go
- docs/install.md
- integration/command.go
Implement undeploy command to fix cases where the deletion gets stuck because there are traces still running. 
Fixes https://github.com/kinvolk/inspektor-gadget/issues/388 
Ref https://github.com/kinvolk/inspektor-gadget/issues/123
TODO:
TODO next PRs:
> Add undeploy cmd

- README.md
Include new `kubectl-gadget` CLI sub-command `seccomp-advisor`.
> README: Update help output with seccomp-advisor

- cmd/kubectl-gadget/bcck8s.go
- docs/guides/biotop.md
- gadget.Dockerfile
- integration/integration_test.go
Hi.
In this PR, I added container information to biotop output:
```bash
$ ./kubectl-gadget biotop --node minikube
17:39:37 loadavg: 0.25 0.40 0.46 1/385 58375
NAMESPACE        POD              CONTAINER        PID    COMM             D MAJ MIN DISK       I/O  Kbytes  AVGms
kube-system      etcd-minikube    etcd             1963   etcd             W 253 0   vda          7      32   0.26
<>               <>               <>               244    jbd2/vda1-8      W 253 0   vda          2      16   0.19
<>               <>               <>               0 
```
TODO:
Best regards.
> `biotop`: Added container information to output.

- cmd/kubectl-gadget/deploy.go
- pkg/container-collection/options.go
In order to enrich the containers with the owner reference information, it is necessary to be able to get the information of the pods (There is already a rule that covers it) and a list of specific Kubernetes resources.
Check containers are enriched with the owner reference information.
After #429, this functionality stop working because the cluster role does not allow getting some required Kubernetes resources. The error was reported in the gadget logs:
```
$ kubectl logs -n gadget <gadget-pod> | grep error
time="2022-01-13T04:13:47Z" level=error msg="kubernetes enricher: Failed to enrich with owner reference: failed to get calico-system/daemonsets/apps/v1/calico-node owner reference: cannot fetch daemonsets/apps/v1 calico-system/calico-node: daemonsets.apps \"calico-node\" is forbidden: …
```
> kubectl-gadget/deploy: Add cluster role rule needed by seccomp gadget

- cmd/kubectl-gadget/deploy.go
As #466, these rules were missed in #429 to allow the integration with the Kubernetes Security Profiles Operator (SPO).
Generate a seccomp profile using the integration with the SPO.
```
$ kubectl apply -f https://raw.githubusercontent.com/kubernetes/website/main/content/en/examples/controllers/nginx-deployment.yaml
deployment.apps/nginx-deployment created
$ kubectl get pods
NAME                                READY   STATUS    RESTARTS   AGE
nginx-deployment-66b6c48dd5-2l6nt   1/1     Running   0          17s
nginx-deployment-66b6c48dd5-s7h6t   1/1     Running   0          17s
nginx-deployment-66b6c48dd5-xb89p   1/1     Running   0          17s
$ ./kubectl-gadget seccomp-advisor start -m seccomp-profile -p nginx-deployment-66b6c48dd5-2l6nt
vu5JsBXFrrbgVTjJ
$ kubectl delete -f …
```
> kubectl-gadget/deploy: Add cluster role rule needed for SPO integration

- cmd/kubectl-gadget/collector.go
- pkg/gadgets/process-collector/gadget.go
- pkg/gadgets/process-collector/tracer/bpf/process-collector.c
- pkg/gadgets/process-collector/tracer/tracer.go
- pkg/gadgets/process-collector/types/process-collector.go
- pkg/gadgettracermanager/bpf-maps.h
Hi.
In this PR, I refactored `process-collector` gadget thus it works like `socket-collector` on the `gadget-container` side.
That is to say, information related to kubernetes (_e.g._ namespace, pod and container name) are taken from `golang` while information related to process (_e.g._ PID and TID) are taken from eBPF.
With this, it is now possible to filter with container (I think this was not functional before but I cannot ensure it):
```bash
$ ./kubectl-gadget process-collector -A -c mypod
NAMESPACE    POD      CONTAINER    COMM     PID     
demo         mypod    mypod        nginx    7175    
demo         mypod    mypod        nginx    7211    
demo         mypod    mypod        nginx    7212
```
I also added the container's node to gadget's output:
```bash
$ ./kubectl-gadget …
```
> process-collector: Refactor the gadget and add node to output.

- integration/command.go
- integration/integration_test.go
Hi.
In this PR, I contain each integration test within its proper namespace, then I made integration tests running in parallel.
Here are the results I had running with different configuration (run once on `minikube` with 4CPU cores and 6GB of RAM, no mean, no standard deviation, so no real scientific value):
| nproc | time (s)  | absolute gain (s) | relative gain  |
| ------- | ----------- | ---------------------- | ----------------- |
| 1       | 958.723 | 0                          | 1                   |
| 2       | 548.589 | 410.134               | 1.748            |
|    4    | 343.915 | 614.808               | 2.788            |
Sadly, GitHub runners have only 2 cores the gain will be limited but there is still a gain.
Best regards.
> integration: run tests in parallel.

- cmd/kubectl-gadget/collector.go
- docs/guides/socket-collector.md
- pkg/gadgets/socket-collector/tracer/bpf/socket-common.h
- pkg/gadgets/socket-collector/tracer/bpf/tcp4-collector.c
- pkg/gadgets/socket-collector/tracer/bpf/udp4-collector.c
- pkg/gadgets/socket-collector/tracer/tracer.go
- pkg/gadgets/socket-collector/types/socket-collector.go
Hi.
In this PR, I added inode number to `socket-collector` for TCP and UPD socket:
```bash
$ ./kubectl-gadget socket-collector -n kube-system | head
NODE        NAMESPACE      POD                                 PROTOCOL    LOCAL                   REMOTE                  STATUS         INODE
minikube    kube-system    coredns-78fcd69978-ds8tc            TCP         172.17.0.2:57272         10.96.0.1:443           ESTABLISHED    49410
minikube    kube-system    coredns-78fcd69978-ds8tc            TCP         127.0.0.1:34372          127.0.0.1:8080          TIME_WAIT      0
minikube    kube-system    coredns-78fcd69978-ds8tc            TCP         127.0.0.1:34380          127.0.0.1:8080          TIME_WAIT      0
minikube    kube-system    coredns-78fcd69978-ds8tc            TCP …
```
> Add inode number to `socket-collector`

- .github/actions/install-debian-packages/action.yml
- .github/workflows/inspektor-gadget.yml
- .krew.yaml
Hi.
In this PR, I parallelized CI jobs, thus CI time was divided by approximately 1.5, from around 35 minutes to around 20 minutes.
Everything was tested and validated even [release](https://github.com/eiffel-fl/inspektor-gadget/releases/tag/vtest20) [jobs](https://github.com/eiffel-fl/inspektor-gadget/actions/runs/1718575715).
I would like to have your opinion about it because there are several caveats:
1. There are several places where I do the same action, _e.g._ getting go 1.17, but I do not want to share it between jobs as artifact.
2. I bumped `libseccomp` from `2.5.1-1ubuntu1~20.04.1` to `2.5.1-1ubuntu1~20.04.2` because it seems to not exist anymore in `ubuntu-latest`.
3. I was not able to test `rajatjindal/krew-release-bot` due to a [strange …
> Increase CI speed.

- cmd/kubectl-gadget/bcck8s.go
- cmd/kubectl-gadget/utils/exec.go
Ideally, there is one gadget pod on each worker node and it is in the
'running' phase. However, it could be that the gadget pod does not run
properly on one node. For example, Kubernetes could have a worker pool
with Windows and since the gadget container does not support Windows,
those containers are not running.
In this situation, it would still be useful to be able to use Inspektor
Gadget to inspect the other nodes. Currently, the kubectl-gadget CLI
fails immediately if one node does not work well.
This patch makes the CLI more tolerant of errors.
Failure when testing on a single node:
```
$ ./kubectl-gadget execsnoop --node aksalbanw000000
Node aksalbanw000000: Gadget pod not found
```
Failure when testing on all nodes:
```
$ ./kubectl-gadget execsnoop
Node aksalbanw000000: Gadget pod …
```
> kubectl-gadget: tolerate errors on some nodes

- README.md
- docs/guides/filetop.md
This guide is rather simple as there is a single pod performing a very simple operation. I tried some of the examples available here (https://github.com/kubernetes/examples) but they are a bit complex to install and they don't produce that much I/O, hence I decided to use this approach. 
Fixes https://github.com/kinvolk/inspektor-gadget/issues/477
> docs: Add filetop guide

- .github/workflows/inspektor-gadget.yml
Hi.
Before this PR, it was possible to do a release if the linter, document checks or the local-gadget unit tests failed.
This PR corrects this bad behavior:
* [Linter failed and no release is published](https://github.com/eiffel-fl/inspektor-gadget/actions/runs/1790422149).
* [Everything is OK and release is published](https://github.com/eiffel-fl/inspektor-gadget/actions/runs/1790720493).
Best regards.
> Prevent releasing if a job failed.

- gadget-container/entrypoint.sh
- gadget.Dockerfile
Testing IG on [OpenShift 4.9](https://developers.redhat.com/courses/explore-openshift/openshift-49-playground) and [Azure Red Hat Openshift](https://docs.microsoft.com/en-us/azure/openshift/) (OpenShift 4.8), the gadget pod is not able to download the kernel headers which makes the container fail:
```
OS detected: "Red Hat Enterprise Linux CoreOS 49.84.202110081407-0 (Ootpa)"
Kernel detected: 4.18.0-305.19.1.el8_4.x86_64
bcc detected: 0.24.0-1
Gadget image: joseregistry.azurecr.io/gadget:latest
Deployment options:
INSPEKTOR_GADGET_OPTION_FALLBACK_POD_INFORMER=true
INSPEKTOR_GADGET_OPTION_TOOLS_MODE=standard
INSPEKTOR_GADGET_OPTION_HOOK_MODE=auto
Inspektor Gadget version: v0.4.2
CRI-O detected.
Fetching kernel-devel from CentOS 8.
curl: (22) The requested URL returned error: 404 Not Found …
```
> entrypoint: Fix kernel-header download for CentOS

- docs/install.md
- gadget-container/cleanup.sh
- gadget-container/entrypoint.sh
Testing IG on [OpenShift 4.9](https://developers.redhat.com/courses/explore-openshift/openshift-49-playground) and [Azure Red Hat Openshift](https://docs.microsoft.com/en-us/azure/openshift/) (OpenShift 4.8), the gadget pod is not able to install the hooks configurations because the folder `/host/usr/share/containers/oci/hooks.d/` is read-only:
```bash
$ kubectl logs -n gadget <gadget-name>
OS detected: "Red Hat Enterprise Linux CoreOS 48.84.202110270303-0 (Ootpa)"
Kernel detected: 4.18.0-305.19.1.el8_4.x86_64
bcc detected: 0.24.0-1
Gadget image: joseregistry.azurecr.io/gadget:latest
Deployment options:
INSPEKTOR_GADGET_OPTION_FALLBACK_POD_INFORMER=true
INSPEKTOR_GADGET_OPTION_TOOLS_MODE=core
INSPEKTOR_GADGET_OPTION_HOOK_MODE=auto
Inspektor Gadget version: v0.4.2-115-g40b27d56ec9d-dirty …
```
> entrypoint: Install OCI hooks also in /etc/containers/oci/hooks.d

- .github/workflows/inspektor-gadget.yml
An issue with GitHub Actions not printing annotations and golangci/golangci-lint-action block the output from being printed. This patch is a workaround for this.
See https://github.com/golangci/golangci-lint-action/issues/119#issuecomment-981090648
> github action: print lint output

- cmd/kubectl-gadget/deploy.go
When running IG on [OpenShift 4.9](https://developers.redhat.com/courses/explore-openshift/openshift-49-playground) and [Azure Red Hat Openshift](https://docs.microsoft.com/en-us/azure/openshift/) (OpenShift 4.8), the gadge DaemonSet fails to deploy the gadget pods with the following error: 
```bash
$ describe daemonsets -n gadget gadget
...
Error creating: pods "gadget-" is forbidden: unable to validate against any security context constraint: [provider "anyuid": Forbidden: not usable by user or serviceaccount, provider restricted: .spec.securityContext.hostNetwork: Invalid value: true: Host network is not allowed to be used, provider restricted: .spec.securityContext.hostPID: Invalid value: true: Host PID is not allowed to be used, spec.volumes[0]: Invalid value: "hostPath": hostPath …
```
> kubectl-gadget/deploy: Use `privileged` security context constraint on OpenShift

- pkg/gadgettracermanager/containerutils/crio/crio.go
- pkg/gadgettracermanager/containerutils/crio/crio_test.go
Commit https://github.com/cri-o/cri-o/commit/be8e876cdabec4e055820502fed227aa44971ddc (>= v1.18.0) changed the syntax of the ContainerStatus() response when adding the runtime specs.
From:
```
{
"status": {
"id": "325c19b044c9e6af924cd8eecb309e91d4d78468474e7e83670453dbc2a3c501",
. . .
},
"info": {
"sandboxID": "ef93e1fa5b3ff08f150368cd5a935ca23460e78bd90da7dcd7c6a916872b1728",
"pid": 8415,
}
}
```
To:
```
{
"status": {
"id": "325c19b044c9e6af924cd8eecb309e91d4d78468474e7e83670453dbc2a3c501",
. . .
},
"info": {
"info": "{\"sandboxID\":\"ef93e1fa5b3ff08f150368cd5a935ca23460e78bd90da7dcd7c6a916872b1728\",\"pid\":8415,\"runtimeSpec\":{...}}"
}
}
```
**NOTE**: Is it worth opening a PR upstream? It doesn't make sense to have `info` twice. 
Try IG on OpenShift 4.9 or ARO.
Using `crictl` does …
> gadgettracermanager/crio: Update ContainerStatus() response syntax 

- pkg/gadgets/dns/tracer/tracer.go
- pkg/gadgets/execsnoop/tracer/core/tracer.go
- pkg/gadgets/oomkill/tracer/tracer.go
Use "errors.Is(err, perf.ErrClosed)" as "err == perf.ErrClosed" doesn't
work because the error is wrapped. Also avoid using "perf.IsClosed()"
as it will be removed in cilium/ebpf@v0.8.0 [1].
[1] https://github.com/cilium/ebpf/commit/a02484a72f85d00556bbf48ca89dfe68aea92a28
> gadgets: Fix error handling when perf ring buffer is closed

- cmd/kubectl-gadget/deploy.go
- gadget.Dockerfile
/etc/localtime is normally a symlink to a regular file such as
/usr/share/zoneinfo/Etc/UTC. However, recent versions of Flatcar don't
have it anymore, and it could be created as a directory.
The gadget pod cannot control whether /etc/localtime on the host is a
directory or a file. This means it is not safe to have a host volume in
the gadget pod with the /etc/localtime -> /etc/localtime bind mount.
As a workaround, remove this host volume and instead let's have a
symlink /etc/localtime -> /host/etc/localtime in the pod. As opposed to
bind mounts, symlinks can be created regardless if the target is a
directory or a file.
See also: https://github.com/flatcar-linux/Flatcar/issues/324
> Fix localtime volume

- pkg/gadgets/dns/gadget.go
- pkg/gadgets/dns/tracer/tracer.go
- pkg/gadgets/dns/types/dns.go
- pkg/rawsock/rawsock.go
- pkg/types/types.go
During the review of #369, there were changes suggested to the dns gadget. This PR introduces the suggested change, taking example on execsnoop. This will make it easier to write the snisnoop gadget without duplicating too much code.
> dns gadget: refactor

- pkg/gadgettracermanager/k8s/k8s.go
Align these two logs to the same format as other logs:
Before this PR:
```
time="2022-02-17T15:13:06Z" level=info msg="pubsub: ADD_CONTAINER: openshift-marketplace/community-operators-ll4dn/registry-server"
time="2022-02-17T15:13:14Z" level=info msg="pubsub: REMOVE_CONTAINER: openshift-marketplace/community-operators-ll4dn/registry-server"
time="2022-02-17T15:13:39Z" level=info msg="pubsub: ADD_CONTAINER: openshift-marketplace/redhat-operators-xgmgs/registry-server"
time="2022-02-17T15:13:46Z" level=info msg="pubsub: REMOVE_CONTAINER: openshift-marketplace/redhat-operators-xgmgs/registry-server"
2022/02/17 15:13:53 Skip pod default/mypod: cannot find pid: couldn't extract pid from container status reply: {"sandboxID":"aca1f72fe633bb310ae2941874ad4e0b19bf70373e7831691a8374669486f943","pid": …
```
> k8s: Fix log format when container pid is not found

- cmd/kubectl-gadget/utils/trace.go
An operation warning doesn't mean an error, hence the logic should
just store the warning and continue ahead instead of returning.
ref https://github.com/kinvolk/inspektor-gadget/pull/438#discussion_r793902479
> cmd/kubectl-gadget: Fix handling of trace operation warning

- integration/Makefile
- integration/command.go
If `kubectl wait` goes in timeout because the pod is not yet ready (Or will never be ready, e.g. fail to pull image), the tests will start unnecessary running anyway using resources that can be used by others.
> integration-tests: Do not run tests if pods are not ready

- pkg/controllers/trace_controller.go
- pkg/gadgets/biolatency/gadget.go
- pkg/gadgets/dns/gadget.go
- pkg/gadgets/execsnoop/gadget.go
- pkg/gadgets/filetop/gadget.go
- pkg/gadgets/fsslower/gadget.go
- pkg/gadgets/helpers.go
- pkg/gadgets/mountsnoop/gadget.go
- pkg/gadgets/networkpolicy/gadget.go
- pkg/gadgets/oomkill/gadget.go
- pkg/gadgets/opensnoop/gadget.go
- pkg/gadgets/process-collector/gadget.go
- pkg/gadgets/seccomp/gadget.go
- pkg/gadgets/sigsnoop/gadget.go
- pkg/gadgets/snisnoop/gadget.go
- pkg/gadgets/socket-collector/gadget.go
- pkg/gadgets/traceloop/gadget.go
```
gadgets.CleanupTraceStatus() was being used at some many different
places decreasing code readability. This commit modifies the trace
controller to clean the status of the trace before calling the gadget,
so it doesn't have to worry about cleaning its status up.
```
Fixes https://github.com/kinvolk/inspektor-gadget/issues/522
> Uniform trace status cleanup

- cmd/kubectl-gadget/utils/trace.go
- integration/integration_test.go
Hi.
Before changing the trace operation, we should ensure there is no running operation.
Indeed, before this commit, we could loose operations if we change, on client side, the operation while it is being processed on trace controller side.
```
Will set trace op to: "stop"
trace: {TypeMeta:{Kind:Trace APIVersion:gadget.kinvolk.io/v1alpha1} ObjectMeta:{Name:seccomp-rlw89 GenerateName:seccomp- Namespace:gadget SelfLink: UID:5bb29a54-0c11-47c6-9978-e670d48e08d6 ResourceVersion:7306 Generation:1 CreationTimestamp:2022-02-08 15:19:36 +0000 UTC DeletionTimestamp:<nil> DeletionGracePeriodSeconds:<nil> Labels:map[containerName: gadgetName:seccomp global-trace-id:k96VNBUizlFupAnj namespace:gadget nodeName: outputMode:Status podName:gadget-8kmhf] …
```
> Wait end of current operation before modifying trace operation

- docs/_index.md
Brace yourselves for some heavy contribution.
This PR fixes a [broken link](https://kinvolk.io/docs/inspektor-gadget/latest/) to the installation page, spotted while digging into inspektor-gadget.
Hope this helps.
> docs: Fix install link

- cmd/kubectl-gadget/seccompadvisor.go
It is mandatory to specify the trace ID when stopping the seccomp-advisor gadget but it is not mentioned at all in the command help.
I followed the same notation of [biolatency](https://github.com/kinvolk/inspektor-gadget/blob/1d273dfb08b1c922c1ba158a4d301067f3d923e7/cmd/kubectl-gadget/biolatency.go#L64).
```bash
$ kubectl gadget seccomp-advisor stop --help
Stop monitoring and report the policies
Usage:
kubectl-gadget seccomp-advisor stop [flags]
Flags:
-h, --help   help for stop
Global Flags:
-A, --all-namespaces                 Show data from pods in all namespaces
...
```
```bash
$ ./kubectl-gadget seccomp-advisor stop --help
Stop monitoring and report the policies
Usage:
kubectl-gadget seccomp-advisor stop <trace-id> [flags]
Flags:
-h, --help   help for stop
Global Flags:
-A, …
```
> cmd/kubectl-gadget: Fix seccomp-advisor gadget help

- cmd/kubectl-gadget/bcck8s.go
- cmd/kubectl-gadget/bindsnoop.go
- cmd/kubectl-gadget/biolatency.go
- cmd/kubectl-gadget/collector.go
- cmd/kubectl-gadget/deploy.go
- cmd/kubectl-gadget/dns.go
- cmd/kubectl-gadget/execsnoop.go
- cmd/kubectl-gadget/filetop.go
- cmd/kubectl-gadget/fsslower.go
- cmd/kubectl-gadget/mountsnoop.go
- cmd/kubectl-gadget/networkpolicyadvisor.go
- cmd/kubectl-gadget/oomkill.go
- cmd/kubectl-gadget/opensnoop.go
- cmd/kubectl-gadget/seccompadvisor.go
- cmd/kubectl-gadget/sigsnoop.go
- cmd/kubectl-gadget/snisnoop.go
- cmd/kubectl-gadget/tcpconnect.go
- cmd/kubectl-gadget/traceloop.go
- cmd/kubectl-gadget/undeploy.go
- cmd/kubectl-gadget/utils/errors.go
- cmd/kubectl-gadget/utils/exec.go
- cmd/kubectl-gadget/utils/flags.go
- cmd/kubectl-gadget/utils/table.go
- cmd/kubectl-gadget/utils/trace.go
- cmd/kubectl-gadget/utils/trace_test.go
This PR tries to uniform the way kubectl-gadget CLI shows errors to the users.
I created a set of functions to ease the adoption of this uniformity for new gadgets, see [cmd/utils/errors.go](https://github.com/kinvolk/inspektor-gadget/blob/jose/uniform-errors/cmd/kubectl-gadget/utils/errors.go).
TODO in other PRs:
> cmd/kubectl-gadget: Uniform errors between gadgets

- integration/Dockerfile
- integration/integration_test.go
Hi.
This PR enables `*-collector` tests in GitHub CI.
It is made possible thanks to `btfgen`.
Best regards.
> integration: Enable *-collector tests in GitHub CI.

- docs/guides/oomkill.md
- docs/guides/tcptracer.md
- integration/integration_test.go
Hi.
This PR adds a guide and an integration test for `tcptracer`.
It fixes #463.
Best regards.
> `tcptracer`: Add guide and integration test

- pkg/gadgets/bindsnoop/tracer/core/tracer.go
- pkg/gadgets/dns/tracer/tracer.go
- pkg/gadgets/execsnoop/tracer/core/tracer.go
- pkg/gadgets/fsslower/tracer/core/tracer.go
- pkg/gadgets/helpers.go
- pkg/gadgets/mountsnoop/tracer/core/tracer.go
- pkg/gadgets/oomkill/tracer/tracer.go
- pkg/gadgets/opensnoop/tracer/core/tracer.go
- pkg/gadgets/sigsnoop/tracer/core/tracer.go
- pkg/gadgets/snisnoop/tracer/tracer.go
- pkg/gadgets/tcpconnect/tracer/core/tracer.go
Many gadgets were using different values for the memory size of the
perf ring buffer. This commit defines a const and uses the same value
for all of them.
> pkg/gadgets: Uniform perf buffer memory size for all gadgets

- cmd/kubectl-gadget/deploy.go
- pkg/gadgets/traceloop/gadget.go
Hi.
In this PR, I increased the gadget container opened file limit from 1024 to 2048, using `ulimit -n`, right before running `traceloop`.
This is needed in CBL Mariner to avoid this type of error:
```
I0204 11:03:10.222056  197541 podinformer.go:282] Starting Pod controller
error while loading "tracepoint/raw_syscalls/sys_enter" (too many open files):
processed 2529 insns (limit 1000000) max_states_per_insn 4 total_states 209 peak_states 209 mark_read 7
```
Since now all gadgets work on CBL Mariner, merging this PR will fix #401. 
Best regards.
> Increase traceloop opened file limit.

- cmd/kubectl-gadget/utils/trace.go
This PR increases the time the CLI waits for a trace operation to be completed from 2 to 5 seconds. 
It is needed because, for instance, on an AKS cluster, with a CO:RE gadget (which does not need to be compiled), the start operation sometimes takes around 4 seconds:
```bash
time="2022-03-08T07:14:00Z" level=info msg="Reconcile trace gadget/bindsnoop-8znxw (gadget bindsnoop, node aks-agentpool-31885719-vmss000000)"
time="2022-03-08T07:14:00Z" level=info msg="Gadget bindsnoop operation \"start\" on gadget/bindsnoop-8znxw"
time="2022-03-08T07:14:04Z" level=info msg="Gadget completed operation. Trace status will be updated accordingly"
time="2022-03-08T07:14:04Z" level=info msg="Updating new status of trace \"gadget/bindsnoop-8znxw\": state=Started operationError=\"\" operationWarning=\"\" …
```
> cmd/kubectl-gadget: Increase trace timeout

- cmd/kubectl-gadget/deploy.go
- gadget-container/entrypoint.sh
This PR limits the maximum time the download of the kernel headers can last to 40 seconds (the default value was 2 min) and increases the `initialDelaySeconds` to 60 seconds so that the gadget pod will never be restarted while it is downloading the headers.
In addition, this PR sets the `terminationMessagePolicy` to "FallbackToLogsOnError" in order to have more information when gadget pod exited with an error:
Ref: [Customizing the termination message](https://kubernetes.io/docs/tasks/debug-application-cluster/determine-reason-pod-failure/#customizing-the-termination-message)
> By setting the terminationMessagePolicy to "FallbackToLogsOnError", you can tell Kubernetes to use the last chunk of container log output if the termination message file is empty and the container exited with an …
> cmd/kubectl-gadget: Increase livenessProbe initial delay

- .github/workflows/inspektor-gadget.yml
#383 introduces a new integration test which uses a pod with the seccompProfile field introduced in Kubernetes v1.19.
> ci: update minikube and kubernetes version

- cmd/kubectl-gadget/bcck8s.go
- cmd/kubectl-gadget/deploy.go
- docs/requirements.md
- gadget-container/entrypoint.sh
The tools-mode flag was intended to let the user choose the kind of
BCC tools to use: python-based/standard vs libbpf-based/core.
We have ported the tools to have their control plane in Golang
and we implemented a logic to automatically fallback to standard mode
when it's not possible to use CO:RE. For this reason this flag is not
useful anymore. In the future we could think about a way to specify the
tool mode (mainly for tests).
Fixes https://github.com/kinvolk/inspektor-gadget/issues/397
> Remove tools-mode flag

- docs/examples/init-containers.yaml
- pkg/container-collection/options.go
- pkg/gadgettracermanager/k8s/k8s.go
This PR fixes #114 by adding support for init containers to the `PodToContainers` function in `k8s.go`.
I also added `/examples/init-containers.yaml`, which I used to test the changes. Please let me know if adding this file is not necessary/desired.
Unfortunately, I couldn't come up with a way to test this change without adding temporary logging to the function and observing the logs, please let me know if there is 👍 
As mentioned above, I used `init-containers.yaml` with apply/delete.
I used
```
time="2022-03-05T16:38:14Z" level=info msg="pubsub: ADD_CONTAINER: kube-system/gadget-vbxmd/gadget"
time="2022-03-05T16:38:14Z" level=info msg="Checked 1 containers."
time="2022-03-05T16:38:14Z" level=info msg="Returning 1 running containers."
time="2022-03-05T16:38:14Z" level=info msg="Checked 1 …
```
> Add init containers to pod informer

- docs/guides/dns.md
- integration/integration_test.go
Hi.
This PR changed the name of docker image used for DNS integration test because:
```
========================= IMPORTANT ==============================
Few years ago, I created this tool with Henrik Høegh, as `praqma/network-multitool`. Praqma was bought by another company, and now the "Praqma" brand is being dismantled. This means the network-multitool's git and docker repositories must go. Since, I was the one maintaining the docker image for all these years, it was decided by the current representatives of the company to hand it over to me so I can continue maintaining it. So, apart from a small change in the repository name, nothing has changed.
The existing/old/previous container image `praqma/network-multitool` will continue to work and will remain available for **"some time"** - …
```
> integration: Use wbitt/network-multitool for dns integration test.

- pkg/gadgets/audit-seccomp/gadget.go
- pkg/gadgets/audit-seccomp/tracer/bpf/Makefile
- pkg/gadgets/audit-seccomp/tracer/embed-ebpf.go
- pkg/gadgets/audit-seccomp/tracer/embed-none.go
- pkg/gadgets/audit-seccomp/tracer/tracer.go
- pkg/gadgettracermanager/gadgettracermanager.go
- pkg/gadgettracermanager/gadgettracermanager_test.go
- pkg/local-gadget-manager/local-gadget-manager.go
- pkg/local-gadget-manager/local-gadget-manager_test.go
- pkg/tracer-collection/tracer-collection.go
This introduces a new package `tracer-collection` that will handle a set of tracers with their BPF maps such as `/sys/fs/bpf/gadget/mntnsset_trace_gadget_trace1`. It is used both in gadget-tracer-manager and local-gadget-manager.
Fixes https://github.com/kinvolk/inspektor-gadget/issues/579
Prepare a seccomp profile `profile.json`:
```json
{
"defaultAction": "SCMP_ACT_ALLOW",
"architectures": [
"SCMP_ARCH_X86_64"
],
"syscalls": [
{
"action": "SCMP_ACT_LOG",
"names": [
"unshare"
]
}
]
}
```
Start a container with the seccomp profile:
```
$ docker run --name demo -ti --rm --security-opt seccomp=profile.json ubuntu
```
Use the audit-seccomp gadget in local-gadget, filtering with the container name created above:
```
$ sudo ./local-gadget
» create audit-seccomp trace1 --container-selector demo …
```
> Implement filters in audit-seccomp

- cmd/kubectl-gadget/deploy.go
- BCC python-based tools were failing to start because the container was missing the sys_mod capability. 
It seems it was only happening in ARO because that system don't have the kernel headers available.
- NET_RAW: Needed by gadgets that open a raw sock like dns and snisnoop
Fixes https://github.com/kinvolk/inspektor-gadget/issues/570
Fixes https://github.com/kinvolk/inspektor-gadget/issues/568
Fixes https://github.com/kinvolk/inspektor-gadget/issues/572
Fixes https://github.com/kinvolk/inspektor-gadget/issues/569
> kubectl-gadget: Add missing capabilities needed in ARO

- gadget-container/entrypoint.sh
The previous logic was changing the directory to a path and then
removing it, which was causing issues when calling "getcwd" in BCC
python scripts.
This commit fixes the logic by using pushd/popd instead of plain cd, it
also changes the current directoy to / before executing
gadgettracermanager to be sure this problem doesn't happen again.
This solves some issues when running standard tools on ARO clusters. 
cc  @blanquicet
> entrypoint.sh: Set current directory to a valid path

- integration/command.go
Printing the output no matter whether the test failed or not allows us to understand why it failed if it did.
```bash
$ sudo -E go test -tags withebpf -run TestBiolatency -integration -no-deploy ./...
using random seed: 1649428227236645175
--- FAIL: TestBiolatency (15.37s)
command.go:204: Run command: id=$($KUBECTL_GADGET biolatency start --node $(kubectl get node --no-headers | cut -d' ' -f1)); sleep 15; $KUBECTL_GADGET biolatency stop $id
command.go:207: exit status 1
FAIL
exit status 1
FAIL    github.com/kinvolk/inspektor-gadget/integration 15.369s
```
```bash
$ sudo -E go test -tags withebpf -run TestBiolatency -integration -no-deploy ./...
using random seed: 1649428324109800923
--- FAIL: TestBiolatency (15.44s)
command.go:204: Run command: id=$($KUBECTL_GADGET biolatency start --node …
```
> integration-tests: Print the output before making the test fail

- integration/integration_test.go
Many of the integration tests run commands in a loop to generate events.
This commit add some delay between consecutive executions of the
commands to avoid creating so many events making it difficutl to handle
the test log.
> integration: add some delay to commands execution

- Makefile
- cmd/kubectl-gadget/undeploy.go
This commit adds logic to wait until the gadget namespace is removed
before returning. This is useful to guarantee that Inspektor Gadget
is completely remove when the command returns. This behaviour is
enabled by default and can be turn off by using '--wait=false'
Fixes https://github.com/kinvolk/inspektor-gadget/issues/573
> cmd/kubectl-gadget: Wait for gadget namespace to be removed

- pkg/gadgettracermanager/containerutils/containerutils.go
Call free() on variable even when there are errors to avoid leaking it.
> containerutils: Fix possible memory leak

- README.md
- cmd/kubectl-gadget/trace/sni.go
It's "Server Name Indication" instead of "Server Name Indicator"
> SNI: Fix typo

- Makefile
The local-gadget target in our Makefile requires having CLang and libbpf-dev installed locally, which are not considered required dependencies for building Inspektor Gadget. The default build target should only include targets that can be built with the listed tools.
This change removes local-gadget from "build", and creates an "all" target that includes local-gadget
Run `make` and see how it doesn't call CLang outside of docker.
Run `make all` and see how it does (or fails to, if you machine doesn't have CLang and/or libbpf-dev).
> Remove local-gadget from the default build target

- gadget-container/gadgettracermanager/main.go
- pkg/gadgettracermanager/gadgettracermanager.go
- pkg/runcfanotify/runcfanotify.go
When using the hook-mode auto, we were only checking that runc was present, but not that they system had fanotify  capabilities. In systems without `CONFIG_FANOTIFY` enabled, this would cause the Gadget Tracer Manager to fail to start.
This change checks that `fanotify_init` returns successfully before selecting it when in hook mode auto.
It also improves the error message when starting the tracer manager fails, and avoids adding the fallback podinformer when the auto hook mode selected podinformer, thus avoiding unnecessary warning messages.
I deployed the modified container to a minikube instance using the kvm driver (which was failing to start before, as explained in #612), and verified that it correctly selected the podinformer and -after fixing the fallback selection- didn't log …
> Check for fanotify support before selecting it

- pkg/gadgets/process-collector/gadget.go
- pkg/gadgets/socket-collector/gadget.go
There was a problem in the CLI where the collect operation would timeout.
Particularly, if there was, e.g., 3 nodes but target namespace only has one pod
on a given node.
Then the traces created for the nodes without trace would make the CLI code
timeout because they would never reach Completed state.
> pkg/gadget/-*collector: Mark trace as completed when no container matches.

- README.md
- docs/gadgets/_index.md
- docs/guides/_index.md
- docs/guides/advise/network-policy.md
- docs/guides/advise/seccomp-profile.md
- docs/guides/audit/seccomp.md
- docs/guides/profile/block-io.md
- docs/guides/profile/cpu.md
- docs/guides/snapshot/process.md
- docs/guides/snapshot/socket.md
- docs/guides/top/block-io.md
- docs/guides/top/file.md
- docs/guides/top/tcp.md
- docs/guides/trace/bind.md
- docs/guides/trace/capabilities.md
- docs/guides/trace/dns.md
- docs/guides/trace/exec.md
- docs/guides/trace/fsslower.md
- docs/guides/trace/mount.md
- docs/guides/trace/oomkill.md
- docs/guides/trace/open.md
- docs/guides/trace/signal.md
- docs/guides/trace/tcp.md
- docs/guides/trace/tcpconnect.md
- docs/install.md
- docs/local-gadget.md
Some of our usage guides were still using the old CLI names, and even those that weren't were using a weird title format (The "audit seccomp" gadget).  This change updates all titles to the new names, and changes the title template, e.g. Using `audit seccomp`
Also, it moves the "Gadget specs" title to "CR Usage Reference", as those specs are not about how to use the gadget, but rather what the custom resources take as parameters and so on.
There are also some other minor fixes that I ran across when reviewing the docs.
> Retitle usage guides in the docs (plus some minor updates)

- gadget.Dockerfile
- tools/btfgen.sh
Those are not needed anymore as we implemented such tools directly
in Inspektor Gadget. This changes reduces the container image size by about 60MB.
> Remove libbpf-tools from container image

- docs/guides/advise/network-policy.md
- docs/guides/advise/seccomp-profile.md
- docs/guides/audit/seccomp.md
- docs/guides/profile/block-io.md
- docs/guides/profile/cpu.md
- docs/guides/snapshot/process.md
- docs/guides/snapshot/socket.md
- docs/guides/top/block-io.md
- docs/guides/top/file.md
- docs/guides/top/tcp.md
- docs/guides/trace/bind.md
- docs/guides/trace/capabilities.md
- docs/guides/trace/dns.md
- docs/guides/trace/exec.md
- docs/guides/trace/fsslower.md
- docs/guides/trace/mount.md
- docs/guides/trace/oomkill.md
- docs/guides/trace/open.md
- docs/guides/trace/signal.md
- docs/guides/trace/tcp.md
- docs/guides/trace/tcpconnect.md
- docs/guides/traceloop.md
The documentation rendered that we're using doesn't support formatting in the titles of our docs. :(
> Remove formatting from titles

- docs/install.md
File is now called kubectl-gadget instead of inspektor-gadget
> docs: Fix installation instructions

- .github/actions/run-integration-tests/action.yml
- .github/workflows/inspektor-gadget.yml
- docs/CONTRIBUTING.md
- docs/ci.md
- integration/Dockerfile
- integration/Makefile
- integration/command.go
- integration/integration_test.go
This PR modifies the CI to also run the integration tests on a pre-created [Azure Red Hat OpenShift (ARO) cluster](https://docs.microsoft.com/en-us/azure/openshift/intro-openshift).
- It is a pre-created ARO cluster because its creation takes about 35 minutes: [documentation](https://docs.microsoft.com/en-us/azure/openshift/tutorial-create-cluster#create-the-cluster).
- Integration tests on ARO was added to the `test-integration` job with the minikube (already existing) using a [build matrix](https://docs.github.com/en/actions/using-jobs/using-a-build-matrix-for-your-jobs). Notice it was configured with `fail-fast: false` to continue running on other Kubernetes distributions so that one can understand if it is a distro-specific issue or not.
- The [concurrency …
> ci: Run integration tests on ARO

- Makefile
fanotify is already used if available, there's no reason why this should
be forced. Putting it in auto allows this rule to be used on
minikube installations that don't support fanotify (like the one used in
the cloud native bpf workshop)
> Use hook-mode=auto when deploying to minikube

- cmd/kubectl-gadget/audit/seccomp.go
- cmd/kubectl-gadget/top/block-io.go
- cmd/kubectl-gadget/top/file.go
- cmd/kubectl-gadget/top/tcp.go
- cmd/kubectl-gadget/trace/bind.go
- cmd/kubectl-gadget/trace/capabilities.go
- cmd/kubectl-gadget/trace/dns.go
- cmd/kubectl-gadget/trace/exec.go
- cmd/kubectl-gadget/trace/fsslower.go
- cmd/kubectl-gadget/trace/mount.go
- cmd/kubectl-gadget/trace/oomkill.go
- cmd/kubectl-gadget/trace/open.go
- cmd/kubectl-gadget/trace/signal.go
- cmd/kubectl-gadget/trace/sni.go
- cmd/kubectl-gadget/trace/tcp.go
- cmd/kubectl-gadget/trace/tcpconnect.go
- cmd/kubectl-gadget/utils/errors.go
- cmd/kubectl-gadget/utils/table.go
- pkg/gadgettracermanager/gadgettracermanager.go
- Fix bad json sent to client in gadget tracer manager
- Add extra information to WrapInErrUnmarshalOutput() on the client
> Fix bad json event and provide more information when unmarshal fails

- cmd/local-gadget/main.go
- pkg/container-collection/options.go
- pkg/container-utils/containerd/containerd.go
- pkg/container-utils/containerutils.go
- pkg/container-utils/crio/crio.go
- pkg/container-utils/docker/docker.go
- pkg/container-utils/runtime-client/interface.go
- pkg/gadgettracermanager/k8s/k8s.go
- pkg/local-gadget-manager/local-gadget-manager.go
- pkg/local-gadget-manager/local-gadget-manager_test.go
Currently, `local-gadget` only supports containers managed by Docker regardless they were created by Kubernetes or directly using the Docker CLI. To have such visibility, `local-gadget` communicates directly with the Docker Engine API and not the CRI (Docker-shim). 
This PR extends `local-gadget` to support CRI-O and Containerd CRIs. Notice that using the CRIs, the rogue containers (ie, not managed by Kubernetes) are not visible. It means that the containers created with `ctr` (Containerd CLI) are not yet visible by `local-gadget` (Work for a future PR).
With this PR, the `local-gadget` will try to collect the containers from Docker Engine API, CRI-O and Containerd CRIs by default. But it can be restricted, e.g. `--runtime=docker`. The Unix socket path for each runtime is also …
> local-gadget: Support CRI-O and Containerd

- docs/guides/profile/block-io.md
My previous change somehow had removed one hyphen from the file format,
causing the doc renderer to choke.
> Fix breaking typo

- pkg/gadgets/snisnoop/tracer/bpf/snisnoop.c
Unroll the loop up to TLS_MAX_SERVER_NAME_LEN iterations instead of server_name_len.
See:
https://github.com/gardener/connectivity-monitor/commit/7442cb91f3051096bb365c56a6c0cce8a2f847d5
https://github.com/gardener/connectivity-monitor/pull/25
> trace sni: fix verifier issue on some 5.15 kernels

- integration/integration_test.go
Hi.
In this PR, I added a new flag to skip integration tests for gadgets which do not have a CO-RE version.
This can be useful for #640 and #608.
Best regards.
> integration: Add a flag to skip tests which do not have CO-RE version.

- docs/CONTRIBUTING.md
This change tries to make the Contributing page more accessible by
better organizing the content.
Additionally, it adds links to our public planning boards.
> Rework Contributing page and add Planning section

- README.md
- cmd/kubectl-gadget/profile/block-io.go
- cmd/kubectl-gadget/profile/cpu.go
- cmd/kubectl-gadget/snapshot/socket.go
- docs/guides/advise/network-policy.md
- docs/guides/advise/seccomp-profile.md
- docs/guides/audit/seccomp.md
- docs/guides/general-usage.md
- docs/guides/profile/block-io.md
- docs/guides/profile/cpu.md
- docs/guides/snapshot/process.md
- docs/guides/snapshot/socket.md
- docs/guides/top/block-io.md
- docs/guides/top/file.md
- docs/guides/top/tcp.md
- docs/guides/trace/bind.md
- docs/guides/trace/capabilities.md
- docs/guides/trace/dns.md
- docs/guides/trace/exec.md
- docs/guides/trace/fsslower.md
- docs/guides/trace/mount.md
- docs/guides/trace/oomkill.md
- docs/guides/trace/open.md
- docs/guides/trace/signal.md
- docs/guides/trace/sni.md
- docs/guides/trace/tcp.md
- docs/guides/trace/tcpconnect.md
- docs/guides/traceloop.md
This PR includes three documentation changes:
- Add a guide documenting common parameters (pod selection, output formatting, kubernetes runtimes CLI)
- Review all guides to ensure that the gadgets are named correctly and also fix typos and so on.
- Add descriptions to all guides, for the Overview page. Which looks like this:
Fixes: #495
> Add general usage page, improve guides navigation and content

- cmd/kubectl-gadget/profile/block-io.go
- docs/guides/profile/block-io.md
- integration/integration_test.go
Before this commit the profile block-io (biolatency) gadget needed
multiple iterations to get a result:
$ kubectl gadget profile block-io start --node worker-node
4b5501BrEjiw2GxG
$ kubectl gadget profile block-io stop 4b5501BrEjiw2GxG
<histogram printed here>
This commit changes it to make it a "single execution" command printing
the results when Ctrl+C is hit:
$ kubectl gadget profile block-io --node worker-node
Tracing block device I/O... Hit Ctrl-C to end^C
Tracing block device I/O... Hit Ctrl-C to end.
usecs               : count     distribution
0 -> 1          : 0        |                                        |
2 -> 3          : 0        |                                        |
4 -> 7          : 0        |                                        |
8 -> 15         : 0        | …
> profile: Rework block-io CLI

- integration/command.go
- integration/integration_test.go
This PR modifies the integration tests to not install the SPO from the `main` branch but the latest released version to ease the maintenance of the CI. In this way, we just need to verify that the integration tests are working correctly after each new release instead of dealing with all the changes introduced to the `main` branch.
This PR also avoids limiting the resources when the integration tests are running on ARO where we have 6 nodes and we don't have resource limitations like in the case of Minikube running on a GH runner.
> ci/integration-tests: Install a fixed version of SPO and CertManager

- .github/actions/run-integration-tests/action.yml
- integration/Makefile
- integration/command.go
- integration/integration_test.go
Fixes: https://github.com/kinvolk/inspektor-gadget/issues/641 
Based on the [GitHub documentation](https://docs.github.com/en/actions/managing-workflow-runs/canceling-a-workflow#steps-github-takes-to-cancel-a-workflow-run), this is the proposed solution:
1. Capture the `SIGINT` sent from bash on runner: [here](https://github.com/kinvolk/inspektor-gadget/blob/b47a55db25c1f976e9ac73200e34034512737b58/.github/actions/run-integration-tests/action.yml#L58-L63).
2. Notify the container that the workflow run is being cancelled, [here](https://github.com/kinvolk/inspektor-gadget/blob/b47a55db25c1f976e9ac73200e34034512737b58/.github/actions/run-integration-tests/action.yml#L41-L56). Notice that it is done only when the `SIGINT` is received. For `SIGTERM`, we just capture the signal so that we have …
> ci/integration-tests: Clean up resources when the workflow run is cancelled

- cmd/kubectl-gadget/trace/capabilities.go
The capabilities gadget was using the wrong function to print the custom-columns headers.
> cmd/kubectl-gadget: Fix capabilities headers printer

- Makefile
Hi.
In this PR, I `s/gadget-container/gadget-default-container/` for `minikube-install` Makefile target.
For now, I prefer to use default instead of CO-RE.
Best regards.
> Use gadget-default-container as minikube-install dependency.

- integration/command.go
- integration/integration_test.go
This PR fixes two issues:
1. The SPO installation was sometimes failing with timeout (also in Minikube) because we were not waiting correctly for the SPO daemon to be ready. 
2. The AuditSeccomp test was failing on ARO because the seccomp profile took around 2 minutes to be installed into the nodes. After investigating this issue, I found that those 2 minutes are not needed to install the seccomp profile but to wait until the SPO daemon is ready. That's why these two issues are correlated. Therefore, I decided to create one single PR to solve them.
Proposed solutions:
1. Manually wait for the SPO daemon to be created (It is not installed as part of the YAML but by the SPO so we cannot use kubectl-wait). Then, if needed, remove the resource management from the SPO webhook and daemon and …
> ci/integration-tests: Improve SPO installation and enable AuditSeccomp test on ARO

- integration/Makefile
The CI is capturing the signal sent by GH when a cancellation occurs, but it is not able to forward it to the integration-tests container because it does not have the expected name:
[CI is notifying](https://github.com/kinvolk/inspektor-gadget/blob/820cf8312ac0d89a3907b5d0149dd39597a37a66/.github/actions/run-integration-tests/action.yml#L41-L63) the container, but it is not named as expected:
```
docker kill --signal="SIGINT" ig-integration-tests
```
This error comes from a wrong rebased of https://github.com/kinvolk/inspektor-gadget/pull/653 where this modification got lost somehow.
Force-pushing a commit on the same branch while running the integration tests or manually cancelling it on the Actions section of the repo.
The cancellation request is captured, but it is not forwarded to the …
> ci/integration-tests: Name the container to notify it about cancellation

- pkg/local-gadget-manager/local-gadget-manager_test.go
Increase the maximum time we wait before failing the test to give enough
time to the runcnotify poll logic to finish.
I run the tests 11 times in https://github.com/kinvolk/inspektor-gadget/actions/runs/2476289888 and all of them are passing. 
This issue was introduced in https://github.com/kinvolk/inspektor-gadget/pull/656.
> local-gadget-tracer-manager: Fix leak fds testing

- .github/workflows/inspektor-gadget.yml
- .golangci.yml
- crd.mk
- docs/install.md
- go.mod
- go.sum
- hack/client-gen.sh
- pkg/gadgets/capabilities/tracer/core/tracer.go
- pkg/gadgets/execsnoop/tracer/core/tracer.go
- pkg/gadgets/filetop/tracer/tracer.go
- pkg/gadgets/fsslower/tracer/core/tracer.go
- pkg/gadgets/mountsnoop/tracer/core/tracer.go
- pkg/gadgets/opensnoop/tracer/core/tracer.go
- pkg/gadgets/sigsnoop/tracer/core/tracer.go
- pkg/gadgets/standardtracerbase.go
- pkg/gadgets/tcpconnect/tracer/core/tracer.go
Go 1.18 is useful because:
- it introduces generics (see #695)
- we depends on cilium/ebpf which requires Go 1.18
This PR updates to Go 1.18, update the GitHub Action with the cache feature from `setup-go` and add fixes required by Go 1.18.
No changes.
None
> go: Update to version 1.18

- docs/guides/advise/seccomp-profile.md
- integration/command.go
The SPO releases [v0.4.3](https://github.com/kubernetes-sigs/security-profiles-operator/releases/tag/v0.4.3). From [the installation usage](https://github.com/kubernetes-sigs/security-profiles-operator/blob/v0.4.3/installation-usage.md), it says that it is necessary to install the CertManager v1.8.0.
After some local tests, I noticed that the installation takes almost 2 min (which is also our timeout), so I increased the timeout.
CI tests passed.
> ci/integration-tests: Update to the use new version of SPO/CertManager

- gadget-core.Dockerfile
- gadget-default.Dockerfile
- integration/Dockerfile
- integration/Makefile
- integration/go.mod
- integration/go.sum
- local-gadget-linux-arm64.Dockerfile
The Dockerfiles were forgotten in the previous update to Go 1.18
Follow-up to https://github.com/kinvolk/inspektor-gadget/pull/696
> go: Update to version 1.18 in Dockerfiles

- Makefile
The minikube-install target was using 'minikube docker-env', which only
works with the docker container runtime. Also support 'minikube image
load' for other container runtimes.
```
$ minikube start --container-runtime=containerd --cni=calico
...
$ make minikube-install
...
Image on the host:
docker image list --format "table {{.ID}}\t{{.Repository}}:{{.Tag}}\t{{.Size}}" |grep albantest.azurecr.io/gadget:alban_minikube_containerd
dbda06991888   albantest.azurecr.io/gadget:alban_minikube_containerd                        805MB
...
Image in Minikube:
minikube image ls --format=table | grep "albantest.azurecr.io/gadget\s*|\s*alban_minikube_containerd" || true
| albantest.azurecr.io/gadget             | alban_minikube_containerd | sha256:dbda06 | 354MB  |
...
kubectl rollout status daemonset …
```
> Makefile: support containerd in minikube-install target

- cmd/kubectl-gadget/deploy.go
Use quotes to ensure that string fields are parsed as a string and avoid the following error when the values could be also parsed as a number, e.g. `8510575` or `47704e5` (which is read as `4770400000`).
```bash
$ kubectl-gadget deploy $GADGET_IMAGE_FLAG | kubectl apply -f -
Error from server (BadRequest): error when creating "STDIN": DaemonSetin version "v1" cannot be handled as a DaemonSet: v1.DaemonSet.Spec:v1.DaemonSetSpec.Template: v1.PodTemplateSpec.Spec:v1.PodSpec.Containers: []v1.Container: v1.Container.Env: []v1.EnvVar:v1.EnvVar.Value: ReadString: expects " or n, but found 8, error found in #10 byte of ...|,"value":8510575},{"|..., bigger context...|-re"},{"name":"INSPEKTOR_GADGET_VERSION","value":8510575},{"name":"INSPEKTOR_GADGET_OPTION_HOOK_MODE|...
```
This issue was making …
> kubectl-gadget/deploy: Use quotes to avoid incorrect parsing

- cmd/kubectl-gadget/main.go
- cmd/kubectl-gadget/snapshot/process.go
- cmd/kubectl-gadget/snapshot/snapshot.go
- cmd/kubectl-gadget/snapshot/socket.go
- cmd/kubectl-gadget/utils/errors.go
- cmd/kubectl-gadget/utils/flags.go
- pkg/gadgets/process-collector/types/process-collector.go
- pkg/gadgets/socket-collector/types/socket-collector.go
This PR factorizes the code of the snapshot gadgets to avoid repeating patterns on each of them. The common code was moved to a snapshot source code, and each gadget kept only its specific code.
I used generics to simplify the code. It implies updating the required Go to v1.18.
- I tried to make progressive changes at each commit so that it is easier to do a review per commit.
- Please consider that the final goal of this series of PRs is to move most of the code to other packages and then use it from local-gadget.
> cmd/kubectl-gadget: Avoid repeated code on snapshot gadgets

- cmd/kubectl-gadget/trace/fsslower.go
- integration/integration_test.go
The parameter is called "type" and not filesystem.
> kubectl-gadget: Fix typo in fsslower command

- cmd/kubectl-gadget/advise/seccomp-profile.go
- cmd/kubectl-gadget/profile/block-io.go
- cmd/kubectl-gadget/profile/cpu.go
- cmd/kubectl-gadget/snapshot/snapshot.go
- cmd/kubectl-gadget/utils/trace.go
This PR removes the dependency of the Trace CR from the CLI-specific code. Now, the only code that imports `gadgetv1alpha1` is [utils/trace](https://github.com/kinvolk/inspektor-gadget/blob/d31164c5726530fd81eb50bbb4156b92ab474fad/cmd/kubectl-gadget/utils/trace.go#L40) which is indeed the module in charge of transforming the user request (through the CLI) to a Trace CR to communicate with the gadget pod.
The advise-seccomp gadget could be still improved to use `PrintTraceOutputFromStatus` only when it is using the `Status` output mode. It would also allow to remove the `traceOutputMode` from the callback, see [here](https://github.com/kinvolk/inspektor-gadget/blob/da286f7ed1ed3769840d402cada5f4172bb9cd03/cmd/kubectl-gadget/utils/trace.go#L716-L719).
It does not have any impact on the …
> kubectl-gadget: Remove trace CR dependency from CLI code

- pkg/gadgets/network-graph/tracer/bpf/graph.h
This commit fixes a compilation issue when building the eBPF programs
of the network-graph gadget:
```
In file included from [...]pkg/gadgets/network-graph/tracer/bpf/graphmap.c:4:
In file included from ./bpf/graphmap.h:10:
./bpf/graph.h:7:10: fatal error: '../../../../vmlinux/vmlinux-cgo.h' file not found
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
Error: clang: exit status 1
exit status 1
tracer.go:30: running "bash": exit status 1
```
This uses the same approach as in the audit-seccomp gadget.
> gadgets/network-graph: Fix eBPF code compilation

- Makefile.btfgen
Only consider the objects for the current architecture when using BTFGen.
> Makefile: Filter BPF objects by architecture in BTFGen

- cmd/kubectl-gadget/profile/block-io.go
This PR fixes the following error (full logs [here](https://github.com/kinvolk/inspektor-gadget/runs/7330130963?check_suite_focus=true)) introduced in PR https://github.com/kinvolk/inspektor-gadget/pull/746:
```bash
--- FAIL: TestBiolatency (15.54s)
command.go:378: Run command(RunBiolatencyGadget):
$KUBECTL_GADGET profile block-io --node $(kubectl get node --no-headers | cut -d' ' -f1 | head -1) --timeout 15
command.go:380: Command returned(RunBiolatencyGadget):
Error: failed to run gadget on node "fv-az135-470": Not started
panic: runtime error: index out of range [0] with length 0
github.com/kinvolk/inspektor-gadget/cmd/kubectl-gadget/profile.(*BlockIOParser).DisplayResultsCallback(0xc0003f3320?, {0xc0001a7a28?, 0x44b6b2?}, {0x25de840, 0x0, 0x9?}) …
```
> cmd/kubeclt-gadget: Do not try to print empty results in profile/block-io

- cmd/kubectl-gadget/trace/bind.go
- cmd/kubectl-gadget/trace/capabilities.go
- cmd/kubectl-gadget/trace/dns.go
- cmd/kubectl-gadget/trace/exec.go
- cmd/kubectl-gadget/trace/fsslower.go
- cmd/kubectl-gadget/trace/mount.go
- cmd/kubectl-gadget/trace/network.go
- cmd/kubectl-gadget/trace/oomkill.go
- cmd/kubectl-gadget/trace/open.go
- cmd/kubectl-gadget/trace/signal.go
- cmd/kubectl-gadget/trace/sni.go
- cmd/kubectl-gadget/trace/tcp.go
- cmd/kubectl-gadget/trace/tcpconnect.go
- cmd/kubectl-gadget/trace/trace.go
The implementations of TraceParser already have this information when
they are instantiated. (BaseParser on this case). Hence, remove that
parameter to make this interface simpler.
> cmd/kubectl-gadget: Remove requestedColumns parameter from TransformEvent()

- go.mod
- go.sum
- pkg/local-gadget-manager/local-gadget-manager_test.go
cilium/ebpf v0.9.1 has the following fix:
https://github.com/cilium/ebpf/commit/54f34552d7e3ddc690722fd1f1dcc7685962c216
So the ebpf file descriptors are correctly closed and it is no longer
necessary to call runtime.GC() explicitly.
> go.mod: update cilium/ebpf and remove GC workaround

- cmd/kubectl-gadget/deploy.go
It seems there was an issue with a merge.
d3ba10e4e6fc ("cmd/common: Move error wrappers to common package") moved
WrapInErrSetupK8sClient() to "cmd/common/utils" and
2a233cad91dc ("cmd/kubectl-gadget: Use k8s API for deploy operation.")
didn't take it into account.
> cmd/kubectl-gadget: Fix compilation

- cmd/common/snapshot/process.go
- cmd/common/snapshot/snapshot.go
- cmd/common/snapshot/socket.go
- cmd/common/utils/parser.go
- cmd/common/utils/parser_test.go
- cmd/kubectl-gadget/profile/cpu.go
- cmd/kubectl-gadget/snapshot/process.go
- cmd/kubectl-gadget/snapshot/socket.go
- cmd/kubectl-gadget/trace/bind.go
- cmd/kubectl-gadget/trace/capabilities.go
- cmd/kubectl-gadget/trace/dns.go
- cmd/kubectl-gadget/trace/exec.go
- cmd/kubectl-gadget/trace/fsslower.go
- cmd/kubectl-gadget/trace/mount.go
- cmd/kubectl-gadget/trace/network.go
- cmd/kubectl-gadget/trace/oomkill.go
- cmd/kubectl-gadget/trace/open.go
- cmd/kubectl-gadget/trace/signal.go
- cmd/kubectl-gadget/trace/sni.go
- cmd/kubectl-gadget/trace/tcp.go
- cmd/kubectl-gadget/trace/tcpconnect.go
- cmd/kubectl-gadget/trace/trace.go
- cmd/local-gadget/snapshot/process.go
- cmd/local-gadget/snapshot/socket.go
When working on https://github.com/kinvolk/inspektor-gadget/pull/763, I wanted to reuse the logic already implemented for snapshot gadgets to print columns separated by taps. Therefore, I thought to move the `BaseSnapshot` implementation to the common utils library. However, once there, I realized that it was pretty similar to the already existing `BaseParser` used by other gadgets (trace category and profile/cpu gadget). The only difference is that one uses tabs and the other uses a predefined width. Therefore, I decided to [merge them](https://github.com/kinvolk/inspektor-gadget/blob/661aab572fa2554d3b158d9bac6561cba41a095b/cmd/common/utils/parser.go#L22-L36) and add a `SeparateWithTabs` which allows specifying whether the parser has to print using tabs or the predefined width.
Tests …
> cmd/common: Merge `BaseSnapshot` and `commonutils.BaseParser`

- cmd/local-gadget/containers/containers.go
- pkg/container-collection/containers.go
- pkg/container-collection/options.go
- pkg/container-utils/docker/docker.go
- pkg/container-utils/runtime-client/interface.go
This PR enriches the `list-containers` command to show the ID and the name of the runtime managing the container:
```bash
$ sudo local-gadget list-containers
RUNTIME       ID               NAME
containerd    7766d32caded4    calico-kube-controllers
containerd    2e3e4968b456f    calico-node
containerd    d3be7741b94ff    coredns
containerd    e7be3e4dc1bb4    coredns
containerd    fb4fe41921f30    etcd
containerd    136e7944d2077    kube-apiserver
containerd    ad8709a2c2ded    kube-controller-manager
containerd    66cf05654a47f    kube-proxy
containerd    a68bed42aa6b2    kube-scheduler
docker        95b814bb82b9e    myContainer
```
The flag `--no-trunc` was also implemented:
```bash
$ sudo local-gadget list-containers --no-trunc
RUNTIME       ID …
```
> cmd/local-gadget: Enrich list-containers with ID and Runtime information

- Makefile
- pkg/gadget-collection/gadgets/trace/network/gadget.go
The trace/network gadget checks the content of a global BPF map every
second in a go routine. When a pod is deleted, the BPF program for that
network namespace is removed in a different go routine.
This patch handles the pod deletion in the same go routine and make sure
that the BPF map is read before.
Symptoms:
```bash
$ make local-gadget-tests
=== RUN   TestNetworkGraph
local-gadget-manager_test.go:120: Container docker.io/library/alpine output:
local-gadget-manager_test.go:492: Received: {Event:{Type:debug Message:tracer detached Node:local Namespace:default Pod:test-local-gadget-network-graph001 Container:} PktType: Proto: IP: Port:0 RemoteKind: PodHostIP: PodIP: PodOwner: PodLabels:map[] RemoteSvcNamespace: RemoteSvcName: RemoteSvcLabelSelector:map[] RemotePodNamespace: …
```
> trace/network: fix race on containerDetach

- pkg/resources/manifests/deploy.yaml
`kubectl apply -f pkg/resources/manifests/deploy.yaml` wasn't working because the image was wrong.
> pkg/resources: Fix image tag in manifest

- pkg/gadgets/snapshot/process/tracer/tracer.go
- pkg/gadgets/snapshot/socket/tracer/tracer.go
The documentation on NewCollectionWithOptions() states that
"Omitting Collection.Close() during application shutdown is an error.",
this commit fixes that by adding this missing line.
Even if AttachIter() doesn't state we should call Close() on the 
returned link, it's a good practice.
> gadgets/collect/process: Add missing Close() calls

- cmd/common/snapshot/process.go
- cmd/common/snapshot/snapshot.go
- cmd/common/snapshot/socket.go
- cmd/common/utils/parser.go
- cmd/common/utils/parser_test.go
- cmd/kubectl-gadget/audit/seccomp.go
- cmd/kubectl-gadget/profile/cpu.go
- cmd/kubectl-gadget/trace/bind.go
- cmd/kubectl-gadget/trace/capabilities.go
- cmd/kubectl-gadget/trace/dns.go
- cmd/kubectl-gadget/trace/exec.go
- cmd/kubectl-gadget/trace/fsslower.go
- cmd/kubectl-gadget/trace/mount.go
- cmd/kubectl-gadget/trace/network.go
- cmd/kubectl-gadget/trace/oomkill.go
- cmd/kubectl-gadget/trace/open.go
- cmd/kubectl-gadget/trace/signal.go
- cmd/kubectl-gadget/trace/sni.go
- cmd/kubectl-gadget/trace/tcp.go
- cmd/kubectl-gadget/trace/tcpconnect.go
- cmd/kubectl-gadget/trace/trace.go
- cmd/kubectl-gadget/utils/trace.go
- cmd/local-gadget/containers/containers.go
Before this PR, all the gadgets using `RunTraceAndPrintStream` don't have the full control over the JSON output mode because this function was internally managing that case [here](https://github.com/kinvolk/inspektor-gadget/blob/0f5fd1688e67494beb52dd995d2dbb69f2e4ad53/cmd/kubectl-gadget/utils/trace.go#L928-L930). However, with the introduction of the gadget parsers, keeping this logic on the utils/trace doesn't make sense anymore. The full management of the output format must be controlled by the parsers.
In this PR, the logic to print the received lines was moved from [cmd/kubectl-gadget/utils/trace.go](https://github.com/kinvolk/inspektor-gadget/blob/0f5fd1688e67494beb52dd995d2dbb69f2e4ad53/cmd/kubectl-gadget/utils/trace.go#L928-L930) to …
> cmd: Manage JSON output mode outside of utils/trace

- cmd/kubectl-gadget/audit/audit.go
- cmd/kubectl-gadget/audit/seccomp.go
- cmd/kubectl-gadget/main.go
- integration/integration_test.go
With this PR, the audit-seccomp gadget starts using the `BaseParser` to reuse the logic that prints the header columns and transforms the events into columns.
In addition, using `BaseParser` for all the gadgets that support JSON and columns output modes will make easier the implementation of some common features like: combine the `OutputModeColumns` and `OutputModeCustomColumns` and printing the columns that can be used with `custom-columns`.
The only impact of these changes is that the columns now follow the order we defined for other gadgets: node, podname, container, pid, comm and then the rest.
Integration tests were updated with the changes in the order of the columns, and it is passing.
> cmd/kubectl-gadget/audit: Use BaseParser on seccomp gadget

- pkg/gadget-collection/gadgets/audit/seccomp/gadget.go
- pkg/gadgets/audit/seccomp/tracer/tracer.go
Enriching the event with node information on the gadget-collection side allows using the tracer from outside a Kubernetes context. For instance, from local-gadget or 3rd party apps using IG packages. 
No changes for users.
> audit/seccomp: Remove node parameter from tracer

- cmd/kubectl-gadget/undeploy.go
The undeploy command wasn't printing any error when there was a timeout
trying to remove the gadget namespace. It was misleading as Inspektor
Gadget was not actually removed and the command exited with 0.
> kubectl-gadget: Print error when undeploy command timeouts

- integration/integration_test.go
Enable it again when https://github.com/kinvolk/inspektor-gadget/issues/371 is done.
> integration: Disable TestTraceloop

- integration/command.go
- integration/integration_test.go
- pkg/resources/manifests/deploy.yaml
2a233cad91dc ("cmd/kubectl-gadget: Use k8s API for deploy operation.")
introduced some logic in the deploy command to wait until the gadget
pods are ready to process operations. The logic checks that the number
of ready pods in the daemon set is the desired one.
Even if the logic was right, (it waited until all pods where Ready),
there was a missing piece. It could happen that the gadget tracer
manager is started but it's not ready to take requests yet becuase its
initialization isn't done. This issue happens sometimes when we try to
run a gadget just after deploying Inspektor Gadget on a heavy loaded
machine:
```
$ ./kubectl-gadget deploy && ./kubectl-gadget snapshot process
Creating Namespace/gadget...
Creating ServiceAccount/gadget...
Creating Role/gadget-role...
Creating …
```
> cmd/kubect-gadget: Add readiness probe

- docs/gadgets/seccomp.md
- docs/local-gadget.md
- pkg/container-collection/container-collection.go
- pkg/container-collection/containers.go
- pkg/container-collection/interface.go
- pkg/container-collection/match_test.go
- pkg/container-collection/options.go
- pkg/gadget-collection/gadgets/advise/seccomp/gadget.go
We copied the OwnerReference definition in IG because it needed to be included in the gRPC interface. Since commit https://github.com/kinvolk/inspektor-gadget/commit/a84b26fd6525feb2cfe782292392c2e5ed9dde95, it is no longer in the gRPC interface, so we can now use the OwnerReference type from Kubernetes upstream.
In addition, add JSON tags to the Container struct because it is useful for the `local-gadget list-containers` command.
> pkg/container-collection: Add `omitempty` tag to Container struct

- cmd/common/audit/seccomp.go
- cmd/common/utils/parser.go
- cmd/kubectl-gadget/audit/seccomp.go
- docs/guides/audit/seccomp.md
- pkg/gadgets/audit/seccomp/types/types.go
By moving the parser code to the `common` folder, we are allowing 3rd party apps to use it without importing the code of kubectl-gadget. In addition, there is no need to specify the columns to be printed by default, only if one wants to specify exactly which ones to print. Check the example below.
This is the first step to running the audit/seccomp gadget from `local-gadget` using the tracer directly instead of passing through the CRD.
Once we agree it is the correct approach, I will do the same work for the rest of the gadgets.
For `kubectl-gadget` nothing changes. Instead, after this PR, unlike [this example](https://github.com/kinvolk/inspektor-gadget/pull/764#pullrequestreview-1054463622) for the trace/exec gadget, the audit/seccomp gadget parse can be used by importing only packages …
> audit/seccomp: Move parser to common folder

- integration/integration_test.go
Now all our gadgets support CO-RE, hence we can revert 9327f2f6dda6c752c593471f58c3153ca5aa30bd.
> Revert "integration: Add a flag to skip tests without CO-RE version."

- integration/command.go
- integration/integration_test.go
Make integration tests work on ARO. More details in https://github.com/kinvolk/inspektor-gadget/issues/799.
> integration: Disable liveness probes when running on ARO

- gadget-container/entrypoint.sh
- gadget-core.Dockerfile
- Do not fail when checking BCC version
- Fix dependency install command with apt-get
- Install util-linux to provide mount command
This PR installs some of the dependencies mentioned in https://github.com/kinvolk/inspektor-gadget/issues/801, some are still missing but I'd like to handle it directly in https://github.com/kinvolk/inspektor-gadget/issues/801.
> Fix issues with CO-RE container image

- integration/command.go
A space before "--image" is needed, otherwise it fails with
"Error: invalid argument "true--image=XXX" for "--liveness-probe""
Fixes: b9db9360d8b8 ("integration: Disable liveness probes when running on ARO")
> integration: Fix logic to generate command

- cmd/kubectl-gadget/consts.go
- cmd/kubectl-gadget/debug.go
- cmd/kubectl-gadget/deploy.go
- cmd/kubectl-gadget/undeploy.go
- integration/command.go
Add a "--debug" option to print extra information when the deploy
command fails. It's useful for scenarios where it's not possible to
access the logs, like the CI, and also to ask for more information in
case a user reports an issue.
We need to make the deploy to fail. One option is to add a delay to the gadget tracer manager and use a smaller timeout:
```diff
diff --git gadget-container/gadgettracermanager/main.go gadget-container/gadgettracermanager/main.go
index 7325c875..019f8905 100644
--- gadget-container/gadgettracermanager/main.go
+++ gadget-container/gadgettracermanager/main.go
@@ -214,6 +214,9 @@ func main() {
log.Fatalf("Environment variable NODE_NAME not set")
}
+               fmt.Printf("sleeping\n")
+               time.Sleep(20 * time.Second)
+
lis, err := …
```
> kubectl-gadget: add more detailed error logs when deploying fails

- examples/README.md
- examples/container-collection/.gitignore
- examples/container-collection/README.md
- examples/container-collection/container-collection.go
Add an example that uses this package. It's simpler than the
"kube-container-collection" as Kubernetes is not used.
> examples: Add basic ContainerCollection example

- .golangci.yml
- pkg/container-utils/runtime-client/interface.go
grpc.WithDialer() is marked as deprecated, so we need to move on to grpc.WithContextDialer().
Fixes #541
> pkg/container-utils/runtime-client: replace grpc.WithDialer() with grpc.WithContextDialer()

- cmd/kubectl-gadget/top/top.go
We're using snake-case for CLI parameters.
> cmd/kubectl-gadget: Rename maxRows to max-rows

- cmd/kubectl-gadget/main.go
- cmd/kubectl-gadget/top/block-io.go
- cmd/kubectl-gadget/top/ebpf.go
- cmd/kubectl-gadget/top/file.go
- cmd/kubectl-gadget/top/tcp.go
- cmd/kubectl-gadget/top/top.go
This PR modifies the top category gadgets to use `BaseParser` so that they don't have to implement the logic to print the header and transform stats to columns.
This PR doesn't modify the logic or current behaviour of the gadgets. This PR aims to uniform this category with the rest of the categories so we can manage the two mentioned logics from a single place for all the gadgets. For instance, combine the `OutputModeColumns` and `OutputModeCustomColumns`, and printing the columns that can be used with the `custom-columns` flag.
These changes don't have any impact on the user.
> cmd/kubectl-gadget/top: Use `BaseParser` to uniform and simplify gadgets

- .github/workflows/inspektor-gadget.yml
According to [the documnetation](https://docs.github.com/en/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks), it would add the button because we configured the repo with _Require approval for all outside collaborators_.
> ci: Allow running workflow on pull_request to test external contributions

- pkg/bpfstats/bpfstats.go
- pkg/resources/manifests/deploy.yaml
Instead of using `/proc/sys/kernel/bpf_stats_enabled` directly, this PR prefixes it with the environment variable `HOST_ROOT`, which defaults to `/host`.
This will be enabled by default and used whenever the fallback for enabling ebpf stat collection is used.
Fixes #850
> pkg/bpfstats: introduce and use HOST_ROOT for bpf_stats_enabled fallback

- cmd/kubectl-gadget/top/ebpf.go
- docs/gadgets/ebpftop.md
- docs/guides/top/ebpf.md
- pkg/gadgets/top/ebpf/tracer/tracer.go
- pkg/gadgets/top/ebpf/types/types.go
- pkg/resources/samples/trace-ebpftop.yaml
This PR adds cumulative stats (runtime and run count) that use times and counters relative to the start of the trace (instead of relative to the last interval and absolute values, which are already handled).
I also refactored how previous stats were saved to avoid unnecessary lookups.
```
kubectl gadget top ebpf -o custom-columns=node,progid,type,name,runtime,runcount,totalruncount,totalruntime,cumulruncount,cumulruntime --sort totalruntime
```
will output something like this:
```
NODE             PROGID   TYPE             NAME                  RUNTIME   RUNCOUNT TOTALRUNCOUNT TOTALRUNTIME CUMULRUNCOUNT CUMULRUNTIME
minikube         2346     Tracing          gadget_ebpftop        72.92µs       1059         18012   1.676893ms         18012   1.676893ms
minikube         24 …
```
> pkg/gadgets/top/ebpf: introduce cumulruntime and cumulruncount

- pkg/container-utils/docker/docker.go
The correct variable to use is State instead of Status. It was causing
to always have the State as "unknown", causing
"./local-gadget list-containers" not to show any docker containers.
Fixes: 6444282dc5d1 ("Replace `PidFromContainerID` for `GetContainerDetails`, providing more details")
> pkg/container-utils/docker: Fix bad state

- cmd/kubectl-gadget/top/ebpf.go
- docs/gadgets/ebpftop.md
- docs/guides/top/ebpf.md
- pkg/gadgets/top/ebpf/tracer/tracer.go
- pkg/gadgets/top/ebpf/types/types.go
- pkg/resources/samples/trace-ebpftop.yaml
This PR will add the number and the maximum size of the referenced maps to the programs. It does so by getting the referenced map ids using the cilium/ebpf library and then getting information about the defined sizes for that map (then it's basically (keysize+valuesize)*maxentries).
```
$ kubectl gadget top ebpf --sort mapmemory
NODE             PROGID   TYPE             NAME             PID     COMM                      RUNTIME   RUNCOUNT      MAPMEMORY MAPCOUNT
minikube         3460     Kprobe           vfs_write_entry  4169649 gadgettracerman         467.908µs        257     40.953 MiB        4
minikube         3459     Kprobe           vfs_read_entry   4169649 gadgettracerman         380.821µs        414     40.953 MiB        4
minikube         3458     Tracing          gadget_ebpftop …
```
> pkg/gadgets/top/ebpf: add information about referenced maps and their size

- pkg/container-utils/cri/cri.go
- pkg/container-utils/docker/docker.go
- pkg/container-utils/runtime-client/interface.go
Add pod UID, name and namespace to the `CotnainerExtendedData` structure.
This is relevant only for containerd and cri-o.
PR has dependency on #819
> container-utils: Add pod info to runtime client's container data

- Makefile
Currently, the following commands fail:
```
$ make build install/kubectl-gadget
```
Because the first target produces 'kubectl-gadget' but then requires 'kubectl-gadget-linux-amd64'.
In general, a Makefile target should not remove the output of a previous target, unless it is something like the 'clean' target.
> Makefile: fix target dependencies

- .github/workflows/inspektor-gadget.yml
- .golangci.yml
- Makefile
- pkg/apis/gadget/v1alpha1/groupversion_info.go
- pkg/gadgets/trace/network/tracer/tracer.go
- pkg/gadgets/trace/tcp/tracer/tracer.go
- pkg/gadgettracermanager/containers-map/tracer.go
In https://github.com/kinvolk/inspektor-gadget/pull/821 I'm hitting https://github.com/golangci/golangci-lint/issues/2859, hence I need to update the version of golangci-lint to something that contains https://github.com/golangci/golangci-lint/pull/2976.
I decided to switch to the latest release (v1.49.0) to keep it as updated as possible. I have to add an exception for `SA1019: "io/ioutil" has been deprecated since Go 1.16`, we can fix it later on.
> lint: Update to golangci-lint v1.49.0 and fix issues detected by it.

- .github/workflows/inspektor-gadget.yml
- Makefile
- pkg/gadgets/internal/test/helpers.go
- pkg/gadgets/internal/test/runner.go
- pkg/gadgets/trace/bind/tracer/tracer.go
- pkg/gadgets/trace/capabilities/tracer/tracer.go
- pkg/gadgets/trace/exec/tracer/tracer.go
- pkg/gadgets/trace/exec/tracer/tracer_test.go
- pkg/gadgets/trace/fsslower/tracer/tracer.go
- pkg/gadgets/trace/mount/tracer/tracer.go
- pkg/gadgets/trace/oomkill/tracer/tracer.go
- pkg/gadgets/trace/open/tracer/tracer.go
- pkg/gadgets/trace/open/tracer/tracer_test.go
- pkg/gadgets/trace/signal/tracer/tracer.go
- pkg/gadgets/trace/tcp/tracer/tracer.go
This PR proposes a reusable logic to implement unit tests for the different gadgets. Motivation to add unit tests can be found in https://github.com/kinvolk/inspektor-gadget/issues/817.
One easy way to try it is to run the new tests `make gadget-unit-tests`, but it's not so interesting as tested as expected to pass. A more interesting way is to introduce bugs and check how they're detected by those tests:
```bash
$ git diff pkg/gadgets/trace/exec/
diff --git pkg/gadgets/trace/exec/tracer/tracer.go pkg/gadgets/trace/exec/tracer/tracer.go
index ac7d88c7..87481b19 100644
--- pkg/gadgets/trace/exec/tracer/tracer.go
+++ pkg/gadgets/trace/exec/tracer/tracer.go
@@ -153,7 +153,7 @@ func (t *Tracer) run() {
Event: eventtypes.Event{
Type: eventtypes.NORMAL,
},
-                       Pid: …
```
> pkg/gadgets/trace/{exec,open}: Implement unit tests

- .github/workflows/inspektor-gadget.yml
- integration/command.go
- integration/integration_test.go
This PR switches to artifact based [image sharing ](https://github.com/docker/build-push-action/blob/master/docs/advanced/share-image-jobs.md) allowing PR checks on external contributions. Also, we don't need `package: write` permissions during normal CI run and hence limiting access to our production package registry as well. 
Fixes #873 Related #823
(1) Build the image for each architecture in parallel
(2) Run `buildx` to push by digest (this run will be fast because it uses the cache from the previous steps)
(3) Use `docker buildx imagetools create` to "push" the manifest for the image.
(4) Fetch image from the artifact and load in minikube for integration-testing.
(5) Make the workflow permissions `read-only` and only open them at job level.
- …
> ci: switch from registry to artifact based image sharing

- cmd/kubectl-gadget/debug.go
- cmd/kubectl-gadget/deploy.go
- cmd/kubectl-gadget/undeploy.go
- cmd/kubectl-gadget/utils/consts.go
- cmd/kubectl-gadget/utils/flags.go
- cmd/kubectl-gadget/utils/trace.go
- pkg/resources/manifests/deploy.yaml
Inspektor Gadget can only be used in Linux nodes for now. This commit:
- add a nodeSelector to the deployment to only schedule gadget pods in
Linux nodes.
- add logic in different places to only list Linux nodes.
Create an AKS cluster with a Linux and Windows pool (https://docs.microsoft.com/en-us/azure/aks/windows-faq?tabs=azure-cli). 
```
$ kubectl get nodes -o wide
NAME                                STATUS   ROLES   AGE   VERSION   INTERNAL-IP    EXTERNAL-IP   OS-IMAGE                         KERNEL-VERSION     CONTAINER-RUNTIME
aks-agentpool-23349554-vmss000000   Ready    agent   37m   v1.23.8   10.240.0.4     <none>        Ubuntu 18.04.6 LTS               5.4.0-1089-azure   containerd://1.5.11+azure-2
akswin000001                        Ready    agent   34m   v1.23.8   10.240.1.112 …
```
> kubectl-gadget: Only support Linux nodes explicitly

- .github/workflows/inspektor-gadget.yml
Allow `package: write` to push integration testing image during release
> ci: fix permissions for aro integration tests

- cmd/kubectl-gadget/utils/kube-config.go
The PR fixes couple of things:
- `clientcmd.NewDefaultClientConfigLoadingRules` already handles multipath in KUBECONFIG so no need to do it explicitly.
- `loadingRules.ExplicitPath` should be using the value specified via --kubeconfig flag to respect kubernetes/cli-runtime flags. Also `loadingRules.ExplicitPath` should be a path and not a list of paths. It is fine to use it with --kubeconfig flag since it is always expected to be a path like with `kubectl` as well:
```
$ kubectl get pods --kubeconfig ~/.kube/config:~/.kube/config
error: stat /home/qasim/.kube/config:~/.kube/config: no such file or **directory**
```
Fixes #880 
```
$ mv ~/.kube/config ~/.kube/test
$ KUBECONFIG=~/.kube/test:~/.kube/test go run ./cmd/kubectl-gadget/ trace exec -A
NODE             NAMESPACE        POD …
```
> kubectl-gadget/utils: Handle KUBECONFIG with several paths

- Makefile
Docker ignore file named myapp.Dockerfile.dockerignore are only used
when using the BuildKit backend. The BuildKit backend can be enabled
either with DOCKER_BUILDKIT=1 or with the 'docker buildx' command:
https://docs.docker.com/engine/reference/commandline/build/#use-a-dockerignore-file
With this patch, the local-gadget-linux-amd64-builder container shrinked
from 4.15GB to 2.66GB.
> Use Dockerfile.dockerignore for saving disk space

- cmd/kubectl-gadget/utils/trace.go
- cmd/kubectl-gadget/version.go
- docs/install.md
- go.mod
While checking the stats of the krew plugin index and Github Container registry for Inspektor Gadget I found a discrepancy: the kubectl-gadget has more downloads than the container image for v0.8.0.
It doesn't make sense as normally clusters have multiple nodes, so one should expect the container image number of downloads to be much higher than the plugin downloads. 
One possibility is that users are updating the kubectl-gadget plugin but not the Inspektor Gadget deployed on the cluster. This PR adds a warning to tell users when there is a version skew between both components. 
```
$ ./kubectl-gadget deploy --image ghcr.io/kinvolk/inspektor-gadget:v0.8.0
$ git diff
diff --git Makefile Makefile
index 056b0c9a..9ecd66d0 100644
--- Makefile
+++ Makefile
@@ -22,6 +22,8 @@ else
VERSION := …
```
> cmd: Version skew warning

- docs/CONTRIBUTING.md
The description of how to build `local-gadget` was missing in the documentation. 
I also moved the building notes to the _Building the gadget container image_ section because those notes are only relevant for the gadget container image, and not general for the kubectl-gadget, ebpf objects and local-gadget.
> docs: Add description about building local-gadget

- gadget-container/gadgettracermanager/main.go
- pkg/resources/manifests/deploy.yaml
Currently, the probes will time out with the minimum value between `{livenessProbe|readinessProbe}.timeoutSeconds` and our internal `clientTimeout`. In fact, changing `timeoutSeconds` to any value larger than our 2 seconds doesn't have any effect, as 2 seconds is the internal timeout for the client that is performing the probe. The same happens in the oppose situation:
<details>
<summary>Test 1 (clientTimeout < livenessProbe.timeoutSeconds) </summary>
**Condition**: `clientTimeout = 5` and `livenessProbe.timeoutSeconds = 10`
**Result**: The liveness probe failed after 5 seconds. 
**Pod events**:
```bash
Unhealthy          Liveness probe failed: Gadget Tracer Manager health RPC reached the timeout: 5s
```
**Kubelet logs**:
```bash
$ sudo journalctl -xeu kubelet  | grep -i …
```
> probes: Don't set an internal timeout but rely on the probe's timeout

- Makefile
- cmd/kubectl-gadget/deploy.go
- pkg/resources/manifests/deploy.yaml
The current worse case startup time (77 sec) is not actually covering the worse case (3 minutes was reported in [#940](https://github.com/kinvolk/inspektor-gadget/issues/940)). Of course, we must investigate why the gadget pod takes so much time during the initialization ([#799](https://github.com/kinvolk/inspektor-gadget/issues/799)). But, in the meanwhile, to prevent users from completely disabling the liveness probe, this PR increases such time to 5 minutes using the `startupProbe`. I propose using the `startupProbe` instead of `livenessProbe.initialDelaySeconds`  because it allows us to avoid compromising the fast response to deadlocks that motivated us to introduce the liveness probe, as suggested [here](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readi …
> probe: Set initial delay to 5 min using the startupProbe

- cmd/common/trace/tcp.go
- cmd/kubectl-gadget/trace/tcp.go
- cmd/local-gadget/trace/tcp.go
- cmd/local-gadget/trace/trace.go
- docs/local-gadget.md
This PR first moved the code that will be shared between `kubectl-gadget` and `local-gadget` to the `common` folder and updated `kubectl-gadget` properly. Then, it added the `tcp` trace gadget to the `local-gadget`, reusing such code. And finally, this PR updates the documentation in [docs/local-gadget.md](https://github.com/kinvolk/inspektor-gadget/blob/jose/use-tracers-for-tcp/docs/local-gadget.md#tracetcp).
This PR fixes https://github.com/kinvolk/inspektor-gadget/issues/894. 
Run `local-gadget trace tcp`.
```bash
$ ./kubectl-gadget trace tcp -A
NODE             NAMESPACE        POD                            CONTAINER        T  PID     COMM             IP  SADDR                  DADDR                  SPORT   DPORT
master           kube-system      kube-apiserver-master …
```
> local-gadget: Add tcp trace gadget

- .github/actions/install-debian-packages/action.yml
The current CI version for libbpf-dev is failing for me in a fork without caching. This PR bumps the version to avoid the issue.
- Failed CI [run](https://github.com/mqasimsarfraz/inspektor-gadget/actions/runs/3090182879/jobs/4998660751)
> ci: Bump libbpf-dev version

- cmd/common/trace/tcpconnect.go
- cmd/kubectl-gadget/trace/tcpconnect.go
This refactor prepares for creating a local-gadget version of the tcpconnect cmd.
I followed the example for the TCP trace cmd which was similarly refactored in https://github.com/kinvolk/inspektor-gadget/pull/896
Related to this issue: https://github.com/kinvolk/inspektor-gadget/issues/895
No functional changes.
* Ran the unit tests with `make test`
* Installed inspector gadget in minikube and ran `./kubectl-gadget trace tcpconnect`. Created an nginx service and a `curl` pod to verify that tcp connections were traced.
> Move tcpconnect cmd construction to cmd/common

- examples/kube-container-collection/main.go
- pkg/container-collection/container-collection.go
- pkg/container-collection/containers.go
- pkg/container-collection/match_test.go
- pkg/container-collection/options.go
- pkg/container-collection/pubsub.go
- pkg/container-collection/pubsub_test.go
- pkg/gadget-collection/gadgets/advise/seccomp/gadget.go
- pkg/gadget-collection/gadgets/trace/dns/gadget.go
- pkg/gadget-collection/gadgets/trace/network/gadget.go
- pkg/gadget-collection/gadgets/trace/sni/gadget.go
- pkg/gadgettracermanager/containers-map/tracer.go
- pkg/tracer-collection/tracer-collection.go
https://github.com/kinvolk/inspektor-gadget/pull/435 added the owner reference to the container structure. However, collecting that information makes the start up of the gadget tracer manager slow. This PR changes the logic to only collect that information when needed. 
I applied the following patch to measure the time it takes to enrich each container:
<details>
<summary>Patch</summary>
```diff
diff --git pkg/container-collection/container-collection.go pkg/container-collection/container-collection.go
index fe4a0344..a3c0a0eb 100644
--- pkg/container-collection/container-collection.go
+++ pkg/container-collection/container-collection.go
@@ -23,8 +23,10 @@ package containercollection
import (
"sync"
+       "time"
eventtypes "github.com/kinvolk/inspektor-gadget/pkg/types"
+       log …
```
> container-collection: Lazily enrich ownerReferences

- Makefile
Rename "**_epbf_**-objects-outside-docker" to "**_ebpf_**-objects-outside-docker".
`make ebpf-objects-outside-docker`
* Ran `make ebpf-objects-outside-docker`
* Grep'd the codebase for references to the command with the typo, but didn't find any.
> Fix typo in ebpf-objects-outside-docker Makefile target

- .github/workflows/inspektor-gadget.yml
- integration/command.go
- integration/helpers.go
- integration/integration_test.go
This PR starts using JSON instead of columns output mode in the integration-tests. It starts by implementing just some gadgets:
- Trace/Bind
- Trace/Exec
- Trace/Signal
- Trace/Tcp
Notice I had to upgrade the Go version for the integration-tests jobs because the helper functions created to verify the JSON output use generics, which was introduced in v1.18.
Fixes https://github.com/kinvolk/inspektor-gadget/issues/719.
> integration-tests: Use the JSON mode to verify the gadgets' output

- pkg/gadgets/trace/capabilities/tracer/tracer.go
- pkg/gadgets/trace/capabilities/types/types.go
InsetID represents the INSETID used in cap_capable() for kernel >= 5.1. It's possible to represent it by using *bool instead of string. nil indicates that the running kernel is < 5.1.
> trace/capabilities: Use *bool for InsetID

- cmd/common/trace/tcpconnect.go
- cmd/local-gadget/trace/tcpconnect.go
- cmd/local-gadget/trace/trace.go
- docs/local-gadget.md
Add tcpconnect trace to local-gadget.
Resolves: https://github.com/kinvolk/inspektor-gadget/issues/895
1. `sudo local-gadget trace tcpconnect`
2. `docker run -it --rm --name test-container busybox /bin/sh -c "wget http://www.example.com"`
Tested locally:
> Implement local-gadget version of tcpconnect

- integration/command.go
Currently, if SPO is deleted before all the seccompprofiles are removed we can run into situations where a profile will have a dangling finalizer. This PR makes sure we remove all the profiles first and then remove the SPO, avoiding a profile to be stuck on termination.
Fixes #724 
We saw all the integration-test runs on ARO [stuck](https://github.com/kinvolk/inspektor-gadget/actions/runs/3094483604/jobs/5008045840) forever and upon investigation we realized that the cluster had a `seccompprofile` stuck on termination. The root cause was a test creating a `seccompprofile` and if the SPO was deleted before test clean up we end up having the dangling profile because of unremoved finalizer. The clean up approach is taken from [here](https://github.com/kubernetes-sigs/security-profiles-operato …
> integration-tests: Delete all seccompprofiles before deleting SPO

- integration/integration_test.go
While reviewing https://github.com/kinvolk/inspektor-gadget/pull/945 I tried to implement some tests by myself to check how easy it was. Opening a PR to not lose that work.
> integration: Switch trace open tests to use json

- integration/integration_test.go
It's possible that the tracer captures other events than the one we're expecting, hence we should use expectEntriesToMatch() instead of expectAllToMatch().
Example of failure:
```
2022-09-22T13:31:02.9530851Z     command.go:430: invalid command output(StartOpensnoopGadget): verifying output with custom function: unexpected output entry:
2022-09-22T13:31:02.9532458Z           &types.Event{
2022-09-22T13:31:02.9533177Z           	... // 2 identical fields
2022-09-22T13:31:02.9533832Z           	Pid:  0,
2022-09-22T13:31:02.9534421Z           	UID:  0,
2022-09-22T13:31:02.9535013Z         - 	Comm: "cat",
2022-09-22T13:31:02.9535714Z         + 	Comm: "runc:[2:INIT]",
2022-09-22T13:31:02.9536312Z         - 	Fd:   3,
2022-09-22T13:31:02.9536882Z         + 	Fd:   6,
2022-09-22T13:31:02.9537386Z …
```
> integration: Fix trace open tests

- integration/integration_test.go
- pkg/gadgets/trace/bind/tracer/tracer.go
The Interface field is the name of the interface that the socket is bound to. If the socket is not bound to any interface we can have an empty string as default.
> trace/bind: Use empty string for iface as default instead of "0"

- integration/integration_test.go
Use --audit-only=false to avoid issue on ARO.
Ref https://github.com/kinvolk/inspektor-gadget/issues/985
> integration: Add workaround for trace capabilities test on ARO

- Makefile
Hitting Ctrl+C doesn't work for `make ebpf-objects`. This fixes the problem by making the Docker command interactive.
Run `make ebpf-objects`, hit Ctrl+C and ensure the command returns.
The above.
> Allow terminating ebpf-objects Make target

- integration/command.go
- integration/integration_test.go
AKS mutates the spod webhook config resulting in SPO stuck in `UPDATING` state forever. This can result in timeout of `cleanupSPO` because of dangling finalizers. Since SPO is stuck on `UPDATING` state any resource we tried to clean might end up showing again when controller starts a new reconciliation loop. This patch makes sure SPO goes to `RUNNING` state allowing in-order cleanup.
Related https://github.com/Azure/AKS/issues/1771
SPO was stuck in `UPDATING` state during test run:
```
→ kubectl -n security-profiles-operator get spod 
NAME   STATE
spod   UPDATING
```
SPO goes to `RUNNING` state during test run:
```
→ kubectl -n security-profiles-operator get spod 
NAME   STATE
spod   RUNNING
```
Running few times against an AKS cluster without any timeouts:
``` …
```
> ci: Fix SPO deployment on AKS Cluster

- pkg/columns/columninfo.go
- pkg/columns/columninfo_test.go
- pkg/columns/columns.go
- pkg/columns/columns_test.go
- pkg/columns/filter.go
- pkg/columns/filter/filter.go
- pkg/columns/filter/filter_test.go
- pkg/columns/formatter/textcolumns/options_test.go
- pkg/columns/formatter/textcolumns/output.go
- pkg/columns/formatter/textcolumns/scaler.go
- pkg/columns/formatter/textcolumns/textcolumns.go
- pkg/columns/formatter/textcolumns/textcolumns_test.go
- pkg/columns/group/group.go
- pkg/columns/group/group_test.go
- pkg/columns/helpers.go
- pkg/columns/sort/sort_test.go
- pkg/gadgets/trace/bind/types/types.go
- pkg/gadgets/trace/exec/types/types.go
This PR introduces two new parameters to columns, `minWidth` and `maxWidth`. Whenever the auto-scaler is in use, it will prevent columns from shrinking to less than minWidth or expanding to more than maxWidth. This is helpful when you know beforehand that a field will not cross those boundaries and instead give the remaining space to other columns.
This PR also introduces a new special value for `width`, `minWidth` and `maxWidth` called `type`. This can be used on columns that have an underlying integer value and will automatically use the maximum space that can be occupied for the specific type - e.g. a uint8 will result in a width of 3 (as 255 is the maximum value, holding a maximum of three digits).
I also added some leftover cleanups (mostly regarding the tests) from the initial PR - …
> pkg/columns: add support for minWidth/maxWidth to help with auto-scaling

- examples/container-collection/container-collection.go
- examples/gadgets/basic/top/file/file.go
- examples/gadgets/basic/trace/dns/dns.go
- examples/gadgets/basic/trace/exec/exec.go
- examples/gadgets/parser/trace/exec/exec.go
- examples/gadgets/withfilter/trace/exec/exec.go
- examples/kube-container-collection/main.go
- examples/runc-hook/main.go
Cosmetic change to only use syscall package for signals in the examples.
> examples: Use syscall.SIGINT instead of os.Interrupt

- pkg/columns/formatter/textcolumns/output.go
- pkg/columns/formatter/textcolumns/scaler.go
- pkg/columns/formatter/textcolumns/textcolumns.go
- pkg/columns/formatter/textcolumns/textcolumns_test.go
This PR adds a couple of helper functions discussed [in this PR](https://github.com/kinvolk/inspektor-gadget/pull/980).
* `FormatTable()` to return a full table as string
* `SetAutoScale()` to enable/disable auto-scaling on demand
* `GetTerminalWidth()` to easily get the current width of the terminal
This PR also prevents a potential crash when using AdjustWidthsToContent().
> pkg/columns/formatter/textcolumns: Add a couple of helper functions

- integration/command.go
- integration/integration_test.go
Revert b9db9360d8b8 ("integration: Disable liveness probes when running on ARO") given that https://github.com/kinvolk/inspektor-gadget/issues/799 is now fixed.
> integration: Re-enable liveness probe on ARO

- cmd/kubectl-gadget/utils/trace.go
Print those messages to stderr instead to avoid an application parsing the output to fail.
This commit is a temporal solution until we investigate why those are printed making the integration tests to fail.
Details in https://github.com/kinvolk/inspektor-gadget/issues/1002.
> cmd/kubectl-gadget: Don't pring warning messages to stdout

- integration/inspektor-gadget/integration_test.go
During #946 it seems that we lost the fix introduced by #984 in rebase. This patch reintroduces the fix.
A manual run against the ARO cluster is passing now.
> integration-tests: Fix Opensnoop test again

- pkg/gadgets/trace/signal/types/types.go
- pkg/gadgets/trace/tcp/types/types.go
As discussed in https://github.com/kinvolk/inspektor-gadget/pull/934#discussion_r977580600 and https://github.com/kinvolk/inspektor-gadget/pull/934#discussion_r977459998, update `signal` and `tcp` to use `(min|max)Width` feature.
> columns: Update `signal` and `tcp` to use (min|max)Width feature

- cmd/kubectl-gadget/version.go
The `version` command now additionally outputs the deployed Inspektor Gadget version.
The information is from the deployed image-tag of the pods.
Solves https://github.com/kinvolk/inspektor-gadget/issues/902
_Versions are commit hashes, since these commits are not tagged._
```
➭ ./kubectl-gadget version
Client version: af1512e
Server version: v0.8.0
```
1. Additional message prompting the user to take action. For Example: `Please update Inspektor Gadget on the pods using kubectl gadget deploy`, ....
> cmd/version: Additionally show server version

- cmd/common/trace/mount.go
- cmd/kubectl-gadget/trace/mount.go
- docs/guides/trace/mount.md
- integration/inspektor-gadget/integration_test.go
- pkg/gadgets/trace/mount/types/types.go
The trace mount gadget now uses the columns library
See https://github.com/kinvolk/inspektor-gadget/issues/1003
Columnwidths are not the same as the old one. Currently it looks like this:
> trace/mount: Use columns library

- Makefile
This PR adds the following changes:
1. Remove the hardcoded minikube profile name so that users can run:
```bash
MINIKUBE="minikube -p minikube-containerd" make minikube-install
```
2. If the image is not correctly loaded into Minikube, then we shouldn't go ahead and try to redeploy IG.
> makefile: Some changes on `minikube-install` target

- pkg/types/types.go
This PR adds the first batch of column templates discussed in #1037. I'll create another PR where I migrated column definitions to templates for already to columns converted gadgets.
> pkg/types: register column templates

- pkg/types/types.go
This PR fixes the need to manually call Init(nodeName) for column template registration by putting it into an automatically called init() function.
> pkg/types: move column template registration into init()

- pkg/container-collection/containers.go
- pkg/gadgets/trace/bind/types/types.go
- pkg/gadgets/trace/capabilities/types/types.go
- pkg/gadgets/trace/exec/types/types.go
- pkg/gadgets/trace/fsslower/types/types.go
- pkg/gadgets/trace/mount/types/types.go
- pkg/gadgets/trace/oomkill/types/types.go
- pkg/gadgets/trace/signal/types/types.go
- pkg/gadgets/trace/tcp/types/types.go
- pkg/gadgets/trace/tcpconnect/types/types.go
In this PR, I changed the column information of all already to columns converted gadgets to use templates (where possible).
> pkg/gadgets/...: replace column information with template where applicable

- cmd/common/trace/open.go
- cmd/kubectl-gadget/trace/open.go
- pkg/gadgets/trace/open/types/types.go
The trace open gadget now uses the columns library
See https://github.com/kinvolk/inspektor-gadget/issues/1003
> trace/open: Use columns library

- cmd/common/utils/errors.go
- cmd/kubectl-gadget/traceloop.go
- cmd/kubectl-gadget/utils/exec.go
- cmd/kubectl-gadget/utils/flags.go
- cmd/kubectl-gadget/utils/trace.go
- cmd/kubectl-gadget/version.go
Fixes the usage of the wrong error message function in https://github.com/inspektor-gadget/inspektor-gadget/pull/977#discussion_r988874555
> kubectl-gadget/version: Use appropiate error message

- cmd/common/utils/flags.go
- cmd/kubectl-gadget/deploy.go
- cmd/kubectl-gadget/utils/consts.go
- cmd/kubectl-gadget/utils/flags.go
- cmd/local-gadget/utils/flags.go
- examples/container-collection/container-collection.go
- examples/gadgets/formatter/trace/exec/exec.go
- examples/gadgets/withfilter/trace/exec/exec.go
- pkg/container-utils/containerd/containerd.go
- pkg/container-utils/containerutils.go
- pkg/container-utils/crio/crio.go
- pkg/container-utils/docker/docker.go
- pkg/container-utils/runtime-client/interface.go
- pkg/resources/manifests/deploy.yaml
When the socketpath of the underlying container runtime is not the default it can be configured through these newly added cmd options of the `deploy` cmd
See #451. This change bases on https://github.com/flyth/inspektor-gadget/tree/michael/socketpaths
The newly added 3 subcommands to the `deploy` command are the following:
`--socketpath-docker`, `socketpath-containerd` and `--socketpath-containerd`
`kubectl gadget deploy --socketpath-docker /burak.docker.sock` for docker.
Same for `crio` and `containerd`
```
time="2022-10-07T14:59:46Z" level=warning msg="Skip pod default/kubernetes-bootcamp-75c5d958ff-f2s5l: cannot find container (ID: docker://1fb5a0580223858c8ee7d105be6b74e01472630abaf28c760a29cfef02e340e6): Cannot connect to the Docker daemon at unix:///burak.docker.sock. Is the docker …
```
> cmd/deploy: Add container socketpath configuration

- integration/inspektor-gadget/integration_test.go
A previous PR https://github.com/inspektor-gadget/inspektor-gadget/pull/1046 breaks the ARO CI Test.
This PR loosens the requirements for the test to be successfull so it does not check the following fields anymore:
1. RemoteSvcNamespace
2. RemoteSvcName
3. RemoteSvcLabelSelector
> integration-tests/networkgraph: Don't rely on svc names

- docs/guides/trace/network-graph.md
- integration/inspektor-gadget/integration_test.go
- pkg/gadget-collection/gadgets/trace/network/enricher.go
- pkg/gadgets/advise/networkpolicy/advisor/advisor.go
- pkg/gadgets/trace/network/tracer/tracer.go
- pkg/gadgets/trace/network/types/types.go
- pkg/local-gadget-manager/local-gadget-manager_test.go
This PR introduces two changes to the network trace gadget:
1. Use `unint16` for the port field.
2. Currently, we are using `ip` to describe if it is IPv4 or IPv6 in tcp and tcpconnect gadget. Instead, we use `saddr`, `daddr` or `addr` for the IP addresses, e.g. in bind, tcp and tcpconnect. This commit aligns the network gadget to bind, tcp and tcpconnect gadgets.
> gadgets/network: Align name and type notation with the rest of gadgets

- integration/inspektor-gadget/integration_test.go
Fixes conflict created by merging #1050 and #1046 without rebasing.
> ci: Fix outdated field name

- cmd/local-gadget/trace/signal.go
- cmd/local-gadget/trace/trace.go
- docs/local-gadget.md
- pkg/gadget-collection/gadget-collection.go
This is a fix for https://github.com/inspektor-gadget/inspektor-gadget/issues/892 .
`local-gadget` doesn't support tracing signal, like `kubectl-gadget` do. Use the common functionality available to add the same support to `local-gadget`.
- Ran `local-gadget` integration test on `minikube` cluster
- Build and run `local-gadget`
```
sudo ./local-gadget trace signal
CONTAINER                                          PID        COMM             SIGNAL      TPID       RET
minikube-docker                                    47618      cri-dockerd      SIGURG      51004      0
minikube-docker                                    47618      cri-dockerd      SIGURG      3073       0
minikube-docker                                    49410      kubelet          SIGURG      85749      0
...
```
> local-gadget: Add signal trace gadget

- integration/helpers.go
- integration/inspektor-gadget/integration_test.go
Uses the json output in order to validate as much information as possible from the `top tcp` gadget
> integrationtest/TestTcptop: Validate json output

- integration/inspektor-gadget/integration_test.go
- integration/local-gadget/trace_exec_test.go
- integration/local-gadget/trace_signal_test.go
- integration/local-gadget/trace_tcp_test.go
These three gadgets were missing for tests.
> ci: Add integration tests for exec/signal/tcp trace gadgets

- integration/inspektor-gadget/integration_test.go
- pkg/gadgets/top/file/types/types.go
Uses the json output in order to validate as much information as possible from the `top file` gadget
General comment/question about the `FileType` member variable of the `Stats struct` in `top/types.go`.
Should the type of `FileType` be a char/enum, since in the eBPF program only `R`,  `S` or `O` will get assigned.
And where can we put this documentation. Is it right when it is in the same line for such a small comment?
> integrationtest/TestFiletop: Validate json output

- pkg/columns/columninfo.go
- pkg/columns/columns.go
- pkg/columns/filter/filter.go
- pkg/columns/sort/sort.go
This PR improves the performance of the sort and filter subpackage of our columns library. The performance increase is mainly achieved by caching the offsets of fields inside structs and accessing them directly via the `unsafe` package. As we've collected all required information on fields anyways, this isn't particularly unsafe.
Another optimization has been done in the filter package by preparing dedicated functions for types instead of switching on them with every call.
```
name                    old time/op    new time/op    delta
FilterNumberGte-10        23.5ns ± 0%     2.8ns ± 1%   -87.94%  (p=0.008 n=5+5)
FilterNumberEq-10         23.0ns ± 0%     2.8ns ± 1%   -87.70%  (p=0.008 n=5+5)
FilterNumberNeq-10        22.8ns ± 1%     2.8ns ± 1%   -87.59%  (p=0.008 n=5+5)
FilterStringEq-10 …
```
> pkg/columns: improve performance of sort & filter

- cmd/common/trace/network.go
- cmd/kubectl-gadget/trace/network.go
- docs/guides/trace/network.md
- integration/inspektor-gadget/integration_test.go
- pkg/gadgets/trace/network/types/types.go
The trace network gadget now uses the columns library
See https://github.com/kinvolk/inspektor-gadget/issues/1003
The names of the gadget is `network` but the gadgetname of the deployed pod is `network-graph` (See modified `network.md`). This is also true for other gadgets like `mount` <-> `mountsnoop`. 
Is this by design or should i open a separate issue for this to discuss it?
This is the first PR where i did not anootate every variable with a `column:...`
Do we want to do that or are we leaving these hidden fields without an annotation?
> trace/network: Use columns library

- .github/actions/run-integration-tests/action.yml
We moved the inspektor-gadget integration tests to a new directory resulting in the test process named differently i.e inspektor-gadget.test rather than integration.test. This PR uses the correct process name in the cleanup. 
A [workflow run](https://github.com/inspektor-gadget/inspektor-gadget/actions/runs/3338706275/jobs/5527308288) with cancellation.
> ci: Fix cleanup process for integration-tests

- gadget-container/cleanup.sh
- gadget-container/entrypoint.sh
We don't have a deterministic way to understand where these hooks should be installed, then try to install in the well-known paths.
Installing multiple times the same hook is not an issue as they are only executed once https://github.com/containers/podman/blob/v3.0.1/pkg/hooks/docs/oci-hooks.5.md#directories
It seems we got this wrong on https://github.com/inspektor-gadget/inspektor-gadget/pull/483. 
```
$ minikube start --container-runtime=cri-o --driver=kvm2
$ kubectl gadget trace exec 
$ kubectl run mypod$RANDOM --image=praqma/network-multitool -- sleep 9999
```
```
$ minikube start --container-runtime=cri-o --driver=kvm2
$ kubectl gadget trace exec 
$ kubectl run mypod$RANDOM --image=praqma/network-multitool -- sleep 9999
```
> hooks: Install cri-o hooks in multiple folders

- cmd/kubectl-gadget/profile/block-io_test.go
- go.mod
- go.sum
- integration/inspektor-gadget/integration_test.go
Uses the json output in order to validate as much information as possible from the `profile` gadgets. Additionally two unittest for the `profile block-io` gadget helper functions were written.
For testing i like something like `assert.Equal` or `assert.Assert` to avoid having to write `if ... {t.Fail(...)}`
> Unit and Integrationtests for `profile` gadgets

- integration/command.go
- integration/helpers.go
- integration/inspektor-gadget/integration_test.go
- integration/local-gadget/trace_tcp_test.go
- integration/local-gadget/trace_tcpconnect_test.go
Many TCP Tests sometimes fail.
These flaky tests are not productive for the team, since we should rely on their results.
Outside services are not always up or can change their behavior. Furthermore we should not check for both ports `80` and `443` when we only specificed one.
This PR creates a new `nginx` pod and tries to connect to its port `80`
See:
https://github.com/inspektor-gadget/inspektor-gadget/actions/runs/3378520742/jobs/5610001881#step:7:499
https://github.com/inspektor-gadget/inspektor-gadget/actions/runs/3378520742/jobs/5610002721#step:8:603
> tests/tcp: Only test against a cluser local IP

- integration/inspektor-gadget/integration_test.go
Avoid leaving log files after running the IG integration tests.
> integration/inspektor-gadget: Clean up log files after NetworkPolicy test

- README.md
It would useful to quickly get some information regrading the repository especially the CI status. So, I propose to add these badges.
Fixes #828
> docs: Add badges for quick information

- Makefile
- integration/helpers.go
- integration/inspektor-gadget/integration_test.go
If we have a cluster with pre-installed IG/SPO we end up removing them if '-no-deploy-ig/-no-deploy-spo' isn't specified. Here we add some logic to detect if these components are already installed and skip deployment/cleanup. This can also be helpful to skip SPO installation against ARO cluster without extra config. 
Fixes #976
> integration-tests: Improve deployment workflow for IG/SPO

- cmd/common/trace/sni.go
- cmd/kubectl-gadget/trace/sni.go
- pkg/gadgets/trace/sni/types/snisnoop.go
Use columns library for `sni` gadget.
Task #1003 Related #893
> trace/sni: Use columns library

- pkg/container-utils/cgroups/cgroups.go
- pkg/gadgets/helpers.go
- pkg/gadgettracermanager/common/common.go
- pkg/gadgettracermanager/common/common.h
- pkg/gadgettracermanager/containers-map/tracer.go
- pkg/gadgettracermanager/gadgettracermanager.go
As we want to enable third parties to use our gadgets directly in their own environments / tools, we should make it as easy as possible. Sometimes, a significant hurdle in building tools written in Go is the requirement of CGO - hence we should try to remove as many dependencies on that as possible. Also, switching from Go to C code at runtime always comes with increased costs in terms of CPU usage, so that is another reason to avoid mixed code.
This is the first PR laying the groundwork for all our gadgets. The updated gadgets themselves will follow in separate PRs by gadget category.
* #1093
Fixes #872
> Remove cgo where possible from gadgets

- pkg/gadgets/trace/capabilities/tracer/tracer_test.go
The TestCapabilitiesTracer/audit_only_false test was failing in some kernel versions. I found out that "/bin/cat /dev/null" doesn't always generate a non audit capability check. For this reason, I switched to "/bin/cat /proc/kallsyms" that seems to generate that in more cases.
> trace/capabilities: Fix unit tests

- cmd/kubectl-gadget/profile/cpu.go
- pkg/gadgets/profile/cpu/types/types.go
Used the `columns` library wherever possible. Can't generalize for the `profile` gadgets, since `profile block-io` is outputting a graph. Also `profile cpu` also has its special case where the stack is printed on its separate line
> profile/cpu: Use columns library

- integration/command.go
- integration/inspektor-gadget/integration_test.go
We have seen multiple times that SPO is stuck on 'Terminating' state because of dangling finalizers this commit fixes the issue by forcefully removing finalizers allowing SPO cleanup, since we don't really want to test if the cleanup is working fine.
Fixes #1111 
- Start an integration test run: 
```
$ INTEGRATION_TESTS_PARAMS="-run TestExecsnoop -v" make IMAGE_TAG=latest  integration-tests
```
- During test run delete all SPO pods to reproduce finalizers issue with:
```
$ kubectl delete mutatingwebhookconfigurations.admissionregistration.k8s.io spo-mutating-webhook-configuration ; kubectl delete deployments.apps -n  security-profiles-operator  security-profiles-operator  security-profiles-operator-webhook; kubectl delete pods -l name=spod -n ssecurity-profiles-operator; kubectl delete ds …
```
> integration-tests: Patch seccomp profiles to force SPO cleanup

- pkg/gadgets/trace/capabilities/types/types.go
For people using the CLI, the default is true. Let's set the same default for people using the trace CR directly.
> pkg/gadget/trace/capabilities: Sync default audit-only value with CLI

- Makefile
- integration/inspektor-gadget/integration_test.go
With PR #1110 we introduced changes to skip installation of IG/SPO in case they are already installed on the cluster. This commit reverts the changes related to IG and re-introduces '-no-deploy-spo/-no-deploy-ig' flags.
> integration-tests: Only Skip deployment for SPO.

- cmd/common/snapshot/snapshot.go
- cmd/common/utils/flags.go
- cmd/kubectl-gadget/profile/cpu.go
- cmd/kubectl-gadget/trace/trace.go
- cmd/kubectl-gadget/traceloop.go
- cmd/local-gadget/containers/containers.go
- cmd/local-gadget/trace/trace.go
- cmd/local-gadget/traceloop.go
The output mode is validated in ParseOutputConfig() when building the common flags. Let's remove some extra validations around as they're not needed.
> Remove extra output mode validation

- cmd/common/snapshot/snapshot.go
- cmd/common/trace/trace.go
- cmd/common/utils/events.go
- cmd/kubectl-gadget/audit/seccomp.go
- cmd/kubectl-gadget/trace/trace.go
- cmd/kubectl-gadget/traceloop.go
- cmd/local-gadget/audit/seccomp.go
- cmd/local-gadget/trace/dns.go
- cmd/local-gadget/trace/trace.go
- pkg/gadgets/snapshot/process/types/process-collector.go
- pkg/gadgets/snapshot/socket/types/socket-collector.go
- pkg/gadgets/trace/bind/types/types.go
- pkg/gadgets/trace/capabilities/types/types.go
- pkg/gadgets/trace/dns/types/dns.go
- pkg/gadgets/trace/exec/types/types.go
- pkg/gadgets/trace/fsslower/types/types.go
- pkg/gadgets/trace/mount/types/types.go
- pkg/gadgets/trace/network/types/types.go
- pkg/gadgets/trace/oomkill/types/types.go
- pkg/gadgets/trace/open/types/types.go
- pkg/gadgets/trace/signal/types/types.go
- pkg/gadgets/trace/sni/types/snisnoop.go
- pkg/gadgets/trace/tcp/types/types.go
- pkg/gadgets/trace/tcpconnect/types/types.go
- pkg/gadgets/traceloop/types/types.go
- pkg/types/types.go
- There is no need to make a copy of the Event to print special events, instead, use pointers.
- Move `GetBaseEvent` into the embedded struct so that it doesn't need to be implemented by every gadget.
- Rename ManageSpecialEvent to HandleSpecialEvent as in this case, "Handle" is more accurate than "Manage".
> cmd/common: Clean up special event management

- docs/guides/top/ebpf.md
- pkg/gadgets/top/ebpf/tracer/tracer.go
Instead of calculating the size ourself we read it from `fdinfo`. See https://github.com/inspektor-gadget/inspektor-gadget/issues/924
This does not solve the _issue_ regarding to perf maps or maps of maps. Their value is still a descriptor and therefore 4 bytes.
Is there any possiblity to query the perf buffer sizes too? Do we want to include them in the size too?
> gadgets/top/ebpf: Read fdinfo of map to get its size

- cmd/local-gadget/containers/containers.go
- docs/local-gadget.md
- integration/command.go
- integration/helpers.go
- integration/local-gadget/list_containers_test.go
- integration/local-gadget/trace_bind_test.go
- integration/local-gadget/trace_capabilities_test.go
- integration/local-gadget/trace_exec_test.go
- integration/local-gadget/trace_fsslower_test.go
- integration/local-gadget/trace_mount_test.go
- integration/local-gadget/trace_oomkill_test.go
- integration/local-gadget/trace_open_test.go
- integration/local-gadget/trace_signal_test.go
- integration/local-gadget/trace_tcp_test.go
- integration/local-gadget/trace_tcpconnect_test.go
- pkg/container-collection/annotations.go
- pkg/container-collection/containers.go
- pkg/container-collection/options.go
- pkg/local-gadget-manager/local-gadget-manager.go
- pkg/runcfanotify/runcfanotify.go
`runcfanotify` doesn't work for `cri-o` containers. The idea here is to adopt it to support tracing `cri-o` containers. 
Fixes #1018
Related #1028
During `runc` notification container creation is blocked on `pidfile` so enriching the container using the container runtime won't work because we hit `Runtime enricher (cri-o): failed to get container: container "2899fb3ce898a2ed1d4426b0cb6df81ee72cd630ce0fb9e10eb53f04d5eb4e9b" not found`. In order to avoid this we are using annotations fetched via `OCIConfig` to enrich containers. 
```
$ docker exec -it minikube-cri-o bash
$ local-gadget list-containers --watch 
...
cri-o      a0ddd82147f5536d38c449f39edff4151ae0aa39b9653045449302915c85… test-pod
...
```
JSON mode should also work here. Before this PR this will only works for …
> local-gadget: fix tracing new crio containers

- .github/actions/install-debian-packages/action.yml
Patch initially proposed in https://github.com/inspektor-gadget/inspektor-gadget/pull/1148
> lint: update github action to fix deprecation warning

- .github/actions/run-integration-tests/action.yml
Resolves the last warnings/messages from a successful CI run. See https://github.com/inspektor-gadget/inspektor-gadget/actions/runs/3547192062
Only breaking change in the Changelog is the following:
`With the update to Node 16, all scripts will now be run with Node 16 rather than Node 12.`
> ci: Update download-artifact from v2 to v3

- .github/workflows/inspektor-gadget.yml
This PR removes the Lint Errors that we see on the summary page of Workflows and the Lint page itself.
Example see https://github.com/inspektor-gadget/inspektor-gadget/actions/runs/3540176371
Even though everything was ok, we see errors.
With this change we do not use the cache of the `setup go` step on the Lint step anymore
Related https://github.com/golangci/golangci-lint-action/issues/23
> Remove Lint errors

- .github/workflows/inspektor-gadget.yml
- integration/helpers.go
It seems like if no entries are passed to `expectAllToMatch` the test still goes and passes. We should explicitly fail if no entries are given.
> integraton-tests: Fail if no entries provided to expectAllToMatch

- cmd/common/snapshot/process.go
- cmd/common/snapshot/snapshot.go
- cmd/common/snapshot/socket.go
- cmd/kubectl-gadget/snapshot/process.go
- cmd/kubectl-gadget/snapshot/snapshot.go
- cmd/kubectl-gadget/snapshot/socket.go
- cmd/local-gadget/snapshot/process.go
- cmd/local-gadget/snapshot/snapshot.go
- cmd/local-gadget/snapshot/socket.go
- pkg/gadget-collection/gadgets/snapshot/socket/gadget.go
- pkg/gadgets/snapshot/process/tracer/tracer.go
- pkg/gadgets/snapshot/process/types/process-collector.go
- pkg/gadgets/snapshot/socket/tracer/tracer.go
- pkg/gadgets/snapshot/socket/types/socket-collector.go
With this PR both `snapshot` gadgets are using the `columns` library.
Specifically it is using the `TransformIntoTable` function which finds the perfect width, since we already have all events. (Like not using extra width on a wide column which currently only has very small entries)
Example:
```
NODE     NAMESPACE POD                                  CONTAINER           COMM PID
minikube default   kubernetes-bootcamp-75c5d958ff-rntpk kubernetes-bootcamp sh   648715
minikube default   kubernetes-bootcamp-75c5d958ff-rntpk kubernetes-bootcamp node 648781
minikube default   kubernetes-bootcamp-75c5d958ff-rntpk kubernetes-bootcamp bash 650668
```
Additionally the sorting was also modified to use the `columssort` instead of doing it ourselves in the different gadgets
> gadgets/snapshot: Use columns library

- pkg/container-collection/options.go
- pkg/container-utils/oci-annotations/resolver_containerd.go
- pkg/container-utils/oci-annotations/resolver_containerd_test.go
- pkg/container-utils/oci-annotations/resolver_crio.go
- pkg/container-utils/oci-annotations/resolver_crio_test.go
- pkg/container-utils/oci-annotations/types.go
- pkg/container-utils/oci-annotations/types_test.go
Move annotation handling to separate package to simplify OCIConfig enricher. 
Fixes #1145
> ociannotations: Move annotation handling to separate package

- cmd/kubectl-gadget/profile/cpu.go
A kubernetes parameter already uses the `--user` parameter.
The following screenshot (yellow highlight by me) shows that `-U`/`--user` is missing for `profile cpu` which would only show the userspace stack.
While getting a minimal testcode i discovered that the behavior changed. On our version the global flag (the kubernetes one) has precedence.
With the newest version `1.6.1` the local parameter (the userspace stack one) will be shown and shadows the global flag
Should i open an Issue/PR with a potential fix on the cobra github?
> profile/cpu: Add suffix "stack" to kernel/user parameter name

- cmd/kubectl-gadget/top/block-io.go
- cmd/kubectl-gadget/top/ebpf.go
- cmd/kubectl-gadget/top/file.go
- cmd/kubectl-gadget/top/tcp.go
- cmd/kubectl-gadget/top/top.go
- docs/gadgets/ebpftop.md
- docs/gadgets/filetop.md
- docs/guides/top/tcp.md
- pkg/columns/columninfo.go
- pkg/columns/sort/doc.go
- pkg/columns/sort/sort.go
- pkg/columns/sort/sort_test.go
- pkg/gadget-collection/gadgets/top/block-io/gadget.go
- pkg/gadget-collection/gadgets/top/ebpf/gadget.go
- pkg/gadget-collection/gadgets/top/file/gadget.go
- pkg/gadget-collection/gadgets/top/tcp/gadget.go
- pkg/gadgets/top/block-io/types/types.go
- pkg/gadgets/top/ebpf/types/types.go
- pkg/gadgets/top/file/types/types.go
- pkg/gadgets/top/tcp/types/types.go
Use the columns library in the `top` gadgets:
- `block-io`
- `ebpf`
- `file`
- `tcp`
The first commit was made so that every commit itself can be compiled and ran without any issues
1. The columns library now can sort on columns with a custom extractor. But it can't be a virtual column
2. `Template` and `UseTemplate` are now exported to use templates on virtual columns
@flyth are these modifications ok?
> gadgets/top: Use the column library

- pkg/local-gadget-manager/local-gadget-manager_test.go
There is not anymore a poll on the runcnotify package, however 2 seconds seems like a good timeout to use there, so the value is not changed.
> pkg/local-gadget: Update comment

- examples/gadgets/basic/trace/dns/dns.go
- pkg/container-collection/networktracer/connect.go
- pkg/gadget-collection/gadgets/trace/dns/gadget.go
- pkg/gadget-collection/gadgets/trace/sni/gadget.go
- pkg/gadgets/helpers.go
- pkg/gadgets/internal/networktracer/tracer.go
- pkg/gadgets/trace/dns/tracer/tracer.go
- pkg/gadgets/trace/sni/tracer/tracer.go
This PR also moves the attachment key's management internally into the tracer itself to avoid callers generating a key that was always the network namespace (it can be computed internally from the PID).
> dns/sni: Reduce duplicated code in network tracers

- .github/workflows/inspektor-gadget.yml
It seems that we are missing step to move the image cache to correct location as per [example](https://docs.docker.com/build/ci/github-actions/examples/#local-cache). Also, the [cache sizes](https://github.com/inspektor-gadget/inspektor-gadget/actions/caches) `key=Linux-docker-{core,default}-` seem to be indicating we aren't using cache for docker images. Only useful for re-triggers of all steps. 
- [Initial Run](https://github.com/inspektor-gadget/inspektor-gadget/actions/runs/3438568041/attempts/1) - 33m 30s
- [Re-triggered Run](https://github.com/inspektor-gadget/inspektor-gadget/actions/runs/3438568041/attempts/2) - 12m 41s
[Cache sizes](https://github.com/inspektor-gadget/inspektor-gadget/actions/caches) seems to be of the expected sizes with new keys.
> ci: Add missing step for image caching

- cmd/kubectl-gadget/deploy.go
- docs/install.md
Currently Inspektor Gadget is deployed to all nodes in the cluster. In
some conditions we don't want to deploy it to all nodes, for instance
when there're some nodes that are not compatible with it.
This commit introduces a new "--node-selector" flag to the kubectl
gadget deploy command. This allows the user to set the nodes to
deploy / no deploy based on labels.
--- 
While checking old issues in the repo I found https://github.com/inspektor-gadget/inspektor-gadget/issues/168 and https://github.com/inspektor-gadget/inspektor-gadget/issues/125. IMO it's a valid use case to allow users to select the nodes that they want to deploy Inspektor Gadget to. 
```bash
$  minikube start --nodes=3
$ ./kubectl-gadget deploy --node-selector kubernetes.io/hostname=minikube-m02
$ kubectl -n gadget get …
```
> cmd/deploy: Add node-selector flag

- cmd/common/snapshot/process.go
- docs/local-gadget.md
- integration/inspektor-gadget/integration_test.go
- integration/local-gadget/snapshot_process_test.go
- pkg/gadgets/snapshot/process/tracer/tracer.go
- pkg/gadgets/snapshot/process/types/process-collector.go
The naming around process / thread / task in kernel and user space
is different and it's very confusing. In the kernel, each thread has an
ID, called PID, and also has a TGID (Task Group ID) that is the PID of
the first thread in the group. From user space we have PID
(Process Identifier), that matches TGID on the kernel, and TID
(Thread ID), that matches PID on the kernel.
In summary[0]:
User  | Kernel
------+-------
PID   | TGID
TID   | PID
Then, TGID is a kernel concept and we shouldn't show this to the user,
hence this commit uses PID and TID on the snapshot process gadget.
> gadgets/snapshot/process: Rename columns to match user space

- README.md
Fixes: 03d1ff082c4d ("docs: Rename guides to gadgets")
Thanks to @flyth for reporting!
> readme: Fix links to gadgets documentation.

- cmd/local-gadget/snapshot/process.go
- examples/gadgets/basic/snapshot/process/process.go
- integration/inspektor-gadget/integration_test.go
- pkg/gadget-collection/gadgets/snapshot/process/gadget.go
- pkg/gadgets/internal/test/helpers.go
- pkg/gadgets/snapshot/process/tracer/tracer.go
- pkg/gadgets/snapshot/process/tracer/tracer_test.go
Add a fallback mechanism that works on older kernels too. This reads
the information about the processes from /proc/, even if this is slower
than the eBPF-based implementation, it can be useful in cases that
eBPF-iterators are not available.
The following benchmark shows that the procfs-based implementation is
~30% slower than the ebpf-based one:
```
$ go test -exec sudo -bench=. -benchtime=100x . -v
[sudo] password for mvb:
goos: linux
goarch: amd64
pkg: github.com/inspektor-gadget/inspektor-gadget/pkg/gadgets/snapshot/process/tracer
cpu: AMD Ryzen 7 3700X 8-Core Processor
BenchmarkEBPFTracer
BenchmarkEBPFTracer-16               100          21743119 ns/op
BenchmarkProcfsTracer
BenchmarkProcfsTracer-16             100          31169492 ns/op
PASS
ok …
```
> gadgets/snapshot/process: Add support for older kernels

- pkg/gadgettracermanager/gadgettracermanager.go
Add the OCI enrichment to `inspektor-gadget`. The root cause of why `KubernetesEnrichment`/`RuncFanotify` weren't working for cri-o containers was fixed [by ensuring a unique key is used for every cri-o container](https://github.com/inspektor-gadget/inspektor-gadget/blob/main/pkg/runcfanotify/runcfanotify.go#L461). So this is just an improvement to use OCI annotations for metadata once available. 
Fixes #1142 
Build IG with following patch to ensure `KubernetesEnrichment` isn't used:
```
diff --git a/pkg/gadgettracermanager/gadgettracermanager.go b/pkg/gadgettracermanager/gadgettracermanager.go
index 4f46975a..9f11a435 100644
--- a/pkg/gadgettracermanager/gadgettracermanager.go
+++ b/pkg/gadgettracermanager/gadgettracermanager.go
@@ -259,7 +259,7 @@ func NewServer(conf *Conf) …
```
> pkg/gadgettracermanager: Add OCI enricher to IG

- cmd/common/top/top.go
- integration/helpers.go
- integration/inspektor-gadget/integration_test.go
- integration/local-gadget/k8s/top_block_io_test.go
- integration/local-gadget/k8s/top_ebpf_test.go
- integration/local-gadget/k8s/top_file_test.go
- integration/local-gadget/k8s/top_tcp_test.go
Rationale see https://github.com/inspektor-gadget/inspektor-gadget/issues/1157
Output for example:
```bash
$ ./kubectl-gadget top file -o json
[]
[{"node":"minikube","namespace":"default","pod":"nginx","container":"nginx","pid":582310,"tid":582310,"comm":"touch","reads":1,"rbytes":832,"mountnsid":4026533425,"fileType":82,"filename":"libc-2.31.so"}]
[]
[]
[]
[]
[{"node":"minikube","namespace":"default","pod":"nginx","container":"nginx","pid":582618,"tid":582618,"comm":"cat","reads":2,"rbytes":262144,"mountnsid":4026533425,"fileType":82,"filename":"docker-entrypoint.sh"},{"node":"minikube","namespace":"default","pod":"nginx","container":"nginx","pid":582618,"tid":582618,"comm":"cat","reads":1,"rbytes":832,"mountnsid":4026533425,"fileType":82,"filename":"libc-2.31.so"}]
[]
```
> cmd/top: Output JSON Arrays instead of single JSON objects

- integration/helpers.go
The output of the ARO test was too large for the default buffer of `bufio.Scanner`. Sometimes there was more than 100k characters in a line. Optimistically i set the size to `1 MB`.
Additionally an error will now be logged when the scanner encounters any issue. This was the problem why we didn't see any problems in the logs.
Huge thanks to @mqasimsarfraz for finding this :fire: :rocket:
> [Fix ARO CI] Increase the buffersize of `bufio.Scanner`

- Dockerfiles/gadget-core.Dockerfile
- Dockerfiles/gadget-default.Dockerfile
- gadget-container/entrypoint.sh
Because of 441f909 we can remove some of the packages from the final image. Also, there is change from 'bash' to 'sh' in the entrypoint.
Related #801 
```
REPOSITORY                                      TAG                                                      IMAGE ID       CREATED          SIZE
ghcr.io/inspektor-gadget/inspektor-gadget       latest-core                                              d7a3e747aab8   47 seconds ago   133MB
ghcr.io/inspektor-gadget/inspektor-gadget       qasim-remove-packages-core                               550aa27a7732   6 hours ago      129MB
ghcr.io/inspektor-gadget/inspektor-gadget       latest                                                   d7127ddb103e   57 seconds ago   743MB
ghcr.io/inspektor-gadget/inspektor-gadget       qasim-remove-packages …
```
> gadget-container: Remove unneeded dependencies from container images

- tools/getbtfhub.sh
This reverts commit 9694d16360bcd4391f57e4c8f6af2c9da863efa1.
The necessary patch was merged upstream:
https://github.com/aquasecurity/btfhub/pull/52#event-8192729854
See https://github.com/aquasecurity/btfhub/issues/51
> Revert "tools: Use fork of btfhub until upstream is fixed"

- cmd/common/snapshot/process.go
The columnname for the Command column is `comm` and not `cmd`. Same for `pid` and `tid`
> snapshot/process: Fix false sorting name for column "comm", "pid" and "tid"

- .github/workflows/inspektor-gadget.yml
- .gitignore
- Dockerfiles/gadget-core.Dockerfile
- Dockerfiles/gadget-core.Dockerfile.dockerignore
- Dockerfiles/gadget-default.Dockerfile
- Dockerfiles/gadget-default.Dockerfile.dockerignore
- Makefile
- hack/btfs/README.md
- tools/getbtfhub.sh
BTFGen takes a lot of time to execute because it has to:
1. clone the btfhub-archive repo (some GBs)
2. uncompress all files from btfhub-archive
3. run btfgen for all btf files uncompressed above
It's only required to run this command when the bpf objects are changed or new BTF files are pushed to btfhub-archive.
This commit modifies the building system to use the Github actions to cache the generated BTF files. The changes done here are:
1. Execute btfgen outside the building container: It's hard to extract the BTF files from the container to save them in the cache.
2. Define a cache for the btf files: It uses as key the architecture, the latest commit of btfhub-archive and the hash of all bpf objects.
First run to create the cache -> …
> CI: Cache BTFGen

- cmd/common/snapshot/process.go
- cmd/common/snapshot/snapshot.go
- cmd/common/snapshot/socket.go
This was needed since the filtering logic for the thread ids in `snapshot process` was on the client side and the slice had to get modified.
With https://github.com/inspektor-gadget/inspektor-gadget/pull/1223 this changes and we can remove the pointer to the slice making the code more readable and maintainable
> cmd/snapshot: Remove unnecessary pointer to slice

- pkg/gadgets/snapshot/process/tracer/tracer.go
Symptoms: 'make lint' gives the following:
> pkg/gadgets/snapshot/process/tracer/tracer.go:21:2: SA1019: "io/ioutil"
> has been deprecated since Go 1.16: As of Go 1.16, the same functionality
> is now provided by package io or package os, and those implementations
> should be preferred in new code. See the specific function documentation
> for details. (staticcheck)
> 	"io/ioutil"
> 	^
It seems to have been fixed by #1225 but it came back.
> Remove deprecated ioutil.ReadFile

- cmd/common/profile/cpu.go
- cmd/common/snapshot/snapshot.go
- cmd/common/top/top.go
- cmd/common/utils/flags.go
- cmd/common/utils/parser.go
- cmd/kubectl-gadget/audit/seccomp.go
- cmd/kubectl-gadget/trace/trace.go
- cmd/kubectl-gadget/traceloop.go
- cmd/local-gadget/audit/seccomp.go
- cmd/local-gadget/containers/containers.go
- cmd/local-gadget/trace/dns.go
- cmd/local-gadget/trace/sni.go
- cmd/local-gadget/trace/trace.go
This PR removes `OutputModeColumns` from the `SupportedOutputModes`.
As the default value of `--output` there is an empty string now. Internally it will get parsed as `OutputModeCustomColumns` with no `CustomColums` selected.
Achieving this combination is manually not possible, which means that `--output OutputModeCustomColums=` is not possible. This behavior is the same before this PR
Is this the way we should implement this or do we want a now option like `OutputModeDefault` (Which internally maps to `OutputModeCustomColumns` with no `CustomColums` again, etc...) or else?
resolves #908
> cmd: Remove OutputModeColumns

- .golangci.yml
- Dockerfiles/linter.Dockerfile
The 'Lint' step in GitHub Action sometimes fails with a timeout. The timeout is set to 1 minute by default. This patch increases this to 10 minutes.
> lint: increase timeout

- cmd/local-gadget/trace/network.go
https://github.com/inspektor-gadget/inspektor-gadget/pull/1255 was not rebased on top of main
> trace/network: Remove OutputModeColumns

- integration/inspektor-gadget/snapshot_socket_test.go
For some unknown reason the tested cluster is using Ubuntu 18.04:
https://pipelines.actions.githubusercontent.com/serviceHosts/4d4f4f2a-5591-4838-91d9-a0bf1152d97d/_apis/pipelines/1/runs/6673/signedlogcontent/50?urlExpires=2023-01-11T20%3A58%3A34.2655967Z&urlSigningMethod=HMACV1&urlSignature=NopV9FZ%2Bl0XBAJ%2Bg5%2Fdf0UBhkIcVQ1ilIoAwAJ07b7k%3D
```
2023-01-11T20:51:08.8431329Z         + kubectl get pods -n gadget -o name
2023-01-11T20:51:08.8431903Z         + kubectl logs -n gadget pod/gadget-6bk87
2023-01-11T20:51:08.8432382Z         OS detected: Ubuntu 18.04.6 LTS
2023-01-11T20:51:08.8432903Z         Kernel detected: 5.4.0-1098-azure
2023-01-11T20:51:08.8433357Z         bcc detected: 0.24.0-1
```
This reverts commit 2741fa08929435f4d50682da8bb32c7ce5d673f8.
> Revert "integration: Remove skipping snapshot socket test on AKS."

- .github/actions/prepare-and-publish-test-reports/action.yml
- .github/actions/run-integration-tests/action.yml
- .github/workflows/inspektor-gadget.yml
- Makefile
- tools/testjson2md/go.mod
- tools/testjson2md/go.sum
- tools/testjson2md/testjson2md.go
Initial attempt to improve readability for test results. As a first step we are using [job summaries](https://github.blog/2022-05-09-supercharging-github-actions-with-job-summaries/) to publish test report containing details about tests and [failure logs](https://github.com/mqasimsarfraz/inspektor-gadget/actions/runs/3856171191/attempts/1#summary-10484646582) (truncated) to ease identifying the failing test. You can find sample report [failed](https://github.com/inspektor-gadget/inspektor-gadget/actions/runs/3856411053/attempts/1#summary-10485328919)/[passed](https://github.com/inspektor-gadget/inspektor-gadget/actions/runs/3873387049/attempts/1#summary-10523660691) here.
Relates #688
We can use `gopogh` (will need a dedicated storage for `html` reports) or something similar latter on. …
> CI: use job summaries for test reports

- pkg/types/types.go
This is not using the 'fixed' keyword so that the width can be reduced if necessary.
Example of output:
```
$ ./kubectl-gadget trace open -A -o custom-columns=timestamp,comm,path
TIMESTAMP                           COMM             PATH
2023-01-12T16:31:47.311311188+01:00 kube-apiserver   /var/lib/minikube/certs/apiserver-kubelet-client.crt
2023-01-12T16:31:47.311342955+01:00 kube-apiserver   /var/lib/minikube/certs/apiserver-kubelet-client.key
```
With this patch, there is more space for the path.
> timestamp column: set maximum width

- pkg/gadgets/internal/networktracer/tracer.go
There is a missing call to FixBpfKtimeGetBootNs() in networking gadgets to enable them to work in old kernels.
Fixes: ffb7d9910f2d ("gadgets: get timestamp from userspace on Linux <5.7")
Fixes: 7982f833d3ba ("trace sni gadget: add timestamps")
---
[Integration tests on AKS (Ubuntu, amd64)](https://github.com/inspektor-gadget/inspektor-gadget/actions/runs/3906312046/jobs/6674433125#logs) were failing because that uses an old kernel.
> gadgets: Fix networking gadgets on old kernels

- pkg/gadgets/trace/network/tracer/tracer.go
Same as 21437a26ec7c ("gadgets: Fix networking gadgets on old kernels") but for the trace network gadget.
Fixes: ffb7d9910f2d ("gadgets: get timestamp from userspace on Linux <5.7")
Fixes: 7982f833d3ba ("trace sni gadget: add timestamps")
> gadgets/trace/network: Fix for old kernels

- integration/local-gadget/non-k8s/snapshot_process_test.go
- integration/local-gadget/non-k8s/top_ebpf_test.go
- integration/local-gadget/non-k8s/trace_dns_test.go
- integration/local-gadget/non-k8s/trace_network_test.go
- pkg/local-gadget-manager/local-gadget-manager_test.go
This is the first step to removing the local-gadget interactive mode (Trace CR).
> local-gadget: Run docker tests in non-interactive mode

- integration/local-gadget/non-k8s/trace_dns_test.go
- integration/local-gadget/non-k8s/trace_network_test.go
We have seen [scenario](https://github.com/inspektor-gadget/inspektor-gadget/actions/runs/3949717373/attempts/1#summary-10727271605) in CI here `local-gadget` isn't ready when test events are generated resulting in missing initial events. Add a sleep to ensure local-gadget is ready before we generate test events.
> integration: Ensure local-gadget is ready before running test

- .github/workflows/inspektor-gadget.yml
The latest version for buildkit v0.11.0 breaks the image push to registry. Use the previous stable version till upstream bug is fixed. Related upstream issues are: 
- https://github.com/docker/build-push-action/issues/761
- https://github.com/containerd/containerd/issues/7972
- https://github.com/moby/buildkit/issues/3347
The workaround has been recommended [here](https://github.com/docker/build-push-action/issues/761#issuecomment-1383822381) and I tested ([v0.10.6](https://github.com/mqasimsarfraz/actions/actions/runs/3947633886) vs [v0.11.0](https://github.com/mqasimsarfraz/actions/actions/runs/3940073459)) it as well. Also, on [fork](https://github.com/mqasimsarfraz/inspektor-gadget/actions/runs/3949535040/jobs/6760870559#step:4:151).
We can also wait till the situation is clear and …
> CI: Workaround for buildkit error while pushing to registry

- .github/actions/prepare-and-publish-test-reports/action.yml
- .github/actions/run-integration-tests/action.yml
- tools/testjson2md/go.mod
- tools/testjson2md/testjson2md.go
It is better to skip some logs then to truncate all of them. In this PR we skip the logs if job summary can't handle but by default we will retain all the logs. 
- [sample report](https://github.com/mqasimsarfraz/inspektor-gadget/actions/runs/3929358173/attempts/1#summary-10671123474). (skipped test `TestTraceFsslower`)
Should help with the [cases](https://github.com/inspektor-gadget/inspektor-gadget/actions/runs/3912844172/attempts/1#summary-10634393081) like here.
> CI: Do not truncate failure logs

- cmd/local-gadget/advise/seccomp-profile.go
- cmd/local-gadget/audit/seccomp.go
- cmd/local-gadget/containers/containers.go
- cmd/local-gadget/profile/profile.go
- cmd/local-gadget/snapshot/process.go
- cmd/local-gadget/snapshot/socket.go
- cmd/local-gadget/top/top.go
- cmd/local-gadget/trace/trace.go
- cmd/local-gadget/utils/flags.go
- cmd/local-gadget/utils/utils.go
This PR adds a new flag called `--timeout` to `local-gadget`.
A helper function was introduced which waits for `SIGTERM` or `SIGINT` or an elapsed timeout in order to reduce code duplication. Of course there are special cases like for `advise seccomp-profile`
1. Naming things is still not easy for me :smile: Suggestions welcome, be it for the function name or filename
1. Since now every gadget in `local-gadget` has the `--timeout` flag available, it has needed to "hide" it in some gadgets like `snapshot`. Is this a good way to solve that?
1. Should i create another following PR which unifies this `--timeout` flag, since now `kubectl-gadget` and `local-gadget` has it? There is currently a Flagset which is shared called `OutputConfig`. `--timeout` would not fit in there -> Rename the …
> cmd/local-gadget: Add global flag `--timeout`

- Dockerfiles/local-gadget-builder.Dockerfile
- Dockerfiles/local-gadget-tests.Dockerfile
- Dockerfiles/local-gadget-tests.Dockerfile.dockerignore
- Dockerfiles/local-gadget.Dockerfile
- integration/local-gadget/k8s/Makefile
Since i am on `Ubuntu 22.04` i get the following error when i try to run the integration tests for `local-gadget`:
```bash
.....
/home/burak/codes/inspektor-gadget/integration/local-gadget/bin/minikube-v1.27.0 -p ${MINIKUBE_PROFILE} ssh "sudo local-gadget-integration.test -test.v -integration -container-runtime docker ${INTEGRATION_TESTS_PARAMS}"
Checking minikube with profile minikube-docker is running ...
Preparing minikube with profile minikube-docker for testing ...
Running test in minikube with profile minikube-docker ...
local-gadget-integration.test: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by local-gadget-integration.test)
local-gadget-integration.test: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by …
```
> integration: Build local-gadget-test in the same container as local-gadget

- integration/command.go
We have seen errors related to SPO webhook not available in CI, resulting in failing tests. It seems they have made SPO webhook opt-in [upstream](https://github.com/kubernetes-sigs/security-profiles-operator/pull/1207) to avoid such situation. Upgrading so we don't hit such issues in the CI.
```
Error from server (InternalError): error when creating "STDIN": Internal error occurred: failed calling webhook "recording.spo.io": failed to call webhook: Post "[https://webhook-service.security-profiles-operator.svc:443/mutate-v1-pod-recording?timeout=10s](https://webhook-service.security-profiles-operator.svc/mutate-v1-pod-recording?timeout=10s)": context deadline exceeded
```
Also, I tried to check why `webhook` wasn't available and it seems for some reason `webhook` was being restarted maybe …
> integration: Upgrade SPO to v0.6.0

- pkg/gadgets/snapshot/process/tracer/tracer_test.go
Under heavy load, tracers might take a few seconds to start. The sleep of 3 seconds is not always enough.
How to reproduce:
```
$ go test -test.v -exec sudo ./pkg/gadgets/...
```
So it tests all gadgets at the same time, generating enough load.
The following is not generating heavy load enough to reproduce the bug:
```
$ go test -test.v -exec sudo ./pkg/gadgets/snapshot/process/...
```
Example of output:
```
--- FAIL: TestSnapshotProcessEBPFTracer (0.00s)
--- PASS: TestSnapshotProcessEBPFTracer/no_threads_are_captured (2.37s)
--- FAIL: TestSnapshotProcessEBPFTracer/captures_events_with_matching_filter (3.24s)
--- FAIL: TestSnapshotProcessEBPFTracer/captures_all_events_with_no_filters_configured (3.35s)
--- FAIL: TestSnapshotProcessEBPFTracer/captures_events_with_matching_filter_threads …
```
> test snapshot process gadget: increase timeout

- integration/helpers.go
- integration/inspektor-gadget/top_tcp_test.go
- integration/inspektor-gadget/trace_network_test.go
- integration/inspektor-gadget/trace_tcp_test.go
- integration/inspektor-gadget/trace_tcpconnect_test.go
- integration/local-gadget/k8s/top_tcp_test.go
- integration/local-gadget/k8s/trace_network_test.go
- integration/local-gadget/k8s/trace_tcp_test.go
- integration/local-gadget/k8s/trace_tcpconnect_test.go
It's possible that GetTestPodIP() fails as in https://github.com/inspektor-gadget/inspektor-gadget/actions/runs/3986343020/jobs/6834925048. This PR introduces a better way to handle errors in this function, hence avoiding weird test failures messages like:
```
invalid command output(StartTraceTcpconnectGadget): verifying output with custom function: output doesn't contain the expected entry: &{Event:{CommonData:{Node: Namespace:test-tcpconnect-2634895312520334714 Pod:test-pod Container:test-pod} Timestamp:1970-01-01T00:00:00.000000000Z Type:normal Message:} Pid:0 UID:0 Comm:wget IPVersion:4 Saddr:failed to get Pod IP: exit status 1 Daddr:172.17.0.11 Dport:80 MountNsID:0}
```
> tests: Make GetTestPodIP() return an error too

- integration/inspektor-gadget/trace_sni_test.go
- integration/local-gadget/k8s/trace_sni_test.go
Sometimes, the command 'wget https://inspektor-gadget.io' blocks on a read() syscall forever. In my tests, it blocks only in the busybox container (not on ubuntu or on the host), and only with that website (https://wikipedia.org works fine).
This patch adds a timeout to the 'wget', so that the command terminates and the loop can reexecute the next wget.
How to reproduce with the integration test:
```
INTEGRATION_TESTS_PARAMS="-run TestTraceSni -no-deploy-ig -no-deploy-spo" make integration-tests
```
How to reproduce manually:
```
$ docker run -ti --rm busybox
/ # wget https://inspektor-gadget.io
```
The last strace logs are:
```
[pid 3777692] write(3, "GET / HTTP/1.1\r\nHost: inspektor-"..., 82 <unfinished ...>
[pid 3777692] <... write resumed>)      = 82
[pid 3777692] shutdown(3, SHUT_WR …
```
> integration: sni: add timeout to wget

- pkg/gadgets/trace/bind/tracer/tracer_test.go
The previous tests were only testing UDP4, TCP4 and TCP6.
Thanks @mauriciovasquezbernal  for the code suggestion.
> trace/bind: add unit test for UDP on IPv6

- .github/workflows/inspektor-gadget.yml
Reverts inspektor-gadget/inspektor-gadget#1276 since upsteam https://github.com/docker/build-push-action/issues/761 issue is fixed.
> Revert "CI: Workaround for buildkit error while pushing to registry"

- .github/workflows/inspektor-gadget.yml
From documentation [0]:
"jobs.<job_id>.strategy.fail-fast applies to the entire matrix. If jobs.<job_id>.strategy.fail-fast is set to true, GitHub will cancel all in-progress and queued jobs in the matrix if any job in the matrix fails. This property defaults to true."
"fast-failing" hides the result of other jobs on the same matrix, hence we don't know if the issue is specific to that job or something more generic. For instance, in [1] we not that the "Integration tests on AKS (Ubuntu, amd64)" test failed, however we don't know the result of other OS / arch combinations, and that information could help to have a better understanding of what's going on.
[0]: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstrategyfail-fast
[1]: …
> githubactions: Disable fail-fast

- .github/actions/setup-minikube/action.yml
- .github/workflows/inspektor-gadget.yml
- minikube.mk
This PR allows running inspektor-gadget integration tests on `containerd` and `cri-o` on PR runs.
Fixes #1283
> integration: Run IG tests on containerd and crio

- .github/workflows/inspektor-gadget.yml
- .golangci.yml
- Dockerfiles/ebpf-builder.Dockerfile
- Dockerfiles/gadget-core.Dockerfile
- Dockerfiles/gadget-default.Dockerfile
- Dockerfiles/kubectl-gadget.Dockerfile
- Dockerfiles/local-gadget-builder.Dockerfile
- docs/install.md
- examples/kube-container-collection/Dockerfile
- examples/runc-hook/Dockerfile
- go.mod
- go.sum
- pkg/client/clientset/versioned/fake/register.go
- pkg/client/clientset/versioned/scheme/register.go
- tools/testjson2md/go.mod
The only specific reason to update is to have [0] in that automatically increases the number of open file descriptors we can have. I didn't updated to 1.20 because the base docker images we use don't have this version available yet.
> Update to golang 1.19

- .github/actions/setup-minikube/action.yml
Currently we need `docker-ce` >= 23.0.0 for minikube to work for `cri-o` runtime. Something changed in upstream docker packages and now we need to specify `containerd.io` in packages to avoid conflicts. Should have done in the first place as mentioned on their [guide](https://docs.docker.com/engine/install/ubuntu/). :see_no_evil:  
Hopefully, GH action will upgrade to `docker-ce` 23.0.0 and we can get rid of this workaround.
```
The following packages have unmet dependencies:
containerd.io : Conflicts: containerd
Conflicts: runc
moby-containerd : Conflicts: containerd
Conflicts: containerd.io
moby-runc : Conflicts: runc
E: Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages.
Error: Process completed with exit code 100.
```
> CI: Fix docker upgrade for cri-o

- pkg/container-collection/k8s.go
- pkg/container-collection/options.go
[Ephemeral Containers](https://kubernetes.io/docs/concepts/workloads/pods/ephemeral-containers/) were introduced in Kubernetes v1.25 [stable], see [KEP-277: Ephemeral Containers](https://github.com/kubernetes/enhancements/blob/master/keps/sig-node/277-ephemeral-containers/README.md).
They allow to introduce a container to an existing pod for debugging. This ephemeral container is listed in the podSpec in the `ephemeralContainers` section. But so far, Inspektor Gadget only looked in the `containers` section and `initContainers` section (init containers added by https://github.com/inspektor-gadget/inspektor-gadget/pull/549).
This PR adds support for ephemeral containers.
Example of command to start an ephemeral container:
```
$ kubectl debug -it -n seccomp-demo hello-python --image=ubuntu …
```
> container-collection: support ephemeral containers

- Dockerfiles/gadget-core.Dockerfile
- Dockerfiles/gadget-default.Dockerfile
- gadget-container/entrypoint.sh
Symptoms:
```
+ kubectl logs -n gadget pod/gadget-jlgvt
/entrypoint.sh: line 34: dpkg-query: not found
```
See https://github.com/inspektor-gadget/inspektor-gadget/pull/1337#issuecomment-1436849662
> entrypoint.sh: fix dpkg error on alpine

- pkg/gadgets/trace/network/types/types.go
Currently the column is called padlabels:
```
$ kubectl gadget trace network -o custom-columns=node,padlabels
NODE  PADLABELS
```
This patch renames it to podlabels.
> trace network gadget: fix typo

- cmd/kubectl-gadget/utils/flags.go
- go.mod
- go.sum
As part of fixing #132 #880 we stopped using `viper` but I somehow missed removing it as a dependency. Also, I don't see any occurrence of `viper.GetString()` in the code base so I assume it is safe to remove this? 
```bash
$ mv ~/.kube/config ~/kube/config.test
$ ./kubectl-gadget trace open # fails since no default config found
NODE                                  NAMESPACE                             POD                                   CONTAINER                             PID        COMM             FD   ERR PATH                                   
Error: failed to run gadget: error creating trace: listing pods: Get "http://localhost:8080/api/v1/namespaces/gadget/pods?labelSelector=k8s-app%3Dgadget": dial tcp 127.0.0.1:8080: connect: connection refused
$ …
```
> kubectl-gadget: Remove viper

- cmd/common/registry.go
- pkg/columns/formatter/textcolumns/textcolumns.go
- pkg/columns/formatter/textcolumns/textcolumns_test.go
- pkg/parser/outputhelpers.go
- pkg/parser/parser.go
Print a warning in case the user passes columns that are not available:
Before:
```
$ sudo ./local-gadget  trace exec -o columns=container,sdasadafd
WARN[0000] Runtime enricher (cri-o): couldn't get current containers
CONTAINER
...
```
Now:
```
$ sudo ./local-gadget  trace exec -o columns=container,sdasadafd
WARN[0000] Runtime enricher (cri-o): couldn't get current containers
WARN[0000] column "sdasadafd" is invalid
CONTAINER
```
> Better validation for -o columns

- pkg/gadgets/top/ebpf/types/types.go
Instead of only printing the information for the first process, let's print all the PIDs and comms that are using a given ebpf program. The columns library will take care of "cutting" the output if it's too long:
```
$ sudo ./local-gadget top ebpf
PROGID      TYPE        NAME        PID         COMM           RUNTIME RUNCO…  MAPMEMORY MAPCOUNT
75          Tracing     ig_top_ebp… 159953      local-gadge  784.377µs 8684         4KiB 1
3           CGroupSKB               1           systemd             0s 0              0B 0
68          Kprobe      kprobe_exe… 156948,159… kprobe,foo          0s 0            4KiB 1
```
> top/ebpf: Print all information about processes

- .github/actions/prepare-and-publish-test-reports/action.yml
- .github/actions/run-integration-tests/action.yml
- .github/workflows/inspektor-gadget.yml
- tools/testjson2md/testjson2md.go
Currently, we mark test report as red only when we have failed test cases but there can be scenarios when test run failed because of [timeout or some setup issues](https://github.com/inspektor-gadget/inspektor-gadget/actions/runs/4233214077/attempts/1#summary-11491881666) but no failing tests have been reported. This PR use the test step conclusion to mark the test report correctly. 
- [test commit](https://github.com/mqasimsarfraz/inspektor-gadget/pull/23/commits/0d3d9708efa9b1122f05a431b9fe5b62e2b1d03f): [Timed out test](https://github.com/mqasimsarfraz/inspektor-gadget/actions/runs/4254216230/jobs/7400279629) run with [red job summary](https://github.com/mqasimsarfraz/inspektor-gadget/actions/runs/4254216230/attempts/1#summary-11552704511)
- [normal failing …
> CI: Fix test report status/conclusion

- docs/crds/gadgets/ebpftop.md
- integration/inspektor-gadget/top_ebpf_test.go
- integration/local-gadget/k8s/top_ebpf_test.go
- integration/local-gadget/non-k8s/top_ebpf_test.go
- pkg/gadgets/top/ebpf/tracer/tracer.go
- pkg/gadgets/top/ebpf/types/types.go
PidInfo was a struct with a Pid and a Comm. It seems a bit misleading. This commit renames PidInfo to Process to make it clear that this includes the PID and the command.
--- 
This is somehow related to https://github.com/inspektor-gadget/inspektor-gadget/pull/1361, but I prefer to have separated PRs to keep the discussion independent.
> top/ebpf: Rename Pids to Processes in Stats struct

- pkg/snapshotcombiner/snapshotcombiner.go
- pkg/snapshotcombiner/snapshotcombiner_test.go
This PR adds a new and simple SnapshotCombiner library that takes stats of nodes and returns them combined on request. 
It adds a caching mechanism, so that when no stats get reported for a node and a certain amount of intervals, "old" stats will be used. This should increase user experience by not "flickering" if a node doesn't report its stats in time. The tradeoff in doing this, is that for one interval (or the ttl given in the settings), the results will not be 100% accurate (but they won't accurate as well if results are missing).
You create a new SnapshotCombiner and add stats via `AddSnapshot()` for each node once the node reports stats. Periodically, you request the combined stats using `GetSnapshots()`.
Every time stats get added, a `ttl` (time-to-live) timer is reset for the …
> pkg/snapshotcombiner: introduce SnapshotCombiner to handle combining and caching stats

- integration/local-gadget/non-k8s/Makefile
- pkg/container-utils/testutils/docker.go
It seems we were only printing `stdout` in case of docker tests. This PR will allow printing `stderr` so we can get complete test logs.
> testutils: Print stderr logs for docker containers

- docs/devel/how-to-write-a-gadget.md
This PR adds a small and (hopefully) simple guide on how to write a new gadget using the updated architecture. Operators are not used for now, we can add that later in a more in-depth guide.
> docs: Add guide for 'How to write a Gadget'

- .github/workflows/inspektor-gadget.yml
Sometimes it happens that the changes to our docs break the website build, let's check if this work fine here.
- The action fails when the website can't be built -> https://github.com/mauriciovasquezbernal/inspektor-gadget/actions/runs/4357810587/jobs/7617577958
> GithubActions: Check that website is built correctly

- integration/helpers.go
- integration/ig/k8s/trace_dns_test.go
- integration/inspektor-gadget/trace_dns_test.go
- tools/dnstester/Dockerfile
- tools/dnstester/dnstester.go
As mentioned [here](https://github.com/inspektor-gadget/inspektor-gadget/pull/1407#issuecomment-1461623922) we had issues getting `kube-dns` service on ARO so I switched to using local dns in all the tests.
Related #1378
> integration: Use 'dnstester' for k8s tests

- .github/workflows/inspektor-gadget.yml
- tools/dnstester/Dockerfile
- tools/dnstester/build.sh
As mentioned [here](https://github.com/inspektor-gadget/inspektor-gadget/pull/1411#issuecomment-1462359438) we need to create arm64 images for dnstester. This PR reworks the image to handle multi platform support. The corresponding arm64 [jobs](https://github.com/inspektor-gadget/inspektor-gadget/actions/runs/4376025214/jobs/7661323843) seems to be passing fine now.
> tools: dnstester for arm64

- integration/ig/non-k8s/trace_dns_test.go
Add a delay so the container is not finished immediately, this gives more time to the tracer to capture the events.
> test: Fix trace dns test

- .github/workflows/inspektor-gadget.yml
- Makefile
- internal/benchmarks/benchmarks_test.go
- internal/test/helpers.go
- internal/test/runner.go
- pkg/gadget-registry/gadget-registry.go
- pkg/gadgets/internal/socketenricher/tracer_test.go
This PR runs benchmarks for (almost) all gadgets with 100 fake containers. It uses the GitHub Action https://github.com/benchmark-action/github-action-benchmark to publish the graphs on a website automatically.
Run benchmarks locally:
```
$ make gadgets-benchmarks
```
Use the CI, and check the results:
[screenshot source](https://github.com/alban/inspektor-gadget/actions/runs/4387055722/jobs/7681888513)
Check the graphs automatically updated for each commit pushed on the repository:
https://alban.github.io/ig-benchmarks/dev/bench/
```
BenchmarkAllGadgetsManyContainers/-traceloop-4         	       1	2023389297 ns/op
BenchmarkAllGadgetsManyContainers/advise-seccomp-4     	      26	  68125372 ns/op
BenchmarkAllGadgetsManyContainers/audit-seccomp-4      	      15	  67188176 ns/op …
```
> CI: benchmarks all gadgets and publish graphs

- pkg/gadget-collection/gadgets/snapshot/socket/gadget.go
- pkg/gadgets/snapshot/socket/tracer/tracer.go
Creates the BPF iterators only once for all network namespaces.
This patch improves the performances of the snapshot socket gadget by 98.93% when we have 100 containers.
```
$ git checkout alban_perf_snapshot_socket
$ go test -exec sudo \
-bench='^BenchmarkAllGadgetsWithContainers$/^container100$/snapshot-socket' \
-run=Benchmark -count 8 \
./internal/benchmarks/...  | tee patched.bench
$ git checkout main
$ go test -exec sudo \
-bench='^BenchmarkAllGadgetsWithContainers$/^container100$/snapshot-socket' \
-run=Benchmark -count 8 \
./internal/benchmarks/...  | tee main.bench
$ benchstat main.bench patched.bench
goos: linux
goarch: amd64
pkg: github.com/inspektor-gadget/inspektor-gadget/internal/benchmarks
cpu: Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz
│   main.bench   │ …
```
> snapshot socket: improve performances

- .github/actions/run-integration-tests/action.yml
- .github/workflows/inspektor-gadget.yml
- Makefile
- integration/ig/k8s/Makefile
- integration/ig/k8s/integration_test.go
- integration/ig/k8s/trace_dns_test.go
- integration/ig/non-k8s/Makefile
- integration/ig/non-k8s/integration_test.go
- integration/ig/non-k8s/trace_dns_test.go
- integration/inspektor-gadget/integration_test.go
- integration/inspektor-gadget/trace_dns_test.go
This PR introduces a way to test changes to dnstester in a PR and on a fork. The idea is to save the dnstester image tag if changes are detected and pass it as a flag to integration tests. The push is disabled by default on forks and for external contributors by using `PUSH_HELPERS` secret. 
I tested the changes on a fork after setting `PUSH_HELPERS = ENABLE_PUSH_HELPERS` secret as:
- [Without custom PR image](https://github.com/mqasimsarfraz/inspektor-gadget/actions/runs/4511808818) - [logs](https://github.com/mqasimsarfraz/inspektor-gadget/actions/runs/4511808818/jobs/7944477217#step:6:1741)
- [With custom PR image](https://github.com/mqasimsarfraz/inspektor-gadget/actions/runs/4512232476) - [logs](https://github.com/mqasimsarfraz/inspektor-gadget/actions/runs/4512232476/jobs/7945491138# …
> integration: Allow using PR image for dnstester

- pkg/parser/outputhelpers.go
- pkg/parser/parser.go
- pkg/types/types.go
Handle error events
Add logic to handle the events that are use to provide debug information.
Before this commit those events were erroneously handled as normal events
printing wrong data to the terminal. For instance, for the DNS gadget:
```
$ go build . && sudo ./ig trace dns
WARN[0000] Runtime enricher (cri-o): couldn't get current containers
CONTAINER                       PID        TID        COMM             QR NAMESERVER      TYPE      QTYPE      NAME                           RCODE
0          0
0          0
0          0
```
"broke" the dns gadget by applying the following diff
```diff
$ git diff
diff --git pkg/gadgets/trace/dns/tracer/tracer.go pkg/gadgets/trace/dns/tracer/tracer.go
index be5a5af5..9842ae02 100644
--- pkg/gadgets/trace/dns/tracer/tracer.go
+++ …
```
> Fix error handling

- pkg/gadgets/snapshot/socket/tracer/tracer.go
Server side validation is implemented in service.go, so each gadget doesn't have to implemented it.
ref https://github.com/inspektor-gadget/inspektor-gadget/pull/1370#discussion_r1154641697
> gadgets/snapshot/socket: Remove unneeded validation

- pkg/gadgets/trace/network/types/types.go
- pkg/operators/kubeipresolver/kubeipresolver.go
- pkg/types/types.go
Currently, kubeipresolver is only used by the 'trace network' gadget and it can resolve 1 local IP and 1 remote IP. In the 'trace tcpdrop' gadget, we will need to resolve 2 IPs (source IP and destination IP) and they might not be local IPs (i.e. not tied to a pod).
This refactoring does not change anything for the 'trace network' gadget but will allow kubeipresolver to be used by other gadgets.
No changes.
Only the CI
> kubeipresolver: refactor in preparation for use in tcpdrop

- cmd/ig/main.go
- gadget-container/gadgettracermanager/controller.go
- gadget-container/gadgettracermanager/main.go
- gadgettracermanager: move the imports from the controller to main.go
- ig: do not import gadget-collection anymore
xref https://github.com/inspektor-gadget/inspektor-gadget/pull/1469#discussion_r1162023912
xref https://github.com/inspektor-gadget/inspektor-gadget/pull/1469#discussion_r1162023217
> ig,kubectl-gadget: clean up blank imports

- pkg/container-collection/operator.go
- pkg/gadgets/trace/tcpdrop/tracer/gadget.go
- pkg/gadgets/trace/tcpdrop/tracer/tracer.go
- pkg/gadgets/trace/tcpdrop/types/types.go
- pkg/operators/kubemanager/kubemanager.go
- pkg/operators/localmanager/localmanager.go
- pkg/operators/operators.go
- pkg/runtime/grpc/grpc-runtime.go
Perform the node enrichment in the grpc runtime instead of the kubemanager operator as discussed in https://github.com/inspektor-gadget/inspektor-gadget/pull/1469#discussion_r1157291531.
Check individual commits to get more details:
- pkg/grpc-runtime: Enrich event node
- Revert "operators: node enrichment"
- Don't use eventtypes.Event as base
> Implement node enrichment in grpc runtime

- .github/actions/run-integration-tests/action.yml
- .github/workflows/inspektor-gadget.yml
- Dockerfiles/gadget-default.Dockerfile
- Makefile
- README.md
- cmd/kubectl-gadget/main.go
- docs/gadgets/script.md
- docs/requirements.md
- gadget-container/gadgettracermanager/main.go
- integration/inspektor-gadget/integration_test.go
- integration/inspektor-gadget/script_test.go
- pkg/all-gadgets/allgadgets.go
- pkg/gadgets/script/gadget.go
- pkg/gadgets/script/tracer.go
- pkg/gadgets/script/types/types.go
This PR implements a basic support for bpftrace. 
```bash
$ kubectl gadget bpftrace -e 'tracepoint:syscalls:sys_enter_openat { printf("%s %s\n", comm, str(args->filename)); }'
NODE                             OUTPUT
minikube-m02                     Attaching 1 probe...
minikube-m02                     bpftrace /sys/devices/system/cpu/online
minikube-m02                     bpftrace /sys/devices/system/cpu/online
minikube-m03                     Attaching 1 probe...
minikube-m02                     bpftrace /dev/null
minikube-m02                     bpftrace /sys/kernel/debug/tracing/events/syscalls/sys_enter_openat/id
minikube-m02                     bpftrace /sys/devices/system/cpu/online
minikube-m03                     bpftrace /sys/devices/system/cpu/online
minikube-m03 …
```
> gadgets: Initial bpftrace support

- cmd/common/registry.go
- pkg/gadgets/snapshot/socket/tracer/gadget.go
- pkg/gadgets/top/file/tracer/gadget.go
- pkg/operators/localmanager/localmanager.go
Before:
```
$ ./kubectl-gadget script
NODE                               OUTPUT
Error: running gadget: rpc error: code = Unknown desc = setting gadget parameters: expected value for "program"
```
^^^ validation was performed in the server side
Now:
```
$ ./kubectl-gadget script
Error: required flag(s) "program" not set
```
Validation is done by cobra on the client side.
Ref https://github.com/inspektor-gadget/inspektor-gadget/pull/1370#pullrequestreview-1383795267
> registry: Make mandatory parameters required cmd flags

- integration/inspektor-gadget/script_test.go
- pkg/gadgets/script/tracer.go
So far only amd64 is supported, skip the tests and show a clear error in that platform.
> Show error for bpftrace when not running on amd64

- integration/ig/k8s/profile_bio_test.go
- integration/inspektor-gadget/profile_blockio_test.go
- pkg/gadgets/profile/block-io/tracer/gadget.go
- pkg/gadgets/profile/block-io/tracer/tracer.go
- pkg/gadgets/profile/block-io/types/types.go
- pkg/histogram/histogram.go
- pkg/histogram/histogram_test.go
This PR moves the functions that allow generating and printing a histogram from the profile block-io gadget to an internal package. It also adds unit-tests for such package.
This new package will be used also by the upcoming gadget: [profile tcprtt](https://github.com/inspektor-gadget/inspektor-gadget/pull/1517).
> pkg/histogram: Create new package for all gadgets using histograms

- .golangci.yml
- integration/ig/k8s/trace_capabilities_test.go
- integration/ig/k8s/trace_exec_test.go
- integration/ig/k8s/trace_open_test.go
- integration/inspektor-gadget/trace_capabilities_test.go
- integration/inspektor-gadget/trace_exec_test.go
- integration/inspektor-gadget/trace_open_test.go
- internal/test/runner.go
- pkg/gadgets/trace/capabilities/tracer/tracer.go
- pkg/gadgets/trace/capabilities/tracer/tracer_test.go
- pkg/gadgets/trace/capabilities/types/types.go
- pkg/gadgets/trace/exec/tracer/tracer.go
- pkg/gadgets/trace/exec/tracer/tracer_test.go
- pkg/gadgets/trace/exec/types/types.go
- pkg/gadgets/trace/open/tracer/tracer.go
- pkg/gadgets/trace/open/tracer/tracer_test.go
- pkg/gadgets/trace/open/types/types.go
- pkg/gadgets/trace/tcpconnect/tracer/tracer.go
- pkg/gadgets/trace/tcpconnect/types/types.go
The official go packages call it Uid rather than UID:
- https://github.com/golang/go/blob/bdccb85f509d24789694df198fe7bde948aa7955/src/syscall/ztypes_linux_amd64.go#L106
- https://github.com/golang/go/blob/bdccb85f509d24789694df198fe7bde948aa7955/src/os/user/user.go#L39
I also consider Uid is way better than UID, so I prefer to make this change now before it's impossible to make in the feature.
ref https://github.com/golang/lint/issues/89
> tree-wide: Rename UID fields to Uid

- docs/devel/CONTRIBUTING.md
I suggest adding these minimal build requirements for compiling from source for avoiding spending too much time debugging 
in case one of the requirements is missing. It was the case for me when I did an upgrade to golang 1.20.3 and tried to run the tests. The error message wasn't clearly stating that gcc was missing from my system. 
**LE:** Realized that the these requirements were actually needed for the unit tests and moved them to contributing.
> docs: add unit tests requirements

- pkg/gadgets/internal/socketenricher/bpf/sockets-map.h
When tcpretrans used vmlinux.h's trace_event_raw_tcp_event_sk_skb instead of a custom struct (see https://github.com/inspektor-gadget/inspektor-gadget/pull/1561#discussion_r1176919879), the skb field changed in this way:
```diff
- 	void *skbaddr;
-	void *skaddr;
+       const void *skbaddr;
+       const void *skaddr;
```
This caused compilation warnings such as:
> /work/pkg/gadgets/trace/tcpretrans/tracer/bpf/tcpretrans.bpf.c:105:55: warning: passing 'const struct sock *' to parameter of type 'struct sock *' discards qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
>         struct sockets_value *skb_val = gadget_socket_lookup(sk, event.netns);
>                                                             ^~
> ../../../internal/socketenricher/bpf/sockets-map.h:109:35: note: …
> socket-enricher: fix compilation warnings

- pkg/operators/localmanager/localmanager.go
This PR reintroduces the flags related to custom socket paths for container runtimes:
```
→ ig -h
Collection of gadgets for containers
...
...
Flags:
-h, --help              help for ig
-r, --runtimes string   Container runtimes to be used separated by comma. Supported values are: docker, containerd, cri-o (default "docker,containerd,cri-o")
...
```
```
→ ./ig -h
Collection of gadgets for containers
...
...
Flags:
--containerd-socketpath string   Containerd CRI Unix socket path (default "/run/containerd/containerd.sock")
--crio-socketpath string         CRI-O CRI Unix socket path (default "/var/run/crio/crio.sock")
--docker-socketpath string       Docker Engine API Unix socket path (default "/var/run/docker.sock")
-h, --help                           help for ig
-r, --runtimes string …
```
> localmanager: Reintroduce custom socket paths for container runtimes

- docs/devel/release-process.md
We should not keep the milestone for the release open. We should update the Inspektor Gadget Addon in Minikube.
> docs/devel/release-process.md: add post-release instructions

- integration/ig/k8s/top_tcp_test.go
- integration/inspektor-gadget/top_tcp_test.go
- pkg/gadgets/top/tcp/tracer/tracer.go
- pkg/gadgets/top/tcp/types/types.go
- pkg/gadgets/trace/tcp/types/types.go
- pkg/gadgets/trace/tcpconnect/types/types.go
- pkg/gadgets/trace/tcpdrop/types/types.go
- pkg/gadgets/trace/tcpretrans/types/types.go
- pkg/types/types.go
This PR creates a template for the ip version column and applies it to all gadgets with such a column. In particular, notice that the top tcp gadget was using `maxWidth` instead of `width:2,fixed`, thus this PR uniforms it with other gadgets.
> pkg/types: Create ip version column template

- docs/install.md
Inspektor Gadget is now available as an Addon in minikube: https://minikube.sigs.k8s.io/docs/handbook/addons/inspektor-gadget/
This patch adds this in the documentation as an option in the possible ways to install Inspektor Gadget on minikube.
cc @yolossn
> docs: installation on minikube

- cmd/common/registry.go
- cmd/ig/main.go
- cmd/kubectl-gadget/main.go
- pkg/columns/columninfo.go
- pkg/columns/columns.go
- pkg/columns/columns_test.go
- pkg/columns/doc.go
- pkg/columns/filter.go
- pkg/columns/sort/sort_test.go
- pkg/gadgets/snapshot/process/types/process-collector.go
- pkg/gadgets/snapshot/socket/types/socket-collector.go
- pkg/gadgets/top/ebpf/types/types.go
- pkg/gadgets/top/tcp/types/types.go
- pkg/gadgets/trace/mount/types/types.go
- pkg/gadgets/trace/network/types/types.go
- pkg/gadgets/trace/tcpconnect/types/types.go
- pkg/gadgets/trace/tcpdrop/types/types.go
- pkg/gadgets/trace/tcpretrans/types/types.go
- pkg/parser/parser.go
Right now, the `snapshot/process` gadget has the parameter `--threads`, which, if enabled, would allow displaying a new column showing `TID`. This column however doesn't get shown automatically right now, if said parameter is `true`. Instead, the user would have to specify the column explicitly by using `-o columns=...,tid`.
This PR allows adding `columnTags` in the form of `param:threads` to columns. These tags then will be compared to boolean parameters available for a gadget (like said `--threads`) - and if those parameters are falsy, columns with corresponding tags will be hidden.
To improve UX, required parameters will now also be shown in the `--help` for the columns:
```
-o, --output string          Output format (jsonpretty, yaml, tree, json, columns).
Columns (columns)
The output …
```
> Allow hiding columns based on selected features / parameters

- cmd/common/utils/flags.go
- cmd/ig/utils/flags.go
- cmd/kubectl-gadget/deploy.go
- cmd/kubectl-gadget/utils/consts.go
- integration/ig/k8s/trace_fsslower_test.go
- pkg/container-collection/container-collection.go
- pkg/container-collection/options.go
- pkg/container-utils/containerutils.go
- pkg/container-utils/oci-annotations/types.go
- pkg/container-utils/podman/podman.go
- pkg/container-utils/runtime-client/interface.go
- pkg/operators/localmanager/localmanager.go
- pkg/runcfanotify/runcfanotify.go
* runcfanotify adds support for crun.
* runtime-client adds support for podman.
```
$ make ig && sudo ./ig list-containers -w
...
...
TIMESTAMP                      EVENT      RUNTIME    ID                                               NAME                                                                                                         
2023-05-02T17:47:41+02:00      CREATED    docker     ba4b260ec89864a1cd2de86dc0b918c04c9da7bc1d8139a… boring_ride                                                                                                  
2023-05-02T17:47:41+02:00      DELETED    docker     ba4b260ec89864a1cd2de86dc0b918c04c9da7bc1d8139a… boring_ride                                                                                                  
2023-05-02T17:47:54+02:00 …
```
> Add support for crun and podman

- .github/workflows/inspektor-gadget.yml
Long names are not visible in the web UI, making it impossible to distinguish the different actions.
Example of too long names:
<details>
</details>
> GitHub Action: use shorter names

- .github/workflows/inspektor-gadget.yml
The scanning only uses the container image, it doesn't need the code nor the image tag.
Suggested-by: Qasim Sarfraz <qasimsarfraz@microsoft.com>
ref https://github.com/inspektor-gadget/inspektor-gadget/pull/1641#discussion_r1198715827
/cc @mqasimsarfraz
> gha: Remove uneeded steps for CVE scanning

- .github/workflows/inspektor-gadget.yml
Ignore unfixed CVEs to avoid the CI failing in those cases.
> ci: Ignore unfixed CVEs

- examples/kube-container-collection/deploy.yaml
- examples/runc-hook/deploy.yaml
- pkg/container-collection/options.go
- pkg/resources/manifests/deploy.yaml
hostNetwork=true was initially necessary for the traceloop gadget. But since it was refactored, it is not necessary anymore.
This patch changes the gadget DaemonSet to use hostNetwork=false.
Since the gadget pod is no longer running in the host network namespace, changes the code to get the inode of the host network namespace with `$HOST_ROOT/proc/1/ns/net`.
We cannot use `$HOST_ROOT/proc/$(os.Getpid)/ns/net` anymore because:
- gadgettracermanager might not be in the host network namespace
- os.Getpid() will not return a valid pid in the host pid namespace.
Reading `$HOST_ROOT/proc/1/ns/net` requires `CAP_SYS_PTRACE` if pid 1 runs as a different uid than Inspektor Gadget. We should avoid that from an init() function because it makes 'make generate-documentation' fail.
Part of …
> Don't use hostNetwork=true

- .github/workflows/inspektor-gadget.yml
- integration/container_interface.go
- integration/containerd.go
- integration/docker.go
- integration/ig/non-k8s/Makefile
- integration/ig/non-k8s/integration_test.go
- integration/ig/non-k8s/list_containers_test.go
- integration/ig/non-k8s/snapshot_process_test.go
- integration/ig/non-k8s/trace_dns_test.go
- integration/ig/non-k8s/trace_network_test.go
- pkg/container-utils/testutils/containerd.go
- pkg/container-utils/testutils/options.go
- pkg/container-utils/testutils/options_test.go
This will be merged into a branch that is an open PR #1233 
The `non-k8s` intergration tests for `ig` were restructured to generalize around the runtime.
> Test non-k8s containerd API

- cmd/common/params.go
- cmd/common/params_test.go
- cmd/common/registry.go
- pkg/params/params.go
- pkg/params/params_test.go
- pkg/params/validators.go
Sometimes a parameter can become long or one wants to set the whole content of a file as the parameter. For this use case one can now specify the filepath if a `@` is used as a prefix 
Example: `echo docker > test.txt && sudo ./ig -r @./test.txt snapshot process`
Furthermore the `bytes` type was introduced. For best transportation it is compressed and then b64 encoded (because of CR)
> Registry/Columns: Read from file + new `bytes` type

- go.mod
It's not needed anymore. Trivy doesn't report CVE-2021-3121 anymore:
```
$ ./trivy image  --format table --exit-code  1 --vuln-type  os,library --severity  CRITICAL,HIGH mauriciovasquezbernal/gadget:latest --ignore-unfixed 2023-05-18T10:18:30.907-0500	INFO	Vulnerability scanning is enabled 2023-05-18T10:18:30.907-0500	INFO	Secret scanning is enabled 2023-05-18T10:18:30.907-0500	INFO	If your scanning is slow, please try '--scanners vuln' to disable secret scanning 2023-05-18T10:18:30.907-0500	INFO	Please see also https://aquasecurity.github.io/trivy/v0.41/docs/secret/scanning/#recommendation for faster secret detection 2023-05-18T10:18:30.923-0500	INFO	Detected OS: ubuntu 2023-05-18T10:18:30.923-0500	INFO	Detecting Ubuntu vulnerabilities... 2023-05-18T10:18:30.929-0500	INFO	Number of …
```
> dependencies: Remove replace for protobuf

- .semgrep_rules.yaml
I forgot to git add the file in previous commit. It's not clear to me why the CI didn't fail, but the semgrep container returns 0 if the config file doesn't exist:
```bash
$ docker run -v $(pwd):/host returntocorp/semgrep sh -c "cd /host && semgrep ci --config /doesnotexist.yaml"
┌────────────────┐
│ Debugging Info │
└────────────────┘
SCAN ENVIRONMENT
versions    - semgrep 1.22.0 on python 3.11.3
environment - running in environment git, triggering event is unknown
[ERROR] WARNING: unable to find a config; path `/doesnotexist.yaml` does not exist (since you are running in docker, you cannot specify arbitrary paths on the host; they must be mounted into the container)
[ERROR] invalid configuration file found (1 configs were invalid)
$ echo $?
0
```
Fixes: f825ff80e29d ("ci: Add semgrep …
> ci: Add missing semgrep file

- pkg/columns/columninfo.go
- pkg/columns/columns.go
- pkg/columns/columns_test.go
- pkg/columns/filter/filter.go
- pkg/columns/filter/filter_test.go
- pkg/columns/formatter/textcolumns/output.go
- pkg/columns/options.go
- pkg/columns/sort/sort.go
- pkg/columns/sort/sort_test.go
This change enhances support for embedded structs (pointer and non-pointer types). Previously, only non-pointer types were supported.
Additionally, embedded struct members can now be prefixed automatically with the name of the parent field to avoid duplicate field names.
```go
type Demo struct {
Parent *struct {
Child int `column:"int"`
} `column:"parent" columnTags:"abc"`
}
```
So in this case, the inner field will be accessible using `parent.int`. Additionally, `columnTags` will now be inherited by members of the sub-structs. In the case above, `parent.int` will also have the columnTag `abc`.
This is in preparation of gadgets that want to embed certain struct types in their event types more than once (like src/destination address information).
I also updated some test files to use the …
> pkg/columns: add support for embedded struct handling, optimize raw access

- integration/helpers.go
- integration/inspektor-gadget/prometheus_test.go
- integration/inspektor-gadget/testdata/prometheus/counter.yaml
This is the initial idea of integration tests for Prometheus gadget. It need polishing to be ready for merge but I wanted to get early feedback on the approach in general. 
-  Start a prometheus server  with scrape_config for gadget pod.
- Start prometheus gadget to start collecting metrics.
- Generate test events.
- Validate metrics against prometheus API. 
```bash
$ make minikube-deploy
$ INTEGRATION_TESTS_PARAMS="-run TestPrometheus/CounterMetrics -no-deploy-ig -no-deploy-spo" make integration-tests
...
...
--- PASS: TestPrometheus (34.22s)
--- PASS: TestPrometheus/CounterMetrics (32.37s)
PASS
Cleaning up...
Start command(DeleteRemainingTestNamespace): kubectl delete ns -l scope=ig-integration-tests
Wait for command(DeleteRemainingTestNamespace)
Command …
```
> integration: Add tests for prometheus gadget

- cmd/common/frontends/console/console.go
- cmd/common/frontends/frontends.go
- cmd/common/registry.go
When frontend is not a terminal:
```bash
CONTAINER                      PID              COMM             IP               REMOTE           LOCAL            SENT             RECV
CONTAINER                      PID              COMM             IP               REMOTE           LOCAL            SENT             RECV
konnectivity-agent             6270             proxy-agent      4                52.224.21.37:443 10.224.0.138:438 43.56KiB         2.077KiB
konnectivity-agent             6270             proxy-agent      4                52.224.21.37:443 10.224.0.138:339 3.518KiB         1.624KiB
ama-logs                       1856536          in_cadvisor_pe*  4                10.224.0.113:102 10.224.0.125:394 1.969KiB         37.08KiB
ama-logs                       1856536 …
```
> gadget/top: Print first header columns only when frontend is a terminal

- docs/design/001-prometheus.md
CI job that checks for broken links failed because I removed that branch. Update the link to point to the PR instead.
> docs: Fix link in prometheus design

- docs/gadgets/trace/oomkill.md
The name of the field is kcomm and not komm.
> docs: oomkill: fix typo

- pkg/columns/columninfo.go
- pkg/columns/columns_test.go
Currently, in the following case, the prefix `runtime` is not applied to the `Container` field because it uses a template. While the prefix is correctly applied to the `ID` field:
```golang
type RuntimeMetadata struct {
ID        string `column:"id"`
Container string `column:"container,template:container"`
}
type GadgetData struct {
RuntimeMetadata RuntimeMetadata `column:"runtime" columnTags:"runtime"`
GadgetData      string          `column:"gadgetData"`
}
```
This PR makes the columns library to support applying prefixes also when templates are used.
> columns: Support prefix when using templates

- integration/helpers.go
Ignore unexported fields when doing `cmp.Diff` to avoid panic during test runs. Currently, I see only `containercollection.Container{}` has unexported events. 
Break the test with:
<details><summary>Patch</summary>
<p>
```
diff --git a/integration/ig/non-k8s/list_containers_test.go b/integration/ig/non-k8s/list_containers_test.go
index fb68774a..10d56f8b 100644
--- a/integration/ig/non-k8s/list_containers_test.go
+++ b/integration/ig/non-k8s/list_containers_test.go
@@ -37,7 +37,7 @@ func TestFilterByContainerName(t *testing.T) {
normalize := func(c *containercollection.Container) {
c.ID = ""
-                               c.Pid = 0
+                               //c.Pid = 0
c.OciConfig = nil
c.Bundle = ""
c.Mntns = 0
```
</p>
</details> 
<details><summary>Diff</summary>
<p>
```
...
--- …
```
> integration: Use cmpopts.IgnoreUnexported for cmp.Diff

- pkg/container-collection/container-collection.go
- pkg/container-collection/options.go
- pkg/container-utils/cri/cri.go
- pkg/ig-manager/ig-manager.go
We want to disable container runtime warnings in case user is running with default container runtime configuration to improve the user experience. Also, I don't want to disable warnings by default and allow it to be configured via an option e.g we should keep these warnings for `gadgettracermanager` 
Fixes #1537 
```bash
→ sudo ./ig trace open
WARN[0000] Failed to determine CRI API version: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial unix /run/crio/crio.sock: connect: no such file or directory" using v1 
WARN[0000] Runtime enricher (cri-o): couldn't get current containers: listing containers with request &ListContainersRequest{Filter:nil,}: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: …
```
> logs: Print ig warnings only with custom config

- Makefile
- pkg/container-collection/container-collection.go
- pkg/container-collection/container-collection_test.go
- pkg/container-collection/containers.go
- pkg/container-collection/options.go
- pkg/runcfanotify/runcfanotify.go
pidfd_open(), os.FindProcess() and process.Signal() don't work for processes outside of the current pid namespace. Since we'd like IG to run in a container without hostPID=true, re-implement watchContainersTermination() with a periodic iteration on /proc (or /host/proc).
In preparation for #1658
> runcfanotify: replace pidfd_open/kill by reading /host/proc

- go.mod
- go.sum
- pkg/netnsenter/netnsenter.go
- pkg/rawsock/rawsock.go
As part of https://github.com/inspektor-gadget/inspektor-gadget/issues/1658, we want Inspektor Gadget to support deployments with hostPID=false.
Since Inspektor Gadget can run in a container with a new pid namespace, pid numbered in the host pid namespace have to be looked up in /host/proc instead of /proc.
There are a couple of places where /proc was used instead of /host/proc:
- OpenRawSock() for socket filters in networking gadgets (dns, sni)
- NetnsEnter() for the snapshot socket gadgets: tcp/udp iterators have to be opened from the correct netns
Both were using the vishvananda/netns library. We need a patch in that library:
https://github.com/vishvananda/netns/pull/76
No changes
> Open network namespaces from /host/proc (preparation for hostPID=false)

- pkg/utils/bpf-iter-ns/bpf-iter-ns.go
The host might not have bpffs mounted in some setups. See:
- [IG's entrypoint.sh#L50-L59](https://github.com/inspektor-gadget/inspektor-gadget/blob/v0.17.0/gadget-container/entrypoint.sh#L50-L59)
-  [minikube's entrypoint#L76-L81](https://github.com/kubernetes/minikube/blob/99a0c91459f17ad8c83c80fc37a9ded41e34370c/deploy/kicbase/entrypoint#L76-L81)
So use the bpffs mountpoint in the container mount namespace.
Symptoms before the fix:
> creating socket enricher: read BPF iterator: creating temporary
> directory in bpffs: mkdir /host/sys/fs/bpf/ig-iter-3218307710: no such
> file or directory
Fixes: 55f58bbe8dcf ("bpf-iter-ns: fix bpf pin path"), #1719
Fixes: e91a93bb2c0a ("Read bpf iterators from host pid ns"), https://github.com/inspektor-gadget/inspektor-gadget/pull/1708#discussion_r122017 …
> bpf-iter-ns: fix bpf pin path again

- .github/workflows/inspektor-gadget.yml
- docs/devel/CONTRIBUTING.md
It's useful for debugging purposes to avoid having to setup all of this
in a personal fork or pushing to main.
Signed-off-by: Mauricio Vásquez <mauriciov@microsoft.com>
---
I tried to implement a solution to automatically remove the image in the container repository but I'm too afraid that I can get this wrong and remove important images, hence I prefer to leave this as a manual step. 
---
Tested in https://github.com/mauriciovasquezbernal/inspektor-gadget/actions/runs/5212558595, I don't have AKS secrets configured but the image was pushed to https://github.com/mauriciovasquezbernal/inspektor-gadget/pkgs/container/inspektor-gadget, so it should work all fine :tm: .
> gha: Run AKS and ARO integration tests for `citest/` branches too.

- cmd/common/registry.go
- cmd/common/verbose.go
- cmd/ig/main.go
- cmd/kubectl-gadget/main.go
This change adds a global verbose flag that affects all logging operations using logrus instead of implementing it per command.
> cmd: move verbose flag to top level

- Dockerfiles/gadget-core.Dockerfile
- Dockerfiles/gadget-default.Dockerfile
golang1.19 switched to using [debian bookworm](https://github.com/docker-library/golang/commit/cd607138e461368506a6ba50be2163a09b93dab5) by default. This results in [couple of issues](https://kubernetes.slack.com/archives/CSYL75LF6/p1686815178297799) related to libseccomp for arm64 and missing GLIBC version for BCC image. We use 'bullseye' image to unblock, till we have a proper way to handle debian bookworm.
Related :
- #1749 
- https://github.com/docker-library/golang/issues/466
> Dockerfiles: Ensure we use 'bullseye' for golang builder image

- pkg/parser/parser.go
Currently we don't do any sorting after combining events related to top gadgets from different node. I believe this isn't an expected behavior so I sort events after combining from all the nodes. 
Fixes: #1733 
```bash
$ MINIKUBE_PARAMS="-n 3" make minikube-deploy
$ make kubectl-gadget 
$ ./kubectl-gadget top tcp --all-namespaces --interval 5 --max-rows 20 --sort -sent
```
> parser: Sort events after combining for top/snapshot gadgets

- pkg/gadget-service/service.go
- pkg/gadgets/params.go
- pkg/runtime/grpc/grpc-runtime.go
This PR moves the serialization / deserialization of params (gadget, runtime and operator params) from and into `map[string]string` for our gadgets to a central location that can easily be reused. One such upcoming reuse will happen when serializing to and from custom resources.
> pkg/gadgets: add helpers to copy from/to param maps

- integration/inspektor-gadget/integration_test.go
- integration/inspektor-gadget/top_blockio_test.go
- integration/inspektor-gadget/top_ebpf_test.go
- integration/inspektor-gadget/top_file_test.go
- integration/inspektor-gadget/top_tcp_test.go
- pkg/parser/parser.go
- pkg/runtime/grpc/grpc-runtime.go
As mentioned in the comment [here](https://github.com/inspektor-gadget/inspektor-gadget/issues/716#issuecomment-1581315275) the [snapshot ticker](https://github.com/inspektor-gadget/inspektor-gadget/blob/main/pkg/parser/parser.go#L159) can go off bit early compared to when we [receive](https://github.com/inspektor-gadget/inspektor-gadget/blob/main/pkg/runtime/grpc/grpc-runtime.go#L310) events. Which should be fine in case user is running gadget for multiple intervals since the missed events will be printed in following interval. But this is problematic when gadget is only ran for single interval (`timeout==interval`). 
The idea with this change it to introduce a flush mechanism to ensure all the outstanding events are sent downstream for handling before exiting. Timeout timer is running …
> kubectl-gadget/top: Ensure timeout=interval prints event before exiting

- integration/ig/k8s/list_containers_test.go
- pkg/container-hook/tracer.go
- pkg/runcfanotify/runcfanotify.go
As mentioned in the comment [here](https://github.com/inspektor-gadget/inspektor-gadget/issues/1692#issuecomment-1591486516) we need to handle `passwd` file in case of non root crio containers. The idea is to ignore events from `passwd` similar to `config.json`.
Fixes: #1692 
Added an integration test: [TestPodWithSecurityContext](https://github.com/inspektor-gadget/inspektor-gadget/blob/69f61a3df1bbecbcad775a708c66ea74b6f4634a/integration/ig/k8s/list_containers_test.go#L247). Also, can be tested manually as:
```bash
$ make CONTAINER_RUNTIME=cri-o minikube-start
$ make ig && docker cp ig minikube-cri-o:/bin/ig
$ docker exec -it minikube-cri-o ig list-containers -w
$ kubectl run test-pod --image=busybox --overrides='{ "apiVersion": "v1", "spec": { "securityContext": { "runAsUser": 1000 } } …
```
> runcfanotify/container-hook: Ignore events from 'passwd' in pidfile directory

- Dockerfiles/gadget-core.Dockerfile
- Dockerfiles/kubectl-gadget.Dockerfile
- tools/dnstester/Dockerfile
Since alpine 3.14 has reached end of support (https://www.alpinelinux.org/releases/), Update to latest (stable) release for all builder images. Also, change the CO-RE base image to `debian:bullseye-slim` till #801 is fixed and we are able to move to distroless. The change in the size of the final image is from  `67 MB (192 MB)` compressed to `90 MB (260 MB)`.
> Dockerfiles: Update alpine image and change CO-RE image to debian:bullseye-slim

- cmd/kubectl-gadget/deploy.go
- pkg/resources/manifests/deploy.yaml
It seems the pods with hostNetwork/hostPid [1] aren't confined by SELinux. But recently we disabled both hostNetwork/hostPid for gadget pod hence we need to set appropiate SELinux context allowing us to mount host paths with correct persmission. This change also introduces a flag 'skip-selinux-opts' to allow user to skip this option if needed. Please see the [comments](https://github.com/inspektor-gadget/inspektor-gadget/pull/1709#issuecomment-1599080208) for details.
1 - https://github.com/cri-o/cri-o/blob/v1.27.0/server/sandbox_run_linux.go#L537
> deploy: Add 'seLinuxOptions' for gadget container

- pkg/container-utils/containerutils_test.go
We should be able to initialze runtimeclient.ContainerRuntimeClient even if the underlying runtime isn't available e.g socketPath not found etc. I added a test to ensure we can track this intention.
> container-utils: Add TestNewContainerRuntimeClient

- integration/inspektor-gadget/prometheus_test.go
TestPrometheus failed few times in the CI without [expected counter value](https://github.com/inspektor-gadget/inspektor-gadget/actions/runs/5177112743/attempts/1#summary-14008659335). We believe it might be related to wait duration after we generate the events. The idea of this change is to increase the sleep interval to ensure we get enough time to capture all the events. Also, it enables debug logging for prometheus pod.
> integration: Increase wait duration in TestPrometheus

- gadget-container/entrypoint.sh
- pkg/container-collection/k8s.go
- pkg/container-collection/options.go
- pkg/container-collection/podinformer.go
This commit fixes few issues with the logic to remove non-runinng
containers:
1. Remove container that weren't added by the pod informer: it can happen
that a container is added by a different hook but such hooks fails to
remove it. In this case the podinformer can act as a backup mechanism
to remove such container.
This cause the enrichment to fail in some cases as the cotainer
collection keep a container with a mount or net ns reference that
doesn't exist anymore, then it can be reused by a new container making
the enrichment to enrich with the wrong data.
2. Remove runtime prefix from id: The container's ID in the container
collection is stored without a container runtime prefix. Remove this
before calling cc.RemoveContainer().
3. Remove elements from containerIDsByKey map when pod is …
> podinformer: Fix removing non-running containers

- pkg/container-collection/container-collection.go
- pkg/container-collection/container-collection_test.go
- pkg/container-collection/containers.go
- pkg/container-collection/options.go
We're hitting, again, the issue where the events are enriched with the wrong container data, this time in networking gadgets. This is happenning because in some situations the container collection can keep the reference to a container that is not present anymore in the kernel (yes, I know containers aren't a kernel concept but you get the point). In this case, the kernel can reuse the net ns inode in a new container, making the enrichment process to use the wrong container.
The solution proposed here is the same as 4dedafc8565d ("Fix race condition on enrichers") but this time for the net ns.
Fixes https://github.com/inspektor-gadget/inspektor-gadget/issues/1001
TODO
> container-collection: Keep net ns inode id reference

- docs/crds/gadgets/ebpftop.md
- docs/gadgets/top/ebpf.md
- go.mod
- go.sum
- integration/ig/k8s/top_ebpf_test.go
- integration/ig/non-k8s/top_ebpf_test.go
- integration/inspektor-gadget/top_ebpf_test.go
- pkg/gadgets/top/ebpf/tracer/tracer.go
- pkg/gadgets/top/ebpf/types/types.go
This PR introduces cpu usage column in top ebpf gadget. Related issue: https://github.com/inspektor-gadget/inspektor-gadget/issues/1757
For those who want to compare ebpf prog overheads with other processes, runtime is not intuitive. Thus, It would be better if we have a column `CPU` to show sth like what we see in top.
The definition for cpuusage here is similar to that in `top`. It is defined as: The ebpf prog's share of the elapsed CPU time since the last update, expressed as a percentage of total CPU time. Because the ebpf prog's runtime is adding up runtime on each core in kernel, it's possible that the cpuusage here is over 100%.
1. build ig: `make ig`
2. run ig ebpf top: `sudo ./ig top ebpf -o columns=progid,type,name,pid,comm,runtime,cpu`
3. check test case: `make test`
1. make …
> pkg/gadgets/top/ebpf: introduce cpu usage

- gadget-container/entrypoint.sh
The entry point script reads the os-release information from /host/etc/os-release. This is used to print some debug messages and to gather the BTF files from btfhub.  In some cases, this file is not available at that location, for instance in NixOS. This makes the installation fail and hence IG is unusable there.
This commit modifies the logic not to return a hard error in that case, as this information is not fundmental and Inspektor Gadget can work without it.
Fixes https://github.com/inspektor-gadget/inspektor-gadget/issues/1697. 
--- 
I followed the instructions in https://nixos.wiki/wiki/K3s to get a k3s cluster running on NixOS. I used kubectl-gadget v0.17 for this.
```bash
$./kubectl-gadget deploy --image=docker.io/mauriciovasquezbernal/gadget:mauricio-ignore-os-release-error …
```
> entrypoint: Do not fail if os-release info is not available.

- Makefile
- pkg/ig-manager/ig-manager_test.go
Use utilstest.RequireRoot() instead to skip the test if not run as root.
> ig-manager: Remove --root-test flag for unit tests

- Dockerfiles/kubectl-gadget.Dockerfile.dockerignore
When the --experimental flag was added, it added a internal/deployinfo package that is needed to build kubectl-gadget in a container.
Symptoms:
```
cmd/kubectl-gadget/undeploy.go:25:2: no required module provides package github.com/inspektor-gadget/inspektor-gadget/internal/deployinfo; to add it:
go get github.com/inspektor-gadget/inspektor-gadget/internal/deployinfo
make: *** [Makefile:121: kubectl-gadget-linux-amd64] Error 1
```
xref https://github.com/inspektor-gadget/inspektor-gadget/pull/1728
> Fix make kubectl-gadget-container

- pkg/container-collection/container-collection.go
- pkg/container-collection/container-collection_test.go
- pkg/container-collection/operator.go
When enriching container information on events using the container-collection (which is a hot path in our code), we usually look up containers by either mntnsid or netnsid. Previously, we returned matching containers after iterating over the main container map. With this patch, we instead use dedicated lookup maps for both mntns and netns to increase performance. Additionally, previously, when looking up containers using netnsid, a temporary array got created - this allocation has also been moved to the map maintenance and only is done when adding or removing containers instead of on each lookup operation.
Benchmarks:
```
$ benchstat main.bench update.bench
goos: linux
goarch: arm64
pkg: github.com/inspektor-gadget/inspektor-gadget/pkg/container-collection
│   main.bench    │ …
```
> pkg/container-collection: replace container iteration with lookup maps for hot paths

- pkg/operators/localmanager/localmanager.go
Don't call AttachContainer/DetachContainer on gadgets that don't implement that interface.
Symptoms: ig panics after ctrl-c with trace exec --host
```
^Cpanic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x1d8f0eb]
github.com/inspektor-gadget/inspektor-gadget/pkg/operators/localmanager.(*localManagerTrace).PostGadgetRun(0xc0004ca700)
/go/src/github.com/inspektor-gadget/inspektor-gadget/pkg/operators/localmanager/localmanager.go:350 +0x24b
github.com/inspektor-gadget/inspektor-gadget/pkg/operators.OperatorInstances.PostGadgetRun(...)
/go/src/github.com/inspektor-gadget/inspektor-gadget/pkg/operators/operators.go:255
github.com/inspektor-gadget/inspektor-gadget/pkg/runtime/local.(*Runtim …
```
> Fix panic with --host on non-networking gadgets

- pkg/container-hook/tracer.go
- pkg/runcfanotify/runcfanotify.go
Talos Linux (https://www.talos.dev/) has `runc` installed to a different location. Adding this path to the `runcPaths` slice.
I would suggest you try one of the virtualized [local platforms](https://www.talos.dev/v1.3/talos-guides/install/local-platforms/) to validate this PR.
I have used my fork in my project instead of the main repo in my `go.mod`:
```
replace github.com/inspektor-gadget/inspektor-gadget v0.18.0 => github.com/matthyx/inspektor-gadget v0.0.0-20230705092830-3f5f553ecd9c
```
> add extra path for runc on talos

- cmd/common/registry.go
- cmd/common/verbose.go
There was a bug, that prevented gadgets that don't use a parser, from outputting help when requested. This fixes that. This also fixes `--verbose` not working properly on gadgets anymore by manually checking the flag at a later stage.
Reason for the changed behavior is that we delayed flag parsing, so that we can handle them more dynamically and still have proper `--help` output.
> cmd/common/registry: fix `--help` for gadgets without parser, fix `--verbose`

- Makefile
When the ig container image fails to build, don't ignore the error and fail immediately. Otherwise, it's picking up whatever container image was previously built with the same name.
Before this patch, it was continuing as follows:
```
$ make ig
echo Building ig-linux-amd64
Building ig-linux-amd64
docker buildx build --load --platform=linux/amd64 -t ig-linux-amd64 -f Dockerfiles/ig.Dockerfile \
--build-arg VERSION=`git describe --tags --always`-dirty . ;\
docker create --name ig-linux-amd64-container ig-linux-amd64
[+] Building 10.4s (4/4) FINISHED                                                                                     
=> [internal] load .dockerignore                                                                                0.1s
=> => transferring context: 2B …
```
> Makefile: ig: stop on build error

- pkg/gadgets/prometheus/tracer/gadget.go
- pkg/gadgets/prometheus/tracer/tracer.go
- pkg/prometheus/config/config.go
- pkg/prometheus/config/config_test.go
- pkg/prometheus/prometheus.go
- pkg/prometheus/prometheus_test.go
Avoid packages that only need the config having to pull all dependencies. For instance, this avoid kubectl-gadget importing
"github.com/inspektor-gadget/inspektor-gadget/pkg/runtime/local".
Fixes https://github.com/inspektor-gadget/inspektor-gadget/issues/1830
Introduce any linux specific code, for instance:
```diff
$ git diff
diff --git pkg/runtime/local/local.go pkg/runtime/local/local.go
index ab39ee02..3e12262b 100644
--- pkg/runtime/local/local.go
+++ pkg/runtime/local/local.go
@@ -34,6 +34,8 @@ type Runtime struct {
}
func New() *Runtime {
+       fmt.Printf("%s\n", Foo)
+
return &Runtime{
catalog: prepareCatalog(),
}
```
```bash 
$ cat pkg/runtime/local/foo_linux.go 
package local
const Foo = "foo"
```
Compiling kubectl-gadget for Windows works fine with this commit
```
$ make …
```
> pkg/prometheus: Move config to independent package

- cmd/ig/containers/containers.go
- cmd/ig/main.go
- docs/ig.md
- gadget-container/entrypoint.sh
- gadget-container/gadgettracermanager/main.go
- internal/test/helpers.go
- pkg/gadgets/internal/socketenricher/tracer_test.go
- pkg/gadgets/snapshot/process/tracer/tracer_test.go
- pkg/runcfanotify/runcfanotify.go
- pkg/runtime/local/local.go
- pkg/utils/bpf-iter-ns/bpf-iter-ns.go
- pkg/utils/host/host.go
- pkg/utils/host/namespaces.go
- pkg/utils/host/workarounds.go
Since #1787, ig is published as a container image. You can fetch it with:
```
docker pull ghcr.io/inspektor-gadget/ig
```
This PR adds documentation and fixes for kubectl-debug and Docker Desktop on Windows.
This is part of removing things from entrypoint.sh as suggested in #801. This picks up the changes in entrypoint.sh required by Docker Desktop (#1768). See also https://github.com/inspektor-gadget/inspektor-gadget/pull/1789#discussion_r1245693180.
Examples of commands:
```bash
$ kubectl debug node/minikube-docker -ti --image=ghcr.io/inspektor-gadget/ig -- ig trace exec
$ kubectl debug node/minikube-docker -ti --image=ghcr.io/inspektor-gadget/ig -- ig list-containers -o json
```
Example of command:
```bash
$ docker run -ti --rm \
--privileged \
-v /sys/fs/bpf:/sys/fs/bpf \
-v …
```
> ig container image: docs and fixes for kubectl-debug and Docker Desktop on Windows

- cmd/ig/containers/containers.go
- pkg/types/types.go
Wrong order:
```bash
$ sudo ./ig list-containers
RUNTIME.RUNTIMENAME RUNTIME.CONTAINERID                                              RUNTIME.CONTAINERNAME
docker              50a302ad9b0462831f023f3715b9936f09985c0ce59290d577a0e1eee0f82d3f foo
containerd          6791084becce901dd1da36eaad312c6cb58ffb8e308ce491e45b62f30e3f51fe etcd
containerd          b2463090f4483b0bb30e4e37d9fbb0e6149b786b112d1f1173d11e0275e0e4f1 kube-scheduler
containerd          b74c71741d99bc3b6a6d8fd5ef2af0cfbe2b8cd6bd4902bcc5fc81ad2a796514 kube-controller-manager
```
Missing columns:
```bash
$ sudo ./ig list-containers -w
TIMESTAMP                      EVENT      RUNTIME.CONTAINERNAME
2023-07-14T11:37:47Z           CREATED    etcd
2023-07-14T11:37:47Z           CREATED    kube-scheduler
2023-07-14T11:37:47Z …
```
> cmd/ig: Fix order and visible columns in list-containers command

- pkg/container-collection/container-collection.go
- pkg/container-collection/options.go
- pkg/ig-manager/ig-manager_test.go
The enrichers were called twice for initial containers.
This was especially problematic for the WithTracerCollection enricher because it opens file descriptors and they were never closed.
This patch ensures the enricher were called only one time.
Fixes https://github.com/inspektor-gadget/inspektor-gadget/issues/1832
```
go test -test.v -exec sudo -run TestClose ./pkg/ig-manager/...
```
> container-collection: fix fd leak for initial containers

- pkg/gadgets/top/ebpf/types/types.go
The container name doesn't make sense for the top/ebpf gadget. So, let's hide it.
Related with https://github.com/inspektor-gadget/inspektor-gadget/issues/1859
Issue introduced in https://github.com/inspektor-gadget/inspektor-gadget/pull/1702
> top/ebpf: Hide the runtime container name

- pkg/container-hook/tracer.go
- pkg/runcfanotify/runcfanotify.go
We have found an installation with contrainerd where runc was installed into the /usr/local/bin directory. This was not included in the paths where IG is looking for the runc binary though it looks like it should.
Verified the change on the given setup.
> Adding "/usr/local/bin/runc" to the list of potential runc paths

- Dockerfiles/gadget-core.Dockerfile
- Dockerfiles/gadget-default.Dockerfile
- Dockerfiles/ig-tests.Dockerfile
- Dockerfiles/ig.Dockerfile
- Dockerfiles/kubectl-gadget.Dockerfile
The list of standard labels and annotations are defined here: https://github.com/opencontainers/image-spec/blob/main/annotations.md#pre-defined-annotation-keys
When visiting different tags on the following container image pages, [this](https://github.com/inspektor-gadget/inspektor-gadget/pkgs/container/ig/110223979?tag=latest) currently says:
> About this version: No description provided
See:
* https://github.com/inspektor-gadget/inspektor-gadget/pkgs/container/ig
* https://github.com/orgs/inspektor-gadget/packages
According to the following documentation, it is recommended to use labels except for the description of multi-arch images where an annotation should be defined in the GitHub Action.
https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-cont …
> container images: add descriptions and other labels

- integration/inspektor-gadget/run_trace_open_test.go
- integration/run_helpers.go
- pkg/columns/columns.go
- pkg/columns/columns_test.go
- pkg/columns/formatter/json/buffer.go
- pkg/columns/formatter/json/json.go
- pkg/columns/formatter/json/json_test.go
- pkg/columns/formatter/json/options.go
- pkg/columns/formatter/textcolumns/textcolumns_test.go
- pkg/gadgets/run/tracer/run.go
This PR adds a new formatter which outputs json "through" the columns library.
This has the advantage that the columns and json output will always be aligned and the same. Additionally we won't need duplicate logic for the different output modes in the `run` gadget
**WIP and proposal. Ideas really welcome :)**
I just added another commit which adds some integration test helpers and modifies the test for `TestRunTraceOpen`.
We can't use the traditional functions for the containerized gadgets.
They were directly unmarshaling into the Event object which we don't have with containerized gadgets.
Most of the columns are dynamically created and therefore the output json is also mostly dynamic and depends solely on the BTF and config from the input.
So with this commit the expected entry is now …
> gadgets/run: Add JSON output

- integration/ig/k8s/list_containers_test.go
- integration/ig/k8s/profile_cpu_test.go
- integration/ig/k8s/snapshot_process_test.go
- integration/ig/k8s/top_block_io_test.go
- integration/ig/k8s/top_file_test.go
- integration/ig/k8s/top_tcp_test.go
- integration/ig/k8s/trace_network_test.go
- integration/ig/non-k8s/list_containers_test.go
- integration/ig/non-k8s/snapshot_process_test.go
- integration/ig/non-k8s/trace_dns_test.go
- integration/ig/non-k8s/trace_network_test.go
- pkg/container-collection/options.go
- pkg/container-utils/containerd/containerd.go
- pkg/container-utils/cri/cri.go
This PR adds initial containers enrichment with ContainerImageName for containerd and cri-o runtimes.
Implements:  #1310
> containerd and cri-o: Enrich initial containers with container image name

- .github/workflows/inspektor-gadget.yml
- Makefile
- tools/getbpftool.sh
- tools/getbtfhub.sh
btfhub removed their binary from the repo in https://github.com/aquasecurity/btfhub/pull/96. Switch to download the binary from the bpftool repo instead.
Ref https://github.com/inspektor-gadget/inspektor-gadget/pull/1896
> ci: Fix btfgen

- pkg/gadgets/run/tracer/tracer.go
Avoid crashing when the --host parameter is passed as in that case the mount ns filter map is not created.
Fixes: 07ca0fb4e97a ("Initial support for containerized gadgets")
> gadgets/run: Fix handling of --host parameter

- cmd/ig/containers/containers.go
- pkg/container-collection/containers.go
- pkg/types/types.go
`ContainerImageName` column was displayed for most of the gadgets taking unnecessary space on the screen.
It is now hidden for all gadgets and only displayed for `ig list-containers` and `ig list-containers -w`.
Fixes: #1859
> Hide `ContainerImageName` column by default

- docs/examples/ds-ig.yaml
- docs/examples/pod-ig.yaml
- docs/ig.md
The ig documentation included explanations how to run it with Docker and how to run it with the "kubectl debug" command.
This patch adds another way to use ig in a custom pod. This shows an example of Dockerfile and a Kubernetes daemon set yaml. This is useful for third party software that wants to include ig.
> docs: add examples how to run ig in a custom pod

- cmd/ig/containers/containers.go
- integration/ig/k8s/list_containers_test.go
- integration/ig/k8s/profile_cpu_test.go
- integration/ig/k8s/snapshot_process_test.go
- integration/ig/k8s/top_block_io_test.go
- integration/ig/k8s/top_file_test.go
- integration/ig/k8s/top_tcp_test.go
- integration/ig/k8s/trace_bind_test.go
- integration/ig/k8s/trace_capabilities_test.go
- integration/ig/k8s/trace_dns_test.go
- integration/ig/k8s/trace_exec_test.go
- integration/ig/k8s/trace_fsslower_test.go
- integration/ig/k8s/trace_mount_test.go
- integration/ig/k8s/trace_network_test.go
- integration/ig/k8s/trace_oomkill_test.go
- integration/ig/k8s/trace_open_test.go
- integration/ig/k8s/trace_signal_test.go
- integration/ig/k8s/trace_sni_test.go
- integration/ig/k8s/trace_tcp_test.go
- integration/ig/k8s/trace_tcpconnect_test.go
- pkg/container-collection/containers.go
- pkg/container-utils/docker/docker.go
- pkg/types/types.go
Partly implements: #1310
`ContainerImageName` is retrieved from the Docker API. When image name is not provided, then `ContainerImageName` will contain the imageID. 
In json output the image ID is displayed in long form, while for listing containers it is truncated.
Image filed provided by Docker API may looks like e.g.
1. gcr.io/k8s-minikube/kicbase:v0.0.37@sha256:8bf7a0e8a062bc5e2b71d28b35bfa9cc862d9220e234e86176b3785f685d8b15
OR
2. busybox@sha256:3fbc632167424a6d997e74f52b878d7cc478225cffac6bc977eedfe51c7f4e79
These two provide both image name and digest separated by '@'.
3. docker.io/library/busybox:latest or simply busybox
Just image name is provided.
4. sha256:aebe758cef4cd05b9f8cee39758227714d02f42ef3088023c1e3cd454f927a2b
This fourth option provides the imageID and, following …
> Docker-ig: Enrich containers with container image name

- cmd/ig/main.go
- cmd/kubectl-gadget/main.go
- pkg/environment/k8s/k8s.go
- pkg/environment/local/local.go
- pkg/utils/experimental/experimental.go
The information from the deploy info only has to be taken into consideration when running in kubectl-gadget. When running ig, only the env variable is relevant.
This was causing an issue of enabling experimental features in ig when running on the same host where kubectl gadget deploy --experimental was used before.
```bash
$ ./kubectl-gadget deploy --experimental
$ cat $HOME/.ig/info.json  | jq '.Experimental'
true
$ sudo -E echo $IG_EXPERIMENTAL
```
Before this commit:
```
$ sudo -E ./ig trace exec
...
```
After this commit:
```
$ sudo -E ./ig trace exec
RUNTIME.CONTAINERNAME                    RUNTIME.CONTAINERIMA… PID
PPID       COMM             RET ARGS
$ sudo -E IG_EXPERIMENTAL=true ./ig trace exec
... …
```
> experimental: Fix detection logic

- integration/container_interface.go
- integration/containerd.go
- integration/docker.go
- integration/ig/non-k8s/list_containers_test.go
- integration/ig/non-k8s/snapshot_process_test.go
- integration/ig/non-k8s/trace_dns_test.go
- integration/ig/non-k8s/trace_network_test.go
- pkg/container-utils/containerd/containerd.go
- pkg/container-utils/containerutils_test.go
- pkg/container-utils/runtime-client/runtimeclient_test.go
- pkg/container-utils/testutils/container_interface.go
- pkg/container-utils/testutils/containerd.go
- pkg/container-utils/testutils/docker.go
- pkg/container-utils/testutils/options.go
- pkg/container-utils/testutils/options_test.go
- pkg/ig-manager/ig-manager_test.go
The container-utils/testutils package was generalized (new `Container` interface defined) to be easily used directly for any tests involving the creation of containers using Docker or Containerd (Both use the API).
The new `Container` interface was used to create tests to verify the runtime-client interface methods:
```bash
sudo go test -v -run TestRuntimeClientInterface ./pkg/container-utils/runtime-client...
```
NOTE: The same `Container` interface could be used to test other modules like the container-hook (some experiments [here](https://github.com/inspektor-gadget/inspektor-gadget/commit/43692ae9e69240d3dea663a67131b18c2cb04944)). cc @alban
> container-utils: Generalize testutils pkg and test runtime-client interface

- .github/workflows/inspektor-gadget.yml
Since https://github.com/docker/buildx/pull/1965 is merged we can use it to add annotation to multi-arch image index. The added description is visible in the ["About the Version"](https://github.com/mqasimsarfraz/inspektor-gadget/pkgs/container/inspektor-gadget/116822838?tag=latest) section.
> container images: Add description to image index via annotations

- charts/gadget/templates/daemonset.yaml
- charts/gadget/values.yaml
Allow overriding gadget pod capabilities using `values.yaml`. 
Related:  #1934 
```
image:
tag: latest-core
capabilities:
add:
- NET_ADMIN
- SYS_ADMIN
- SYSLOG
- SYS_PTRACE
- IPC_LOCK
- SYS_MODULE
- NET_RAW
```
```
$ make -C charts APP_VERSION=latest  install
$ kubectl get daemonsets.apps -n gadget gadget --template='{{range .spec.template.spec.containers}}{{.securityContext.capabilities}}{{println}}{{end}}'
map[add:[NET_ADMIN SYS_ADMIN SYSLOG SYS_PTRACE SYS_RESOURCE IPC_LOCK SYS_MODULE NET_RAW]]
$ helm upgrade gadget -n gadget charts/bin/gadget --values values.yaml
$ kubectl get daemonsets.apps -n gadget gadget --template='{{range .spec.template.spec.containers}}{{.securityContext.capabilities}}{{println}}{{end}}'
map[add:[NET_ADMIN SYS_ADMIN SYSLOG SYS_PTRACE IPC_LOCK SYS_MODULE …
```
> charts: allow overriding gadget pod capabilities

- docs/design/002-containerized-gadgets.md
Updates the documentation about the packaging of containerized gadgets.
> doc/containerized-gadgets: Update Packaging chapter to reflect current status

- cmd/ig/utils/flags.go
- examples/container-collection/container-collection.go
- examples/gadgets/formatter/trace/exec/exec.go
- examples/gadgets/withfilter/trace/exec/exec.go
- pkg/container-collection/k8s.go
- pkg/container-collection/options.go
- pkg/container-utils/containerd/containerd.go
- pkg/container-utils/containerd/containerd_test.go
- pkg/container-utils/containerutils.go
- pkg/container-utils/containerutils_test.go
- pkg/container-utils/runtime-client/runtimeclient_test.go
- pkg/container-utils/testutils/containerd.go
- pkg/container-utils/testutils/options.go
- pkg/container-utils/types/types.go
- pkg/ig-manager/ig-manager.go
- pkg/ig-manager/ig-manager_test.go
- pkg/operators/localmanager/localmanager.go
Currently we only support initial containers in `k8s.io` namespace for containerd. This change add supports for a `--containerd-namespace` flag to allow selecting custom namespace. The main use case of this change is to allow selecting "default" namespace, used by containers created using `nerdctl/ctr`.
Fixes: #1849 
```
$ sudo ctr image pull docker.io/library/nginx:latest
$ sudo ctr c create docker.io/library/nginx:latest test-container
$ sudo ctr t start test-container -d
$ sudo ./ig list-containers --containerd-namespace default
RUNTIME.RUNTIMENAME RUNTIME.CONTAINERID RUNTIME.CONTAINERNAME RUNTIME.CONTAINERIMAGENAME    
containerd          test-container      test-container        docker.io/library/nginx:latest
$ sudo ./ig snapshot process --containerd-namespace default …
```
> container-utils/containerd: Add support for custom namespace

- docs/gadgets/script.md
The documentation only explained how to use one-liner. This patch shows how to run a script file.
cc @jepio
> docs: script: using a script file

- pkg/gadgets/snapshot/socket/tracer/tracer.go
- pkg/types/types.go
We got two functions that do the same (ProtoString and ProtoToString), use only one of them.
> Remove duplicated function

- charts/gadget/templates/_helpers.tpl
- charts/gadget/templates/clusterrole.yaml
- charts/gadget/templates/clusterrolebinding.yaml
- charts/gadget/templates/daemonset.yaml
- charts/gadget/templates/role.yaml
- charts/gadget/templates/rolebinding.yaml
- charts/gadget/templates/serviceaccount.yaml
- charts/gadget/values.yaml
- Use [Kubernetes recommended labels](https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/)
- Support to additional labels
```
helm template .
```
Manifests seems valid. Ex:
```yaml
---
apiVersion: v1
kind: ServiceAccount
metadata:
labels:
helm.sh/chart: gadget-1.0.0
app.kubernetes.io/name: gadget
app.kubernetes.io/instance: release-name
app.kubernetes.io/component: controller
app.kubernetes.io/version: "1.0.0"
app.kubernetes.io/managed-by: Helm
name: release-name-gadget
namespace: gadget
```
> Refactoring Kubernetes labels

- integration/run_helpers.go
- pkg/gadgets/run/tracer/run.go
- pkg/gadgets/run/tracer/tracer.go
Make logic more generic to support other kind of gadgets later on
Reviewing https://github.com/inspektor-gadget/inspektor-gadget/pull/1866 will take longer, so I'm opening this PR with some preparation work.
> gadgets/run: Generalize logic

- integration/helpers.go
- integration/ig/k8s/top_tcp_test.go
- integration/ig/k8s/trace_network_test.go
- integration/ig/k8s/trace_tcp_test.go
- integration/ig/k8s/trace_tcpconnect_test.go
- integration/ig/non-k8s/trace_network_test.go
- integration/inspektor-gadget/advise_networkpolicy_test.go
- integration/inspektor-gadget/snapshot_socket_test.go
- integration/inspektor-gadget/top_tcp_test.go
- integration/inspektor-gadget/trace_network_test.go
- integration/inspektor-gadget/trace_tcp_test.go
- integration/inspektor-gadget/trace_tcpconnect_test.go
- pkg/gadgets/snapshot/socket/tracer/tracer.go
- pkg/gadgets/snapshot/socket/tracer/tracer_test.go
- pkg/gadgets/top/tcp/tracer/tracer.go
- pkg/gadgets/trace/network/tracer/tracer.go
- pkg/gadgets/trace/tcp/tracer/tracer.go
- pkg/gadgets/trace/tcpconnect/tracer/tracer.go
- pkg/gadgets/trace/tcpdrop/tracer/tracer.go
- pkg/gadgets/trace/tcpretrans/tracer/tracer.go
- pkg/types/types.go
Use [] around IPv6 addresses to make it more clear:
```bash
$ go run -exec "sudo -E" ./cmd/ig/. trace tcpconnect
RUNTIME.CONTAINERNAME               PID        COMM             IP SRC                                           DST                                          
mycontainer                         218949     wget             4  172.18.0.2:52926                              142.250.78.110:80                            
mycontainer                         218949     wget             4  172.18.0.2:47832                              142.250.78.132:80                            
mycontainer                         218950     wget             6  2001:db8::2:54444                             2800:3f0:4005:40a::200e:80 …
```
> gadgets: fix ipv6 printing

- integration/ig/k8s/top_block_io_test.go
- integration/inspektor-gadget/top_blockio_test.go
See issue #2029 for further details.
> integration: Skip top block-io tests on kernels >= 5.17

- .github/workflows/inspektor-gadget.yml
Fixes: 463f5a88fddd ("ci: Publish ig container images.")
It was causing this step to fail with `Warning: No files were found with the provided path: /tmp/ig-container-image-linux-amd64.tar. No artifacts will be uploaded.`
Ref https://github.com/inspektor-gadget/inspektor-gadget/actions/runs/6184453746/job/16790129503
It wasn't causing any other issue as these artifacts are not being used anywhere.
> ci: Fix uploading ig container image as artifact

- docs/gadgets/profile/block-io.md
- docs/gadgets/trace/capabilities.md
For an unknown reason linux.die.net returns 403 when used with wget:
```
$ wget -4 https://linux.die.net/man/1/stress
--2023-09-18 14:40:37--  https://linux.die.net/man/1/stress Resolving linux.die.net (linux.die.net)... 104.26.0.94, 172.67.69.187, 104.26.1.94 Connecting to linux.die.net (linux.die.net)|104.26.0.94|:443... connected. HTTP request sent, awaiting response... 403 Forbidden 2023-09-18 14:40:37 ERROR 403: Forbidden.
```
This is causing our "broken links" CI job to fail. This commit switches to alternative locations for those manuals.
> docs: Replace linkds to linux.die.net

- pkg/gadgets/traceloop/tracer/tracer.go
It's possible that a given syscall doesn't exist for this architecture, hence just skip it instead of erroring out.
This was working before https://github.com/inspektor-gadget/inspektor-gadget/pull/2054 because `libseccomp.GetSyscallFromName` returns a "pseudo syscall number" (https://github.com/seccomp/libseccomp/issues/249 & https://man7.org/linux/man-pages/man3/seccomp_syscall_resolve_name.3.html). I think the correct behaviour is to skip that syscall as it don't actually exist on the system.
Fixes https://github.com/inspektor-gadget/inspektor-gadget/pull/2054
> traceloop: Fix logic around syscalls
