cmd/inspektor-gadget/cmd/bcck8s.go
gadget-ds/files/bcck8s/capable-edge

Upstreamed in https://github.com/iovisor/bcc/pull/2359

capabilities: Fix audit detection for old and new kernels

---

README.md

Add a link to issues with the 'good first issue' label.

README.md: welcoming contributions

---

Documentation/architecture.md
Documentation/install.md
README.md

- Flatcar Linux -> Flatcar Container Linux
- Inspector -> Inspektor

Fix small typos around

---

cmd/inspektor-gadget/cmd/bcck8s.go
cmd/inspektor-gadget/cmd/utils.go

PR performing some code cleanup
- remove dead function
- improve error messages (avoid too nested errors)
- fix usage of spaces instead of tabs
- move flag configuration outside loop

cleanup bcck8s

---

cmd/inspektor-gadget/cmd/deploy.go

Use template instead of manually replacing strings. Not that a big change now
but it could be useful in the future.

Use template for deploy command

---

Documentation/install.md

- update instructions about how to download Github actions artifacts

Documentation: fix installation guide

---

Documentation/demo-profile.md
Documentation/install.md
README.md
cmd/inspektor-gadget/cmd/bcck8s.go
gadget-ds/files/bcck8s/bcc-wrapper.sh

Based on BCC's tool profile:
https://github.com/iovisor/bcc/blob/master/tools/profile_example.txt
---
TODO:

Add "profile" gadget

---

cmd/kubectl-gadget/traceloop.go
gadget-container/gadget.Dockerfile
pkg/gadgettracermanager/containerutils/containerutils.go

Add support for cri-o

---

.github/workflows/inspektor-gadget.yml
Documentation/install.md
Makefile

Fixes https://github.com/kinvolk/inspektor-gadget/issues/65

Add OSX builds

---

Documentation/install.md
README.md

Update version reference in install instructions

Prepare for release v0.1.0

---

gadget-container/Makefile
gadget-container/gadget-from-local-bin.Dockerfile

- Use COPY instead of ADD
- Take traceloop from /bin folder that is part of gitignore

Improve Dockerfile for minikube

---

cmd/kubectl-gadget/bcck8s.go
cmd/kubectl-gadget/deploy.go
cmd/kubectl-gadget/main.go
cmd/kubectl-gadget/traceloop.go
cmd/kubectl-gadget/utils.go

Remove doesKubeconfigExist.
Remove assumptions about kubeconfig location.

Fix kubectl-gadget when running in-cluster

---

.github/workflows/inspektor-gadget.yml
Makefile
go.mod
integration/traceloop_test.go

Integration tests can be executed with 'make integration-tests'.
It includes a basic test of the traceloop gadget.

Add integration tests

---

cmd/kubectl-gadget/deploy.go
gadget-container/entrypoint.sh
gadget-container/gadget.Dockerfile

Example:
```
kubectl gadget deploy --traceloop-loglevel=trace,json
```
----
TODO:
- Tested with traceloop PR 45

traceloop loglevel option

---

.github/workflows/inspektor-gadget.yml
CONTRIBUTING.md
Documentation/architecture.md
Documentation/install.md
Makefile
README.md
gadget-container/Makefile

- Make compilation process more generic to make external contributors' lifes easier.
- Create a contribution guide describing the main aspects to get started.
Solves https://github.com/kinvolk/inspektor-gadget/issues/31.
Solves https://github.com/kinvolk/inspektor-gadget/issues/60.

Create contribution guide

---

.github/workflows/inspektor-gadget.yml
Makefile

Add Windows to the list of platforms. Compile and upload a binary for windows-amd64.
Ref https://github.com/kinvolk/inspektor-gadget/issues/135

Compile windows binary

---

README.md
docs/_index.md
docs/guides/_index.md

These changes are for updating the description and preparing the IG documentation to be added to the new Kinvolk docs.

Add some small updates for documentation

---

docs/CONTRIBUTING.md

docs: fix broken link

---

docs/guides/capabilities.md

Hi there,
as per title
Didier
Signed-off-by: Didier Durand <durand.didier@gmail.com>

capabilities.md : just fixing 1 typo in page

---

docs/guides/network-policy.md

Hi there,
as per title: typo in page network_policy.md
Best
DIdier
Signed-off-by: Didier Durand <durand.didier@gmail.com>

network_policy.md: fixing 1 typo in page

---

README.md

Fix demo links in readme

---

docs/guides/profile.md
docs/guides/tcpconnect.md

Hi there,
The final set of typos that I found after reading full doc.
Your product is very interesting: keep up!
Didier
Signed-off-by: Didier Durand <durand.didier@gmail.com>

profile.md and tcpconnect.md : final typos from full doc reading

---

cmd/kubectl-gadget/deploy.go
docs/install.md
gadget-container/entrypoint.sh
gadget-container/gadgets/bcck8s/bcc-wrapper.sh

Remove flatcar edge related things that are not needed anymore.

Remove flatcar edge specific logic

---

docs/architecture.md

Signed-off-by: Qingyuan Hou <qingyuan.hou@linux.alibaba.com>
[ describe the change in 1 - 3 paragraphs ]

docs: fix the broken link on bcc special filtering

---

gadget-container/entrypoint.sh

In correct configurations, the host has the following mountpoints:
- /sys of type sysfs, mounted in rw mode
- /sys/fs/bpf of type bpf_fs, mounted in rw mode
Then, the gadget pod is bind-mounting the host's /sys/fs/bpf into the
container's /sys/fs/bpf.
However, it does not work well with Minikube when using the Docker
driver: Minikube simulates the host with a container (the "kikbase"
container with the image gcr.io/k8s-minikube/kicbase:v0.0.10) running
systemd and the docker daemon. And the Kubernetes pods are created with
"inner containers" started by this "docker in docker". The problem here
is that the kicbase container has a read-only /sys and the bpf_fs is not
mounted at all.
The Gadget container does not have the control on the way the host is
configured. This patch merely detects …

entrypoint: remount bpf_fs as workaround

---

gadget.Dockerfile

Fix tools on linux >= 5.11: https://github.com/iovisor/bcc/commit/ef330a393be4b472627b1bfa7fbe50934e519e25.

Update BCC version

---

cmd/kubectl-gadget/networkpolicyadvisor.go

- Align "--namespace" and "--namespaces" flags
- Add --output option for report comman

Some improvements for network policy advisor

---

pkg/gadgets/biolatency/gadget.go

As reported on https://github.com/kinvolk/inspektor-gadget/issues/268, the biolatency gadget sometimes fail. It's difficult to understand why because stdout and stderr are lost in that case. This patch adds stdout and stderr in the error message, so we can debug this.
cc @ashu8912 

biolatency: gives std outputs on error

---

pkg/gadgets/seccomp/tracer/tracer.go

Keep a reference on the eBPF link, even if we don't access it.
Otherwise, the garbage collector will free it and call the finalizer set
up by the cilium/ebpf library: [internal/fd.go#L21](https://github.com/cilium/ebpf/blob/4d5607ee1690d067b7f8befdd69b2bbee07e644b/internal/fd.go#L21)
```
runtime.SetFinalizer(fd, (*FD).Close)
```
Symptoms of the bug before this fix: the seccomp gadget works fine but
stops working after a while (when the garbage collector decides to call
the finalizer and close the file descriptor).

seccomp: fix fd garbage collector issue

---

README.md

Recent talks were missing, this adds a few to the list. I'm sure I'm missing some others, but that's what I could find.

Add more Inspektor Gadget talks

---

docs/guides/socket-collector.md

Adding missing guide.
Fixes #281.

docs: Add guide for socket-collector gadget

---

cmd/kubectl-gadget/bcck8s.go

Some fixes for https://github.com/kinvolk/inspektor-gadget/pull/235, please see each commit message for more details.

Remove duplicated postProcess

---

docs/guides/process-collector.md

Fixes https://github.com/kinvolk/inspektor-gadget/issues/280

docs: Add process-collector guide

---

pkg/gadgettracermanager/gadgettracermanager.go
pkg/gadgettracermanager/k8s/k8s.go

Fixes https://github.com/kinvolk/inspektor-gadget/issues/314

pkg/k8s: Remove non running containers from gadget tracer manager

---

gadget-container/entrypoint.sh

The BTF file is not only useful for bcc core tools but also for the
seccomp gadget. Let's download it regardless of the tools-mode option.

entrypoint.sh: always download btf from BTFHub when necessary

---

cmd/kubectl-gadget/bcck8s.go

BCC gadgets were not updated in https://github.com/kinvolk/inspektor-gadget/pull/235/commits/079d01b9d942531b669463cf07ada60f39470a29.

cmd: use utils.AddCommonFlags() in bcc gadgets too

---

docs/examples/seccomp/basic.yaml
docs/examples/seccomp/confined.yaml
docs/examples/seccomp/trace-external.yaml
docs/examples/seccomp/trace-status.yaml
docs/examples/seccomp/unconfined.yaml
docs/guides/seccomp.md

I've added a guide based on the demo that I created for eBPF day. It includes all examples as files and goes through them step by step.
Fixes: #266

Add a guide on how to use the seccomp gadget

---

pkg/gadgets/seccomp/gadget.go

There is two code paths where the seccomp tracer can be stopped:
1. The "stop" operation is called via the annotation, or
2. The Trace resource is deleted directly
Before this patch, Unsubscribe() was not called in the second case, so a
callback was still called on pod termination.
This patch fixes that by calling Unsubscribe() correctly.
Additionally, the code is made more robust by checking if
traceSingleton.tracer is nil before dereferencing it.
Symptoms:
```
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x179c5ba]
goroutine 753 [running]:
github.com/kinvolk/inspektor-gadget/pkg/gadgets/seccomp/tracer.(*Tracer).Peek(0x0, 0xf0000531, 0x0, 0x0, 0xc002d20588) …
```

seccomp gadget: fix cleanup when the tracer is stopped

---

cmd/kubectl-gadget/bcck8s.go
cmd/kubectl-gadget/networkpolicyadvisor.go
cmd/kubectl-gadget/traceloop.go
cmd/kubectl-gadget/utils/trace.go

Avoid using "Everything()" as those fields default to everything.

cmd: Cleanup ListOptions

---

cmd/kubectl-gadget/bcck8s.go
cmd/kubectl-gadget/utils/flags.go
cmd/kubectl-gadget/utils/trace.go

Some improvements for the CommonFlags structure. Please see individual commits for more details. 
- cmd/utils: Add map of labels to CommonFlags
- cmd/utils: Add Namespace field to CommonFlags

Improvements for common flags

---

.github/workflows/inspektor-gadget.yml
Makefile
local-gadget-linux-arm64.Dockerfile
pkg/gadgets/socket-collector/tracer/tracer.go

Add local-gadget in the next release.
Supported architectures:
* amd64
* arm64
cc @tormath1

local-gadget: add artifacts in release

---

cmd/kubectl-gadget/utils/trace.go

Hi.
This commit fixes wrong behavior where the trace is not being deleted when trying to write to a broken pipe:
```bash
./kubectl-gadget socket-collector -A | head -n0
kubectl get trace -A
NAMESPACE   NAME                      AGE
gadget      socket-collector-vtjxc    1s
```
Best regards.

utils: trace: Add handler for SIGPIPE.

---

.github/workflows/inspektor-gadget.yml
gadget-container/entrypoint.sh

BTFHub repository where BTF files are stored was renamed to
btfhub-archive.

Update BTFHub repository

---

cmd/kubectl-gadget/utils/trace.go

Before this PR:
```
$ ./kubectl-gadget gadget-name list -A
NAMESPACE    NODE(S)                  POD      CONTAINER    TRACEID
default      master,worker2,worker    nginx                 ziZVCIrlUzqbACFH
demo         worker,master,worker2    mypod                 14LBWYxfW6czb4Yo
```
After this PR:
```
$ ./kubectl-gadget gadget-name list -A
NAMESPACE    NODE(S)                  POD      CONTAINER    TRACEID
default      master,worker,worker2    nginx                 ziZVCIrlUzqbACFH
demo         master,worker,worker2    mypod                 14LBWYxfW6czb4Yo
```

kubect-gadget/utils: Sort node list in PrintAllTraces

---

pkg/gadgets/seccomp/gadget.go

Currently, when the policy is generated at pod termination, the gadget is reporting an `operationWarning` when it is stopped because there is no pod that matches the requested filter. However, it already generated the policy thus the message does not make sense. Example:
```
$ ./kubectl-gadget seccomp-advisor start -m seccomp-profile --seccomp-profile-name seccomp-demo/hello-profile -n seccomp-demo -p hello-python
DT8HSvzpYJvw3tAp
$ kubectl delete pod/hello-python -n seccomp-demo
pod "hello-python" deleted
$ kubectl get seccompprofile -A
NAMESPACE    NAME                   STATUS       AGE
gadget       seccomp-mcnw4-pnpdz    Installed    10s
$ ./kubectl-gadget seccomp-advisor stop DT8HSvzpYJvw3tAp
Failed to run the gadget on all nodes: Pod seccomp-demo/hello-python not found
Error: Failed …
```

seccomp: Improve UX when policy is generated at pod termination

---

cmd/kubectl-gadget/dns.go
pkg/gadgets/dns/gadget.go
pkg/local-gadget-manager/local-gadget-manager_test.go
pkg/types/types.go

Add an EventType field for making it easier for clients to parse it,
also remove some fields that are not needed anymore and adapt the DNS
gadget to these changes.

pkg: Modify base event type

---

README.md
docs/CONTRIBUTING.md
docs/custom-resources.md
docs/guides/bindsnoop.md
docs/guides/biotop.md
docs/guides/capabilities.md
docs/guides/dns.md
docs/guides/execsnoop.md
docs/guides/mountsnoop.md
docs/guides/network-policy.md
docs/guides/opensnoop.md
docs/guides/process-collector.md
docs/guides/profile.md
docs/guides/seccomp.md
docs/guides/socket-collector.md
docs/guides/tcpconnect.md
docs/guides/tcptop.md
docs/guides/traceloop.md
docs/install.md
docs/local-gadget.md

Hi.
This PR adds code blocks syntax highlighting to our guides.
Best regards.

docs: Add syntax highlighting to code blocks.

---

gadget.Dockerfile
pkg/gadgettracermanager/containerutils/docker/docker.go

Closes #433
Signed-off-by: Mateusz Gozdek <mgozdek@microsoft.com>

gadget.Dockerfile: mitigate K8s bug with existing manifests

---

integration/integration_test.go

t.Fatal() is called when a test fails, it ends up calling runtime.Goexit()
to exit the current goroutime.
The Goexit documentation states that:
'''
Goexit terminates the goroutine that calls it. No other goroutine is affected.
Goexit runs all deferred calls before terminating the goroutine. Because Goexit
is not a panic, any recover calls in those deferred functions will return nil.
'''
The previous logic was using the same defer call to run the tests and
perform the cleanup, if a test failed then that function was interrupted
without doing the cleanup.
This commit uses a different defer call to perform the cleanup,
guaranteeing that it's always done.
---
An example of this failing can be found at https://github.com/kinvolk/inspektor-gadget/actions/runs/1684275158, `TestOpensnoop` failed …

integration: Fix cleaning up commands

---

cmd/kubectl-gadget/dns.go
docs/guides/dns.md
integration/integration_test.go
pkg/gadgets/dns/gadget.go
pkg/gadgets/dns/tracer/bpf/dns-common.h
pkg/gadgets/dns/tracer/bpf/dns.c
pkg/gadgets/dns/tracer/tracer.go
pkg/gadgets/dns/tracer/tracer_test.go
pkg/gadgets/dns/types/dns.go
pkg/local-gadget-manager/local-gadget-manager_test.go

Hi.
In this PR, I added query type to `dns` output:
```bash
$ ./kubectl-gadget dns -n demo &
POD                            TYPE      QTYPE     NAME
$ kubectl -n demo run mypod -it --image=praqma/network-multitool -- /bin/sh
mypod                          OUTGOING  A         microsoft.com.demo.svc.cluster.local.
mypod                          OUTGOING  A         microsoft.com.svc.cluster.local.
mypod                          OUTGOING  A         microsoft.com.cluster.local.
mypod                          OUTGOING  AAAA  microsoft.com.
```
<details>
<summary>To test all DNS request type, run the following:</summary>
```bash
$ ./kubectl-gadget dns -n demo &
POD                            TYPE      QTYPE     NAME
$ kubectl -n demo run mypod -it --image=praqma/network-multitool -- /bin/sh
eid …
```

`dns`: Added query type.

---

cmd/kubectl-gadget/seccompadvisor.go
pkg/gadgets/seccomp/gadget.go

Hi.
In this PR, I added printing of the generated profile name when using seccomp profile:
```bash
$ ./kubectl-gadget seccomp-advisor start -n kube-system -p gadget-2l5s7 -m seccomp-profile
b19PNlTOk6mABOKY           
$ ./kubectl-gadget seccomp-advisor stop b19PNlTOk6mABOKY
Successfully created seccomp profile: gadget-2l5s7
$ kubectl get seccompprofile -A
NAMESPACE                    NAME           STATUS      AGE
gadget                       gadget-2l5s7               42s
```
This PR fixes #442.
Best regards.

Print generated `seccomp` profile name

---

README.md

Added improved intro and removed Lokomotive reference.

Update the Readme to improve the introduction

---

integration/integration_test.go

Yet another iteration on this one. The goal of TestMain() is to setup
Inspektor Gadget before running the test and tear it down after.
d061e9e4cd74 ("integration: Fix cleaning up commands") switched to use
defer in order to perform the clean up when the test fails. (It ends up
calling runtime.Goexit() which executes all defer calls). It worked fine
for that case but then when the test succeded it wasn't working fine
because os.Exit() doesn't call the defered functions.
This commit switches to an approach that mixes both of them, defer is
used in case the test fails and the cleanup functions are explictly
called before os.Exit().

integration: Fix cleaning up resources when tests complete

---

pkg/runcfanotify/runcfanotify.go

pidfd_open was introduced in Linux 5.3. Introduce a fallback mechanism
for older kernel.
The code automatically detects if pidfd_open can be used.
* Checked for regression on a AKS cluster by starting & stopping a pod manually (`kubectl run -ti --restart=Never --rm --image ubuntu shell -- /bin/bash`) and looking at the logs (`kubectl logs -n gadget gadget-qq292`)
* Checked for regression with `local-gadget` and the `list-containers` command by starting and stopping a container (`docker run -ti --rm ubuntu`)
* Same check with `local-gadget` but by manually changing the code to force the call to `watchContainerTerminationFallback`

runcfanotify: fallback when pidfd_open fails

---

pkg/gadgets/oomkill/tracer/bpf/oomkill.bpf.c
pkg/gadgets/oomkill/tracer/bpf/oomkill.h
pkg/gadgets/oomkill/tracer/tracer.go

Hi.
In this PR, I updated the `oomkill` eBPF code to be in sync with bcc one.
Best regards.

Update oomkill eBPF CO-RE program to upstream bcc

---

pkg/gadgets/execsnoop/tracer/core/tracer.go
pkg/gadgets/filetop/tracer/tracer.go
pkg/gadgets/fsslower/tracer/core/tracer.go
pkg/gadgets/helpers.go
pkg/gadgets/oomkill/tracer/tracer.go
pkg/gadgets/opensnoop/tracer/core/tracer.go
pkg/gadgets/seccomp/tracer/tracer.go

Introduce a small helper that closes a link and returns nil. There
is nothing special about this helper, it just improves code readability
by removing a lot of conditionals when closing a link.

pkg/gadgets: Introduce CloseLink() helper

---

integration/integration_test.go
pkg/gadgets/fsslower/tracer/core/tracer.go

Fix some issues with the fsslower gadget. Please see each commit to get more details.

Fix fsslower issues

---

cmd/kubectl-gadget/utils/trace.go

Hi.
This PR removes the computing of total traces number from `waitForCondition()`.
So, it fixes #525.
Best regards.

utils: trace: Fix traces number increasing in waitForCondition().

---

integration/command.go

When running integration tests, the kubectl-gadget CLI process is not correctly terminated. In addition, if the option `-no-deploy` is used, the traces are not deleted.
This fix is particularly useful when running tests locally.
It is enough to run the integration test locally and check the processes.
When we run the `kubect-gadget` CLI to run a gadget during the integration tests, we do it by executing `/bin/sh -c kubectl-gadget <gadget-name> ...`, see [here](https://github.com/kinvolk/inspektor-gadget/blob/c8fe352aeb33b2366dec4df8a000ecd1d478e80a/integration/command.go#L160). It means that `/bin/sh` executes a child process for `kubectl-gadget`. The issue occurs because the current code is [killing the process of `/bin/sh`](https://github.com/kinvolk/inspektor-gadget/blob/c8fe352aeb33b23 …

Avoid leaving processes running after integration tests

---

go.mod
go.sum
pkg/runcfanotify/runcfanotify.go

Fixes https://github.com/kinvolk/inspektor-gadget/issues/294

Update go fanotify

---

cmd/kubectl-gadget/filetop.go
docs/gadgets/filetop.md
pkg/gadgets/filetop/gadget.go
pkg/gadgets/filetop/types/types.go

Hi.
This PR fixes #562.
Best regards.

filetop: fix params keys

---

cmd/kubectl-gadget/audit-seccomp.go
docs/gadgets/audit-seccomp.md
docs/guides/audit-seccomp.md
pkg/gadgets/audit-seccomp/gadget.go
pkg/gadgets/audit-seccomp/tracer/embed-ebpf.go
pkg/gadgets/audit-seccomp/tracer/embed-none.go
pkg/gadgets/audit-seccomp/tracer/tracer.go
pkg/gadgets/audit-seccomp/types/types.go

@blanquicet gave a review of audit-seccomp (https://github.com/kinvolk/inspektor-gadget/pull/383). This PR addresses this review.

audit-seccomp fixes from previous review

---

integration/command.go

The main three changes of this PR are:
1. Print tests even if they pass. It is useful to compare them with the ones that fail.
2. Refactor the code to avoid having the same logic repeated in different places.
3. Print the log of the gadget pods when a gadget fails.

ci: Factorize code and add gadget pod logs after failure

---

pkg/gadgets/biotop/tracer/tracer.go
pkg/gadgets/tcptop/tracer/tracer.go

Two small fixes for biotop and tcptop gadgets

Small fixes for biotop tcptop

---

cmd/kubectl-gadget/top/block-io.go
cmd/kubectl-gadget/top/file.go
cmd/kubectl-gadget/top/tcp.go
cmd/kubectl-gadget/utils/flags.go
cmd/kubectl-gadget/utils/trace.go

- Add a timeout parameter that specifies the number of seconds that a gadget will run
- Add some logic to handle it in filetop

Add timeout parameter

---

integration/integration_test.go

The SPO is required for TestAuditSeccomp(), make it optional in case
somebody wants to run tests that don't require this component.

integration: Make SPO deployment optional

---

.github/workflows/inspektor-gadget.yml
Makefile
docs/CONTRIBUTING.md
gadget-container/entrypoint.sh
gadget-core.Dockerfile
gadget-default.Dockerfile
gadget.Dockerfile
kubectl-gadget.Dockerfile
kubectl-gadget.Dockerfile.dockerignore

Please see individual commits for more information.
--- 
It's still not clear if we want to push these images to a container registry, so this PR doesn't handle it.

Create dockerfiles for kubectl-gadget and CO-RE tools

---

docs/guides/audit/seccomp.md

Hi.
In this PR, I added syntax coloration for code block inside the audit seccomp guide.
Best regards.

docs: Add code block syntax coloration for audit seccomp.

---

docs/guides/advise/_index.md
docs/guides/audit/_index.md
docs/guides/profile/_index.md
docs/guides/snapshot/_index.md
docs/guides/top/_index.md
docs/guides/trace/_index.md

Group different guides in categories.

docs: Group guides by categories

---

gadget-container/entrypoint.sh

Fixes https://github.com/kinvolk/inspektor-gadget/issues/611

entrypoint: Do not load headers when kheaders mod is available

---

cmd/kubectl-gadget/deploy.go

Add the --file flag to save the generated yaml to a file instead of
printing it to stdout.

cmd/kubectl-gadget: Add --file parameter to deploy command

---

pkg/container-collection/container-collection.go
pkg/container-collection/options.go
pkg/gadgettracermanager/containers-map/tracer.go
pkg/gadgettracermanager/gadgettracermanager.go
pkg/gadgettracermanager/k8s/k8s.go
pkg/gadgettracermanager/k8s/podinformer.go
pkg/local-gadget-manager/local-gadget-manager.go
pkg/local-gadget-manager/local-gadget-manager_test.go
pkg/runcfanotify/runcfanotify.go

Implement method to release resources when they aren't needed anymore.
Fixes https://github.com/kinvolk/inspektor-gadget/issues/624

containercollection: Implement ContainerCollectionClose()

---

docs/guides/trace/tcp.md

Hi.
This PR fixes `trace tcp` header in its guide.
Best regards.

docs: Fix trace tcp header.

---

pkg/gadgets/biolatency/tracer/core/tracer.go

Apply also "go fmt" to tracer.go

gadgets/profile/block-io: Remove unused function

---

docs/guides/trace/fsslower.md

Fixes 0cc4394757c6e17fb69b53acd6bfab7a97e94999

docs: fsslower: Rename --type parameter to --filesystem

---

cmd/kubectl-gadget/utils/trace.go

Avoid creating traces on nodes that are not ready as it means those
nodes are having issues and it's likely that the gadget pod is not
running there.
Partially fixes https://github.com/kinvolk/inspektor-gadget/issues/632. We should still consider the case when the node is ready but the gadget pod has issues.

cmd/kubectl-gadget: Only create traces in ready nodes

---

cmd/local-gadget/utils/flags.go
docs/local-gadget.md
pkg/container-utils/docker/docker.go

This PR updates the [local-gadge documentation](https://github.com/kinvolk/inspektor-gadget/blob/jose/local-gadget-docs/docs/local-gadget.md).
This PR goes on top of https://github.com/kinvolk/inspektor-gadget/pull/763.

local-gadget: Update documentation

---

cmd/kubectl-gadget/utils/trace.go

Add logic to handle the case when some the trace controller is dead
in some nodes, i.e. some traces don't reach the expected state.
This is important because it should be possible to get some results
from the cluster even if the gadget pod is not running fine in all of
the nodes.
It's not so easy to kill the gadgettracermanager on a node because kubernetes restarts it, for this reason I have to use this hack:
1. Modify the gadget tracer manager not to start on a specific node:
```diff
$ git diff
diff --git gadget-container/gadgettracermanager/main.go gadget-container/gadgettracermanager/main.go
index 7325c875..777d4ee9 100644
--- gadget-container/gadgettracermanager/main.go
+++ gadget-container/gadgettracermanager/main.go
@@ -214,6 +214,10 @@ func main() {
log.Fatalf("Environment variable …
```

cmd/kubectl-gadget: Do not fail if tracer controller is dead on node

---

cmd/kubectl-gadget/deploy.go

Modify the deploy command not to fail if Inspektor Gadget was already
installed on the cluster. The new behaviour tries to update it, if
possible.
Try the deploy command multiple times to update the existing deployment.
```bash
$ ./kubectl-gadget deploy
Creating Namespace/gadget...
Error: problem while creating resource: failed to create "Namespace": namespaces "gadget" already exists
```
```bash
$ ./kubectl-gadget deploy
Creating Namespace/gadget...
Creating ServiceAccount/gadget...
Creating Role/gadget-role...
Creating RoleBinding/gadget-role-binding...
Creating ClusterRole/gadget-cluster-role...
Creating ClusterRoleBinding/gadget-cluster-role-binding...
Creating DaemonSet/gadget...
Creating CustomResourceDefinition/traces.gadget.kinvolk.io...
Waiting for gadget pod(s) to be ready... …
```

cmd/kubectl-gadget: Make deploy command idempotent

---

examples/gadgets/top/file/file.go
examples/gadgets/trace/exec/exec.go

- Use defer
- Rename channel to exit

examples/gadgets: Align code to other examples

---

examples/kube-container-collection/main.go
pkg/container-collection/container-collection.go
pkg/container-collection/match_test.go
pkg/container-collection/options.go
pkg/gadgettracermanager/gadgettracermanager.go
pkg/gadgettracermanager/gadgettracermanager_test.go
pkg/local-gadget-manager/local-gadget-manager.go
pkg/tracer-collection/tracer-collection.go

- Rename withEbpf to testOnly
- Rename methods

container-collection: small api improvements

---

Dockerfiles/gadget-default.Dockerfile
pkg/standardgadgets/trace/bind/tracer.go

Update base BCC image to include https://github.com/kinvolk/bcc/pull/23. 
TODO: 
Fixes https://github.com/kinvolk/inspektor-gadget/issues/826

Update BCC to fix trace bind issue

---

pkg/gadget-collection/gadgets/advise/seccomp/gadget.go

It's possible to create multiple instances of the seccomp advisor gadget, however it internally uses a single eBPF program that captures all the syscalls on the host.
The current logic is wrong as it only subscribes to the container termination events taking into consideration the filter spec of the first seccomp advisor instance. Hence, the following case doesn't work:
```
$ kubectl run mypod1 --restart=Never --image=praqma/network-multitool \
-- bash -c "while true; do ping -c 1 8.8.8.8 && sleep 1; done"
$ kubectl run mypod2 --restart=Never --image=praqma/network-multitool \
-- bash -c "while true; do ping -c 1 8.8.8.8 && sleep 1; done"
$ kubectl -n gadget get seccompprofile
No resources found in gadget namespace.
$ ./kubectl-gadget advise seccomp-profile start -m seccomp-profile -p …
```

advise/seccomp: Fix logic around container termination notification

---

pkg/runcfanotify/runcfanotify.go

On Ubuntu 22.04 WSL2, /var/run is symlinked to /run.
Docker-CE generates a containerd configuration that sets the state path
to /var/run/docker/containerd/daemon, which containerd uses to construct
runc's --pid-file path. However, the fanotify event path uses /run,
and since the paths don't match, runcfanotify returns false.
This had the effect of "dropping" the container create event,
so that (1) the container did not show up in trace results, and
(2) on SIGINT, the runcfanotify Close() method would hang waiting on
the read sycall in `pidFileDirNotify.GetEvent()`.
Fix it by using `os.Samefile` to compare the device/inode of the
two files instead of comparing paths.
Resolves: https://github.com/kinvolk/inspektor-gadget/issues/958
Follow the steps to reproduce from …

Fix runcfanotify dropping events for docker-ce on WSL2 / Ubuntu 22.04

---

pkg/container-collection/options.go

https://github.com/kinvolk/inspektor-gadget/pull/824 retrieves the Kubernetes information from the container runtime, but we were not enriching the containers with such information when using the `WithContainerRuntimeEnrichment` option.
Check the namespace, pod and pod-uid fields when using `WithContainerRuntimeEnrichment` option. For instance, `local-gadget`  uses this option.
Both k8s and no-k8s containers were enriched with the default info: namespace="default" and podname=container-name.
```bash
$ sudo /inspektor-gadget/local-gadget list-containers -o json --containername etcd
[
{
"id": "3ea21dfe1b9191c5dca7c3e1b4b102b7e6edd0f456d5651b9c1899e18eccccdf",
[...]
"namespace": "default",
"podname": "etcd",
"name": "etcd",
"runtime": "containerd"
}
]
```
```bash
$ sudo …
```

container-collection: Enrich container with k8s info from container runtime

---

pkg/gadgets/internal/test/helpers.go
pkg/gadgets/trace/bind/tracer/tracer_test.go
pkg/gadgets/trace/exec/tracer/tracer_test.go
pkg/gadgets/trace/open/tracer/tracer_test.go

Fixes https://github.com/kinvolk/inspektor-gadget/issues/829

pkg/gadgets: Implement trace bind unittests

---

pkg/gadgets/internal/test/runner.go

We don't need to persist the mount namespace after our goroutine running there is done, so we don't need to get a handle for it. Remove getMntNsHandle() and modify createMntNamespace() to return the inode of the namespace.

pkg/gadgets/test: Remove uneeded getMntNsHandle()

---

docs/ci.md

Update the outdated documentation. 
Related #871 #955

docs: Update docs related to container repository

---

integration/command.go
integration/integration_test.go

Disable this test until https://github.com/kinvolk/inspektor-gadget/issues/985 is fixed.

integration: Disable TestCapabilities on ARO

---

.github/workflows/inspektor-gadget.yml

This file doesn't exist anymore

Do not upload integration test asset

---

docs/CONTRIBUTING.md
docs/install.md
docs/local-gadget.md

It also updates the index in the installation guide.

docs: Add installation instruction for local-gadget

---

pkg/columns/group/group_test.go
pkg/gadgets/internal/test/helpers.go
pkg/gadgets/trace/bind/tracer/tracer_test.go
pkg/gadgets/trace/capabilities/tracer/tracer_test.go
pkg/gadgets/trace/exec/tracer/tracer_test.go
pkg/gadgets/trace/open/tracer/tracer_test.go

Fixes https://github.com/kinvolk/inspektor-gadget/issues/830

trace/capabilities: Implement unit tests

---

pkg/gadgets/trace/capabilities/tracer/tracer_test.go

Implement unit tests for `--unique` flag introduced in https://github.com/kinvolk/inspektor-gadget/pull/1032.

trace/capabilities: Implement units tests for unique flag

---

pkg/runcfanotify/runcfanotify.go

This PR brings two improvements for the runcfanotify package:
- Make Supported() logic more robust
- Use HOST_ROOT env variable
- The logic doesn't try to use fanotify on systems where it can't work, for instance, systems without CONFIG_FANOTIFY_ACCESS_PERMISSIONS. (like minikube using the kvm2 driver for instance)
- This fixes a bug when the bundle path of a container is in a path that can't be accessed by the gadget pod. 
- Deploy this version in a system without CONFIG_FANOTIFY_ACCESS_PERMISSIONS and check how it doesn't use fanotify by default when hook-mode = auto. 
- Use this version in a system that creates the pods in a path that is not directly accessible from the gadget pod, like `/var/run`.

pkg/runcfanotify: Fix bug and improve detection logic 

---

cmd/local-gadget/trace/oomkill.go
cmd/local-gadget/trace/trace.go
integration/inspektor-gadget/integration_test.go
integration/local-gadget/trace_oomkill_test.go

local-gadget: Add oomkill trace gadget

---

integration/inspektor-gadget/integration_test.go

Added a test for the `network` gadget, since there was none yet.
Could not use `BuildBaseEvent(ns)` for the `Event`, since the `network` gadget doesn't capture the `CommonData.Container` string. (Is this intentional or did i do the trace wrong?)

integration-tests/networkgraph: Add network gadget test

---

pkg/local-gadget-manager/local-gadget-manager_test.go
pkg/runcfanotify/runcfanotify.go

Fixes https://github.com/inspektor-gadget/inspektor-gadget/issues/1072

runc-fanotify: close correctly in error cases

---

integration/inspektor-gadget/integration_test.go

Uses the json output in order to validate as much information as possible from the `top ebpf` gadget
Can not validate locally on minikube or aks because of https://github.com/inspektor-gadget/inspektor-gadget/issues/931

integrationtest/TestEbpftop: Validate json output

---

integration/inspektor-gadget/integration_test.go

Uses the json output in order to validate as much information as possible from the `top block-io` gadget
Is the `Operations` always guaranteed to be 2?

integrationtest/TestBiotop: Validate json output

---

integration/inspektor-gadget/integration_test.go

integration-tests: Use JSON output format for TestSnisnoop

---

integration/inspektor-gadget/integration_test.go

Uses the json output in order to validate as much information as possible from the `snapshot process` gadget
Bases on #1083 . Will rebase after it is merged

integrationtest/TestProcessCollector: Validate json output

---

cmd/local-gadget/trace/mount.go
cmd/local-gadget/trace/trace.go
docs/local-gadget.md
integration/local-gadget/trace_mount_test.go

Fixes https://github.com/inspektor-gadget/inspektor-gadget/issues/888

Support trace mount in local-gadget

---

cmd/local-gadget/trace/open.go
cmd/local-gadget/trace/trace.go
docs/local-gadget.md
integration/local-gadget/trace_open_test.go

Fixes https://github.com/inspektor-gadget/inspektor-gadget/issues/891

localgadget: Add trace open command

---

cmd/local-gadget/trace/fsslower.go
cmd/local-gadget/trace/trace.go
integration/local-gadget/trace_fsslower_test.go

Fixes https://github.com/inspektor-gadget/inspektor-gadget/issues/887

localgadget: Support trace fsslower gadget

---

integration/inspektor-gadget/integration_test.go

Last test to be ported over to json. See https://github.com/inspektor-gadget/inspektor-gadget/issues/719
Note: The container name was different in this test. Was that on purpose?

integrationtest/TestAuditSeccomp: Validate json output

---

cmd/common/audit/audit.go
cmd/common/audit/seccomp.go
cmd/kubectl-gadget/audit/seccomp.go
cmd/local-gadget/audit/audit.go
cmd/local-gadget/audit/seccomp.go
cmd/local-gadget/main.go
docs/guides/audit/seccomp.md
pkg/gadget-collection/gadget-collection.go
pkg/gadgets/audit/seccomp/types/types.go
pkg/local-gadget-manager/local-gadget-manager_test.go

Fixes https://github.com/inspektor-gadget/inspektor-gadget/issues/867

local-gadget: Add seccomp audit gadget

---

cmd/local-gadget/trace/dns.go
cmd/local-gadget/trace/trace.go
integration/local-gadget/trace_dns_test.go
pkg/container-collection/containers.go
pkg/container-collection/networktracer/connect.go
pkg/container-collection/options.go
pkg/gadget-collection/gadgets/trace/dns/gadget.go
pkg/gadget-collection/gadgets/trace/sni/gadget.go

Fix https://github.com/inspektor-gadget/inspektor-gadget/issues/886

local-gadget: trace dns localgadget

---

gadget-container/gadgettracermanager/main.go
gadget-container/hooks/nri/main.go
gadget-container/hooks/oci/main.go
pkg/container-utils/cri/cri.go

Patch initially proposed in #1148

Remove deprecated grpc.WithInsecure

---

pkg/runcfanotify/runcfanotify.go

The runcnotify package uses poll() to monitor the file descriptors (pidfd) of containers to detect when they are removed. A 1000ms timeout is used to make poll() return and update the list of file descriptors to monitor. This solution is not perfect since after a creation of a container, this mechanism could take up to 1 second to start monitoring for its deletion, also, from a performance point of view to unblock each second to rebuild the file descriptors list is not optimal.
This commit uses the self-pipe trick[0]: an end of the pipe is monitored by poll() and the other end is written by another goroutine to unblock it. This approach updates the list of watched fds faster as we don't have to wait for the timeout, also this timeout is completed removed and poll() only returns when there …

pkg/runcnotify: Use self-pipe trick to wake up poll()

---

cmd/kubectl-gadget/trace/sni.go
cmd/local-gadget/trace/sni.go
cmd/local-gadget/trace/trace.go
docs/local-gadget.md
integration/local-gadget/trace_dns_test.go
integration/local-gadget/trace_sni_test.go

local-gadget: Add trace sni gadget

---

cmd/common/advise/advise.go
cmd/common/advise/seccomp-profile.go
cmd/kubectl-gadget/advise/network-policy.go
cmd/kubectl-gadget/advise/seccomp-profile.go
cmd/kubectl-gadget/main.go
cmd/local-gadget/advise/advise.go
cmd/local-gadget/advise/seccomp-profile.go
cmd/local-gadget/main.go
pkg/gadget-collection/gadget-collection.go
pkg/gadget-collection/gadgets/advise/seccomp/gadget.go
pkg/gadget-collection/gadgets/advise/seccomp/syscalls.go
pkg/gadget-collection/gadgets/advise/seccomp/syscalls_none.go
pkg/gadgets/advise/seccomp/tracer/syscalls.go
pkg/gadgets/advise/seccomp/tracer/syscalls_none.go
pkg/gadgets/advise/seccomp/tracer/tracer.go
pkg/local-gadget-manager/local-gadget-manager_test.go

Fixes https://github.com/inspektor-gadget/inspektor-gadget/issues/866

local-gadget: Add seccomp-profile advise gadget

---

pkg/columns/columninfo.go
pkg/columns/columns.go
pkg/columns/columns_test.go

This PR adds the ability to embed structs non-anonymously and have them handled by the columns library.
This idea/requirement for this came up [here](https://github.com/inspektor-gadget/inspektor-gadget/pull/1167#discussion_r1041030558).
Example from the tests:
```golang
type embeddedStruct struct {
EmbeddedString string `column:"embeddedString"`
}
type embeddedPtrStruct struct {
EmbeddedString2 string `column:"embeddedString2"`
}
type ptrStruct struct {
EmbeddedString string `column:"ptrStructString"`
}
type normalStruct struct {
EmbeddedString string `column:"normalStructString"`
}
type testStruct struct {
embeddedStruct
*embeddedPtrStruct
PointerStruct           *ptrStruct
NormalStruct            normalStruct
NotEmbeddedPtrStruct    *ptrStruct   `column:"ptrStruct,noembed"` …
```

pkg/columns: add support for embedded structs via pointer

---

cmd/local-gadget/containers/containers.go
integration/local-gadget/list_containers_test.go
pkg/container-collection/pubsub.go

Add support for watching for container deletion events
Fixes #1028 
```
$ sudo ./local-gadget list-containers --watch
TIMESTAMP                      EVENT      RUNTIME    ID                                                     NAME                                                                                                                        
2022-12-01T19:13:10+01:00      CREATED    docker     c6b7cb5f7ab2c4f7db33c22c77d219010c7e0a2512fd3f3c65b31… busy_knuth                                                                                                                  
2022-12-01T19:13:16+01:00      DELETED    docker     c6b7cb5f7ab2c4f7db33c22c77d219010c7e0a2512fd3f3c65b31… busy_knuth   
```

local-gadget: Add support for printing container deletion events

---

README.md

- Sort by date
- Add kubecon2022 talks

docs: Organize talks

---

pkg/gadgets/trace/network/tracer/bpf/graph.c

Wrong ifdef declaration found by @burak-ok in #1201.

trace network: fix #ifndef condition

---

tools/getbtfhub.sh

See https://github.com/aquasecurity/btfhub/issues/51

tools: Use fork of btfhub until upstream is fixed

---

cmd/common/registry.go
internal/operators/localmanager/localmanager.go
pkg/gadgets/profile/cpu/tracer/tracer.go
pkg/gadgets/snapshot/process/tracer/tracer.go
pkg/gadgets/snapshot/socket/tracer/tracer.go
pkg/gadgets/top/block-io/tracer/tracer.go
pkg/gadgets/top/ebpf/tracer/tracer.go
pkg/gadgets/top/file/tracer/tracer.go
pkg/gadgets/top/tcp/tracer/tracer.go
pkg/gadgets/trace/bind/tracer/tracer.go
pkg/gadgets/trace/capabilities/tracer/tracer.go
pkg/gadgets/trace/fsslower/tracer/tracer.go
pkg/gadgets/trace/signal/tracer/tracer.go
pkg/params/params.go
pkg/params/validators.go

@flyth what do you think about these changes?

[internal]: Suggestions to https://github.com/inspektor-gadget/inspektor-gadget/pull/1281

---

.github/workflows/inspektor-gadget.yml
README.md
examples/README.md

Fix also a couple of broken links found by it.

Add action to check for broken links

---

docs/CONTRIBUTING.md
pkg/columns/formatter/textcolumns/textcolumns_test.go

This library makes the tests more compact and avoids a lot of conditionals.
---
What do you all folks think? IMO we could start using this library in the tests as I think the result tests are more readable.

RFC: pkg/columns: Use testify

---

pkg/operators/operators_test.go

Tests the sorting of Operators

pkg/operators: Add tests for SortOperators

---

cmd/common/registry.go

Print the error message as early as possible in case the output mode passed by the user is not valid.
Before:
```
$ sudo ./local-gadget profile block-io -o foobar
-> waiting some seconds before hitting ctrl + c
^CError: invalid output mode "foobar"
```
Now:
```
$ sudo ./local-gadget profile block-io -o foobar
Error: invalid output mode "foobar"
```

cmd: Check if output mode is valid before running the gadget

---

docs/devel/how-to-write-a-gadget.md
docs/ig.md

`make run` on the website repo was failing because some yaml headers were wrong.

docs: Fix documents for website

---

.github/workflows/inspektor-gadget.yml
Makefile
internal/benchmarks/benchmarks_test.go
internal/test/helpers.go
internal/test/runner.go
pkg/gadget-registry/gadget-registry.go
pkg/gadgets/internal/socketenricher/tracer_test.go

Same as https://github.com/inspektor-gadget/inspektor-gadget/pull/1419
But the base of the PR is the upstream repository. This way I can check the GitHub action in both cases.

CI: benchmarks all gadgets and publish graphs

---

docs/design/001-prometheus.md

Add document with the design of the Prometheus support in IG
Fixes https://github.com/inspektor-gadget/inspektor-gadget/issues/1513

design: Add prometheus design doc

---

cmd/common/registry.go

Add documentation for >=, <, <= operators too.

Fully document filtering operators

---

docs/devel/release-process.md

Follow up to https://github.com/inspektor-gadget/inspektor-gadget/pull/1608

docs/devel/release-process.md: add vscode-aks-tools

---

pkg/container-collection/options.go
pkg/container-utils/cgroups/cgroups.go
pkg/container-utils/containerutils.go
pkg/gadgets/snapshot/process/tracer/tracer.go
pkg/gadgets/top/ebpf/tracer/tracer.go
pkg/runcfanotify/runcfanotify.go
pkg/utils/host/host.go

In preparation for https://github.com/inspektor-gadget/inspektor-gadget/issues/1658

Access /proc via $HOST_ROOT

---

internal/test/helpers.go

Small cleanup to use stretchr/testify.

test/helpers: Use stretchr/testify

---

pkg/utils/bpf-iter-ns/bpf-iter-ns.go

I didn't set the correct path when addressing this comment:
https://github.com/inspektor-gadget/inspektor-gadget/pull/1708#discussion_r1220175307
Fixes: e91a93bb2c0a ("Read bpf iterators from host pid ns")

bpf-iter-ns: fix bpf pin path

---

docs/gadgets/trace/tcpdrop.md

Listing tools similar to the tcpdrop gadget.

docs: tcpdrop: listing similar tools

---

pkg/prometheus/prometheus_test.go

Add a timeout in case there's an issue to avoid the test being blocked the default 10m test timeout.
How to test:
Apply the following diff:
```diff
$ git diff
diff --git pkg/prometheus/stubgadgets_test.go pkg/prometheus/stubgadgets_test.go
index f3bbc2a8..0b3ab95e 100644
--- pkg/prometheus/stubgadgets_test.go
+++ pkg/prometheus/stubgadgets_test.go
@@ -86,13 +86,13 @@ func (t *stubTracer) Run(gadgetCtx gadgets.GadgetContext) error {
t.eventCallback(ev)
}
-       ctx := gadgetCtx.Context()
-
-       // Tell the caller test that events were generated
-       if val := ctx.Value(valuekey); val != nil {
-               wg := val.(*sync.WaitGroup)
-               wg.Done()
-       }
+       //      ctx := gadgetCtx.Context()
+       //
+       //      // Tell the caller test that events were …
```

pkg/prometheus: Implement timeout in test

---

cmd/common/registry.go

Another copy & pasta error.
Fixes: 8511d3b25dd7 ("gadgets: Add custom formatting options")

cmd: Fix json pretty output

---

docs/ig.md

Since https://github.com/inspektor-gadget/inspektor-gadget/pull/1702, the first column of `ig trace exec` is displayed as `RUNTIME.CONTAINERNAME`.
Update the documentation for the "kubectl debug node" command (https://github.com/inspektor-gadget/inspektor-gadget/pull/1809) accordingly.

docs: ig: update the columns for kubectl-debug

---

pkg/gadgets/run/tracer/tracer.go

Fixes: 5455443dcbd2 ("gadgets/run: Implement JSON and JSON pretty output")

gadgets/run: Remove unused field

---

docs/design/002-containerized-gadgets.md

Add document with the design of the containerized gadget support in IG.
Fixes https://github.com/inspektor-gadget/inspektor-gadget/issues/1722
Supersedes  https://github.com/inspektor-gadget/inspektor-gadget/pull/1716

design: Add containerized gadgets design doc

---

pkg/params/params.go
pkg/params/params_test.go
pkg/params/validator_test.go
pkg/params/validators.go

Implement some functionality needed in https://github.com/inspektor-gadget/inspektor-gadget/pull/2119
- pkg/params: Add IsSet() method
- pkg/params: Add AsAny()
- pkg/params: Implement float32 and float64 validators

pkg/params: Implement some extra functions

---

docs/install.md

It is now released since some time

install.md: Update minikube addon information

---

.github/workflows/inspektor-gadget.yml
cmd/gen-doc/crd.template
docs/SECURITY.md
docs/crds/traces.gadget.kinvolk.io.md
docs/devel/CONTRIBUTING.md
docs/devel/ci.md
docs/devel/hello-world-gadget.md
docs/devel/how-to-write-a-gadget.md
docs/devel/release-process.md

See individual commit  messages.
Visit https://inspektor-gadget.io/docs/
- Check out https://github.com/inspektor-gadget/website
- Run `make all run`
- Visit http://localhost:1313/docs/latest/
- Update hugo pages (e.g. `cp docs/SECURITY.md ../website/external-docs/inspektor-gadget.git_mainlatest/docs/`)

Reorganise documentation

---

pkg/gadgets/run/tracer/tracer.go

First commit reworks the logic to provide better debug information and error control.

run: Add support for fentry, fexit and raw_tracepoint programs

---

pkg/operators/common/kubeinventorycache.go
pkg/operators/kubeipresolver/kubeipresolver.go
pkg/operators/kubenameresolver/kubenameresolver.go

`Close()` should really only be called by `Stop()` and not by an operator directly.
If this would happen the enrichment for every other running gadget would fail (no new pods/services are getting registered)
The problem with the rare race condition was the following (This issue was before 0071cee0ffc63da02c862eea99ecf589cac1d266):
> In `Close()` the channel was closed and set to `nil`
> In the same time the loop had a chance to query the `exit` channel variable which was set to `nil` -> :boom: 
After this commit the race condition could only happen in the following situation:
> K8sInventoryCache.Start() is called and gets scheduled away after it created the channel exit
> K8sInventoryCache.Close() is called and exit gets assigned to nil
> K8sInventoryCache.Start() resumes and now gives …

K8sInventoryCache: Manage resources better + fix rare race condition

---

gadgets/Makefile
gadgets/trace_sni/gadget.yaml
gadgets/trace_sni/program.bpf.c
integration/inspektor-gadget/run_trace_sni_test.go

This PR adds trace_sni as image based gadget.

run: Add trace sni

---

README.md

This PR adds All Systems Go, Container Days, KubeCon + CloudNativeCon and Cloud Native Rejekts talks links to the Readme.

readme: update talks list

---

pkg/utils/host/workarounds.go

Amazon Linux does not use the new path "/sys/kernel/tracing" but only the old path "/sys/kernel/debug/tracing".
If tracefs is mounted at one of those paths, it is good enough for Inspektor Gadget. No need to error out or suggest anything.
Fixes https://github.com/inspektor-gadget/inspektor-gadget/issues/2426

auto-mount-filesystems: add alternative path for tracefs

---

docs/devel/hello-world-gadget.md

Docs update to provide clarity and fix pointer error in the example code in hello-world.
Nothing I suppose, test it locally ?
Tested locally on my machine whilst trying to setup the dev environment by following the documentation.

docs: add clarity and fix pointer error

---

docs/getting-started/requirements.md

[ describe the change in 1 - 3 paragraphs ]

Mark Talos as supported since #1934 is closed

---

pkg/columns/columns.go
pkg/columns/columns_test.go

This patch is coming from #2398 by @burak-ok. Since it is independent from the rest, it could be merged separately.

pkg/columns: Add support for map[string]string

---

gadgets/trace_exec/program.bpf.c

Same as 73acd49caedb ("trace exec: fix sys_exit_execve from thread") from #2454 but for the image-based gadget.
sys_enter_execve adds an entry in the "execs" map and sys_exit_execve removes it. However, sys_enter_execve and sys_exit_execve can be called from different thread id in case of a multithreaded application. This caused the map to not get cleaned up properly.
This patch fixes the tracking between sys_enter_execve and sys_exit_execve.
No changes
Tested with:
```
make -C gadgets/ trace_exec
sudo -E ./ig run ghcr.io/inspektor-gadget/gadget/trace_exec:alban_fix_execve_threads2
```
Same scenarios as in #2454.

image-based trace exec gadget: fix sys_exit_execve from thread

---

integration/inspektor-gadget/audit_seccomp_test.go

Tests on ARO were failing with: "error: no matching resources found", this because it's not possible to watch a resource that hasn't been created.
See https://github.com/kubernetes/kubernetes/issues/87352 & https://github.com/radius-project/radius/pull/6914
Fixes: 4e1bb6433081 ("integration: Disable installing Security Profile Operator")
Failing log: https://github.com/inspektor-gadget/inspektor-gadget/actions/runs/7878045886/attempts/3#summary-21498205420

integration: Fix disabling spo

---

README.md

Readme from PR: https://github.com/inspektor-gadget/inspektor-gadget/blob/c3389442fa6807a97ee902c2dce6f90ac0591eab/README.md

Readme: Add badges for test-reports/benchmarks

---

.github/workflows/inspektor-gadget.yml

ci: Use --force then deleting EKS cluster

---

pkg/columns/columninfo.go
pkg/columns/helpers.go

This publishes a previously internal function from the columns package to be used by other packages.
Part of #2512

pkg/columns: publish GetWidthFromKind(reflect.Kind) helper

---

pkg/gadgets/run/tracer/run.go

In some cases it's not possible to order the fields in the event structure in a human-friendly way (padding and other reasons), hence it's possible to change the order of those fields in the metadata file. This commit updates the logic to use the same order defined in such file instaed of relying on the event structure layout.
Fields are printed in the same order of the struct event
https://github.com/inspektor-gadget/inspektor-gadget/blob/432375356fac33c3ea32031f3adf06c827addb2f/gadgets/trace_open/program.bpf.c#L24-L36
```bash 
$ sudo -E ig run trace_open 
RUNTIME.CONTAINERNAME                PID                 UID                 GID                 RET    COMM             FNAME 
```
Fields are printed in the same order as …

run: Print fields on same order as defined in the metadata

---

docs/devel/hello-world-gadget.md

This PR updates the guide with recent changes to the code.

docs/devel: Update hello world gadget guide

---

gadgets/snapshot_process/artifacthub-pkg.yml
gadgets/snapshot_socket/artifacthub-pkg.yml
gadgets/top_file/artifacthub-pkg.yml
gadgets/trace_dns/artifacthub-pkg.yml
gadgets/trace_exec/artifacthub-pkg.yml
gadgets/trace_malloc/artifacthub-pkg.yml
gadgets/trace_mount/artifacthub-pkg.yml
gadgets/trace_oomkill/artifacthub-pkg.yml
gadgets/trace_open/artifacthub-pkg.yml
gadgets/trace_signal/artifacthub-pkg.yml
gadgets/trace_sni/artifacthub-pkg.yml
gadgets/trace_tcp/artifacthub-pkg.yml
gadgets/trace_tcpconnect/artifacthub-pkg.yml
gadgets/trace_tcpdrop/artifacthub-pkg.yml
gadgets/trace_tcpretrans/artifacthub-pkg.yml

Command used to update:
```
inspektor_gadget_version=$(curl --silent https://api.github.com/repos/inspektor-gadget/inspektor-gadget/releases/latest | jq .tag_name | tr -d '"v')
for PKGFILE in $(find gadgets/ -name artifacthub-pkg.yml) ; do
sed -i -e "s/^version:.*$/version: ${inspektor_gadget_version}/" $PKGFILE
done
```
#2586 attempts to make it automatic but it is not ready yet.

artifacthub-pkg.yml: update gadget versions to new release

---

.github/workflows/inspektor-gadget.yml

Avoid building the gadgets twice
See https://github.com/inspektor-gadget/inspektor-gadget/pull/2642

ci: Check that metadata file is updated to build-and-push-gadgets

---

pkg/datasource/data.go

The [sync.Pool](https://pkg.go.dev/sync#Pool) was useful in a previous refactoring iteration where we were creating fixed-sized buffers, which is not the case anymore.
CI is green 🙂.

pkg/datasource: Don't use sync.Pool for data

---

pkg/operators/ebpf/tracer.go

The perf event array can contain trailing garbage, we need to remove it before emitting the sample.
Build the following gadget
```c
#include <vmlinux.h>
#include <bpf/bpf_helpers.h>
#include <gadget/macros.h>
#include <bpf/bpf_core_read.h>
struct event {
__u64 mntns_id;
__u32 pid;
};
struct {
__uint(type, BPF_MAP_TYPE_PERF_EVENT_ARRAY);
__uint(key_size, sizeof(__u32));
__uint(value_size, sizeof(__u32));
} events SEC(".maps");
// [Optional] Define a tracer
GADGET_TRACER(open, events, event);
SEC("tracepoint/syscalls/sys_enter_openat")
int enter_openat(struct syscall_trace_enter *ctx)
{
struct event event = {};
struct task_struct *task;
event.pid = bpf_get_current_pid_tgid() >> 32;
task = (struct task_struct *)bpf_get_current_task();
event.mntns_id = (u64)BPF_CORE_READ(task, nsproxy, …
```

ebpf: Remove trailing garbage when reading sample from perf event array

---

docs/getting-started/install-kubernetes.md

Update and formatting was done automatically by VS Code

install-kubernetes.md: Fix and update table of contents

---

pkg/oci/oci.go

Remove some more code we aren't using.

oci: Remove dead code

---

gadgets/trace_open/test/trace_open_test.go

- Leverage the [containers.TestContainer](https://github.com/inspektor-gadget/inspektor-gadget/blob/97eaf2fc80da992a6ed1b54cebc861bbf91844bd/pkg/testing/containers/factory.go#L45-L48) methods to retrieve the container ID and verify it in the expected output.
- Specify the image we want to use and verify it in the expected output.
- NOTE: The image digest is not yet enriched for Docker. See https://github.com/inspektor-gadget/inspektor-gadget/issues/2365.
CI is green 🙂 
The [containers.TestContainer](https://github.com/inspektor-gadget/inspektor-gadget/blob/97eaf2fc80da992a6ed1b54cebc861bbf91844bd/pkg/testing/containers/factory.go#L45-L48) also provides the `Pid()`. Using that value, we can retrieve the mount ns inode as we do in [getNsInode](https://github.com/inspektor-gadget/inspektor-ga …

gadgets/trace_open/test: Verify container name and ID

---

pkg/columns/filter/filter.go
pkg/columns/filter/filter_test.go

Fixes: https://github.com/inspektor-gadget/inspektor-gadget/issues/2752
```bash
→ go run -exec 'sudo' ./cmd/ig trace dns -o columns=+latency --host -F 'latency:>10ms'
RUNTIME.CONTAINERNAME                                 PID        TID        COMM             QR TYPE      QTYPE      NAME                                                 RCODE                        NUMANSW… LATENCY             
2697972    2697973    isc-net-0000     R  HOST      A          inspektor-gadget.io.                                 No Error                     2        394.511µs           
2697972    2697973    isc-net-0000     R  HOST      AAAA       inspektor-gadget.io.                                 No Error                     2        292.461µs           
933        933        systemd-resolve  R  HOST      A …
```

columns/filter: Add support for time.Duration

---

pkg/oci/oci.go

Concurrent calls to different oci.Store instances leads to race condition on the files that are written to the disk. oci.Store is goroutine safe only against its own instance.
cc @mqasimsarfraz

pkg/oci: Use Singleton for getLocalOciStore

---

.github/workflows/cloud-cleanup.yml

Add a check to not run cloud-cleanup on a fork!

ci: Do not run cloud-cleanup on fork

---

pkg/datasource/accessors.go
pkg/datasource/formatters/json/json.go

Handling bool fields in useful in some cases, for instance one of the examples in #2753 needs this.

datasources: Add Bool accessors

---

pkg/datasource/accessors.go
pkg/datasource/compat/wrapper.go
pkg/datasource/data.go
pkg/datasource/datasource.go
pkg/datasource/datasource_test.go
pkg/operators/ebpf/snapshotter.go
pkg/runtime/grpc/oci.go

See individual commits for more details.

datasources: Add missing setters, allocate memory and add tests

---

.github/workflows/inspektor-gadget.yml

Backport of https://github.com/inspektor-gadget/inspektor-gadget/pull/2852

[Backport] version: Fix server version for ig-k8s

---

docs/getting-started/install-kubernetes.md
docs/getting-started/install-linux.md
docs/getting-started/quick-start.md

Add documentation related to our official helm charts!

docs: Add installation steps for helm charts

---

.github/dependabot.yml

-  dependabot: Update other packages dependencies too
-  dependabot: use dependency-type: all

Updates to dependabot 

---

docs/design/003-wasm-support.md

Add design document to discuss the use cases we want to support with Wasm.
#2818 is implement the first phase of this support.

docs: Add initial wasm design doc

---

integration/components/image/image_test.go

tests: Add tests for image export and import

---

integration/command.go

The error message we got sometimes in the CI log was quite confusing. It mentioned that there was an error killing the process. Rather it was killing the process (if it still ran) and then also returning potential errors while running the `Command` or the exit code.
xref: https://github.com/inspektor-gadget/inspektor-gadget/pull/3026#discussion_r1644516943

integration/Command: Enhance error messages for kill

---

cmd/ig/main.go
gadget-container/gadgettracermanager/main.go
pkg/datasource/data.go
pkg/datasource/datasource.go
pkg/operators/sort/sort.go
pkg/operators/sort/sort_test.go

This adds the sort operator for image based gadgets.

add sort operator

---

pkg/datasource/data.go
pkg/datasource/datasource.go
pkg/datasource/datasource_test.go
pkg/gadget-context/gadget-context.go
pkg/operators/wasm/consts_test.go
pkg/operators/wasm/datasource.go
wasmapi/go/datasource.go

Check that the datasource type is right.

datasource: Return error on New()

---

pkg/operators/kubemanager/kubemanager.go

Respect --all-namespaces for image based gadgets

---

gadgets/trace_capabilities/test/trace_capabilities_test.go

gadgets/trace_capabilities: Add test

---

pkg/container-utils/docker/docker.go

This PR adds docker runtime image digest enrich for containers that are already running.
This won't work for containers that are being created. For containers that are being created the logic stays the same and the image's digest is an empty string
Part of: https://github.com/inspektor-gadget/inspektor-gadget/issues/2365
And Supersedes: https://github.com/inspektor-gadget/inspektor-gadget/pull/2798
Before:
{
"runtime": {
"runtimeName": "docker",
"containerId": "53cb38ede1bf48c705b62a0df64f4c4f0f134e7dc5e0ab1f9d42eed0a5f2b53d",
"containerName": "charming_murdock",
"containerImageName": "ubuntu"
}
}
After:
{
"runtime": {
"runtimeName": "docker",
"containerId": "53cb38ede1bf48c705b62a0df64f4c4f0f134e7dc5e0ab1f9d42eed0a5f2b53d",
"containerName": "charming_murdock",
"containerImageName": …

Adding docker runtime image digest enrichment for running containers

---

.github/workflows/inspektor-gadget.yml
gadgets/Makefile
gadgets/trace_sni/test/trace_sni_test.go
pkg/testing/utils/utils.go

Enable running the gadgets tests on containerd.

gadgets: Test on containerd too

---

.github/actions/prepare-and-publish-test-reports/action.yml
.github/actions/run-integration-tests/action.yml
.github/actions/sign-container-image/action.yml
.github/workflows/cloud-cleanup.yml
.github/workflows/inspektor-gadget.yml
.github/workflows/release.yml
.github/workflows/stale.yaml

This fixes a lot of security alerts created by scorecard. This was fixed by using https://app.stepsecurity.io/secureworkflow as suggested by the security alert.
Example security issue: https://github.com/inspektor-gadget/inspektor-gadget/security/code-scanning/102

ci: Pin Github Actions

---

Dockerfiles/ebpf-builder.Dockerfile
Dockerfiles/gadget.Dockerfile
Dockerfiles/ig-tests.Dockerfile
Dockerfiles/ig.Dockerfile
Dockerfiles/kubectl-gadget.Dockerfile
Dockerfiles/linter.Dockerfile
Makefile
examples/builtin-gadgets/withfilter/trace/network/Dockerfile
examples/kube-container-collection/Dockerfile
examples/runc-hook/Dockerfile
tools/dnstester/Dockerfile

Fix some issues reported in https://github.com/inspektor-gadget/inspektor-gadget/security/code-scanning/

tree-wide: Pin base images on Dockerfiles

---

gadgets/trace_exec/gadget.yaml
gadgets/trace_exec/program.bpf.c
gadgets/trace_exec/test/trace_exec_test.go
pkg/testing/ig/ig.go

Adding cwd field to trace_exec image-based gadget
* Unit Tests
* Local Testing

Adding cwd field to trace_exec image-based gadget

---

docs/gadgets/profile_blockio.mdx
gadgets/profile_blockio/README.md
gadgets/profile_blockio/README.mdx
gadgets/profile_blockio/artifacthub-pkg.yml

guides: Add profile_blockio

---

README.md
docs/quick-start.md

Do not use an extra section for installing but inline the instructions in the quick start part.
Also align with docs/quick-start.md

README: update

---

docs/gadgets/audit_seccomp.mdx
docs/gadgets/snapshot_process.mdx
gadgets/audit_seccomp/README.md
gadgets/audit_seccomp/README.mdx
gadgets/snapshot_process/README.md
gadgets/snapshot_process/README.mdx

Port few other image based guides

docs: port more guides

---

docs/quick-start.md

quick-start.md: run.md -> run.mdx

quick-start.md: run.md -> run.mdx

---

gadgets/trace_tcpretrans/test/trace_tcpretrans_test.go

fixes: #3241
- added test for trace tcp retransmission gadget.
cc @burak-ok @mauriciovasquezbernal 
I ran test locally and heres output :

feat(test): added test for gadgets/trace_tcpretrans 

---

docs/gadgets/builtin/trace/capabilities.md
docs/reference/install-kubernetes.md
docs/reference/install-linux.md

See https://github.com/inspektor-gadget/inspektor-gadget/pull/3300#issuecomment-2284118927

docs: Fix more broken links

---

docs/legacy/crds/gadgets/ebpftop.md
docs/legacy/crds/gadgets/filetop.md

Two new fields were added in https://github.com/inspektor-gadget/inspektor-gadget/pull/3319. They have to be update in the legacy docs aswell, to satisfy the CI

docs/legacy: Update the sort_by list

---

cmd/common/oci.go
pkg/operators/sort/sort.go

After the combiner operator combines data from all targets, it's necessary to sort the resulting array again on the client side.
```bash
$ ./kubectl-gadget run $MY_REPO/top_file --pull always --sort file -o column --fields=k8s.node,file
WARN[0002] aks-agentpool-19875870-vmss000000 | image signature verification is disabled due to using corresponding option
K8S.NODE                                               FILE
WARN[0002] aks-agentpool-19875870-vmss000002 | image signature verification is disabled due to using corresponding option
WARN[0002] aks-agentpool-19875870-vmss000001 | image signature verification is disabled due to using corresponding option
K8S.NODE                                               FILE
K8S.NODE                                               FILE
K8S.NODE …
```

gadgetctl/kubectl-gadget: Ensure sorting after combining data from all targets

---

cmd/common/image/Makefile.build
docs/gadget-devel/hello-world-gadget-wasm.md
gadgets/trace_dns/go/go.mod
gadgets/trace_dns/go/go.sum
gadgets/trace_exec/go/go.mod
gadgets/trace_mount/go/go.mod
gadgets/trace_open/go/go.mod

Change directory to the folder containing the golang program before running tinygo.

image/build: Fix wasm compilation

---

.github/workflows/inspektor-gadget.yml
gadgets/Makefile

Add a check to ensure gadget guides are updated and we have the necessary symlinks.
Fixes: https://github.com/inspektor-gadget/inspektor-gadget/issues/3365

ci: Add check for gadget guides

---

docs/spec/oci.md

See https://github.com/inspektor-gadget/inspektor-gadget/issues/2151#issuecomment-2291485195

docs: Add some links

---

pkg/operators/cli/clioperator.go

pkg/operators/cli: Improve log level for errors and avoid blocking other ds when one fails

---

docs/gadget-devel/metadata.md
docs/spec/operators/formatters.md
docs/spec/operators/index.mdx

See https://github.com/inspektor-gadget/inspektor-gadget/pull/3406#discussion_r1740992907

docs/operators: remove links from diagram

---

gadgets/trace_dns/README.mdx

Improve trace_dns guide. 
Rendered using: https://github.com/inspektor-gadget/website

docs: Improve trace_dns guide

---

gadgets/fsnotify/gadget.yaml
gadgets/fsnotify/program.bpf.c

New fields:
- ppid
- uid
- gid
- pcomm
For both the tracer and the tracee processes.
This is part of #1567.

fsnotify: add new fields

---

pkg/operators/ebpf/ebpf.go

The socket enricher has been designed to be optional. Examples of patches that makes sure a gadget can run even if the socket enricher fails to start:
35b9e87be4c8 ("socket enricher: make iterators optional")
681c3701c31e ("socketenricher: Print warning rather than error when problem with kallsyms.")
However, there is another reason why the socket enricher can fail to start: for now, the gadget eBPF API is not stable and new versions of Inspektor Gadget can change it, causing problems in old gadgets.
Commit 79c3ebe76cef ("socket enricher: add new fields...") introduced such an API change. This caused Inspektor Gadget v0.32.0 (without the change) to fail to run trace_tcpdrop:latest (with the change):
> starting operators: starting operator "oci": starting operator "ebpf":
> creating eBPF …

socket enricher: warning in case of incompatibility

---

docs/gadget-devel/hello-world-gadget-wasm.md

Minor nits I found while going through wasm guide!

docs: Fixes for hello-world-gadget-wasm

---

gadgets/trace_oomkill/README.mdx

Improve trace_oomkill guide. Upstream References:
- https://github.com/kubernetes/kubernetes/pull/126096
- https://kubernetes.io/docs/concepts/architecture/cgroups/#using-cgroupv2

docs: Improve trace_oomkill guide

---

gadgets/top_blockio/README.mdx
gadgets/top_file/README.mdx
gadgets/top_tcp/README.mdx
gadgets/trace_bind/README.mdx
gadgets/trace_capabilities/README.mdx
gadgets/trace_dns/README.mdx
gadgets/trace_exec/README.mdx
gadgets/trace_fsslower/README.mdx
gadgets/trace_lsm/README.mdx
gadgets/trace_malloc/README.mdx
gadgets/trace_mount/README.mdx
gadgets/trace_oomkill/README.mdx
gadgets/trace_open/README.mdx
gadgets/trace_signal/README.mdx
gadgets/trace_sni/README.mdx
gadgets/trace_ssl/README.mdx
gadgets/trace_tcp/README.mdx
gadgets/trace_tcpconnect/README.mdx
gadgets/trace_tcpdrop/README.mdx
gadgets/trace_tcpretrans/README.mdx

gadgets/README.mdx: Update sidebar_position after adding top_blockio

gadgets/README.mdx: Update sidebar_position after adding top_blockio

---

README.md
gadgets/trace_dns/README.mdx

Add link for Container Days Hamburg 2024 talk. Should we mention this talk in the DNS guide?

readme: Add link for CDS 2024

---

.github/workflows/inspektor-gadget.yml
Makefile
gadgets/Makefile
gadgets/ci/inner_fields/program.bpf.c
gadgets/ci/inner_fields/test/unit/inner_fields_test.go
pkg/testing/gadgetrunner/gadgetrunner.go

Add some tests for #3523 using #3195
What do all think about creating this "ci\" gadgets used for testing purposes? It seems to be aligned with #2301

tests: implement inner field tests

---

cmd/common/image/build.go

Print the logs also when using --local

cmd/image: Print build logs when using verbose mode

---

docs/reference/export-metrics.mdx
gadgets/profile_blockio/README.mdx

Ref: https://github.com/inspektor-gadget/inspektor-gadget/issues/3306

Add gadget user documentation for exporting metrics to Prometheus

---

pkg/operators/cli/clioperator.go

Printing the header when using the columns mode is a simple but complicated task as there are multiple things to take into account.
1. It should only be printed once for gadgets that dump all the information at once. Like snapshotters.
2. It should be printed right away for gadgets that collect and print the information later on (like toppers).
This commit is a "best effort" to fix that, probably there are corner cases not covered yet.
Supersedes #3281
Fixes #3264

operators/cli: Improve logic to print header

---

README.md

This has now landed so we should remove the coming soon part

Readme: Update the declarative config line in the features list

---

pkg/gadget-service/store/k8s-configmap-store/configmapstore.go

- Updated the `createGadgetInstance` function to validate if an instance with the same name already exists.
- If a duplicate is detected, the function will now return an error instead of proceeding with the creation.

feat(kubectl-gadget): disallow instances with same name

---

gadgets/trace_dns/go/program.go

Improve formatting DNS trace events for CNAME records
Local tests were performed successfully. Screenshot attached for reference.

fixes DNS trace formatting

---

pkg/container-hook/tracer.go

- Add more details in error messages
- Turn some error messages into debug, since they are not errors
- Change the logic to reduce verbosity
This is a follow-up from #3812
cc @ninadingole 
No changes
Tested locally with docker.

container-hook: improve logging

---

pkg/oci/build.go
pkg/oci/oci.go
pkg/operators/oci-handler/oci.go

Some small fixes around found while working on #3842

pkg/oci: small fixes

---

.github/workflows/inspektor-gadget.yml

- [0] suggests not to use {{ }} inside a script block to avoid script
injection attacks. Even if we're not using any untrusted input, let's use
a good practice for all inputs to avoid a mistake in the future.
- Use quoting for variables in the script blocks to avoid nasty issues.
[0]: https://securitylab.github.com/resources/github-actions-untrusted-input/

gha: Observe GitHub good practice

---

pkg/operators/common/kubeinventorycache.go

Added node name to slim pod

---

pkg/operators/ebpf/tracer.go

It seems we aren't handling lost samples correctly and under high load, we are getting empty samples: https://github.com/cilium/ebpf/blob/9f201154004369b0bc1b99a06ee578aa46c6aab4/perf/reader.go#L78 resulting in error messages like https://github.com/inspektor-gadget/inspektor-gadget/issues/3936. This change reports the lost samples and continue.
Related: https://github.com/inspektor-gadget/inspektor-gadget/issues/3936
During testing I realized if we have slow subscriber call backs (e.g `wasm`) we can easily end up in a situation where we don't read perf buffer fast enough, resulting in samples being dropped. Is there anything can be done about it?

ebpf/tracer: Report lost samples

---

gadgets/trace_dns/test/integration/trace_dns_test.go

Make server and client image of the trace dns gadget test configurable.

Make images configurable

---

pkg/gadgets/trace/bind/tracer/tracer.go

Resolving interface number to 
Refer #3121
I only added namespace switching to ensure correct interface name while resolving from an interface index in the in-built gadget. Normally it works fine but when I test it on a custom namespace using netns, the interface index cannot be resolved.
Commands I used (Where it's failing) :
sudo ip link add veth0 type veth peer name veth1
sudo ip link set veth0 netns custom_ns
sudo ip netns exec custom_ns ip addr show veth0
sudo ip netns exec custom_ns ip addr add 192.168.1.1/24 dev veth0
sudo ip netns exec custom_ns ip link set veth0 up
sudo ip netns exec custom_ns python3 -c "import socket
import os
def bind_to_custom_interface(interface, port):
sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
try:
sock.setsockopt(socket.SOL_SOCKET, …

Find interface name wrt to namespace

---

gadgets/fsnotify/gadget.yaml
gadgets/fsnotify/program.bpf.c

We can display i_mask of inotify and fa_mask of fanotify as strings

Display external api masks of fsnotify as strings

---

gadgets/fsnotify/program.bpf.c

- fsnotify: fix CORE access to group->priority
No changes.
- Cherry-pick commits from #4036
- Cherry-pick commits from #3729
- Let the CI run on different kernels (see [results](https://github.com/inspektor-gadget/inspektor-gadget/actions/runs/13308312742/job/37167784726))
cc @mauriciovasquezbernal @4rivappa

fsnotify: fix CORE accesses on different kernel versions

---

gadgets/top_blockio/README.mdx

gadgets/top_blockio/README.mdx: fix typo

---

pkg/operators/limiter/limiter.go

When there is more than one target, e.g., a Kubernetes cluster with more than one node, the limiter operator was limiting each node at server side, but not the total amount of outputted entries at client side after merging the output of each node.
Cluster with more than one node:
```bash
$ k get nodes
NAME                                STATUS   ROLES    AGE     VERSION
aks-agentpool-19875870-vmss000000   Ready    <none>   5d22h   v1.29.11
aks-agentpool-19875870-vmss000001   Ready    <none>   5d22h   v1.29.11
aks-agentpool-19875870-vmss000002   Ready    <none>   5d22h   v1.29.11
```
```bash
./kubectl-gadget run top_tcp -A --max-entries 3
K8S.NODE                       K8S.NAMESPACE                  K8S.PODNAME                    K8S.CONTAINERNAME                           PID …
```

limiter: Fix max-entries for multiple targets

---

pkg/container-collection/k8s.go
pkg/container-collection/options.go

Detect early when the container runtime gives an initial container with a pid that does not exist. This could happen if the container terminates while querying the container runtime, or if there is a misconfiguration and we can't query the container details in /host/proc/pid.
It could help with debugging #4127.
Start a test container:
```
docker run --name busyboxtest -ti --rm -v /run:/run -v /usr/bin/runc:/usr/bin/runc busybox
```
Start ig with the wrong configuration:
```
$ sudo HOST_ROOT=/proc/$(docker inspect busyboxtest | jq '.[0].State.Pid')/root/ ./ig list-containers -w
```
Output before the patch:
```
ERRO[0001] cgroup enricher: failed to get cgroup paths on container 7bc5bdded36f820e29bdad5f20f0141e9768919cad4b844b95ec7fa448ae673b: parsing cgroup: open …
```

container-collection: initial containers: better logs for inexistent pid

---

docs/gadget-devel/gadget-ebpf-api.md

Some minor fixes to the demo code for ustack enrichment.

docs: fix ustack sample code

---

pkg/operators/wasm/fields.go
pkg/operators/wasm/testdata/badguest/program.go
pkg/operators/wasm/testdata/fields/program.go

Stack[0] was never assigned to zero, it caused the different set functions to return an error when the operation was successful.
Fixes: 7a3e62698bbc ("operators: Add wasm operator")
Ref https://github.com/inspektor-gadget/inspektor-gadget/pull/4160#discussion_r1979586309

operators/wasm: Fix return code for fieldSet

---

README.md

Removed a redundant word in README.md

Small grammar change

---

pkg/operators/wasm/wasm.go

After switching to golang in guest (previously tinygo) the compile
time (InstantiateWithConfig) for wasm modules has noticeably increased.
Wazero allows using a cache to avoid compiling these modules everytime.
The cache is key is based of SHA of wasm program and cache directory uses
wazero version to ensure no surprises if IG changes wazero version. The change uses the cache across different
gadgets runs to speed-up starting a gadget. 
```
$ time sudo -E ig run trace_dns:v0.38.0 --pull always --verify-image=false --timeout 1
WARN[0001] image signature verification is disabled due to using corresponding option 
WARN[0001] image signature verification is disabled due to using corresponding option 
RUNTIME.CONTAINERNAME                                            SRC …
```

wasm: Use cache to speed-up things

---

charts/gadget/templates/_helpers.tpl

Support all [Kubernetes recommended labels](https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/)

feat(helm): missing Kubernetes recommended labels

---

pkg/kallsyms/kallsyms_test.go

See https://github.com/inspektor-gadget/inspektor-gadget/issues/4367

pkg/kallsyms: disable failing test

---

docs/reference/export-metrics.mdx

Fixes #4007
Should we have deeper documentation on how to install and configure prometheus to scrap the metrics?

docs: Add documentation for exposing metrics on K8s

---

charts/gadget/templates/configmap.yaml
charts/gadget/values.yaml
pkg/resources/manifests/deploy.yaml

helm: Add parameter to enable bpfstats

---

cmd/common/image/build.go

Always print warnings when compiling gadget

---

pkg/operators/filter/filter.go

Include negative regex in the `filter`'s param documentation.
Related #3938

pkg/operators/filter: Update documentation to include negative regex

---

cmd/common/image/build.go

Refer #4335 
The error is visible while building empty directories, but I run into a `pulling builder image` problem whenever I use an
ig executable local to the directory with the new changes or not.
Also it shows an error for directory containing standalone go files. I think this is because they don't form a layer in the final built image.

Give error when incorrect build

---

pkg/gadget-context/gadget-context.go

Fix for https://github.com/inspektor-gadget/inspektor-gadget/pull/4473#discussion_r2101961743

inspect: fixes inconsistent sorting of datasources

---

pkg/operators/combiner/combiner.go

This moves the DS unreference and new DS creation to the InstantiateDataOperator call. This is needed in order for other Operators to reference the new DS instead of the old one that would have been replaced in PreStart

operator/combiner: Move DS creation to Instantiate

---

gadgets/Makefile
gadgets/ci/image_inspect/gadget.yaml
gadgets/ci/image_inspect/program.bpf.c
gadgets/ci/image_inspect/test/unit/image_inspect_test.go

This PR adds testing for the inspect subcommand
Fixes #4332
Part of #3387

inspect: adds testing for inspect command

---

docs/gadget-devel/gadget-ebpf-api.md
pkg/operators/formatters/formatters.go
pkg/utils/annotations/annotations.go

Set visibility of formatted columns

---

.github/workflows/inspektor-gadget.yml
cmd/common/image/build.go

gadgets: Compile with '-Werror' in the CI

gadgets: Compile with '-Werror' in the CI

---

Dockerfiles/gadget-builder.Dockerfile
cmd/common/image/build.go
cmd/common/image/helpers/Makefile.build

This will allow CI to get the updated changes and execute rust tests correctly.

update: allow ig to have rust support

---

docs/gadgets/profile_cpu.mdx

Website build is also broken because of this

docs: Fix symlink for profile_cpu

---

gadgets/README.template
gadgets/advise_networkpolicy/README.mdx
gadgets/advise_seccomp/README.mdx
gadgets/fsnotify/README.mdx
gadgets/profile_blockio/README.mdx
gadgets/profile_cpu/README.mdx
gadgets/profile_qdisc_latency/README.mdx
gadgets/profile_tcprtt/README.mdx
gadgets/snapshot_process/README.mdx
gadgets/snapshot_socket/README.mdx
gadgets/top_blockio/README.mdx
gadgets/top_file/README.mdx
gadgets/top_tcp/README.mdx
gadgets/trace_bind/README.mdx
gadgets/trace_capabilities/README.mdx
gadgets/trace_dns/README.mdx
gadgets/trace_exec/README.mdx
gadgets/trace_fsslower/README.mdx
gadgets/trace_mount/README.mdx
gadgets/trace_oomkill/README.mdx
gadgets/trace_open/README.mdx
gadgets/trace_signal/README.mdx
gadgets/trace_sni/README.mdx
gadgets/trace_tcp/README.mdx
gadgets/trace_tcpdrop/README.mdx
gadgets/trace_tcpretrans/README.mdx
gadgets/traceloop/README.mdx

Document kernel version

---

docs/index.md

The sentence wasn't grammatical and was confusing to read with it in the wrong place.
[ describe the change in 1 - 3 paragraphs ]

Fix placement of a parenthesis in index.md

---

gadgets/advise_networkpolicy/README.mdx
gadgets/advise_networkpolicy/gadget.yaml
gadgets/advise_networkpolicy/test/integration/advise_networkpolicy_test.go
gadgets/advise_seccomp/README.mdx
gadgets/advise_seccomp/gadget.yaml
pkg/gadget-context/context_test.go
pkg/gadget-context/gadget-context.go
pkg/gadget-context/run.go
pkg/operators/oci-handler/oci.go

Some gadgets needs to customize some parameters in order to have a better UX, this commit does it by introducing a new paramDefaults on the metadata file.
Fixes #4443
Related #4570

Allow gadgets to specify default values for parameters

---

pkg/oci/oci.go

Gadget signatures are pushed to the registry as OCI artifacts. Use the oras logic to push those sinagures into the local oci store instead of using a custom logic to save the signagure and the payload.
This also makes it easier to import and export the signatures as they are handled as standard oci artifacts, so we don't need any special logic.
Ref #4526
Ref #4577

oci: Use oras to cache gadget signature

---

pkg/oci/oci.go

Fixes #4577
The below implementation works but there is one problem. Right now I'm saving the signature in the same store as the images, this leads to lot of warnings being printed when using commands like `image list` and `image remove` as they assume all artifacts to be images when some of them could be signatures. IMHO I think that we should create a separate store for signatures otherwise we'll have to add checks whenever we are iterating through tags in the `defaultOciStore`.
**For Example :**
```
$ sudo ./ig image list
WARN[0000] getting gadget image descriptor for sha256-ec61880a80bb1e5b5cffa13452c0ee4c8d0014e540994c282048b0ddd95980f8.sig: getting manifest for "sha256-ec61880a80bb1e5b5cffa13452c0ee4c8d0014e540994c282048b0ddd95980f8.sig": getting index: getting image list …
```

Handle signature during image export/import

---

cmd/common/image/import.go

Considering the output of `ig image import` command is a list of images imported from the specified file, it makes sense to support JSON output mode. This allows users to easily parse the output programmatically, especially when integrating with other tools or for scripting purposes (e.g., in tests).
Maintains backward compatibility with the existing human-readable output as the default.
Current default behaviour doesn't change. Users interested in JSON format need to use `-o json` or `-o jsonpretty`.
Export gadgets into a file:
```bash
ig image export traceloop trace_dns my-gadgets
```
Tests different output modes:
```bash
$ ig image import my-gadgets
Successfully imported images:
ghcr.io/inspektor-gadget/gadget/trace_dns:latest
ghcr.io/inspektor-gadget/gadget/traceloop:latest
``` …

cmd/common/image/import: Support JSON output mode

---

gadgets/top_process/README.md

Add `README.md` file to top_process gadget
Context: readme file is required to mark gadget with `official` status. [[comment-link](https://github.com/artifacthub/hub/issues/4493#issuecomment-3199527042)]

Docs: Add readme file to top_process gadget

---

Makefile
docs/api/grpc.md
docs/design/002-containerized-gadgets.md
docs/devel/ci.md
docs/devel/contributing.md

This is the same as #4854 but targeting v0.44.
cc @burak-ok

[release-v0.44] docs: fix various broken links

---

cmd/kubectl-gadget/undeploy.go

undeploy: Remove legacy logic to deleted old IG deployments

---

gadgets/trace_capabilities/test/integration/trace_capabilities_test.go
pkg/symbolizer/symbolizer.go
pkg/symbolizer/symtab_linux.go

Based on initial work from @blanquicet 
I also added a test to check various build options.
No changes.
As said in the commitmsg, I tested with:
```
IG_FLAGS="--verify-image=false" IG_PATH=$PWD/ig IG_RUNTIME=docker make -C gadgets/ trace_capabilities/test-integration
```

symbolizer: implement support for PIE (Position Independent Executable)
