inspektor-gadget/inspektor-gadget

Makefile, gadget-container/Makefile
According to the documentation [0]: "The cgo tool is enabled by default for native builds on systems where it is expected to work", hence we need to set CGO_ENABLED=0 to explicitly disable it.
It was causing a lot of warnings in make kubectl-gadget on my system:
```
$ make kubectl-gadget
export GO111MODULE=on && \
export GOOS=linux GOARCH=amd64 && \
go build -ldflags "-X main.version=`git describe --tags --always`-dirty -X main.gadgetimage=ghcr.io/inspektor-gadget/inspektor-gadget:latest -extldflags '-static'" \
-tags withoutebpf \
-o kubectl-gadget-${GOOS}-${GOARCH} \
github.com/inspektor-gadget/inspektor-gadget/cmd/kubectl-gadget
/usr/bin/ld: /tmp/go-link-2694774814/000027.o: in function `pluginOpen':
/_/plugin/plugin_dlopen.go:19: warning: Using 'dlopen' in statically linked …
```
=> Disable cgo explicitly

examples/gadgets/basic/trace/dns/dns.go
It panics without this call.
panic: host.Init() must be called before calling isHostNamespace()
Fixes: a65dbbc6bcfd ("host package: workarounds for kubectl-debug and Windows")
@alban do you think it's ok to have this call there or should we move it to the tracer itself so users don't need to add this?
=> examples/dns: Add missing call to host.Init()

pkg/operators/localmanager/localmanager.go
72e7751f9c11 ("pkg: Allow to get events for all processes.") introduced
support for showing events on the host, however, ig still requires
runc to be installed to work. This requirement doesn't make sense anymore
as one could want to get host events without having any container.
This commit makes the container-hook initialization optional for the ig
case, instead of error it prints out a warning message. 
0. Get a system without runc installed (I used vagrant with "ubuntu/mantic64")
```bash
$ runc
Command 'runc' not found, but can be installed with:
apt install runc
Please ask your administrator.
```
```bash
$ sudo ./ig trace open --host
Error: initializing operators: initializing operator "LocalManager": initializing manager: starting container fanotify: no container runtime can be …
```
=> ig: Make container-hook optional

cmd/common/registry.go, cmd/common/utils/parser.go, cmd/ig/containers/containers.go, docs/gadgets/common-features.md, integration/run_helpers.go
This PR add support for relative columns and expanding `runtime` and `k8s` columns. 
Fixes: #1881 #737
```
→ sudo ./ig trace open -o columns=+uid
RUNTIME.CONTAINERNAME                                                         PID        COMM             FD       ERR PATH                                                                              UID       
minikube-docker                                                               448161     cri-dockerd      12       0   /etc/cni/net.d                                                                    0         
minikube-docker                                                               448161     cri-dockerd      12       0   /etc/cni/net.d/1-k8s.conflist                                                     0  
```
```
→ sudo ./ig …
```
=> cmd: Relative columns and expanding runtime/k8s

.github/workflows/inspektor-gadget.yml, Makefile, README.md, cmd/common/registry.go, cmd/common/sync.go, cmd/common/version.go, cmd/gadgetctl/main.go, cmd/ig/daemon.go, cmd/ig/main.go, cmd/kubectl-gadget/deploy.go, cmd/kubectl-gadget/main.go, cmd/kubectl-gadget/version.go, docs/ig.md, gadget-container/gadgettracermanager/main.go, pkg/gadget-service/api/consts.go, pkg/gadget-service/service.go, pkg/runtime/grpc/grpc-runtime.go, pkg/runtime/grpc/info.go, pkg/runtime/grpc/k8s-exec-dialer.go, pkg/runtime/grpc/option.go
This adds support to run `ig` in daemon mode as a service. A new binary called `gadgetctl` has been added to serve as a client for `ig` running in said daemon mode. By default, ig listens on a unix socket when started with `./ig daemon` and `gadgetctl` uses that same socket to connect to by default.
The `grpc-runtime` has been changed to also allow direct gRPC connections - still: most of the code is shared.
```bash
./ig daemon
```
```bash
./gadgetctl trace open
```
Use the gid of a group that you want to have access to the service.
```bash
./ig daemon --daemon-group 1000
```
```bash
./gadgetctl trace open
```
---
Resolves #1681
Requires #2067
=> ig: add daemon mode

pkg/runtime/grpc/grpc-runtime.go, pkg/runtime/grpc/info.go
Refactor the code a bit to allow the caller to close the connection.
Fixes: 2a15d06e4d73 ("pkg/runtime/grpc: add support for direct gRPC connections")
=> runtimes/grpc: Fix connection leakage

Makefile, cmd/common/image/build.go, docs/images.md, gadgets/Makefile
Rename from ghcr.io/inspektor-gadget/inspektor-gadget-ebpf-builder to ghcr.io/inspektor-gadget/ebpf-builder as "inspektor-gadget" is redundant.
---
I pushed the image manually, however it should be automatically pushed once https://github.com/inspektor-gadget/inspektor-gadget/issues/1420 is fixed.
=> Rename ebpf builder image

cmd/common/image/build.go, cmd/common/image/list.go, cmd/common/image/pull.go, cmd/common/image/push.go, cmd/common/image/tag.go, pkg/gadgets/run/tracer/run.go, pkg/gadgets/run/tracer/tracer.go, pkg/oci/build.go, pkg/oci/oci.go, pkg/oci/oci_test.go
This is a complete refactoring of the oci package. The whole idea is to implement all the OCI related functionalities we need in this package, avoiding other parts of the code having to interact with packages like "github.com/docker" or "oras.land/oras-go/v2".
The reasoning behind is:
- We can concentrate all OCI related code in the same place
- It's a lot easier to test if it's a separated package
This package now provides methods for pulling, pushing, tagging and building OCI images. Other methods that we previously exposed are now internal.
This commit also:
- Uses -ing in all error messages
- Small esthetic changes to cmd/*
NOTE: Ideally this should be multiple commits, but it's rather difficult to split a refactor like it into smaller pieces.
=> Refactor pkg/oci

docs/crds/gadgets/ebpftop.md, docs/crds/gadgets/filetop.md, integration/ig/k8s/list_containers_test.go, integration/ig/k8s/profile_cpu_test.go, integration/ig/k8s/snapshot_process_test.go, integration/ig/k8s/top_file_test.go, integration/ig/k8s/top_tcp_test.go, integration/ig/k8s/trace_dns_test.go, integration/ig/k8s/trace_network_test.go, pkg/container-collection/container-collection.go, pkg/container-collection/options.go, pkg/container-utils/containerd/containerd.go, pkg/container-utils/cri/cri.go, pkg/container-utils/runtime-client/runtimeclient_test.go, pkg/types/types.go
This PR adds `ContainerImageDigest` column to initial events of cri-o and containerd containers. 
New containers enrichment is currently blocked because of image digest missing from OCI annotations. Will be cared of in a future iteration.
`RUNTIME.CONTAINERIMAGEDIGEST` column is by default hidden and can be manually added with `ig list-containers -o custom-columns=runtime.containerimagename,runtime.containerimagedigest`
Part of #1310
=> Enrich events with image digest

cmd/common/registry.go
resolves #2005
When we don't specify an oci image the `run` gadget still tried to show all available columns. For this it has to look into the BTF code stored in the oci image.
To resolve the problem this PR implements the following behavior:
1. If no oci image is given the help is printed without any columns. Additionally the message `To see available columns for a specific gadget image, the oci image needs to specified as an argument` will be shown in the help output (See Testing done)
2. If a valid oci image is given, the help behaves like always did
3. If an invalid oci image is given, the help prints an error if the oci image url is malformed, can't be found, ....
```bash
➭ go run --exec "sudo -E" ./cmd/ig/... run --help
Run a …
```
=> run: Show help even if no oci image was given

go.mod
We don't depend on bumblebee anymore, remove this directive.
=> go.mod: Remove replace directive for bumblebee

Dockerfiles/ig.Dockerfile
Fixes: 2020655 ("cmd/common: move version and sync command")
```
$ make ig
$ ./ig version
undefined
```
```
$ make ig
$ ./ig version
v0.21.0-49-g2093eb7c
```
=> Dockerfiles: Fix versioning for ig

cmd/common/registry.go
Fix panic if no args are provided to `run`
```
→ go run -exec 'sudo -E' ./cmd/ig run
panic: runtime error: index out of range [0] with length 0
github.com/inspektor-gadget/inspektor-gadget/pkg/gadgets/run/tracer.(*GadgetDesc).GetGadgetInfo(0xc0008393e0?, 0x452c6b0?, {0x5d93d70, 0x0, 0x4?})
/home/qasim/work/github.com/inspektor-gadget/inspektor-gadget/pkg/gadgets/run/tracer/run.go:86 +0x259
github.com/inspektor-gadget/inspektor-gadget/pkg/runtime/local.(*Runtime).GetGadgetInfo(0x1ae6007?, {0x410b3b8?, 0x3992320?}, {0x452c6b0, 0x5d93d70}, 0x4?, {0x5d93d70, 0x0, 0x0})
/home/qasim/work/github.com/inspektor-gadget/inspektor-gadget/pkg/runtime/local/local.go:90 +0x7c …
```
=> run: Fix panic if no flags are provided

cmd/ig/daemon.go, cmd/kubectl-gadget/deploy.go, cmd/kubectl-gadget/main.go, gadget-container/gadgettracermanager/main.go, pkg/gadget-service/api/helpers.go, pkg/runtime/grpc/grpc-runtime.go, pkg/runtime/grpc/info.go, pkg/runtime/grpc/k8s-exec-dialer.go, pkg/runtime/grpc/k8s-portfwd-dialer.go
This PR changes the default connection method used by `kubectl-gadget` to connect to the gadget-service running on the `gadgettracermgr`.
Until now, we executed a `socat` binary (using the exec method of the Kubernetes API server) inside the gadget pod to be able to forward gRPC traffic to a unix socket, to be able to talk to the gRPC endpoint of the gadget-service.
After this PR, the gadget-service will listen on a tcp socket by default (127.0.0.1:8080) and `kubectl-gadget` will connect to it using the port-forward method of the Kubernetes API server.
The reason that we used a unix socket in the past, was to properly secure the socket. As the gadget pod was running in the host network namespace, running our service on a tcp port would have exposed it on the host, making it accessible …
=> kubectl-gadget/ig-k8s: change connection to gadget service from exec to port-forward

.github/workflows/inspektor-gadget.yml
Fixes: #1420
It uses the same idea of #1472 and will only:
- Build images if changes are detected
- Publish images if variable `PUSH_HELPERS = ENABLE_PUSH_HELPERS` is defined (it helps avoid issues with external contributors PR)
- Publish images for each release
- Fork: A [test commit](https://github.com/mqasimsarfraz/inspektor-gadget/commit/33523afbb00c11be79102946f0d876bd033b56c8) result in helper [image being built](https://github.com/mqasimsarfraz/inspektor-gadget/actions/runs/6482505619/job/17602162537) and used [here](https://github.com/mqasimsarfraz/inspektor-gadget/actions/runs/6482505619/job/17602170043#step:4:1).
- Release: A test release (`v0.10.0`) publish the tags [here](https://github.com/mqasimsarfraz/inspektor-gadget/pkgs/container/ebpf-builder/versions).
=> ci: Publish ebpf builder helper image

pkg/container-collection/options.go, pkg/utils/host/namespaces.go
Resolve a panic issue when getting an unavailable host namespace. Add error format to two functions: `WithLinuxNamespaceEnrichment` and `isHostNamespace`.
Fixes #1858
=> fix: panic issue due to unavailable host network namespace inode

pkg/gadgets/run/types/types.go
Remove this field to avoid confusion on the code.
=> run/types: Remove unused field

pkg/columns/formatter/json/json.go, pkg/columns/formatter/json/json_test.go, pkg/gadgets/run/tracer/run.go
075f2b1e4fd9 ("pkg/columns: add json formatter") implemented a function
to marshal a single entry to json using the columns information. This
commit introduces a new function to marshal a slice of entries to a
json array.
---
This was initially proposed in https://github.com/inspektor-gadget/inspektor-gadget/pull/1866, but since merging that PR is taking a bit long, I decided to extract some commits in a separated PR to help with the review process.
=> pkg/columns/json: Implement FormatEntries()

.github/workflows/inspektor-gadget.yml, Dockerfiles/ig.Dockerfile, Makefile, cmd/common/image/build.go
As mentioned in the comment [here](https://github.com/inspektor-gadget/inspektor-gadget/pull/2135#pullrequestreview-1671244664), this PR will ensures that the `image build` command refers to versioned ebpf-builder for each release.
As per implementation, the `ebpf-builder` image name is only set for releases so it will keep using `DEFAULT_EBPF_BUILDER_IMAGE: ghcr.io/inspektor-gadget/ebpf-builder:latest` for all other cases.
- Did a [test release](https://github.com/mqasimsarfraz/inspektor-gadget/actions/runs/6508344397) (v0.13.0) on the fork and [resulting binary](https://github.com/mqasimsarfraz/inspektor-gadget/suites/17192548593/artifacts/982522014) are showing the correction version:
```
→ sudo -E ./ig image build -h
Build a …
```
=> image: Use release image for ebpf-builder

Makefile
Before this commit:
```
make: ../tools/image-tag: Command not found
KUBECTL_GADGET="/home/mvb/kinvolk/ebpf/inspektor-gadget/kubectl-gadget" \
go test ./integration/inspektor-gadget/... \
-v \
-integration \
-timeout 30m \
-k8s-distro "" \
-k8s-arch amd64 \
-image ghcr.io/inspektor-gadget/inspektor-gadget:latest \
-dnstester-image "ghcr.io/inspektor-gadget/dnstester:latest" \
-gadget-repository ghcr.io/inspektor-gadget/gadget \
-gadget-tag  \
$INTEGRATION_TESTS_PARAMS
flag needs an argument: -gadget-tag
```
Fixes: 145f7570b1f9 ("gadgets: Build OCI images instead of objects")
=> Makefile: Fix gadget tag calculation

pkg/gadgets/run/tracer/run.go
Fixes #2142 
This commit allows the `insecure` flag to be passed to the `run` command, which in turn, allows connections to HTTP-only registries.
`./kubectl-gadget run 192.168.1.150:5000/gadget/foo:latest --insecure `
I ran `./kubectl-gadget run 192.168.1.150:5000/gadget/foo:latest` and did not get `Error: unknown flag: --insecure`
=> add insecure flag to run command

integration/ig/k8s/list_containers_test.go, integration/ig/k8s/trace_bind_test.go, integration/ig/k8s/trace_capabilities_test.go, integration/ig/k8s/trace_dns_test.go, integration/ig/k8s/trace_exec_test.go, integration/ig/k8s/trace_fsslower_test.go, integration/ig/k8s/trace_mount_test.go, integration/ig/k8s/trace_oomkill_test.go, integration/ig/k8s/trace_open_test.go, integration/ig/k8s/trace_signal_test.go, integration/ig/k8s/trace_sni_test.go, integration/ig/k8s/trace_tcp_test.go, integration/ig/k8s/trace_tcpconnect_test.go, integration/ig/non-k8s/list_containers_test.go, integration/ig/non-k8s/snapshot_process_test.go, integration/ig/non-k8s/trace_dns_test.go, integration/ig/non-k8s/trace_network_test.go, pkg/container-utils/containerd/containerd.go, pkg/types/types.go
This PR adds `ContainerImageDigest` to events coming from new containerd containers.
It also partly implements #1911 by introducing `getBasicRuntimeMetadata` to remove code duplication in `GetContainer` and  `taskAndContainerToContainerData`.
=> containerd: Enrich events from new containers with imageDigest

Dockerfiles/ebpf-builder.Dockerfile, cmd/common/image/Makefile.build, cmd/common/image/build.go, docs/images.md, gadgets/trace_dns/build.yaml, gadgets/trace_dns/go.mod, gadgets/trace_dns/go.sum, gadgets/trace_dns/program.go, pkg/oci/build.go
This PR adds the possibility to add a wasm module in a gadget image.
There are no changes in the CLI flags. This can be used by adding an entry in `build.yaml`:
```
wasm: program.go
```
The following file types are supported:
* `*.wasm`: pre-compiled wasm module
* `*.go`: Inspektor Gadget will compile it with tinygo
The wasm module is not executed. This will be for the next PRs.
```
docker build -f Dockerfiles/ebpf-builder.Dockerfile -t ghcr.io/inspektor-gadget/ebpf-builder:alban_wasm2 .
sudo -E ig image build --builder-image=ghcr.io/inspektor-gadget/ebpf-builder:alban_wasm2 -t ghcr.io/inspektor-gadget/gadget/trace_dns:test gadgets/trace_dns/
sudo -E ig run ghcr.io/inspektor-gadget/gadget/trace_dns:test
```
As above.
=> image build: add wasm

pkg/gadgets/run/tracer/run.go, pkg/oci/build.go
As mentioned in the artifact usage [1] of image spec, if we don't have config we should use an empty descriptor [2]. This should avoid running into issues when pushing the images to registry since most of them [don't support](https://github.com/opencontainers/image-spec/issues/1025) "no config" option.
[1] - https://github.com/opencontainers/image-spec/blob/main/manifest.md#guidelines-for-artifact-usage
[2] - https://github.com/opencontainers/image-spec/blob/main/manifest.md#guidance-for-an-empty-descriptor
```
→ sudo rm -rf /var/lib/ig
→ DIR=$(mktemp -d)
→ cp gadgets/trace_open/program.bpf.c $DIR
→ go run -exec "sudo -E" ./cmd/ig image build -t localhost:5000/trace_open:latest $DIR
Successfully built …
```
=> image: Use empty descriptor if no metadata file is provided

cmd/common/utils/flags.go, cmd/gadgetctl/main.go, cmd/kubectl-gadget/main.go
When connecting to a server we need to have informations about the connection itself. That is why we parse the flags as early as possible. Even before we have all of them available, because the flags are derived from the servers information.
This commit enableds the option to ignore unknown flags on this early flag parsing, so we can get information on the connection flags without erroring out.
Run `ig` in daemon mode in a terminal:
```bash
$ sudo -E ./ig daemon -H tcp://127.0.0.1:9999
```
Open a new terminal and do the following:
```bash
$ rm ~/.ig/info.json
$ ./gadgetctl top file --all-files --remote-address tcp://127.0.0.1:9999
WARN[0005] could not load gadget info from remote: dialing random target: dialing "unix:///var/run/ig/ig.socket" ("local"): dialing …
```
=> cmd: Ignore unknown flags when parsing params early

gadgets/trace_dns/gadget.yaml, gadgets/trace_tcpretrans/gadget.yaml, pkg/gadgets/run/types/metadata.go
Gadgets were failing with the following error:
Error: calling custom parser: getting columns: adding fields: duplicate column name "netns"
This commit workaround that by disabling the netns column until a proper fix is implemented.
=> gadgets: Fix trace_dns and trace_tcpretrans failing to run

pkg/gadgets/run/tracer/run.go, pkg/gadgets/run/types/types.go, pkg/oci/oci.go
- `--pull missing` (default) only pulls the image when it is missing
- `--pull always` Pulls always
- `--pull never` Never pulls
The pull policy behavior is the same as Docker, but not the same as for K8s. For K8s in the default case the pull policy is missing, except when the `latest` tag is used. Then it is always pulling
Fixes #2101 
Slack Discussion: https://kubernetes.slack.com/archives/CSYL75LF6/p1697722813839619
=> run: Add pull policy `--pull` flag 

gadgets/snapshot_process/gadget.yaml, gadgets/trace_dns/gadget.yaml, gadgets/trace_dns/program.bpf.c, gadgets/trace_exec/gadget.yaml, gadgets/trace_exec/program.bpf.c, gadgets/trace_open/gadget.yaml, gadgets/trace_open/program.bpf.c, gadgets/trace_tcpconnect/gadget.yaml, gadgets/trace_tcpconnect/program.bpf.c, gadgets/trace_tcpretrans/gadget.yaml, gadgets/trace_tcpretrans/program.bpf.c, include/gadget/types.h, integration/inspektor-gadget/run_snapshot_process_test.go, integration/inspektor-gadget/run_trace_open_test.go, integration/run_helpers.go, pkg/gadgets/run/tracer/run.go, pkg/gadgets/run/tracer/tracer.go, pkg/gadgets/run/types/metadata.go, pkg/gadgets/run/types/types.go
This PR fixes different issues with those columns. Please check each commit to have more details.
Compile and run the trace_exec gadget, now the timestmap and mount ns id columns are present and have the right value:
```bash
$ sudo -E ig run exec -o columns=+timestamp,-uid,-gid,+mntns_id
RUNTIME.CONTAINERNAME              PID                PPID               COMM             RETVAL             TIMESTAMP                           MNTNS_ID     
blissful_payne                     361269             301887             wget             0                  2023-10-30T17:29:22.226031553-05:00 4026536859   
blissful_payne                     361272             301887             wget             0 …
```
=> run: Fix timestamp, mount and net ns columns

cmd/ig/main.go
Use ParseEarlyFlags() on main to be sure flags from the host package are parsed when host.Init() is called.
Deploy https://github.com/inspektor-gadget/inspektor-gadget/blob/main/docs/examples/pod-ig.yaml
(be sure the nodeName is removed or updated and the image used is the right one, main or compiled from this branch)
```bash 
$ kubectl logs ig
error: filesystems tracefs not mounted (did you try --auto-mount-filesystems?)
```
Tracer prints events as expected
=> ig: Fix host.Init() workaround flags

cmd/ig/main.go
This reverts commit 92e0a1864227dd0f1eee3336b4adeaaa9980cb15.
This somehow broke the CI https://github.com/inspektor-gadget/inspektor-gadget/actions/runs/6721665482. It's not clear why, so let's revert this and make the release.
=> Revert "ig: Fix host.Init() workaround flags"

cmd/common/utils/flags.go, cmd/ig/main.go
If we try to shrink args (to drop '--sort ...') e.g from `top file --sort -writes -m 10 --timeout 10 --interval 10` we end up reusing the underlying array and hence the original os.Args end up getting modified resulting in `top file -m 10 --timeout 10 --interval 10 --interval 10`. The commit clones the slice to ensure os.Args stay untouched and evaluated correctly later on.
```
→ ./kubectl-gadget  snapshot process --sort pid  --all-namespaces
K8S.NODE                                   K8S.NAMESPACE                             K8S.POD                                   K8S.CONTAINER                             COMM             PID                  UID        GID       
minikube-docker                            gadget                                    gadget-76f66 …
```
=> flags: Clone to avoid modifying os.Args

.github/workflows/inspektor-gadget.yml, .golangci.yml, Dockerfiles/ebpf-builder.Dockerfile, Dockerfiles/gadget.Dockerfile, Dockerfiles/ig-tests.Dockerfile, Dockerfiles/ig.Dockerfile, Dockerfiles/kubectl-gadget.Dockerfile, cmd/common/utils/flags.go, docs/install.md, examples/kube-container-collection/Dockerfile, examples/runc-hook/Dockerfile, go.mod, go.sum, pkg/container-collection/match.go, tools/dnstester/Dockerfile, tools/testjson2md/go.mod
As discussed in the comment [here](https://github.com/inspektor-gadget/inspektor-gadget/pull/2195#discussion_r1381991808) the pros/cons of updating to golang 1.21:
>  I think 1.21 with its maps and slices packages and the new min() and max() funcs alone are worth the upgrade as we use those things constantly. And this is timed just after a release, so there's plenty of time ahead of us to make sure it's running well. So my opinion is: go for it.
>
>  The release notes state that Go 1.21 no longer runs on Win 7 & 8 and older MacOS versions, but I don't know if the binaries it produces are affected as well - we should check for that and maybe add that to the release notes.
We can continue the reviews and feedback separately from https://github.com/inspektor-gadget/inspektor-gadget/pull/2195
=> treewide: Update to golang 1.21

CODE_OF_CONDUCT.md, docs/devel/CONTRIBUTING.md
Update to the CNCF CoC now that we're a CNCF project.
Adds the top-level file so that Github picks it up and shows that we have a CoC.
=> Update code of conduct to the CNCF CoC

pkg/gadgets/trace/open/types/types.go
TL;DR: We're missing the extractor for the flags and they were always
empty in the columns representation.
Before this commit:
```bash
$ sudo ig trace open -o columns=flags
FLAGS
// ^^^^ empty entries
```
After this commit:
```bash
$ sudo ig trace open -o columns=flags
FLAGS
O_RDONLY|O_CLOEXEC
O_RDONLY|O_CLOEXEC
O_RDONLY|O_CLOEXEC
O_RDONLY|O_CLOEXEC
O_RDONLY|O_CLOEXEC
```
Long story:
3c9916449a05 ("pkg: Add support for flags for trace open.") introduced
support for the flag column but it didn't define a custom extractor, at 
that time the column was formatted as:
```bash
sudo ig trace open -o columns=flags
FLAGS
[O_RDONLY O_CLOEXEC]
[O_RDONLY O_CLOEXEC]
[O_RDONLY O_CLOEXEC]
[O_RDONLY O_CLOEXEC]
[O_RDONLY O_CLOEXEC]
[O_RDONLY O_CLOEXEC]
```
Later on, 5ad73284af88 ("pkg/columns: add support …
=> trace/open: Add missing extractor for flags

cmd/common/registry.go, cmd/common/utils/flags.go, cmd/gadgetctl/main.go, cmd/ig/main.go, cmd/kubectl-gadget/main.go, integration/inspektor-gadget/run_insecure_test.go, integration/inspektor-gadget/run_trace_open_test.go
d1bccf6c124f ("gadgets/run: Support eBPF parameters") introduced a logic to remove the flags before calling GetGadgetInfo(), unfortunately it also broke the --authfile/--insecure flags as they were removed.
This commit changes the approach to use ParseEarlyFlags() to parse flags that are already known before contacting the server, like --insecure & --authfile, so they can be used by the server while it executes GetGadgetInfo().
Fixes: d1bccf6c124f ("gadgets/run: Support eBPF parameters")
Fix https://github.com/inspektor-gadget/inspektor-gadget/issues/2225
0. Push a gadget to a insecure registry. https://github.com/inspektor-gadget/inspektor-gadget/issues/2225 contains instructions for it. In my case I pushed it to 192.168.1.150:5000/foo:latest
I manually tested the following:
```bash
sudo …
```
=> cmd: Fix --authfile/--insecure flags

integration/command.go, integration/inspektor-gadget/run_insecure_test.go
Adds two functions to help in the integration tests:
1. `JobCommand` to create jobs
2. `WaitUntilJobCompleteCommand` which waits until the job completes
=> [integration-tests] Add helpers for Jobs 

charts/gadget/templates/daemonset.yaml, charts/gadget/templates/role.yaml, charts/gadget/templates/rolebinding.yaml, charts/gadget/values.yaml, cmd/kubectl-gadget/deploy.go, docs/gadgets/run.md, gadget-container/entrypoint/entrypoint.go, pkg/gadgets/run/tracer/run.go, pkg/oci/oci.go, pkg/resources/manifests/deploy.yaml
Currently there isn't a way to run gadgets from private registry in Kubernetes. This change mounts/symlinks the registry credentials to allow pulling gadgets from private registries. The flag `gadgetPullSecret` is inspired from [`imagePullSecrets`](https://kubernetes.io/docs/concepts/containers/images#specifying-imagepullsecrets-on-a-pod). 
Fixes: #2096 
```bash
$ kubectl create ns gadget
$ kubectl create secret -n gadget docker-registry gadget-pull-secret --from-file=.dockerconfigjson=$HOME/.docker/config.json
$ ./kubectl-gadget deploy --image-pull-policy Never
$ ./kubectl-gadget run qasimregistry.azurecr.io/gadget/trace_open:latest -A
```
```bash
$ kubectl create ns gadget
$ kubectl create secret -n gadget docker-registry gadget-pull-secret …
```
=> image-based-gadgets: Introduce gadget pull secret

pkg/gadgets/run/tracer/tracer.go
All of this started while investigating [this comment](https://github.com/inspektor-gadget/inspektor-gadget/pull/2248#pullrequestreview-1757941868), which refers to https://github.com/inspektor-gadget/inspektor-gadget/issues/2108. I found that we weren't releasing the network tracer, and then I found that the issue was worst and we're not releasing any programs at all when running image-based gadgets.
Before running any gadget, there are some programs and maps in the node:
```bash
$ sudo bpftool prog list --json | jq length
28
$ sudo bpftool map list --json | jq length
40
```
Run a gadget, and terminate it as soon as it prints some events.
```bash
$ ./kubectl-gadget run ghcr.io/inspektor-gadget/gadget/trace_exec:latest -A
... // ctrl + C
```
The number of open programs and maps increased: …
=> run: Fix a lot of leakages and implement support for multiple socket filter programs

README.md, cmd/common/image/build.go, cmd/common/image/image.go, cmd/common/image/list.go, cmd/common/image/pull.go, cmd/common/image/push.go, cmd/common/image/tag.go, cmd/common/login.go, cmd/common/logout.go, cmd/common/registry.go, cmd/common/utils/experimental.go, cmd/ig/main.go, pkg/gadgets/interface.go, pkg/gadgets/run/tracer/run.go, pkg/gadgets/run/tracer/tracer.go
This commit changes the logic to show the experimental commands on the CLI even if the experimental mode is not enabled. This allows these commands to have a better discoverability.
Experimental commands are shown:
```bash
$ sudo ig
Collection of gadgets for containers
...
image           Manage gadget images (experimental)
...
login           Login to a container registry (experimental)
logout          Logout of a container registry (experimental)
...
run             Run a containerized gadget (experimental)
```
and their help
```bash 
$ sudo ig login -h
Login to a container registry on a specified server.
Usage:
ig login [command options] REGISTRY [flags]
...
$ sudo ig run -h
Run a containerized gadget (experimental)
Usage:
ig run [flags]
... 
```
but they can't be run:
```bash
$ sudo …
```
=> Show experimental commands in all cases

charts/gadget/templates/_helpers.tpl, cmd/common/image/push.go, cmd/kubectl-gadget/advise/advise.go, cmd/kubectl-gadget/advise/network-policy.go, cmd/kubectl-gadget/advise/seccomp-profile.go, cmd/kubectl-gadget/debug.go, cmd/kubectl-gadget/deploy.go, cmd/kubectl-gadget/deploy_test.go, cmd/kubectl-gadget/main.go, cmd/kubectl-gadget/traceloop.go, cmd/kubectl-gadget/undeploy.go, cmd/kubectl-gadget/utils/consts.go, cmd/kubectl-gadget/utils/exec.go, cmd/kubectl-gadget/utils/flags.go, cmd/kubectl-gadget/utils/k8s.go, cmd/kubectl-gadget/utils/trace.go, cmd/kubectl-gadget/version.go, docs/install.md, pkg/gadget-service/api/consts.go, pkg/gadgets/consts.go, pkg/gadgets/run/tracer/helpers.go, pkg/gadgets/run/tracer/run.go, pkg/gadgets/run/tracer/tracer.go, pkg/gadgets/runner.go, pkg/oci/oci.go, pkg/runtime/grpc/grpc-runtime.go, pkg/runtime/grpc/k8s-portfwd-dialer.go
This PR implements the deployment of Inspektor Gadget into a custom Kubernetes Namespace
=> Allow IG to deploy into a custom namespace

pkg/gadget-service/api/api.proto, pkg/gadgets/run/tracer/run.go, pkg/gadgets/run/tracer/tracer.go, pkg/gadgets/run/types/factory.go, pkg/gadgets/run/types/types.go
This commit changes the logic to avoid the client having to decode BTF information. The whole idea consists on having the "columns descriptors" in the GadgetInfo structure. These descriptors are generated by the server and used by the client to decode the data it receives.
The data is sent as a binary blob [][]byte. The first array is the bpf event, the second one are fixed type fields and the other ones are used for strings. This commit adds some helper methods to add fields to the event.
This commit is an intermediate step in order to enable support for wasm. The next work is to start using it from operators to decouple them from the tracer implementation.
Fixes https://github.com/inspektor-gadget/inspektor-gadget/issues/2131
I rebased #2204 on top of this in …
=> Avoid decoding BTF on the client

pkg/gadgets/run/tracer/tracer.go
Also use FixBpfKtimeGetBootNs() in the run command to fix eBPF programs before loading them. 
Use a kernel that doesn't have `BPF_FUNC_ktime_get_boot_ns`:  < 5.8 https://github.com/torvalds/linux/commit/71d19214776e61b33da48f7c1b46e522c7f78221
```bash
$ sudo -E ./ig run ghcr.io/inspektor-gadget/gadget/trace_exec:latest
RUNTIME.CONTAINERNAME                       PID                     PPID                   COMM             UID                    GID                    RET…
Error: running gadget: running gadget: install tracer: loading eBPF objects: create BPF collection: program ig_execve_e: load program: invalid argument: invalid func unknown#125 (110 line(s) omitted)
```
```bash 
$ sudo -E ./ig run …
```
=> gadgets: Fix timestamp handling in old kernels

pkg/gadgets/snapshot/process/tracer/tracer.go, pkg/runtime/grpc/grpc-runtime.go
- Add missing check on pkg/runtime/grpc/grpc-runtime.go
- Use ParseInt() instead of ParseUint() in pkg/gadgets/snapshot/process/tracer/tracer.go
https://github.com/inspektor-gadget/inspektor-gadget/security/code-scanning/12 
https://github.com/inspektor-gadget/inspektor-gadget/security/code-scanning/13
https://github.com/inspektor-gadget/inspektor-gadget/security/code-scanning/14
Fixes: 2ad8b61b0539 ("pkg: Add bound checks for integer converted by strconv functions.")
=> Fix boundary checks

pkg/operators/common/kubeinventorycache.go, pkg/operators/kubeipresolver/kubeipresolver.go, pkg/operators/kubenameresolver/kubenameresolver.go
Use https://pkg.go.dev/k8s.io/client-go/informers instead of active polling in the `K8sInventoryCache` component.
I don't know exactly how to test this change, help needed here.
=> use client-go informers instead of active polling

pkg/columns/columns.go
The value returned by GetFieldFunc() can be used directly.
Found while reviewing https://github.com/inspektor-gadget/inspektor-gadget/pull/2122.
=> columns: Avoid creating uneeded function

charts/gadget/templates/clusterrole.yaml, pkg/operators/kubeipresolver/kubeipresolver.go, pkg/operators/kubenameresolver/kubenameresolver.go, pkg/resources/manifests/deploy.yaml
After https://github.com/inspektor-gadget/inspektor-gadget/pull/2347 changed the way we keep a up-to-date list of all pods and services (watchers instead of polling) everything seem to work.
IPs get resolved successfully to pod names and service names.
But in the gadget logs we see the following:
`1 reflector.go:147] pkg/mod/k8s.io/client-go@v0.29.0/tools/cache/reflector.go:229: Failed to watch *v1.Service: unknown (get services)`
This PR adds the missing watch permissions for our ServiceAccount.
(I also added logging of the returned errors, but in this case they didn't help at all and logged nothing -> no error)
=> Add `watch` permission for `services`

integration/inspektor-gadget/run_trace_sni_test.go
Fixes: 0f81d1d42fe0 ("integration: Add test for run trace sni")
=> integration: Use correct type for netns.

gadgets/Makefile
Currently, if we fail to push a gadget the loop to push the gadgets continues and we can end up in a situation where we will skip a gadget. This change ensures we exit early as soon as we hit an error. [See](https://github.com/inspektor-gadget/inspektor-gadget/actions/runs/7502979343/job/20427140031#step:7:76)
Following run shows that after this change `make` will exit as soon as it hits the first error.
```
→ make -C gadgets GADGETS="trace_dns trace_exec trace_open" GADGET_REPOSITORY=localhost:5000/gadgets push 
make: Entering directory '/home/qasim/work/github.com/inspektor-gadget/inspektor-gadget/gadgets'
Building trace_dns
Successfully built localhost:5000/gadgets/trace_dns:latest@sha256:65713d9a47dc4fe48d1052630c0786404b126b0181 …
```
=> gadgets/Makefile: Exit on error when pushing gadget

integration/helpers.go, integration/ig/k8s/top_block_io_test.go, integration/inspektor-gadget/advise_networkpolicy_test.go, integration/inspektor-gadget/audit_seccomp_test.go, integration/inspektor-gadget/profile_cpu_test.go, integration/inspektor-gadget/snapshot_process_test.go, integration/inspektor-gadget/snapshot_socket_test.go, integration/inspektor-gadget/top_blockio_test.go, integration/inspektor-gadget/top_ebpf_test.go, integration/inspektor-gadget/top_file_test.go, integration/inspektor-gadget/top_tcp_test.go, integration/inspektor-gadget/trace_bind_test.go, integration/inspektor-gadget/trace_capabilities_test.go, integration/inspektor-gadget/trace_dns_test.go, integration/inspektor-gadget/trace_exec_test.go, integration/inspektor-gadget/trace_fsslower_test.go, integration/inspektor-gadget/trace_mount_test.go, integration/inspektor-gadget/trace_network_test.go, integration/inspektor-gadget/trace_oomkill_test.go, integration/inspektor-gadget/trace_open_test.go, integration/inspektor-gadget/trace_signal_test.go, integration/inspektor-gadget/trace_sni_test.go, integration/inspektor-gadget/trace_tcp_test.go, integration/inspektor-gadget/trace_tcpconnect_test.go
This field is not available in all cases, hence normalize it.
Related https://github.com/inspektor-gadget/inspektor-gadget/issues/2358
=> integration: Normalize ContainerImageDigest in all tests

docs/reference/oci.md, pkg/oci/build.go, pkg/oci/oci.go
The wasm program is now in an OCI layer.
Before this patch, the OCI image had 3 architectures with only one layer each:
1. amd64
2. arm64
3. wasm
After this patch, the OCI image has 2 architectures:
1. amd64
2. arm64
And each architecture has 1 or 2 layers with different media types:
- application/vnd.gadget.ebpf.program.v1+binary
- application/vnd.gadget.wasm.program.v1+binary
This patch initially comes from #2204. But I would like to get it merged early before the rest of #2204 is ready.
This is a potentially breaking change. However, the currently published image-based gadgets don't make use of wasm yet, so no existing gadget shoud break.
=> oci: wasm modules are no longer stored in the wasm architecture

.github/workflows/inspektor-gadget.yml, Makefile, cmd/common/image/build.go, cmd/common/image/list.go, cmd/common/image/pull.go, cmd/common/image/push.go, cmd/common/image/remove.go, cmd/common/image/tag.go, go.mod, integration/components/image/image_test.go, integration/components/image/integration_test.go, integration/helpers.go, pkg/container-utils/testutils/container_interface.go, pkg/container-utils/testutils/containerd.go, pkg/container-utils/testutils/docker.go, pkg/container-utils/testutils/options.go
=> image: Add test for build/list/tag/push/pull/remove

integration/ig/k8s/Makefile, integration/ig/non-k8s/Makefile
Avoid integration tests to remain stuck forever:
- https://github.com/inspektor-gadget/inspektor-gadget/actions/runs/7553752554/job/20565654462?pr=2370
- https://github.com/inspektor-gadget/inspektor-gadget/actions/runs/7546441014/job/20544600632
=> integration: Add timeout for all tests

pkg/gadgets/run/tracer/tracer.go
Symptoms:
```
panic: runtime error: index out of range [1] with length 1
```
Fixes: 07ca0fb4e97a ("Initial support for containerized gadgets")
=> tracepoints: check the section has a group and a name

README.md
See https://www.bestpractices.dev/en/projects/7962
A cncf sandbox requirement, see: https://github.com/cncf/toc/issues/1021
[![OpenSSF Best Practices](https://www.bestpractices.dev/projects/7962/badge)](https://www.bestpractices.dev/projects/7962)
This is a work in progress, we are not yet in the "passing" level.
=> README.md: add OpenSSF Best Practices badge

integration/command.go
We're missing the logs if a gadget pod crashes. Use `--previous` to print logs if the pod had crashed.
---
It happened for instance in https://github.com/inspektor-gadget/inspektor-gadget/actions/runs/7572632543/attempts/1#summary-20624243194.
```bash
command.go:273: Inspektor Gadget pod logs:
command.go:274: + kubectl get pods -n gadget -o wide
NAME           READY   STATUS    RESTARTS      AGE    IP           NODE                      NOMINATED NODE   READINESS GATES
gadget-d4z7x   1/1     Running   1 (39s ago)   109s   10.244.1.2   minikube-containerd-m02   <none>           <none>
gadget-sx6nw   1/1     Running   0             109s   10.244.0.3   minikube-containerd       <none>           <none>
+ kubectl get pods -n gadget -o name
+ kubectl logs -n gadget pod/gadget-d4z7x …
```
=> CI: Print previous logs for gadget pods

integration/ig/k8s/trace_oomkill_test.go, integration/inspektor-gadget/run_trace_oomkill_test.go, integration/inspektor-gadget/trace_oomkill_test.go
It can't be assured that our `tail` process will trigger the oomkill. It could be another process with another uid and gid
Locally I got these multiple of 2 events. One time `tail` triggered the oom and another time `conmon` triggered it
```
{"runtime":{"runtimeName":"cri-o","containerId":"dd176d59db623d05640f601d4d99af0df12b165e0493426cee88039fc44cb779","containerImageName":"docker.io/library/busybox:latest"},"k8s":{"node":"minikube-cri-o","namespace":"test-trace-oomkill-2366462858275538090","podName":"test-pod","podLabels":{"run":"test-pod"},"containerName":"test-pod-container"},"timestamp":1706176347489993010,"type":"normal","mountnsid":4026532886,"kpid":295521,"kcomm":"tail","pages":32768,"tpid":295273,"tuid":0,"tgid":0,"tcomm":"conmon"} …
```
=> integration/TraceOOMKill: Don't check triggered uid & gid

charts/gadget/templates/daemonset.yaml, charts/gadget/values.yaml
Fixes #1885
Removed hardcoded toleration key values from `values.yaml` file and specified them in`daemonset.yaml`.
Now custom tolerations can be added without overwriting the required tolerations.
Tested with emtpy toleration field in values.yaml, and ran command `make template`.
Also tested with other custom values in toleration field in values.yaml and ran `make template` the output yaml file generated specified the additional fields in proper format.
=> [RFE] Added toleration to Inspektor Gadget manifest

pkg/gadgets/trace/exec/tracer/tracer.go
The ebpf code has some optimization to only send the right amount of bytes used to hold the arguments.
(See around L200 in pkg/gadgets/trace/exec/tracer/bpf/execsnoop.bpf.c). bpf2go defines `Args` as `[7680]uint8` and the tracer was using `args := bpfEvent.Args`, hence copying the array. It an issue since it's trying to copy memory outside the sample received from the perf ring buffer.
The issue is easy to reproduce on the local machine (at least on mine):
```bash
$ docker run --rm -it --name myfoo2 docker.io/library/busybox:latest sh -c 'while true; do cat /dev/null; done;'
$ go build ./cmd/ig/ && bash -c 'for i in {1..30}; do sudo ./ig trace exec --cwd --timeout 2 || exit 1; done'
...
myfoo2                          1862038    35334      cat               0   /bin/cat /dev/null …
```
=> trace/exec: Fix crash when using --cwd

go.mod, go.sum, pkg/netnsenter/netnsenter.go, pkg/rawsock/rawsock.go, pkg/utils/netns/netns.go
Use upstream version of netns and move custom functions from
fork to utils package. Once https://github.com/vishvananda/netns/pull/76
is merged we can remove the custom functions and use upstream.
=> Don't use vishvananda/netns fork

pkg/gadgets/trace/dns/tracer/bpf/dns-common.h, pkg/gadgets/trace/dns/tracer/tracer.go, pkg/gadgets/trace/exec/tracer/bpf/execsnoop.h, pkg/gadgets/trace/exec/tracer/tracer.go, pkg/gadgets/trace/open/tracer/bpf/opensnoop.h, pkg/gadgets/trace/open/tracer/tracer.go
Before this change, we cast incoming events from the RawSample byte slice directly to expected types (like in other gadgets). However, in these gadgets, we optimized the data we send in eBPF to reduce load by not sending empty fields. Casting those abbreviated events to the full struct though makes them not backed by memory anymore - and thus unsafe to use. This change adds a new type for each gadget containing only the guaranteed parts that are sent and fills the (dynamic) remainder directly from the RawSample data. In case of changes to the original event layout, these new structs have to be updated as well.
This also fixes an issue with the trace/dns example.
Fixes #2337.
=> trace/dns + trace/exec + trace/open: fix unsafe typecasting

pkg/container-utils/cri/cri.go
panic on enriching some imageRef fields:
panic: runtime error: index out of range [1] with length 1
Based on work from: @burak-ok 
Fixes https://github.com/inspektor-gadget/inspektor-gadget/issues/2413
The patch originally comes from #2398
=> cri: check range before accessing imageRef

.github/actions/prepare-and-publish-test-reports/action.yml, .github/actions/run-integration-tests/action.yml, .github/workflows/inspektor-gadget.yml, tools/store-test-reports.sh, tools/testjson2md/testjson2md.go
Currently, getting overview of test failures in the CI can be challenging. This change addresses that by extending the work we did for summaries and enhances that by storing them to a GitHub page. 
It took inspiration from the `ig-benchmarks` and commits the reports on each change. [Similarly](https://github.com/benchmark-action/github-action-benchmark/pull/216/files), uses `retry` to avoid running into multiple `git push` issue.
Reports: https://inspektor-gadget.github.io/ig-test-reports/
=> integration: Publish aggregate test report summary

docs/devel/ci.md
We don't need the subscription name and ID. Everything can be done just with the ID.
BTW @eiffel-fl, great guide! It worked perfectly.
=> docs/devel/ci: Use only subscription ID to create AKS federated credentials

.github/workflows/inspektor-gadget.yml
Now that we're backporting fixes, we need to run the CI in the release branch too.
=> ci: Enable running tests on release branch

.github/workflows/inspektor-gadget.yml, pkg/gadgets/trace/dns/tracer/bpf/dns-common.h, pkg/gadgets/trace/dns/tracer/tracer.go, pkg/gadgets/trace/exec/tracer/bpf/execsnoop.h, pkg/gadgets/trace/exec/tracer/tracer.go, pkg/gadgets/trace/open/tracer/bpf/opensnoop.h, pkg/gadgets/trace/open/tracer/tracer.go
Backporting d841b4238a6d ("trace/dns + trace/exec + trace/open: fix unsafe typecasting") since it's affecting one of our users: https://kubernetes.slack.com/archives/CSYL75LF6/p1707355332239829. 
Upstream PR: https://github.com/inspektor-gadget/inspektor-gadget/pull/2443
=> [Backport]: trace/dns + trace/exec + trace/open: fix unsafe typecasting

gadgets/Makefile, gadgets/trace_tcpdrop/gadget.yaml, gadgets/trace_tcpdrop/program.bpf.c
Adding the conversion of tcpdrop gadget to the image based version.
We have currently no integration tests for tcpdrop, so created this issue for working on that: https://github.com/inspektor-gadget/inspektor-gadget/issues/2476
```
ubuntu@gifted-rattlesnake:~/go/src/github.com/inspektor-gadget/inspektor-gadget$ sudo -E ./ig run claudiafirstregistry.azurecr.io/gadget:claudia-convert-trace-tcpdrop-gadget
RUNTIME.CONTAINERNAME                SRC                      DST                      STATE                TCPFLAGS            REASON              PID                 UID                 GID                 TASK            
netem                                172.17.0.2:37584         1.1.1.1:20480            2                    2 …
```
=> Add trace_tcpdrop image based gadget

docs/devel/hello-world-gadget.md
The easiest way to create a new gadget is to start from the template repository. This patch adds a reference to it. We keep the documentation to start a gadget from scratch: it is still useful in case the developer already has a git repository for their project.
https://github.com/inspektor-gadget/gadget-template
https://github.com/inspektor-gadget/inspektor-gadget/issues/2382
=> docs: add gadget-template

integration/inspektor-gadget/audit_seccomp_test.go, integration/inspektor-gadget/integration_test.go
The security profile operator is only used by TestAuditSeccomp to install a simple seccomp profile in the cluster. This is an overkill.
This commit uses a simpler approach by copying the profile by using a DaemonSet to the node and disables installing this by default. The code to deploy/undeploy the SPO isn't removed as it could be useful to test the "advise seccomp" gadget in the future.
Some reasons to avoid deploying the SPO are:
- It needs quite a lot of resources
- It takes a lot of time to be deployed
- Some times it fails to be deployed, and also to be cleanup, leaving it running on the cluster
=> integration: Disable installing Security Profile Operator

examples/container-hook/main.go, examples/runc-hook/main.go, pkg/container-hook/tracer.go, pkg/gadgets/internal/networktracer/tracer.go, pkg/gadgets/internal/tchandler/tracer.go, pkg/runcfanotify/runcfanotify.go
1.  Build any of `examples/container-hook` or `examples/runc-hook` examples with -race enable:
```bash 
$ cd examples/container-hook/
$ go build -race .
$ sudo ./container-hook
```
2. Create a container in another terminal
```bash 
$ docker run --rm -it --name myfoo3 busybox:latest
```
The first terminal will show a data race:
```bash 
==================
WARNING: DATA RACE
Write at 0x00c0000aab40 by goroutine 28:
runtime.mapassign_faststr()
/usr/local/go/src/runtime/map_faststr.go:203 +0x0
github.com/inspektor-gadget/inspektor-gadget/pkg/container-hook.(*ContainerNotifier).AddWatchContainerTermination()
/home/mvb/kinvolk/ebpf/inspektor-gadget/pkg/container-hook/tracer.go:333 +0x1b7
github.com/inspektor-gadget/inspektor-gadget/pkg/container-hook.(*ContainerNotifier).watchPidFileIterate() …
```
=> Fix race conditions on container hook and runcfanotify

pkg/gadgets/run/types/metadata.go, pkg/gadgets/run/types/metadata_test.go
When generating the metadata from the eBPF code, the tracer is wrongly created with the map name:
https://github.com/inspektor-gadget/inspektor-gadget/blob/dfaeb2992e1ab7ad7316b241e18845e573232e26/pkg/gadgets/run/types/metadata.go#L438
It is clear in the `TestPopulate/1_tracer_1_struct_from_scratch` unit tests as it expects an "events" tracer:
https://github.com/inspektor-gadget/inspektor-gadget/blob/dfaeb2992e1ab7ad7316b241e18845e573232e26/pkg/gadgets/run/types/metadata_test.go#L335-L340
When the eBPF code defines a "test" tracer:
https://github.com/inspektor-gadget/inspektor-gadget/blob/dfaeb2992e1ab7ad7316b241e18845e573232e26/testdata/populate_metadata_1_tracer_1_struct_from_scratch.bpf.c#L22
Remove the metadata file of any of out image-based gadgets, build it with the …
=> run: Populate tracers with the correct name

.github/workflows/inspektor-gadget.yml
We were using a specific version for docker buildx to have support for adding annotaions ( https://github.com/docker/buildx/pull/1965). But it has been released into stable already so removing workaround. You can confirm that `docker/setup-buildx-action@v3` uses [`v0.12.0+` by default now.](https://github.com/inspektor-gadget/inspektor-gadget/actions/runs/7903715108/job/21572292303#step:4:109)
=> ci: unpin docker buildx version

.github/workflows/inspektor-gadget.yml, docs/devel/ci.md, integration/inspektor-gadget/advise_networkpolicy_test.go, integration/inspektor-gadget/integration_test.go, integration/inspektor-gadget/top_ebpf_test.go, integration/inspektor-gadget/trace_network_test.go
This change allows running integration tests on GKE. It uses OIDC to authenticate with GCP similar to other cloud providers. Following are the successful runs:
- (amd64): https://github.com/inspektor-gadget/inspektor-gadget/actions/runs/7901941522/job/21566707127
- (arm64): https://github.com/inspektor-gadget/inspektor-gadget/actions/runs/7901941522/job/21566707426
In case you want to see logs for the tests that I have skipped (happy to have more feedback on this, also [potential fix](https://github.com/inspektor-gadget/inspektor-gadget/pull/2280#issuecomment-1939672769)):
- https://github.com/inspektor-gadget/inspektor-gadget/actions/runs/7900722522/attempts/1#summary-21563030071
- https://github.com/inspektor-gadget/inspektor-gadget/actions/runs/7887098920/attempts/2#summary-21523122919 …
=> ci: Run integration test on GKE

pkg/utils/host/workarounds.go
If there is an error calling statfs on the path, for instance, it doesn't exist, the logic should continue without erroring out to suggest using "--auto-mount-filesystems"
Fixes: 073bcd016837 ("auto-mount-filesystems: add alternative path for tracefs")
Create a privileged container without mounting tracefs nor debugfs from the host:
```bash
$ docker run --privileged -it --rm -v $(pwd):/ig ubuntu:22.04 bash
```
```bash 
$ /ig/ig trace exec --host
error: statfs /sys/kernel/debug/tracing: no such file or directory
```
```bash 
$ /ig/ig trace exec --host
error: filesystems debugfs, tracefs not mounted (did you try --auto-mount-filesystems?)
```
=> Fix auto-mount-filesystems

docs/examples/pod-ig.yaml, docs/ig.md, pkg/utils/host/host.go
Inspektor Gadget requires some filesystems to be mounted in order to work (bpffs, tracefs and debugfs). a65dbbc6bcfd ("host package: workarounds for kubectl-debug and Windows") introduced a way to mount those filesystems automatically, however the logic wasn't enable by default on ig.
This commit enables that logic by default when running inside a container (HOST_ROOT is passed). This helps users to run ig inside a container without having to worry about passing all the mounts from the host.
After this commit, ig can be run as:
docker run --privileged -it --rm -v /:/host -e HOST_ROOT=/host -v /run:/run ig_image trace exec
The logic is still disabled by default when running in the host because we don't want to change the system configuration without making the user aware.
--- 
@alban  what …
=> Mount filesystems by default when running in a container

pkg/gadgets/run/tracer/tracer.go, pkg/gadgets/run/types/metadata.go
```
GetTracerInfo gets the tracer information from what was defined by
the GADGET_TRACER macro. However, such macro is optional, so we
must not rely on it. Additionally, by the time
handleTracerMapDefinition() is called, the metadata was already
built (either from the metadata file or from the eBPF code), so we
can get the tracer information from there.
```
=> pkg/run: Don't rely on GADGET_TRACER as it is optional

docs/core-concepts/images.md, docs/devel/hello-world-gadget.md
This PR makes two changes to the build documentation:
1. Update fields that can be specified in the `build.yaml` file.
2. Add reference to the build customization in the hello-word-gadget file.
=> docs: Update image build documentation

.krew.yaml
The gadget kubectl plugin is published on krew-index and is automatically published on Artifact Hub:
https://artifacthub.io/packages/krew/krew-index/gadget
This patch adds the annotations as documentated here: https://artifacthub.io/docs/topics/annotations/krew/
So that the Artifact Hub page for the gadget kubectl plugin includes more information at the next release.
=> krew plugin: add artifacthub annotations

docs/reference/oci.md, pkg/gadgets/run/types/metadata.go, pkg/gadgets/run/types/metadata_test.go, pkg/oci/build.go
OCI images can have annotations at different levels:
- index
- manifest
- config
- layer
This patch adds annotations in the index, manifest and config levels.
artifacthub reads annotations at the manifest level. The 3 required annotations from artifacthub are defined:
- io.artifacthub.package.readme-url
- org.opencontainers.image.created
- org.opencontainers.image.description
Users can add custom images with the `annotations` field in gadget.yaml.
https://github.com/inspektor-gadget/inspektor-gadget/issues/2175
=> image build: add annotations in OCI image

pkg/oci/oci.go
This adds a couple of exported helper functions for an ongoing refactoring (#2512) - this helps giving more control over image handling from inside other packages.
=> pkg/oci: add some helper functions for more control over image handling

integration/ig/k8s/trace_fsslower_test.go, integration/inspektor-gadget/trace_fsslower_test.go
Look open event instead of read to avoid failing due to https://github.com/inspektor-gadget/inspektor-gadget/issues/2554.
=> tests: Update fsslower to look for open event instead of read

pkg/gadgets/helpers.go, pkg/gadgets/helpers_all.go
This just moves the `FromCString()` helper from a file that is gated by build flags to one that is not.
Part of #2512
=> pkg/gadgets: make FromCString() function available to non-gadget builds as well

pkg/columns/columns.go
This prevents panics if `getStart()` returns a nil pointer. While this should not happen under normal circumstances, this adds another safety mechanism for handling untrusted data coming from image based gadgets.
Part of #2512
=> pkg/columns: add safety mechanism for dynamically added columns

pkg/oci/build.go
As discussed in https://github.com/inspektor-gadget/inspektor-gadget/pull/2177, the ArtifactType must be specified when config.mediaType is set MediaTypeEmptyJSON. In our case, when the metadata file is not provided. However, such PR added the ArtifactType inside the config and not to the general manifest as described in [1].
Fixes: https://github.com/inspektor-gadget/inspektor-gadget/commit/1b04865d86c95ffaa9631d1bd73b43c6a2c43337
[1] https://github.com/opencontainers/image-spec/blob/f5f87016de46439ccf91b5381cf76faaae2bc28f/manifest.md?plain=1#L210
```bash
$ IG_EXPERIMENTAL=true go run --exec "sudo -E" ../../cmd/ig/... image build -t ghcr.io/blanquicet/gadget/trace_exec:latest .
$ IG_EXPERIMENTAL=true go run --exec "sudo -E" ../../cmd/ig/... image push …
```
=> oci/build: Specify ArtifactType in the correct place

.github/workflows/stale.yaml
Issues and PRs will be marked as stale after 60 days of inactivity, and will be closed 14 days after is there is not new activity.
This is used to avoid a lot of old issues / PRs piling up on the repository.
=> gha: Automatically mark and close stale issues / PRs

Dockerfiles/gadget.Dockerfile, Dockerfiles/ig-tests.Dockerfile, Dockerfiles/ig.Dockerfile, Dockerfiles/kubectl-gadget.Dockerfile, Makefile, integration/ig/k8s/Makefile
Users may need GOPROXY for faster download speed, passing the host's GOPROXY into the build container will improve the experience.
Tested by `make ig`.
=> ig: Pass host's GOPROXY to the build container

.github/workflows/stale.yaml
In [0] we hit the limit, hence better to increase it.
[0]: https://github.com/inspektor-gadget/inspektor-gadget/actions/runs/8165699333
=> gha/stale: Update operations-per-run to 500

integration/ig/k8s/top_tcp_test.go, integration/inspektor-gadget/top_tcp_test.go, pkg/gadgets/top/tcp/tracer/tracer.go, pkg/gadgets/top/tcp/types/types.go
The top tcp gadget reports the IPVersion field as the address family `AF_INET` or `AF_INET6`. Instead, all other gadgets reporting such a field use `4` or `6` directly, which avoids further manipulation of output on CLI or third-party applications consuming the JSON. Gadgets using `4` and `6`:
- [Trace tcp](https://github.com/inspektor-gadget/inspektor-gadget/blob/jose/top-tcp-ipversion/pkg/gadgets/trace/tcp/tracer/tracer.go#L203)
- [Trace tcpconnect](https://github.com/inspektor-gadget/inspektor-gadget/blob/jose/top-tcp-ipversion/pkg/gadgets/trace/tcpconnect/tracer/tracer.go#L200)
- [Trace tcpdrop](https://github.com/inspektor-gadget/inspektor-gadget/blob/jose/top-tcp-ipversion/pkg/gadgets/trace/tcpdrop/tracer/tracer.go#L214)
- [Trace …
=> pkg/gadgets/top/tcp: Align IP version field with other gadgets

docs/builtin-gadgets/trace/network.md
For consistency, use the same title for this gadget as all other gadgets in the same category.
See:
https://inspektor-gadget.io/docs/v0.26.0/builtin-gadgets/trace/network/
Before this patch:
=> docs: trace network title

.github/workflows/stale.yaml
It seems we need to use `good first issue` vs `good-first-issue` for `action/stale` because some of the older issues with exception labels have been marked stale:
- https://github.com/inspektor-gadget/inspektor-gadget/issues/1526
- https://github.com/inspektor-gadget/inspektor-gadget/issues/967
Other projects also use ["good first issue"](https://github.com/dapr/dapr/blob/master/.github/workflows/dapr-bot-schedule.yml#L65). 
Fixes: 033664546e74d692e8c71b6c6222249d8e2de15a
=> gha: Fix exempt issue label for action/stale

docs/reference/program-types.md, gadgets/Makefile, gadgets/trace_malloc/gadget.yaml, gadgets/trace_malloc/program.bpf.c, pkg/gadgets/run/tracer/tracer.go
This patch introduces basic support for uprobe and uretprobe.
Filtering as well as auto attach/detach will be supported in the future.
Also, a simple gadget `trace_malloc` is added as demo.
`ig image build -t trace_malloc:latest .`
`ig run trace_malloc:latest --host`
=> run: Support basic uprobe and uretprobe

pkg/oci/oci.go
It doesn't change the integration with other modules, so rebasing refactoring on top of this is fast-forward. cc @flyth
=> pkg/oci: Few cleanups and improvements to make code clearer

.github/workflows/inspektor-gadget.yml
Currently, if both helper images are built together one of the images will have a default value since we set tag for both the images in each matric run. This change ensures we only set the default value when needed and not in each matric run.
I mainly hit it when doing some testing on the fork as mentioned below. Also, it was always the `dnstester` which is affected since it is done building before `ebpf-builder`. Perhaps something that will happen rarely in main repo but still a weird issue.
Fixes: 5ddb3fb2f173e7873e1d9ce52c416fe055b8e74a
- Run with both images built together can be found [here](https://github.com/mqasimsarfraz/inspektor-gadget/actions/runs/8232021327). You can see the integration test are still using [default dnstester …
=> ci: Use correct helper image even if both are built simultaneously

gadget-container/gadgettracermanager/main.go
Currently, the kubemanager operator is implicitly registered (its `init()` is called) because it's imported by the kubenameresolver operator, which is imported by the gadget-collection trace network gadget. It means that if we decide to remove such a gadget, the kubemanager operator won't be registered anymore.
This PR adds the kubemanager operator to the gadgettracermanager to avoid dependence on other operators or gadgets.
After removing the gadget trace network from gadget-collection:
- **Before this PR**: kubemanager won't be registered. It means we won't be able to filter by k8s metadata, events won't be enriched with k8s metadata, etc.
- **After this PR**: Everything will continue working as expected.
=> gadgettracermanager: Explictly import kubemanager operator

integration/ig/k8s/trace_dns_test.go, integration/ig/non-k8s/trace_dns_test.go, integration/inspektor-gadget/trace_dns_test.go, tools/dnstester/dnstester.go
This change adds tests to support testing uncompressed DNS messages.
Related: #2591
=> integration: Test uncompressed DNS messages 

gadgets/README.md, pkg/gadgets/README.md
I've received the "what's the difference between these two folders" question few times. Let's add a small readme to clarify it.
=> Add readmes for image-basde and built-in gadgets

.golangci.yml, cmd/kubectl-gadget/advise/seccomp-profile.go, cmd/kubectl-gadget/deploy.go, cmd/kubectl-gadget/undeploy.go, gadget-container/entrypoint/entrypoint.go, pkg/btfgen/btfgen.go, pkg/container-collection/networktracer/connect.go, pkg/container-utils/cri/cri_test.go, pkg/gadget-collection/gadgets/interface.go, pkg/gadgets/snapshot/socket/tracer/tracer_test.go
Add goimports linter to make sure all imports are grouped in the same way in all the repository.
=> tree-wide: Fix imports grouping and add lint target

cmd/common/image/build.go, cmd/common/image/list.go, pkg/oci/build.go, pkg/oci/oci.go
The OCI image spec defines the creation date annotation: https://github.com/opencontainers/image-spec/blob/main/annotations.md
> `org.opencontainers.image.created` date and time on which the image was built, conforming to RFC 3339.
This patch ensures that the annotation is set with the same value for both amd64 and arm64.
Then, the date is printed in the image list command:
Note: the creation date will also be useful for the future Artifact Hub patch because the 'createdAt' field is mandatory in artifacthub-pkg.yml:
https://github.com/artifacthub/hub/blob/master/docs/metadata/artifacthub-pkg.yml
```
createdAt: The date this package was created (RFC3339 layout) (required)
```
```
$ sudo -E ig image list
REPOSITORY  TAG     DIGEST       CREATED …
```
=> image list: add creation date

docs/devel/hello-world-gadget.md, docs/reference/gadget-helper-api.md, gadgets/trace_malloc/gadget.yaml, gadgets/trace_malloc/program.bpf.c, gadgets/trace_oomkill/gadget.yaml, gadgets/trace_oomkill/program.bpf.c
The macro GADGET_TRACER defines the tracer name with "open" in several places due to copy and paste. This patch renames the tracers to suitable names.
This patch also updates gadget.yaml and the documentation accordingly.
One commit in this PR was picked up from #2634.
cc @eiffel-fl @i-Pear
=> Fix tracer name in GADGET_TRACER(open, ...)

pkg/btfhelpers/bpfhelpers_test.go, pkg/btfhelpers/btfhelpers.go, pkg/gadgets/run/tracer/run.go, pkg/gadgets/run/tracer/tracer.go, pkg/gadgets/run/types/metadata.go
This pkg bundles a couple of helpers around btf type conversion. These versions will now also collect all visited types when going down the typedef tree so that they can later on be used as tags for fields.
Part of #2512
=> add btfhelpers package

pkg/oci/build_metadata.go, pkg/oci/fix_owner_linux.go, pkg/oci/fix_owner_others.go
fixMetadataOwner() was previously added for the following reason:
'ig image build --update-metadata' overwrites gadget.yaml but since ig runs as root, the file gadget.yaml initially ends up belonging to root. The function fixMetadataOwner() fixes this with a chown.
In order to reuse fixMetadataOwner() for a different file, this patch makes it more generic.
This commit was initially part of #2586.
=> pkg/oci: make fixMetadataOwner more generic

gadgets/ci/sched_cls_drop/gadget.yaml
Although the gadget.yaml metadata file is not mandatory, it is best practice to have one. This patch adds it. It will make it easier for the next PRs.
This commit was initially part of #2586.
=> gadgets/ci/sched_cls_drop: add missing gadget.yaml

README.md, artifacthub-repo.yml, docs/devel/hello-world-gadget.md, gadgets/ci/sched_cls_drop/artifacthub-pkg.yml, gadgets/snapshot_process/artifacthub-pkg.yml, gadgets/snapshot_socket/artifacthub-pkg.yml, gadgets/top_file/artifacthub-pkg.yml, gadgets/trace_dns/artifacthub-pkg.yml, gadgets/trace_exec/artifacthub-pkg.yml, gadgets/trace_malloc/artifacthub-pkg.yml, gadgets/trace_mount/artifacthub-pkg.yml, gadgets/trace_oomkill/artifacthub-pkg.yml, gadgets/trace_open/artifacthub-pkg.yml, gadgets/trace_signal/artifacthub-pkg.yml, gadgets/trace_sni/artifacthub-pkg.yml, gadgets/trace_tcp/artifacthub-pkg.yml, gadgets/trace_tcpconnect/artifacthub-pkg.yml, gadgets/trace_tcpdrop/artifacthub-pkg.yml, gadgets/trace_tcpretrans/artifacthub-pkg.yml
Since #2586 will take some time to address the comments, I'm splitting it in two. This PR is the first part and focuses on adding the metadata to get the gadgets published on Artifact Hub. Once this is merged, I will continue with the helper tools.
---
Artifact Hub now supports Gadgets: https://github.com/artifacthub/hub/issues/3665
You can see the list of all gadgets is published on Artifact Hub:
https://artifacthub.io/packages/search?kind=22
Gadget authors can publish their gadgets on Artifact Hub by adding two files on their repositories:
* artifacthub-repo.yml
* artifacthub-pkg.yml
This PR does that for the official gadgets. For now, artifacthub-pkg.yml is written manually. Helpers to automate this will be done in #2586.
The gadgets from the main IG repository are published on this …
=> Artifact Hub: publish gadgets

README.md, docs/devel/hello-world-gadget.md
Two changes:
1. Update the label to: "Helm charts"
2. Update the link to the URL of the Helm chart instead of the search webpage.
Note that the URL still contains "gadget". We are looking to change it to "inspektor-gadget" but at the moment it is linked to the chart name and renaming it would break the updates for users.
See related discussion in:
* https://github.com/inspektor-gadget/inspektor-gadget/pull/2586#discussion_r1526560343
Before this patch:
After this patch:
cc @mqasimsarfraz @eiffel-fl
=> README.md: update artifacthub badges

integration/container_interface.go, integration/containerd.go, integration/docker.go
`IntegrationTestsContainer` defines what a container struct must implement so that it can be run by `RunTestSteps`. However, it's exactly what `TestStep` also does.
=> integration: IntegrationTestsContainer interface is not necessary

pkg/operators/ebpf/attach.go
This commit from @mauriciovasquezbernal ports basic uprobe support to the new architecture / eBPF operator.
=> refactoring: port uprobe support

CODEOWNERS, docs/reference/program-types.md, gadgets/trace_malloc/gadget.yaml, gadgets/trace_malloc/program.bpf.c, go.mod, go.sum, pkg/operators/ebpf/attach.go, pkg/operators/ebpf/ebpf.go, pkg/uprobetracer/ldcache_parser.go, pkg/uprobetracer/tracer.go
Part of #1912.
This patch introduces a new package `uprobetracer` for auto attaching/detaching.
There will be duplicate records with current implementation.
- Starting/stopping/restarting the containers, and see if it works well.
- Use `--pod` and `--containername` to test the filter
=> Introduce uprobetracer for auto attach/detach

pkg/gadget-context/run.go
Data operators will be instantiated (activated) only if the gadget requests a feature the operator provides. If a given operator is not instantiated, then we shouldn't add its parameters.
The struct generated by the `open` tracer defined in the following gadget doesn't meet any of the requirements to activate the LocalManager data operator (All this is also valid for KubeManager):
1. The gadget declares a map named `gadget_mntns_filter_map` (This is automatically done if `mntns_filter.h` is included). Notice this allows gadgets to filter by container.
2. The gadget contains a tc program (`BPF_PROG_TYPE_SCHED_CLS`). It's necessary because the tc programs need to get notifications about the creation and deletion of containers.
3. The struct generated by the gadget containers a field of type …
=> gadget-context: Don't add op instance's params if op is not requested

charts/gadget/templates/daemonset.yaml, pkg/resources/manifests/deploy.yaml
While reducing coverage for '/host' we dropped '/host/var' as well but it turns out when running docker runtime in minikube with kvm2 driver we need this path. This change fixes it by mounting only the needed path.
Fixes: 2b437e17f4e94bd8fff48f3ec2226dadf6bf7a4e
```
$ MINIKUBE_DRIVER=kvm2 make minikube-deploy
$ kubectl logs -n gadget -l k8s-app=gadget -f
$ kubectl create deploy test --image nginx
time="2024-03-28T11:43:01Z" level=error msg="error monitoring runtime instance: marking /host/var/run/docker/containerd/daemon/io.containerd.runtime.v2.task/moby/5b4194d99b44c5298002e334c1b48ad814428262931e57a6e1983618e9b8de5e: fanotify: mark error, no such file or directory\n"
time="2024-03-28T11:43:17Z" level=error msg="error monitoring runtime instance: marking …
```
=> charts: Add '/host/var' to volumeMounts

docs/reference/program-types.md, pkg/operators/ebpf/attach.go, pkg/operators/ebpf/ebpf.go, pkg/uprobetracer/bytes.go, pkg/uprobetracer/ldcache_parser.go, pkg/uprobetracer/tracer.go, pkg/uprobetracer/usdt.go
Added USDT support for uprobe ebpf programs.
A parser for USDT elf notes is included.
Docs are updated.
Use `usdt/<programPath or libraryName>:<providerName>:<probeName>` as the section name of ebpf file.
Use `SEC("usdt//usr/bin/python3:python:function__entry")` and `SEC("usdt//usr/bin/python3:python:function__return")`.
Then run a python program inside the container:
```
from time import sleep
def f():
print(123)
while True:
f()
sleep(1)
```
=> pkg/uprobetracer: add support for USDT tracepoints

pkg/container-collection/containers.go, pkg/container-collection/operator.go, pkg/datasource/compat/wrapper.go, pkg/gadgets/traceloop/tracer/tracer.go, pkg/operators/operators.go, pkg/types/types.go
This fixes an open issue with the hostNetwork information not being set correctly after the refactoring of the image based gadgets. This was mainly due to the enricher interfaces not providing that info, so I've changed those interfaces now to use yet another interface type (`Container`) that can be more easily extended without changing much code.
=> image based gadgets: fix hostNetwork info

pkg/gadget-context/run.go, pkg/operators/oci-handler/oci.go
Fixes #2677
After:
```
$ sudo -E ./ig run ghcr.io/inspektor-gadget/inspektor-gadget:latest
Error: fetching gadget information: initializing and preparing operators: instantiating operator "oci": image doesn't contain valid gadget layers
```
=> image based gadgets: return error if no valid gadget layers are found

integration/containers/container_interface.go, integration/containers/containerd.go, integration/containers/docker.go, integration/containers/factory.go, integration/containers/options.go, integration/ig/non-k8s/integration_test.go, integration/ig/non-k8s/list_containers_test.go, integration/ig/non-k8s/snapshot_process_test.go, integration/ig/non-k8s/trace_dns_test.go, integration/ig/non-k8s/trace_network_test.go
This PR aims to organize all the container-related stuff into a separate package. This way, only the tests interested in running containers will import it. In our case, the tests within `ig/non-k8s`. Furthermore, this PR removes some duplicated code we had for each runtime, consolidating everything into one structure.
Notice this PR prepares things to be easily moved to the `testing` pkg that https://github.com/inspektor-gadget/inspektor-gadget/pull/2607 is creating.
=> integration: Separate and simplify container-related stuff

.github/workflows/inspektor-gadget.yml
This change introduces a wait before we call the cluster deletion for GKE Cluster
Fixes: #2535
- [amd64 cluster with cancellation](https://github.com/inspektor-gadget/inspektor-gadget/actions/runs/8570896605/job/23491650534#step:12:31)
- [arm64 cluster with cancellation](https://github.com/inspektor-gadget/inspektor-gadget/actions/runs/8570896605/job/23491650902#step:12:31)
=> ci: Add wait to ensure GKE clusters are deleted

pkg/datasource/formatters/json/json.go, pkg/datasource/formatters/json/options.go, pkg/operators/cli/clioperator.go
This adds the missing `jsonpretty` and `yaml` output modes to the cli operator. Currently (as was with the previous
run gadget), YAML is handled by first marshaling to JSON and then converting, which is quite slow. We can later
on add an optimized YAML formatter that will handle marshaling directly.
This also sorts fields alphabetically.
```
$ ./ig run "ghcr.io/inspektor-gadget/gadget/trace_exec:latest" -o jsonpretty
{
"args": "/opt/cni/bin/bridge",
"args_count": 1,
"args_size": 20,
"comm": "bridge",
"gid": 0,
"k8s": {
"container": "",
"hostnetwork": false,
"namespace": "",
"node": "",
"pod": ""
},
"loginuid": 4294967295,
"mntns_id": 4026532263,
"pid": 1475846,
"ppid": 8590,
"retval": 0,
"runtime": {
"containerId": …
```
=> re-add support for jsonpretty + yaml to image based gadgets

docs/getting-started/verify.md
Previous logic was downloading an html document instead of the key, hence raw.githubusercontent.com needs to be used.
This commit also uses the version when downloading the key, in case we need to rotate it later on.
Found while checking #2675.
=> docs: Fix instructions to verify container image

cmd/common/oci.go, pkg/gadget-context/options.go, pkg/gadget-context/run.go, pkg/gadget-service/service-oci.go
This adds the parameter `-t` / `--timeout` back to image-based gadgets.
Task from #2653
=> fix: re-add timeout for image-based gadgets

cmd/common/registry.go, cmd/common/utils/flags.go, cmd/common/utils/parser.go, cmd/common/utils/parser_test.go, cmd/ig/containers/containers.go, cmd/kubectl-gadget/traceloop.go, docs/builtin-gadgets/top/ebpf.md, docs/ig.md, pkg/columns/doc.go, tools/demos/trace-dns/demo.sh, tools/demos/trace-exec/demo.sh
This PR fixes #1526 as the `custom-columns` flag has been changed to `columns`, the changes in this PR will replace all the `custom-columns` flag from documentation and code with `columns`
=> Cleanup custom-columns CLI flag

.github/workflows/inspektor-gadget.yml
See https://github.com/inspektor-gadget/inspektor-gadget/issues/2728
Fixes #2728
=> ci: Always build helper images on main and release branches

integration/command.go, integration/teststeps.go, pkg/container-utils/testutils/container_interface.go
To better debug issues with the CI the timestamps of Run/Start/Stop could be useful. Any other suggestions is welcomed
=> integration: Add timestamp to Run/Start/Stop

pkg/operators/common/kubeinventorycache.go, pkg/operators/common/resource_cache_test.go, pkg/operators/kubeipresolver/kubeipresolver.go, pkg/operators/kubenameresolver/kubenameresolver.go
In order to always correctly enrich events we need to keep just deleted pods and services in a separate list.
1. The first commit introduces this mechanism with the disadvantage that for every event a copy of the pods list needs to be made
1. The second commit adds functions so the enricher query for specific pods directly. This solves the problem with the copy
This PR should also solve quite a few of sporadic CI failures. The problem was with `TestAdviseNetworkpolicy`. Sometimes the last events were not enriched, but `advices network-policy report` expects it to be.
```
panic: unknown event
github.com/inspektor-gadget/inspektor-gadget/pkg/gadgets/advise/networkpolicy/advisor.(*NetworkPolicyAdvisor).eventToRule(_, {{{{{...}, {...}, {...}, {...}, {...}}, {{...}, …
```
=> KubeInventoryCache: Keep old pods/svcs in a cached for enrichment

tests.mk
Update `kube-apiserver` we use in `tests.mk` to latest version to get all security fixes and have the latest version
=> tests.mk: Update kube-apiserver to 1.30.0

cmd/common/image/build.go, pkg/oci/build.go, pkg/oci/build_metadata.go, pkg/oci/fix_owner_linux.go, pkg/oci/fix_owner_others.go
There are situations when keeping the built files is useful. Implement a -o/--output option for it
Taken from #2598
```bash 
$ cd gadgets/trace_open
$ mkdir /tmp/build
$ sudo -E ig image build . -o /tmp/build/
Successfully built @sha256:8d3859d56a61db46c286c30e81417025b67c4668c9118b0c6f7c5f466e666f31
$ ls -la /tmp/build/
total 184
drwxrwxr-x  2 mauriciov mauriciov  4096 abr 18 12:51 .
drwxrwxrwt 27 root      root      12288 abr 18 12:51 ..
-rw-r--r--  1 mauriciov mauriciov 88784 abr 18 12:51 amd64.bpf.o
-rw-r--r--  1 mauriciov mauriciov 81704 abr 18 12:51 arm64.bpf.o
```
=> image/build: Implement option to keep built file

Dockerfiles/ebpf-builder.Dockerfile, cmd/common/image/Makefile.build, cmd/common/image/Makefile.build.btfgen, cmd/common/image/build.go, cmd/ig/main.go, docs/core-concepts/images.md, docs/reference/btfgen.md, docs/reference/oci.md, gadget-container/gadgettracermanager/main.go, pkg/btfgen/btfgen.go, pkg/oci/build.go, pkg/oci/fix_owner_linux.go, pkg/operators/btfgen/btfgen.go, pkg/operators/ebpf/ebpf.go
This PR implements support for btfgen for image-based gadgets.
This is based on #2512, however only the last commit is really depending on that, other commits can already be reviewed. 
btfgen is used to generate the BTF files with the types needed by the gadget, those are stored in a new layer on the gadget image. A new btfgen operator uses that layer to get the types for the current kernel, those are passed to the ebpf operator that uses them when loading the programs into the kernel.
> note: btfhub-archive need to be cloned into $HOME, otherwise a step below will fail. The following script already takes care of it
```bash
$ ./tools/getbtfhub.sh
```
Consider the following simple gadget that uses some CO-RE functions:
```c
#include <vmlinux.h>
#include <bpf/bpf_helpers.h>
#include …
```
=> image-based gadgets: Implement btfgen support

docs/reference/program-types.md, pkg/operators/ebpf/attach.go
Use `lsm/<hook>` as section names.
=> pkg/uprobetracer: support LSM trace points

pkg/gadget-collection/gadgets/trace/dns/gadget.go, pkg/gadget-collection/gadgets/trace/sni/gadget.go, pkg/gadgets/trace/dns/tracer/tracer.go, pkg/gadgets/trace/sni/tracer/tracer.go
Before this change NewTracer() installed and run the tracer.
Now calling NewTracer() only installs the tracer, and Run() or RunWorkaround() runs it.
This change is needed so that the socket enricher could be set before loading the eBPF programs.
A similar solution was implemented in the network tracer.
Discussion: https://kubernetes.slack.com/archives/CSYL75LF6/p1713707118485529
Before this change, `MountNsID` was empty even when setting the socket enricher. I have run the DNS tracer with this change implemented and I could see that mount namespace was filled successfully and so enrichment of events is working.
=> trace/{dns,sni}: Split NewTracer() logic

.github/workflows/cloud-cleanup.yml, .github/workflows/inspektor-gadget.yml, tools/eks-cleanup/.gitignore, tools/eks-cleanup/go.mod, tools/eks-cleanup/go.sum, tools/eks-cleanup/main.go
This adds a script to find and delete resources which are older than 3 hours. Unfortunately, the VPCs do not have a creation timestamp and therefore a custom tag is needed.
Additionally when deleting a cloudformation stack there is no option to wait until it actually got deleted. Therefore we need to poll it until it is gone.
Or else deleting the VPCs for that specific stack will fail.
Please take a look at the script and mark everything which seems wrong. I am not the best bash script writer
EKS version of https://github.com/inspektor-gadget/inspektor-gadget/pull/2682
Script is a modified version from @mauriciovasquezbernal (https://github.com/inspektor-gadget/inspektor-gadget/issues/2533#issuecomment-1961456214) 
```
Checking Cloudformation stacks...
Deleting Cloudformation Stack …
```
=> ci: Add workflow to clean eks resources

.github/workflows/inspektor-gadget.yml
Fixes: PR https://github.com/inspektor-gadget/inspektor-gadget/pull/2686 commit 410cb4904f2c400d6191028da8c5e041c8757a2b
Working citest run: https://github.com/inspektor-gadget/inspektor-gadget/actions/runs/8849861291/job/24303110950
Apparently RFC3339 is not always compatible with each implementation
=> test-integration-eks: Fix missing quotes + define explicit timeformat

cmd/common/oci.go
Fixes https://github.com/inspektor-gadget/inspektor-gadget/issues/2767
=> cmd: Require experimental flag for run command.

tools/eks-cleanup/main.go
This is probably the case when the VPCs are not deleted yet. Swapping the order to delete VPCs before the Cloudformation stacks is also not feasible since VPCs can't be deleted when the stack is still running.
So we just try to delete both and in the next run the corresponding stack or VPC will be deleted
Log from the deletion of stacks/VPCs where the previous version failed:
```
{8:56} tools/eks-cleanup:main ✗ ➭ go run .
deleting stack: eksctl-ig-ci-eks-amd64-3197-cluster
deleting stack: eksctl-ig-ci-eks-amd64-22224-cluster
deleting stack: eksctl-ig-ci-eks-arm64-30146-cluster
waiting for stack to be deleted: eksctl-ig-ci-eks-amd64-3197-cluster
waiting for stack to be deleted: RequestCanceled: waiter context canceled
caused by: context deadline exceededwaiting for stack to be deleted: …
```
=> eks-cleanup: Don't error when stack can't be deleted

pkg/gadget-service/api/helpers.go
Make logic fail on socket paths like tcp://foo:9000
---
The following command doesn't show any error: (notice the missing `//` after `tcp`)
```bash 
$ sudo ig daemon --host tcp:127.0.0.1:8888
INFO[0000] starting Inspektor Gadget daemon at "tcp:127.0.0.1:8888"
```
But also doesn't work as ig doesn't listen on that address. Make it print an explicit error in that case.
=> gadget-service: Improve address validation

pkg/runtime/grpc/grpc-runtime.go, pkg/runtime/grpc/oci.go
The timeout could potentially happen if the server had to download a gadget image on a slow connection. This changes the timeout to be connection-related only and not a total time that the gRPC call may take (we don't set such a limit now.)
Discussed on [Slack](https://kubernetes.slack.com/archives/CSYL75LF6/p1712761766862949)
=> fix gRPC timeout for image-based gadgets on GetGadgetInfo()

integration/k8s/run_trace_oomkill_test.go
This waits for 10 seconds for ig or kubectl-gadget to finished downloading the gadget from the OCI registry and starting it
Reference: For the OOMKill test from the builtin legacy gadget we even have a 2 second sleep there. With image based gadget we need a little bit more time to additionally download the image
=> TestRunTraceOOMKill: Add sleep after starting ig/kubectl-gadget

cmd/common/image/export.go, cmd/common/image/import.go, docs/core-concepts/images.md, pkg/oci/oci.go
Implement commands to export / import gadget images to / from a file.
Being able to export and export images from files is useful for the following cases:
- It's possible to distribute images by just using files. Airgapped environments. Cases where reaching the internet is not an option
- Integrate gadget images directly into the application binary. #2021. (I already have a POC of this working, but it's still missing a lot of things)
```bash 
$ sudo rm -rf /var/lib/ig/oci-store
$ sudo -E ig image list
REPOSITORY             TAG                    DIGEST       CREATED
$ sudo -E ig image pull trace_open
Pulling trace_open...
Successfully pulled ghcr.io/inspektor-gadget/gadget/trace_open:latest@sha256:1ef0b57afa …
```
=> cmd: Implement image import and export commands

integration/teststeps.go
When `step.Stop` uses `t.Fatalf` we will never get the timestamp. This way we know when we are initiating the stop at least
=> integration: Logging timestamp before calling step.Stop

cmd/gadgetctl/main.go, cmd/kubectl-gadget/main.go, cmd/kubectl-gadget/version.go, pkg/runtime/grpc/info.go
Add the completion command to the list of commands we need to skip getting the deploy info for.
Fix the following issues:
- kubectl-gadget completion not working when IG is not deployed
- kubectl-gadget version not showing the client version when k8s is not reacheable
Fixes #2773
I performed the following:
```bash 
$ mkdir /tmp/config
$ minikube start -p ig
$ cp $HOME/.kube/config /tmp/config/ig
$ minikube start -p non-ig
$ cp $HOME/.kube/config /tmp/config/non-ig
$ KUBECONFIG=/tmp/config/ig kubectl get nodes
NAME   STATUS   ROLES           AGE     VERSION
ig     Ready    control-plane   2m14s   v1.28.3
$ KUBECONFIG=/tmp/config/non-ig kubectl get nodes
NAME     STATUS   ROLES           AGE   VERSION
non-ig   Ready    control-plane   23s   v1.28.3
$ KUBECONFIG=/tmp/config/ig …
```
=> kubectl-gadget: Multiple fixes around skipInfo logic 

pkg/operators/uidgidresolver/usergroupcache.go
Creating the OnceValue inside the function and then calling it doesn't create the desired effect. It just creates new caches all the time.
Therefore move the creation of the `OnceValue` to the global scope.
=> UserGroupCache: Move OnceValue to global scope

pkg/gadget-collection/gadgets/trace/network/gadget.go
The `eventCallback` is still called multiple times after (some) operators were closed.
It might finally solve our flaky `TestAdviseNetworkpolicy` test in our CI.
Testing was done through calling the command 15-25 times manually :) I reproduced the issue on an AKS cluster. With minikube it always seemed to work before this PR. Now everything looks like it works
=> trace/network: Close Operators after closing the tracer

charts/gadget/templates/daemonset.yaml, examples/builtin-gadgets/withfilter/trace/network/deploy.yaml, examples/kube-container-collection/deploy.yaml, examples/runc-hook/deploy.yaml, pkg/resources/manifests/deploy.yaml
Inspektor Gadget needs access to the host volume /sys/fs/cgroup but does not need write access. Switch to readOnly=true.
No changes.
None yet. Let's run the CI first.
Related PR: https://github.com/inspektor-gadget/inspektor-gadget/pull/2285
=> kubernetes: cgroupfs: mount read-only

pkg/operators/oci-handler/oci.go
Make the whole operation fail is starting an image operator fails.
Create a gadget that doesn't pass the verifier:
```c
#include <vmlinux.h>
#include <bpf/bpf_helpers.h>
#include <gadget/buffer.h>
#include <gadget/macros.h>
#include <gadget/mntns_filter.h>
#include <gadget/types.h>
#define NAME_MAX 255
struct event {
gadget_mntns_id mntns_id;
__u32 pid;
char comm[TASK_COMM_LEN];
char filename[NAME_MAX];
};
// events is the name of the buffer map and 1024 * 256 is its size.
GADGET_TRACER_MAP(events, 1024 * 256);
// [Optional] Define a tracer
GADGET_TRACER(open, events, event);
SEC("tracepoint/syscalls/sys_enter_openat")
int enter_openat(struct syscall_trace_enter *ctx)
{
struct event *event;
u64 mntns_id;
mntns_id = gadget_get_mntns_id();
if (gadget_should_discard_mntns_id(mntns_id)) …
```
=> oci: Fail is start image operator fails

gadgets/trace_malloc/gadget.yaml, gadgets/trace_malloc/program.bpf.c
Gadgets such as `memleak` and `deadlock` need userspace code to further interpret the data collected from kernel side. It needs WASM support, which is not currently available. So this pull request just send the events to ebpf map, and processing the events in userspace is future work.
=> gadgets/trace_malloc: support more memory operations 

gadgets/trace_dns/program.bpf.c
Although string manipulation is more difficult to do in ebpf than in userspace, it is actually possible to convert the domain name encoded in the DNS packet into dot notation strings.
```
$ sudo -E ig run ghcr.io/inspektor-gadget/gadget/trace_dns:latest --verify-image=false INFO[0000] Experimental features enabled
WARN[0000] you set --verify-image=false, image will not be verified WARN[0001] you set --verify-image=false, image will not be verified
RUNTIME.CONTAINERN… SRC… SRC… DST… DST… MNTNS_ID NETNS   PID        TID        UID        GID        TASK       ID         QTYPE      … PKT_… RCODE LATE… NAME               ANCOUNT    ANADDRCOU… ANADDR     TIMESTAMP  SRC.ADDRE… DST.ADDRE…
busybox             565… 17   53   17   40265327 4026533 2869179    2869179    0          0          wget …
```
=> trace_dns: convert domain to dot notation (without wasm)

pkg/operators/simple/simple.go
A wrong check in `Stop()` could lead to a crash if `onStart` had been registered but no `onStop`
=> pkg/operators/simple: fix onStop() callback being called if only onStart is set

.github/workflows/inspektor-gadget.yml
It seems after https://github.com/inspektor-gadget/inspektor-gadget/pull/2718 we expected version to be defined via build-args but we missed passing them in the CI steps so ig-k8s image is build without a version. If you install latest version (`v0.28.0`) from the krew the server version is always `v0.0.0`:
```
$ kubectl krew upgrade gadget
$ kubectl gadget version
Client version: v0.28.0
Server version: v0.0.0
```
```
$  kubectl gadget trace open
WARN[0000] version skew detected: client (v0.28.0) vs server (v0.0.0) 
K8S.NODE                              K8S.NAMESPACE                         K8S.POD                               K8S.CONTAINER                         PID        COMM             FD   ERR PATH  
```
It is annoying to …
=> version: Fix server version for ig-k8s

docs/reference/program-types.md, pkg/operators/ebpf/attach.go, pkg/operators/ebpf/snapshotter.go
This patch implements support for bpf iterators of type "task_file" and "ksym".
Note: support for ksym iterators added in Linux 6.0: https://github.com/torvalds/linux/commit/647cafa223490
This is useful for the snapshot-file gadget:
- https://artifacthub.io/packages/inspektor-gadget/snapshot-file/snapshot-file
- https://github.com/alban/snapshot-file
- https://github.com/inspektor-gadget/inspektor-gadget/pull/1725
=> Add support for more iterators: task_file, ksym

gadgets/trace_dns/program.bpf.c
The dns gadget uses '#pragma pack(2)' to define some structs. Using pragma push/pod is preferred to limit the scope of the alignment setting to the struct definition that needs it.
There is no concrete issue at the moment, so there is no need to backport this patch. I was experimenting with some changes in the dns gadget, and the struct alignment was not as I expected.
This patch should make the code more robust for future changes.
Fixes: 4f7150e96093 ("Add NumAnswers and Addresses to DNS trace events")
=> trace_dns: fix padding

pkg/datasource/accessors.go, pkg/datasource/columns.go, pkg/datasource/compat/wrapper.go, pkg/datasource/datasource_test.go, pkg/datasource/formatters/json/json.go, pkg/operators/formatters/formatters.go
There are cases when an operator needs to change the value of a static string (coming from ebpf for instance). This commit ipt improves the logic to allow the operator calling the PutString() method with a string that is smaller than the buffer size.
---
I found this issue / limitation when trying to update the name field in wasm in #2823. That PR implements a workaround for it, but IMO it needs to be handled directly in the accessor.
@flyth any opinions on this one?
=> datasource: Allow setting smaller static strings

pkg/gadgets/consts.go
Fixes: 13cb070 ('Create include folder with all header files exposed by IG')
=> pkg/gadgets: Update comment about mntns_filter.h location

.github/actions/run-integration-tests/action.yml, Makefile, docs/devel/CONTRIBUTING.md, integration/command.go, integration/k8s/integration_test_kubectl_gadget.go
Shifting deploy and undeploy logic from `integration_test_kubectl_gadget.go` to `.github/actions/run-integration-tests/action.yml`.
This change is required since tests for image-based gadgets don't have a TestMain file.
Passing of Integration Tests in the CI.
=> ci: Shifting deploy and undeploy logic for IG to actions

pkg/operators/localmanager/localmanager.go
Fixes: b2895ee8c0cd ("pkg/operators/localmanager: add compatibility for DataSources")
Get a system without runc 
```bash 
$ runc
Command 'runc' not found, but can be installed with:
apt install runc
Please ask your administrator.
```
Running a gadget with and without --host produces a crash
```bash 
$ sudo -E ./ig run trace_exec:latest
WARN[0002] Failed to create container-collection
WARN[0003] Failed to create container-collection
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x3632c1d]
github.com/inspektor-gadget/inspektor-gadget/pkg/operators/localmanager.(*localManagerTraceWrapper).PreStart(0xc004407d00, {0x4528868, 0xc002d8af00}) …
```
=> localmanager: Avoid crashing if container collection isn't available

docs/devel/hello-world-gadget.md
Avoid image verification, otherwise the commands will fail.
Related  #2872
--- 
@eiffel-fl do we have any documentation to sign gadget images? I couldn't find it.
=> docs/hello-world-gadget: Add missing --verify-image=false

gadgets/snapshot_socket/program.bpf.c, gadgets/trace_dns/program.bpf.c, gadgets/trace_sni/program.bpf.c, gadgets/trace_tcp/program.bpf.c, gadgets/trace_tcpdrop/program.bpf.c, gadgets/trace_tcpretrans/program.bpf.c, include/gadget/types.h, pkg/datasource/compat/wrapper.go, pkg/gadgets/run/types/metadata.go
Let users know that we are not using all the net/mnt ns fields for enrichment but just one.
A gadget defining more than one mntns or netns fileds. For instance:
```c
struct process_entry {
gadget_mntns_id mntns_id;
gadget_mntns_id jose;
__u32 pid;
__u32 tid;
__u32 ppid;
__u32 uid;
__u32 gid;
char comm[TASK_COMM_LEN];
};
```
IG will print a warning error like this:
```bash
$ IG_EXPERIMENTAL=true go run --exec "sudo -E" ./cmd/ig/... run $LOCAL_REPO/snapshot_process --insecure --verify-image=false -o jsonpretty -v
...
DEBU[0000] using mntns enrichment
WARN[0000] multiple fields with "type:gadget_mntns_id" found in DataSource "processes", only "mntns_id" will be used
...
```
=> local/kube manager operators: Print warning for multiple net/mnt ns fields 

gadgets/trace_dns/build.yaml, gadgets/trace_dns/go.mod, gadgets/trace_dns/go.sum, gadgets/trace_dns/program.go
This reverts commit 40b707f035d0856acd42d3d0511ad8219b1f5e6d.
e4745197c798 ("trace_dns: convert domain to dot notation (without wasm)") handled the name conversion without wasm. Now we can remove all golang related things from this gadget as they aren't needed.
=> Revert "gadgets/trace_dns: add empty wasm module"

cmd/common/image/build.go, go.mod
The builder image is quite big. Add a progress bar to avoid annoying users.
Remove the existing builder image
```bash 
$ docker image rm ghcr.io/inspektor-gadget/ebpf-builder
```
Try to build any gadget
```bash 
$ sudo -E ig image build .
Pulling builder image ghcr.io/inspektor-gadget/ebpf-builder:latest
latest: Pulling from inspektor-gadget/ebpf-builder
c6cf28de8a06: Already exists
891494355808: Downloading [==============>                                    ]  6.881MB/24.05MB
6582c62583ef: Downloading [==============>                                    ]  18.38MB/64.14MB
6d74711819e4: Downloading [>                                                  ]  1.072MB/92.2MB
5ca436926747: Waiting
a583c4d6eaf8: Waiting
4f4fb700ef54: Waiting
335c54f5b534: …
```
=> cmd/image/build: Add progress bar when pulling builder image

gadgets/Makefile, gadgets/trace_lsm/artifacthub-pkg.yml, gadgets/trace_lsm/gadget.yaml, gadgets/trace_lsm/program.bpf.c
This gadget is used as a "strace" for LSM tracepoints.
```
ig run --verify-image=false trace_lsm:latest --help  # list all supported LSM tracepoints
ig run --verify-image=false trace_lsm:latest --trace_inode_mkdir  # trace "inode_mkdir" tracepoint
ig run --verify-image=false trace_lsm:latest --trace_all  # trace all supported LSM tracepoints
```
=> gadgets: Add trace_lsm

gadgets/Makefile, gadgets/trace_ssl/artifacthub-pkg.yml, gadgets/trace_ssl/gadget.yaml, gadgets/trace_ssl/program.bpf.c
Usage: capture SSL data/latency from OpenSSL, GnuTLS, NSS and libcrypto.
=> gadgets: Add trace_ssl

.github/workflows/inspektor-gadget.yml, .golangci.yml, Makefile, cmd/kubectl-gadget/deploy.go, gadget-container/gadgettracermanager/main.go, pkg/operators/oci-handler/oci.go
=> ci/linter: bump golangci-lint version to handle Go 1.22 features

cmd/common/oci.go, cmd/ig/daemon.go, gadget-container/gadgettracermanager/main.go, pkg/gadget-context/run.go, pkg/gadget-service/service-oci.go, pkg/gadget-service/service.go
Previously, for image-based gadgets, operators would lazily be initialized by the gadget context. That made it difficult to forward the actual global configuration of operators. Since we didn't really use those in the past, it was not a big issue.
However, now that we're for example using image verification that can be enabled/disabled using parameters, we need to clean this up. Currently, the client decides whether image validation is done by sending the appropriate flag to the server. This is however insecure, as the client shouldn't have authority over that decision. We may later on allow (using another param/setting that can be enabled on the server) clients to override certain behavior, but in general the server should decide about the security features.
This PR moves the …
=> clean up operator initialization code

cmd/ig/main.go, gadget-container/gadgettracermanager/main.go, pkg/datasource/data.go, pkg/datasource/datasource.go, pkg/operators/filter/filter.go, pkg/operators/filter/filter_test.go
This re-adds filter functionality to the image-based gadgets.
I've slightly changed the syntax to be a bit clearer now:
Before:
`--filter ... field:abc ... field2:>=123`
After:
`--filter ... field==abc ... field2>=123`
Also, now the colon `:` is used to target specific DataSources:
`--filter ds:field==abc`
Several things should be fixed/cleaned up before merging this (already in discussion / being worked on):
Later on this should be extended to also expose the filters to eBPF programs so that they can adopt filtering inside eBPF already if possilbe.
=> add filter operator

include/gadget/types.h, pkg/operators/formatters/formatters.go
Syscalls will be formatted to strings, such as `SYS_OPENAT`.
Solves #2908
Use `gadget_syscall` as the type of event field.
=> pkg/operators/formatters: Add syscall formatter

.github/dependabot.yml
There are some dependencies that need to be updated together. Use the grouping feature to update them in the same PR.
Inspired from https://github.com/containerd/containerd/pull/9532.
https://github.blog/changelog/2023-06-30-grouped-version-updates-for-dependabot-public-beta/
Examples of PRs that could have been grouped:
docker/moby:
- https://github.com/inspektor-gadget/inspektor-gadget/pull/2870
- https://github.com/inspektor-gadget/inspektor-gadget/pull/2869
- https://github.com/inspektor-gadget/inspektor-gadget/pull/2865
otel
- https://github.com/inspektor-gadget/inspektor-gadget/pull/2883
- https://github.com/inspektor-gadget/inspektor-gadget/pull/2882
- https://github.com/inspektor-gadget/inspektor-gadget/pull/2881
k8s:
- https://github.com/inspektor-gadget/inspektor-gadget/pull/2854 …
=> dependabot: Group gomod updates by dependency

pkg/operators/oci-handler/oci.go
If an operator fails, let's bail out instead of trying to continue. The previous logic was calling Start() on an operator that failed on Prepare(), producing seg faults on the wasm operator. (not merged at the time of writing this commit)
--- 
Found it while running tests for the wasm operator (#2818)
```bash
$ go test -exec 'sudo' .
time="2024-05-30T18:23:45-05:00" level=error msg="preparing operator \"wasm\": initializing wasm: instantiating wasm: import func[env.dataArrayAppend]: signature mismatch: i32i32_v != i32i32_i32"
--- FAIL: TestWasmDataArray (0.25s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x17db720] …
```
=> oci: Return error if op.Prepare() fails

.github/dependabot.yml
Avoid dependabot updating indirect dependencies too as it creates too much noise.
#2915 updated the config to use `dependency-type: all` hoping it'll be able to fix the multi modules issues we're having (a dependency update on main go module requires running `go mod tidy` on examples/).  Unfortunately it doesn't totally fix the issue and instead is creating us a lot of noise as the bot is updating a lot of indirect dependencies.
Disable this, perhaps we can reenable it for some modules again once we understand how to fix the multi node issue.
=> dependabot: Disable updating indirect dependencies

pkg/datasource/data.go, pkg/datasource/field.go, pkg/operators/ebpf/struct.go
Fixes: #2736 
```
→ go run -exec "sudo -E" ./cmd/ig run trace_open -r docker --verify-image=false
...
RUNTIME.CONTAINERNAME                   PID                   UID                   GID                   MNTNS_ID          ERR FD                   COMM             FNAME                                     TIMESTAMP  
```
```
→ sudo -E ig run trace_open -r docker --verify-image=false
...
RUNTIME.CONTAINERNAME              PID                 UID                 GID                MNTNS_ID      ERR FD                 FLAGS MODE               COMM             FNAME                                TIMESTAMP 
```
Hidden attribute for fields [`FLAGS`](https://github.com/inspektor-gadget/inspektor-gadget/blob/main/gadgets/trace_open/gadget.yaml#L37) and …
=> fields: Mark fields hidden based on attributes

.github/workflows/inspektor-gadget.yml, gadgets/Makefile, gadgets/testing/testing.go, gadgets/trace_open/test/trace_open_test.go, pkg/container-utils/testutils/k8s.go, pkg/datasource/compat/wrapper.go, pkg/testing/containers/containerd.go, pkg/testing/containers/factory.go, pkg/testing/containers/k8s.go, pkg/testing/containers/options.go, pkg/testing/ig/ig.go, pkg/testing/utils/component.go, pkg/testing/utils/utils.go
Support for running image-based gadgets test in k8s cluster with kubectl-gadget.
Previously we were running the test with ig alongside local containers, this PR adds support for running these tests with kubectl-gadget in the k8s cluster (minikube).
We try to have a single test, which applies different options for the **factory runner** as well as **expected entry** based on whether it's `ig` or `kubectl-gadget`.
Issue #2046
Set `IG_PATH=ig` (for testing with local containers using ig) or `IG_PATH=kubectl-gadget` and `IG_RUNTIME=kubernetes` (for testing with containers running in minikube cluster, need to run `minikube-deploy` before).
Note: You can set this to the actual path of those applications as well, for example, `./ig` or `./kubectl-gadget`, should contain the keyword …
=> Support for running image-based gadgets test in k8s

pkg/container-hook/tracer_test.go, pkg/container-utils/testutils/containerd.go, pkg/container-utils/testutils/docker.go, pkg/container-utils/testutils/options.go
This test runs a Docker container and checks it is correctly detected by the container-hook pkg.
This also runs Docker containers with invalid configuration to check if it makes IG misbehave.
There is a TODO in one test: it can only be removed after #2967 is fixed.
No changes.
```
go test -exec 'sudo -E' ./pkg/container-hook/...
```
=> pkg/container-hook: add new test

.github/actions/run-integration-tests/action.yml, .github/workflows/inspektor-gadget.yml, Makefile, gadgets/Makefile, integration/k8s/integration_test_kubectl_gadget.go, integration/k8s/run_schedcls_test.go, integration/k8s/run_snapshot_process_test.go, integration/k8s/run_top_file_test.go, integration/k8s/run_trace_oomkill_test.go, integration/k8s/run_trace_sni_test.go, integration/k8s/run_trace_tcp_test.go, pkg/testing/ig/ig.go
Currently, in order to publish ig-k8s image / gadget images on a fork users will have to:
- Set secrets for cosign (`COSIGN_PRIVATE_KEY/COSIGN_PASSWORD`)
- Update the public key in source (pkg/resources/inspektor-gadget.pub) 
Otherwise `public-key-check` job [will fail](https://github.com/mqasimsarfraz/inspektor-gadget/actions/runs/9061503098/job/24893441499) and ig-k8s image /gadgets images won't be published. The idea of this PR is to improve this workflow by not signing images by default on forks. `public-key-check` is removed from the `needs` of both the image publishing steps, allowing images to be published but not signed on forks. Having said that, `public-key-check` is moved to release to ensure if incorrect keys are configured we won't be able to release. So it isn't a fatal job …
=> ci: improve handling of public-key-check

pkg/container-hook/tracer.go, pkg/container-hook/tracer_test.go
Before this patch, IG had one fanotify fd for monitoring executions of container runtimes (e.g. `/usr/bin/runc`) and one fanotify fd instantiated for each container between the `runc create` and the `runc start` to watch the creation of the pid file. When `runc create` fails, the pid file is never created and `runc start` is never executed; this leads to IG accumulating fanotify fds.
Fanotify fds are a scarce global resource on Linux:
[FANOTIFY_DEFAULT_MAX_GROUPS=128](https://github.com/torvalds/linux/blob/v6.6/fs/notify/fanotify/fanotify_user.c#L32)
This patch changes the logic to use one permanent fanotify fd to watch the creation of the pid files. The number of fanotify fds used by IG is now always 2 and it is not fluctuating anymore.
Fixes …
=> container-hook: use a single fanotify to watch pid files

gadgets/trace_tcp/program.bpf.c, gadgets/trace_tcpconnect/program.bpf.c, gadgets/trace_tcpdrop/program.bpf.c, pkg/operators/formatters/formatters.go
We need to make sure that the network to host endianess conversion is done only once. Before this PR it was sometimes done inside the eBPF and additionally in userspace -> swapping twice == doing nothing
The variable type inside the event struct is `__u16`, which indicates a "normal" `uint16`. If we want to handle the endianess swap in userspace it would be benefitial to mark it as `__be16` to mark these variables explicitly to be big endian (network endian)
This PR is a quick fix to resolve the bugs. Introduction of `__u16` and its handling in userspace should be done in another PR.
Please check if I found all spots. I went over the gadgets multiple times and checked if the corresponding linux variables are `__u16` or `__be16`. The `trace dns` gadget was not intuitive for me to check so …
=> gadgets/ports: Convert to host endianess inside the gadget

cmd/common/image/build.go
I had an older builder image on my system and then tried to compile new gadgets. It failed to compile since the builder image was too old.
I think when specifying `:latest` as a tag we should always check upstream to get the newest version.
WDYT?
=> ig/build: Always pull builder-image if latest tag is used

gadgets/trace_tcpdrop/gadget.yaml, gadgets/trace_tcpdrop/program.bpf.c, gadgets/trace_tcpretrans/gadget.yaml, gadgets/trace_tcpretrans/program.bpf.c, pkg/operators/ebpf/formatters.go
This commit adds support for providing a human readable version of a bitfield.
This is done by using the same logic for enums, in this case, the gadget author has to define an enum with all values of the flags and that its name has the "_set" suffix, with this information the formatter will recognize and format it on the right way. Developers can use the "ebpf.formatter.bitfield.separator" annotation to set the separator to be used when joining the flags, by default "|" is used.
Before I was trying to use annotations in the metadata file, but after talking to @flyth I realized it was not the best solution and suggested by @flyth decided to implement it using 
Run the trace_tcp{drop,retrans} gadgets and see how they behave. 
Fixes #2482
Related #2996
=> Implement bitfield to string conversion

docs/crds/gadgets/ebpftop.md, docs/crds/gadgets/filetop.md, integration/ig/non-k8s/list_containers_test.go, integration/ig/non-k8s/snapshot_process_test.go, integration/ig/non-k8s/trace_dns_test.go, integration/ig/non-k8s/trace_network_test.go, integration/k8s/audit_seccomp_test.go, integration/k8s/enrichment_pod_label_test.go, integration/k8s/integration_test.go, integration/k8s/list_containers_test.go, integration/k8s/snapshot_socket_test.go, integration/k8s/trace_network_test.go, pkg/container-collection/options.go, pkg/gadgettracermanager/gadgettracermanager.go, pkg/ig-manager/ig-manager.go, pkg/types/types.go, pkg/utils/host/host.go
Enrich events with the container started at time retrieved from `/proc/<PID>/stat`. This needs to be done as the runtime clients do not provide the started at data for APIs other than inspect.
This resolves #2961 
I added this works to the local manager and the made the data available for any gadget.
`ig trace exec -o json`
`ig trace exec -o json`
=> container-collection: add process metadata enricher

cmd/common/image/build.go, docs/core-concepts/images.md, integration/components/image/image_test.go, pkg/oci/build.go, pkg/oci/oci.go
The build command now supports the SOURCE_DATE_EPOCH env variable[0] to allow reproducible builds. Also, the export command is changed to always sort the index to guarentee the exported tarball is deterministic.
```bash 
$ export IG_SOURCE_PATH=<absolute path to IG source location>
$ cd gadgets/trace_open # any other gadget works as well
$ sudo -E ig image build . -t trace_open:last
Successfully built ghcr.io/inspektor-gadget/gadget/trace_open:last@sha256:a00e322b2ad607cfb7051dbe241f976b96a189fe7618fc5f4a48e65ffa2fa518
$ sudo -E ig image build . -t trace_open:last
Successfully built ghcr.io/inspektor-gadget/gadget/trace_open:last@sha256:6c530558cb88a5bf3e6be89866477e819111d5af2e077d192c86e42fe05f7946
``` …
=> cmd/image/export: Allow generating deterministic tarballs

gadgets/Makefile, gadgets/snapshot_process/artifacthub-pkg.yml, gadgets/snapshot_socket/artifacthub-pkg.yml, gadgets/top_file/artifacthub-pkg.yml, gadgets/trace_capabilities/README.md, gadgets/trace_capabilities/artifacthub-pkg.yml, gadgets/trace_dns/artifacthub-pkg.yml, gadgets/trace_exec/artifacthub-pkg.yml, gadgets/trace_lsm/artifacthub-pkg.yml, gadgets/trace_malloc/artifacthub-pkg.yml, gadgets/trace_mount/artifacthub-pkg.yml, gadgets/trace_oomkill/artifacthub-pkg.yml, gadgets/trace_open/artifacthub-pkg.yml, gadgets/trace_signal/artifacthub-pkg.yml, gadgets/trace_sni/artifacthub-pkg.yml, gadgets/trace_ssl/artifacthub-pkg.yml, gadgets/trace_tcp/artifacthub-pkg.yml, gadgets/trace_tcpconnect/artifacthub-pkg.yml, gadgets/trace_tcpdrop/artifacthub-pkg.yml, gadgets/trace_tcpretrans/artifacthub-pkg.yml
The date is updated so that artifacthub picks up the changes.
trace_capabilities' README is added.
Fixes: #2671 (Support kernel stack map)
Fixes: #3092 (Add README.md for all image-based gadgets)
=> Update README.md for all image-based gadgets

CODEOWNERS, gadget-container/gadgettracermanager/main.go, pkg/container-utils/cgroups/cgroups.go, pkg/container-utils/containerutils.go, pkg/container-utils/runtime-client/runtimeclient_test.go, pkg/gadgets/snapshot/socket/tracer/tracer.go, pkg/operators/ebpf/snapshotter.go, pkg/tchandler/tracer.go, pkg/utils/host/namespaces.go, pkg/utils/nsenter/nsenter.go
Before this PR, deploying Inspektor Gadget on Kubernetes often gave one error like this:
```
$ kubectl logs -n gadget gadget-m7bdw
(...)
(...) level=error msg="cgroup enricher: failed to get cgroup paths on container 58ad8(...): cgroup path not found in /proc/PID/cgroup"
```
This is because the container runtime often deploys the IG pod in a new cgroup namespace.
As opposed to the network namespace or the pid namespace, the cgroup namespace cannot be configured in the pod spec. The container runtime typically use `HostCgroup=false` for pods with `privileged=false` (such as IG) and `HostCgroup=true` for pods with `privileged=true` (such as IG v0.3.0 from 2021 before commit ed1c54db3e06679777bd67a6eeecf89d69ff0b47). This depends on the container runtime: docker and containerd behave …
=> GetCgroupID: read cgroup paths under host cgroup namespace

docs/guides/prometheus.md, integration/k8s/prometheus_test.go, pkg/gadgets/prometheus/tracer/gadget.go, tools/monitoring/README.md
Use different name for metric flag for prometheus to avoid conflict with: https://github.com/inspektor-gadget/inspektor-gadget/pull/2831
cc: @eiffel-fl
=> prometheus: Use different name for metrics config

cmd/kubectl-gadget/main.go
Currently we are passing down `KubernetesConfigFlags` to runtime before parsing flags which means all of them will be ignored when talking to Kubernetes. This PR fixes it by setting them for runtime after parsing initial flags
```bash
→ go run ./cmd/kubectl-gadget/ run trace_open --kubeconfig foo.bar
...
RUNTIME.CONTAINERNAME              PID                 UID                 GID                MNTNS_ID      ERR FD                 FLAG… MODE_RAW           COMM             FNAME                                TIMESTAMP_RAW   
```
```bash
→ go run ./cmd/kubectl-gadget/ run trace_open --kubeconfig foo.bar
...
FATA[0000] Creating RESTConfig: stat foo.bar: no such file or directory 
exit status 1
```
Found it when testing: https://github.com/inspektor-gadget/inspektor-gadget/pull/2831
=> cmd/kubectl-gadget: Set k8s flags for runtime after parsing

gadgets/trace_tcpconnect/gadget.yaml, gadgets/trace_tcpconnect/program.bpf.c
kprobe/tcp_v._connect is only sending the SYN package and also only returns errors regarding that package.
This commit uses the kprobe/inet_stream_connect kernel function. It encapsulates the entire tcp connect mechanism and therefore the retcodes can now be captured
closes #2880
=> trace_tcpconnect: Add retcode

.github/workflows/release.yml, gadgets/Makefile, gadgets/snapshot_process/artifacthub-pkg.yml, gadgets/snapshot_socket/artifacthub-pkg.yml, gadgets/top_file/artifacthub-pkg.yml, gadgets/trace_capabilities/artifacthub-pkg.yml, gadgets/trace_dns/artifacthub-pkg.yml, gadgets/trace_exec/artifacthub-pkg.yml, gadgets/trace_lsm/artifacthub-pkg.yml, gadgets/trace_malloc/artifacthub-pkg.yml, gadgets/trace_mount/artifacthub-pkg.yml, gadgets/trace_oomkill/artifacthub-pkg.yml, gadgets/trace_open/artifacthub-pkg.yml, gadgets/trace_signal/artifacthub-pkg.yml, gadgets/trace_sni/artifacthub-pkg.yml, gadgets/trace_ssl/artifacthub-pkg.yml, gadgets/trace_tcp/artifacthub-pkg.yml, gadgets/trace_tcpconnect/artifacthub-pkg.yml, gadgets/trace_tcpdrop/artifacthub-pkg.yml, gadgets/trace_tcpretrans/artifacthub-pkg.yml
artifacthub-pkg.yml has the following fields:
- `createdAt`: date identifying a release. It should not be modified in between releases to avoid confusing users.
- `digest`: string used by artifacthub to request a reindexing
#3102 was wrong to use the `createdAt` for requesting reindexing from artifacthub. It might work on the artifacthub staging area but it does not work with the artifacthub in prod.
Fixes: be7b7dd96fe2 ("Update README.md for all image-based gadgets")
Fixes: 81ce92dd3ca8 ("release: automatically update artifact hub version")
Regenerate readmes with:
```bash
make -C gadgets readmes
```
See tests from #3102.
Note: I used the following command to insert the `digest` field.
```
DATE="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
for i in $(find gadgets/ -name artifacthub-pkg.yml) ; do …
```
=> artifacthub: use field 'digest' instead of 'createdAt' for reindexing

README.md, cmd/common/config.go, cmd/common/oci.go, cmd/common/utils/flags.go, cmd/gadgetctl/main.go, cmd/ig/main.go, cmd/kubectl-gadget/main.go, docs/guides/run.md, pkg/config/config.go
Support a Configuration File for `kubectl-gadget`, `gadgetctl` and `ig`. 
1. Flags
2. Environment Variables (`INSPEKTOR_GADGET_`)
3. Config file `[/etc/ig/config.yaml, $HOME/.ig/config.yaml, ./config.yaml]`
4. Defaults
Related: #2493 
```bash
$ go run -exec "sudo -E" ./cmd/ig config default  > ~/.ig/config.yaml
→ go run -exec "sudo -E" ./cmd/ig config view
...
runtime: {}
operator:
filter: {}
formatters: {}
localmanager:
containerd-namespace: k8s.io
...
$ go run -exec "sudo -E" ./cmd/ig run trace_open
...
DEBU[0000] bpf already mounted                          
DEBU[0000] debugfs already mounted                      
DEBU[0000] tracefs already mounted 
...
```
- Handle config …
=> cmd: Support a Configuration File 

examples/gadgets/operators/otel_metrics/.gitignore, examples/gadgets/operators/otel_metrics/README.md, examples/gadgets/operators/otel_metrics/main.go, examples/go.mod, examples/go.sum, pkg/operators/otel-metrics/otel-metrics.go, pkg/operators/otel-metrics/otel-metrics_test.go
This introduces a new otel-metrics operator for image-based gadgets. This operator can consume and export data from data sources / fields if they're correctly annotated:
* DataSource needs "metrics.export" set to "true" to be considered by the operator
* Fields need "metrics.type" set to either "key", "counter", "gauge" or "histogram"
* counter/gauge/histogram will export those fields using the specified type
* "key" can be used optionally (and multiple times) to group metrics by the unique set of keys given
* optionally, "metrics.description" and "metrics.unit" can be used to provide some metadata to the exporter
* fields without a "metrics.type" will be ignored
To actually enable metrics export, the `otel-metrics-name` param __must__ be set to the exported name explicitly. This ensures …
=> add otel-metrics operator for image-based gadgets

pkg/cachedmap/cachedmap.go, pkg/operators/common/kubeinventorycache.go
https://github.com/inspektor-gadget/inspektor-gadget/pull/2751 made the resource cache more general and modified it so that pruning old objects is done periodically in the background with the help of a timer.
That means if the `CachedMap` is allocated, there is a goroutine running in the background for it.
We do not need that if the `KubeInventoryCache` is not running. Therefore this PR creates these maps on demand and closes them accordingly
=> kubeinvcache: Create the cachedmaps on demand

minikube.mk
Minikube v1.33.1 supports Kubernetes v1.30.0 but not v1.30.1. Switch to a supported version.
Using an unsupported version causes minikube to fetch a Kubernetes version list from internet, and this often causes the following error in the CI:
> ! Specified Kubernetes version 1.30.1 is newer than the newest supported version: v1.30.0. Use `minikube config defaults kubernetes-version` for details.
> ! Specified Kubernetes version 1.30.1 not found in Kubernetes version list
> * Searching the internet for Kubernetes version...
>
> X Exiting due to K8S_FAIL_CONNECT: error fetching Kubernetes version list from GitHub: GET https://api.github.com/repos/kubernetes/kubernetes/releases/tags/v1.30.1: 403 API rate limit exceeded for 172.183.154.99. (But here's the good news: Authenticated requests get a …
=> minikube.mk: switch minikube to use kubernetes v1.30.0

docs/crds/gadgets/ebpftop.md, docs/crds/gadgets/filetop.md, integration/ig/non-k8s/list_containers_test.go, integration/ig/non-k8s/snapshot_process_test.go, integration/ig/non-k8s/trace_dns_test.go, integration/ig/non-k8s/trace_network_test.go, integration/k8s/audit_seccomp_test.go, integration/k8s/enrichment_pod_label_test.go, integration/k8s/integration_test.go, integration/k8s/list_containers_test.go, integration/k8s/snapshot_socket_test.go, integration/k8s/trace_network_test.go, pkg/container-collection/options.go, pkg/gadgettracermanager/gadgettracermanager.go, pkg/ig-manager/ig-manager.go, pkg/types/types.go, pkg/utils/host/host.go
This PR picks up #2966, which was merged and then reverted in #3065.
This includes test fixes from #3066.
See #2966
- CI
In the next PR:
=> [2nd attempt] container-collection: add process metadata enricher

gadgets/snapshot_socket/program.bpf.c, gadgets/trace_dns/program.bpf.c, gadgets/trace_tcp/program.bpf.c, gadgets/trace_tcpconnect/program.bpf.c, gadgets/trace_tcpdrop/program.bpf.c, gadgets/trace_tcpretrans/program.bpf.c, include/gadget/types.h, pkg/datasource/accessors.go, pkg/datasource/columns.go, pkg/datasource/data.go, pkg/datasource/formatters/json/json.go, pkg/operators/formatters/formatters.go
This PR improves the way endpoints are formatted in the columns and json formats:
The columns output printed a lot of fields related to the endpoints:
```bash 
$ sudo -E ig run trace_tcpconnect:latest --verify-image=false
RUNTIME.CONTAINERNA… SRC… SRC… DST… DS… TASK       PID        UID        GID        MNTNS_… TIMESTAMP              SRC.ADDRE… DST.ADDRE…
netem                341… 6    80   6   wget       137202     0          0          4026534 2024-06-25T15:42:05.24 172.17.0.2 1.1.1.1:80
netem                454… 6    443  6   wget       137202     0          0          4026534 2024-06-25T15:42:05.36 172.17.0.2 1.1.1.1:44
netem                606… 6    443  6   wget       137202     0          0          4026534 2024-06-25T15:42:06.44 172.17.0.2 …
```
=> Improve endpoints formatter

gadgets/Makefile, gadgets/trace_bind/program.bpf.c
Commit 5bf9b54f0237 ("gadgets: Add trace_bind") and 243939491f74 ("formatter: Improve endpoints") were merged without rebasing one on top of the other. This plus missing the trace_bind entry on the Makefile caused the trace_bind gadget to be broken and being unnoticed by the CI.
=> gadgets/trace_bind: Fix trace_bind after formatters rework

gadget-container/gadgettracermanager/main.go
Fixes: #3014 
```
$ make minikube-deploy
$ ./kubectl-gadget run trace_open:latest -A
RUNTIME.CONTAINERNAME   PID          UID          GID          MNTNS_ID  ERR FD          COMM        FNAME                   TIMESTAMP
```
```
$ make minikube-deploy
$ ./kubectl-gadget run trace_open:latest -A
→ ./kubectl-gadget run trace_open -A
K8S.NAMESPACE        K8S.PODNAME          K8S.CONTAINERNAME    PID         UID         GID         MNTNS_ID E… FD          COMM       FNAME                 MODE       FLAGS      K8S.NODE   TIMESTAMP             
gadget               gadget-lsknt         gadget               844834      0           0           40265331  0 66          gadgettrac /sys/kernel/debug/tra …
```
=> gadgettracermanager: Set environment to Kubernetes

gadgets/trace_bind/test/trace_bind_test.go, gadgets/trace_sni/test/trace_sni_test.go, gadgets/trace_tcp/test/trace_tcp_test.go, pkg/testing/utils/types.go
The trace_sni gadget doesn't provide any information about endpoints, so the previous TODO was wrong.
=> gadgets: Test endpoints too

pkg/gadgets/audit/seccomp/tracer/tracer.go, pkg/gadgets/helpers.go, pkg/gadgets/trace/bind/tracer/tracer.go, pkg/gadgets/trace/capabilities/tracer/tracer.go, pkg/gadgets/trace/exec/tracer/tracer.go, pkg/gadgets/trace/fsslower/tracer/tracer.go, pkg/gadgets/trace/mount/tracer/tracer.go, pkg/gadgets/trace/oomkill/tracer/tracer.go, pkg/gadgets/trace/open/tracer/tracer.go, pkg/gadgets/trace/signal/tracer/tracer.go, pkg/gadgets/trace/tcp/tracer/tracer.go, pkg/gadgets/trace/tcpconnect/tracer/tracer.go, pkg/gadgets/trace/tcpdrop/tracer/tracer.go, pkg/gadgets/trace/tcpretrans/tracer/tracer.go, pkg/gadgets/traceloop/tracer/tracer.go, pkg/networktracer/tracer.go, pkg/operators/ebpf/tracer.go
Applications running in the same host with CAP_SYSADMIN are able to modify the ebpf maps created by other applications, this could cause Inspektor Gadget to stop receiving events if an application does it. 
In order to avoid that possibility, this PR freezes the perf ring buffers used by Inspektor Gadget, so they can't be changes from any other application. 
TODO after merging:
=> tree-wide: Freeze perf event array map

charts/gadget/templates/configmap.yaml, charts/gadget/templates/daemonset.yaml, charts/gadget/values.schema.json, charts/gadget/values.yaml, cmd/ig/daemon.go, cmd/kubectl-gadget/deploy.go, gadget-container/entrypoint/entrypoint.go, gadget-container/gadgettracermanager/main.go, pkg/config/gadgettracermanagerconfig/config.go, pkg/container-collection/k8s.go, pkg/gadget-service/service.go, pkg/resources/manifests/deploy.yaml
This PR allows specifying configuration related to ig-k8s using a configmap. It is mainly split into handling couple of different type of config:
1. config related to gadgettracermanager e.g (`hookMode`, `fallbackPodInformer`, etc) 
2. global params related to operators (currently we don't have any but will allow specify oci params: https://github.com/inspektor-gadget/inspektor-gadget/pull/2902)
Fixes: #2493 
Since I haven't removed the environment variable, we need to delete the env from the deployment and validate if config is working fine:
```
$ kubectl set env daemonsets -n gadget gadget INSPEKTOR_GADGET_OPTION_FALLBACK_POD_INFORMER-
$ kubectl get -n gadget cm gadget  -o yaml
apiVersion: v1
data:
config.yaml: |-
hook-mode: auto
fallback-pod-informer: false
events-buffer-length: 16384 …
```
=> config: Add support for ig-k8s

.github/workflows/inspektor-gadget.yml, gadgets/snapshot_process/gadget.yaml, gadgets/snapshot_socket/gadget.yaml, gadgets/trace_bind/gadget.yaml, gadgets/trace_capabilities/gadget.yaml, gadgets/trace_dns/gadget.yaml, gadgets/trace_exec/gadget.yaml, gadgets/trace_lsm/gadget.yaml, gadgets/trace_malloc/gadget.yaml, gadgets/trace_mount/gadget.yaml, gadgets/trace_oomkill/gadget.yaml, gadgets/trace_open/gadget.yaml, gadgets/trace_signal/gadget.yaml, gadgets/trace_sni/gadget.yaml, gadgets/trace_ssl/gadget.yaml, gadgets/trace_tcp/gadget.yaml, gadgets/trace_tcpconnect/gadget.yaml, gadgets/trace_tcpdrop/gadget.yaml, gadgets/trace_tcpretrans/gadget.yaml, pkg/datasource/accessors.go, pkg/datasource/columns.go, pkg/datasource/compat/wrapper.go, pkg/datasource/data.go, pkg/datasource/datasource.go, pkg/datasource/field_test.go, pkg/gadget-context/gadget-context.go, pkg/operators/cli/clioperator.go, pkg/operators/ebpf/struct.go, pkg/operators/formatters/formatters.go
This PR changes the way how the configuration of the fields is specified in the metadata file. It introduces a new datasources section that allows to (1) set annotations for the data source (will be used later for toppers and other support), (2) specify the 
field configuration. 
Check individual commits for more information. 
Run the gadgets and check that the output makes sense. Also, try changing the annotations in the metadata and check that they have an effect in the way fields are printed.
There are some things we could do later on:
Fixes #3052
=> gadgets: Forward config to datasources

pkg/datasource/data.go, pkg/datasource/field.go, pkg/operators/ebpf/struct.go
After https://github.com/inspektor-gadget/inspektor-gadget/commit/a81f33a, `ebpfoperator.Field` neither has the `Attributes` field nor implements `FieldAnnotations()` anymore. So, the ebpf operator is not anymore able to add field configuration when adding fields with `AddStaticFields()`. It prevents the ebpf operator from setting templates or even simply passing generic annotations.
Additionally, this PR cleans up the management of the hidden configuration.
Image-based gadgets must work as before.
**NOTE**: The ebpf operator will use field annotations for topper and profilers cc @flyth 
I tested it by applying the hidden annotation from ebpf operator and verifying that none of the fields added by the epbf operator were displayed. This test should validate both commits:
```
diff --git …
```
=> pkg/operators/ebpf: Allow passing field configuration as annotations

README.md
This is the first link that we provide on the README for a documentation and right now it's just pointing to a TOC that you wouldn't really understand as a non-developer. Pointing it to the rendered version on the official website is much more suited for general audiences.
(Was on a call with @mqasimsarfraz and we discovered this randomly when talking about the docs)
=> docs: point to the installation instructions on the IG website instead of the TOC on the repo

docs/devel/hello-world-gadget.md, pkg/gadgets/run/types/metadata.go
- Remove extra ':' on description field
- Fix outdated comment on getTracerInfo()
- Improve comment on validateTracerMap()
Fixes: f7c317e0cfeb ("gadgets/run: Update logic to generate and validate metadata")
Ref #3164
=> metadata: Fix leftovers after review

.github/workflows/scorecard-analysis.yml, README.md
- CI: scorecard-analysis: Add config for OpenSSF scorecard
- README: Add OpenSSF scorecard badge
This is required by CNCF projects to move to incubated stage.
Additionally, once merged it gives more code scanning results in the Security tab -> Code Scanning section on github.
https://github.com/inspektor-gadget/inspektor-gadget/security/code-scanning
Once merged click on the badge in the README.
Note, `inspektor-gadget/inspektor-gadget` isn't already scanned by OpenSSF, so it does not have data for it yet. To get the data, the action will have to be run manually the first time, OR wait for the badge results to be updated once daily. The action is run daily via github action cron.
We use it in the headlamp repo, and it uses the OpenSSF template for the workflow.
=> CI: README: Add OpenSSF scorecard badge

pkg/gadget-context/run.go
Without calling cancel on the gadgetContext itself, we're leaking memory as many goroutines won't exit. Although we should probably also optimize and use local synchronization in operators (and waiting for cleanup on Stop()), this makes sure that at least when exiting gadgetcontext.run(), everything gets cancelled.
=> gadget-context: make sure cancel() is called on gadgetContext

pkg/operators/ebpf/ebpf.go, pkg/operators/ebpf/formatters.go, pkg/operators/ebpf/struct.go
This moves the logic from using a map to using an array to fix desync issues when using several nodes.
We still need to address a couple more cases where things like this can happen to make sure the gadgetInfo will always be deterministic.
Fixes #3185
=> pkg/operators/ebpf: make enum handling deterministic

gadgets/trace_bind/gadget.yaml, gadgets/trace_bind/program.bpf.c, gadgets/trace_bind/test/trace_bind_test.go, gadgets/trace_exec/gadget.yaml, gadgets/trace_exec/program.bpf.c, gadgets/trace_exec/test/trace_exec_test.go, gadgets/trace_mount/gadget.yaml, gadgets/trace_mount/go/program.go, gadgets/trace_mount/program.bpf.c, gadgets/trace_mount/test/trace_mount_test.go, gadgets/trace_open/gadget.yaml, gadgets/trace_open/program.bpf.c, gadgets/trace_open/test/trace_open_test.go, gadgets/trace_signal/gadget.yaml, gadgets/trace_signal/program.bpf.c, gadgets/trace_signal/test/trace_signal_test.go, gadgets/trace_ssl/gadget.yaml, gadgets/trace_ssl/program.bpf.c, gadgets/trace_tcpconnect/gadget.yaml, gadgets/trace_tcpconnect/program.bpf.c, include/gadget/types.h, pkg/datasource/columns.go, pkg/operators/formatters/formatters.go
```
$ go run --exec "sudo -E" ./cmd/ig/... run t --verify-image=false --fields task,src,dst,retcode
WARN[0000] Ignoring runtime "podman" with non-existent socketPath "/run/podman/podman.sock" 
WARN[0000] you set --verify-image=false, image will not be verified 
WARN[0000] you set --verify-image=false, image will not be verified 
TASK       SRC                      DST                   RETCODE            
wget       172.17.0.2:51382         1.1.1.1:80                               
wget       172.17.0.2:45834         1.1.1.1:443                              
wget       172.17.0.2:45846         1.1.1.1:443                              
wget       0.0.0.0:0                192.168.2.1:0         ECONNREFUSED       
wget       0.0.0.0:0 …
```
=> gadgets: Provide human readable version of error codes

include/gadget/macros.h, pkg/gadget-service/api-helpers/apihelpers.go, pkg/operators/cli/clioperator.go, pkg/operators/cli/helpers.go, pkg/operators/ebpf/ebpf.go, pkg/operators/ebpf/maps.go, pkg/operators/ebpf/rawbpf.go, pkg/operators/ebpf/types.go
Map iterators are the base of (most) toppers and profilers. Gadgets write data into maps that are regularly fetched (and emptied) into data sources.
Follow-up PRs will be
* support for toppers
* support for profilers
* export from those maps directly to otel-metrics
In addition to the map iterators, this PR also adds the features shared by those follow-up PRs:
* perform a clear screen before outputting data from the CLI operator if the `cli.clear-screen-before` annotation is present on the data source
* add a `none` output mode to the CLI operator, that is basically ignoring the data
* helpers to get per-datasource values from params
=> image-based gadgets: introduce map iterators

Dockerfiles/ebpf-builder.Dockerfile, Dockerfiles/gadget.Dockerfile, Dockerfiles/ig-tests.Dockerfile, Dockerfiles/ig.Dockerfile, Dockerfiles/kubectl-gadget.Dockerfile, docs/ig.md, examples/builtin-gadgets/withfilter/trace/network/Dockerfile, examples/kube-container-collection/Dockerfile, examples/runc-hook/Dockerfile
There was a single `as` keyword that was lowercase. While building the image we get a warning:
```
1 warning found (use --debug to expand):
- FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 9)
```
=> ebpf-builder.Dockerfile: Use uppercase keyword

.github/workflows/inspektor-gadget.yml
Fixes https://github.com/inspektor-gadget/inspektor-gadget/security/code-scanning/254
=> ci: Pin go install command to hash

pkg/testing/ig/ig.go
```bash
$ IG_PATH=ig IG_EXPERIMENTAL=true GADGET_REPOSITORY=$LOCAL_REPO GADGET_TAG=latest IG_FLAGS='--insecure --public-keys=' IG_RUNTIME=docker go test -exec 'sudo -E' -v ./...
=== RUN   TestTraceExec
command.go:111: Start command(Run_trace_exec)
docker.go:152: Container "test-trace-exec" output:
command.go:128: Stop command(Run_trace_exec)
command.go:130: Command returned(Run_trace_exec):
time="2024-07-24T18:43:55+02:00" level=info msg="Experimental features enabled"
Error: fetching gadget information: initializing and preparing operators: instantiating operator "oci": ensuring image: verifying image "127.0.0.1:5000/trace_exec:latest": getting signing information: getting signature: getting signature bytes: Get "https://127.0.0.1:5000/v2/trace_exec/manifests/sha256-e53472850099542387144b …
```
=> pkg/testing/ig: Support more than one flag on IG_FLAGS env variable

gadgets/snapshot_process/test/snapshot_process_test.go, gadgets/top_file/gadget.yaml, gadgets/top_file/program.bpf.c, gadgets/top_file/test/top_file_test.go, include/gadget/macros.h, pkg/gadgets/run/types/metadata.go
Use map iterators datasource introduced in https://github.com/inspektor-gadget/inspektor-gadget/pull/3182 to run top_file gadget.
Ref https://github.com/inspektor-gadget/inspektor-gadget/issues/1924
Tests where implemented using new testing framework.
=> gadgets: Update top_file to use map iterators instead of toppers

gadgets/trace_exec/gadget.yaml, gadgets/trace_exec/program.bpf.c, include/gadget/types.h, pkg/operators/uidgidresolver/uidgidresolver.go
This PR introduces the UidGidResolver to the image based gadgets world. The second commit then showcases how it can be used in `trace_exec`
=> UidGidResolver: Make it usable in image based gadgets

cmd/common/utils/flags.go, cmd/kubectl-gadget/deploy.go, docs/core-concepts/images.md, integration/components/image/image_test.go, integration/k8s/run_insecure_test.go, pkg/config/gadgettracermanagerconfig/config.go, pkg/oci/oci.go, pkg/operators/oci-handler/oci.go
- Allow list of registries instead of global on / off flag
- Move argument to be global (configurable only by admins)
- Add support in kubectl-gadget deploy
An insecure registry can be created on the local host by running 
```bash 
docker run -d -p 5000:5000 --restart always --name registry registry:2
```
Build / tag an image and push it to this registry
```bash 
sudo -E ig image push 192.168.1.16:5000/trace_open:latest --insecure-registries="192.168.1.16:5000"
```
```bash 
$ sudo -E ig run 192.168.1.16:5000/trace_open:latest --verify-image=false --insecure-registries="192.168.1.16:5000" --pull=always
$ sudo -E ig run 192.168.1.16:5000/trace_open:latest --verify-image=false --insecure-registries="192.168.1.16:5000,foo.com" --pull=always
$ sudo -E ig run 192.168.1.16:5000/trace_open:latest …
```
=> Improve insecure registries support

gadgets/trace_dns/build.yaml, gadgets/trace_dns/gadget.yaml, gadgets/trace_dns/go/go.mod, gadgets/trace_dns/go/go.sum, gadgets/trace_dns/go/program.go, gadgets/trace_dns/program.bpf.c, gadgets/trace_dns/test/trace_dns_test.go, gadgets/trace_exec/go/go.mod, gadgets/trace_mount/go/go.mod, gadgets/trace_open/go/go.mod, pkg/container-utils/testutils/container_interface.go, pkg/container-utils/testutils/docker.go, pkg/container-utils/testutils/k8s.go, pkg/operators/wasm/fields.go, wasmapi/go/fields.go
This commit is very similar to d772f2ef04c7 ("dns: Parse DNS packet in user space"),
but in this case the parsing is done in wasm because it's an image-based
gadget.
Unfortunately it seems that using gopacket with tinygo isn't possible,
so I decided to use golang.org/x/net/dns/dnsmessage that provides
the functionality we need.
--- 
Opening as draft until #3076 is merged. Feedback is already welcome. 
Fixes #2999
=> Finish porting trace dns to image-based gadget

cmd/common/oci.go, gadgets/snapshot_process/test/snapshot_process_test.go, pkg/datasource/data.go, pkg/datasource/datasource.go, pkg/gadget-context/gadget-context.go, pkg/gadget-context/run.go, pkg/gadget-service/api/consts.go, pkg/operators/combiner/combiner.go, pkg/operators/ebpf/ebpf.go, pkg/operators/ebpf/maps.go, pkg/runtime/grpc/oci.go, pkg/runtime/runtime.go
This PR introduces a new operator named "combiner". Only for `TypeArray` datasources, this operator will be in charge of merging outcomes from all targets into a single array on the client side.
- The combiner operator will activate itself only if:
- Gadget is run against more than one single target. For instance, it'll never get activated for `ig` used as standalone (without `gadgetctl`).
- There is at least one `TypeArray` datasources. **NOTE**: From now on, this documentation will assume that the datasources are `TypeArray`.
- The combiner operator requires the datasource to be annotated with `FetchIntervalAnnotation`, which is expected to be `time.Duration` type and is used as following:
- If `FetchIntervalAnnotation` is 0, the combiner operator will emit a packet once it has received …
=> pkg/operators: Add combiner

cmd/common/oci.go, examples/gadgets/operators/otel_metrics/main.go, gadgets/Makefile, gadgets/profile_blockio/gadget.yaml, gadgets/profile_blockio/program.bpf.c, include/gadget/types.h, pkg/datasource/accessors.go, pkg/datasource/formatters/json/json.go, pkg/gadget-context/gadget-context.go, pkg/gadget-context/options.go, pkg/gadget-service/api/consts.go, pkg/gadget-service/service-oci.go, pkg/operators/cli/clioperator.go, pkg/operators/ebpf/struct.go, pkg/operators/operators.go, pkg/operators/otel-metrics/otel-metrics.go, pkg/operators/otel-metrics/otel-metrics_test.go, pkg/runtime/runtime.go
This implements support for profiler gadgets as image-based gadgets. It is based on top of the map iterators introduced in #3182.
Additionally, the otel-metrics operator has been updated to support histograms from int/float arrays (which also have been added to the datasources package in this PR).
As an example, the `profile_blockio` gadget has been translated (thanks to @eiffel-fl for covering almost all of it). Please take a look at the attached `gadget.yaml` file to see annotations that help achieving the original behavior of that gadget. In this specific case, the gadget will not export metrics to a Prometheus endpoint, but rather - only on the client side - render the metrics to a human-readable format, which is then picked up by the CLI operator to actually be printed. For that to …
=> image-based gadgets: add support for profiler gadgets

README.md
We want to let users know about the new changes and vision of the project. So, adding a link to the README for the blog post explaining that.
=> Add link to v0.31.0 post in README

gadgets/top_tcp/artifacthub-pkg.yml
Fixes: 7cdb3c733e7a ("gadgets: Add top_tcp as image based gadget")
The date was invalid and was causing the following error in artifact hub:
> error getting package metadata (path: /tmp/artifact-hub3521047503/gadgets/top_tcp): error validating package metadata file: 1 error occurred:
>	* invalid metadata: invalid createdAt (RFC3339 expected): parsing time "2024-07-026T09:22:04Z" as "2006-01-02T15:04:05Z07:00": cannot parse "6T09:22:04Z" as "T"
=> gadgets/top_tcp: fix typo in date

gadgets/trace_tcpconnect/test/trace_tcpconnect_test.go
fixes: #3240
- added test for gadgets/trace_tcpconnect
- the struct for expectedEntry is created with taking into account the map in bpf file.
cc @mauriciovasquezbernal @alban
=> feat(test): added test for gadgets/trace_tcpconnect

gadgets/snapshot_process/test/snapshot_process_test.go
This makes sure that our test container has already spawned and is running the command we want to see in the snapshot
We have many flaky CI failures on `snapshot_process`. This should fix it
=> snapshot_process: Sleep before starting the gadget

.github/workflows/inspektor-gadget.yml
This PR removes the `strategy` section from the `.github/workflows/inspektor-gadget.yml` file. The `strategy: fail-fast: false` lines were causing issues with the workflow execution, specifically triggering a "Missing property 'matrix'" error.
Review the changes in the .github/workflows/inspektor-gadget.yml file.
=> gha: Remove unneeded strategy on workflow file

pkg/container-collection/containers.go, pkg/container-collection/options.go, pkg/datasource/compat/wrapper.go, pkg/types/types.go
When using the `KubernetesEnrichment` resolve also the Owner Kind and Owner Name. Partially solves https://github.com/inspektor-gadget/inspektor-gadget/issues/3260
For `ig w/ K8s` we need to talk to the API server. This is still TODO, needs to be discussed and should be optional (either enrichment failing siliently or actived through flag)
```
./kubectl-gadget run trace_exec -n gadget --fields k8s.podname,k8s.owner.kind,k8s.owner.name,comm
K8S.PODNAME                        K8S.OWNER.KIND     K8S.OWNER.NAME     COMM            
gadget-mdwnx                       DaemonSet          gadget             gadgettracerman 
gadget-mdwnx                       DaemonSet          gadget             gadgettracerman 
```
```
./kubectl-gadget trace exec -n gadget -o …
```
=> container-collection: Add OwnerKind and OwnerName to K8sEnrichment

gadgets/audit_seccomp/artifacthub-pkg.yml, gadgets/profile_blockio/artifacthub-pkg.yml, gadgets/snapshot_process/artifacthub-pkg.yml, gadgets/snapshot_socket/artifacthub-pkg.yml, gadgets/top_file/artifacthub-pkg.yml, gadgets/top_tcp/artifacthub-pkg.yml, gadgets/trace_bind/artifacthub-pkg.yml, gadgets/trace_capabilities/artifacthub-pkg.yml, gadgets/trace_dns/artifacthub-pkg.yml, gadgets/trace_exec/artifacthub-pkg.yml, gadgets/trace_lsm/artifacthub-pkg.yml, gadgets/trace_malloc/artifacthub-pkg.yml, gadgets/trace_mount/artifacthub-pkg.yml, gadgets/trace_oomkill/artifacthub-pkg.yml, gadgets/trace_open/artifacthub-pkg.yml, gadgets/trace_signal/artifacthub-pkg.yml, gadgets/trace_sni/artifacthub-pkg.yml, gadgets/trace_ssl/artifacthub-pkg.yml, gadgets/trace_tcp/artifacthub-pkg.yml, gadgets/trace_tcpconnect/artifacthub-pkg.yml, gadgets/trace_tcpdrop/artifacthub-pkg.yml, gadgets/trace_tcpretrans/artifacthub-pkg.yml
This PR was supposed to be done automatically by `.github/workflows/release.yml` but it failed:
https://github.com/inspektor-gadget/inspektor-gadget/actions/runs/10254676159/attempts/1
Hence making this PR manually.
```bash
inspektor_gadget_version=v0.31.0
DATE="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
for PKGFILE in $(find gadgets/ -name artifacthub-pkg.yml) ; do
sed -i -e "s/^version:.*$/version: ${inspektor_gadget_version}/" -e "s/^createdAt:.*$/createdAt: \"${DATE}\"/" -e "s/^digest:.*$/digest: \"${DATE}\"/" $PKGFILE
done
```
=> Post-release: update gadgets version to v0.31.0

.github/workflows/update-website.yaml
I forced pushed this branch before adding the path filter and removing the citest/** branch and the workflow was executed in https://github.com/inspektor-gadget/website/actions/runs/10359315537. 
- Should it replace https://github.com/inspektor-gadget/website/blob/main/.github/workflows/update-inspektor-gadget-release.yaml? (i.e. run this also when a release is done)
=> ci: Automatically update website on push

cmd/common/image/Makefile.build
Local builds ("ig image build -l") can fail if tinygo or go is too old.
On Fedora 38, I only have tinygo 0.30.0 and go 1.21.10 and those versions are not working.
With this patch, I can successfully build gadgets locally ("-l"). Example of commands:
```
sudo -E TINYGO=/home/alban/programs/tinygo/tinygo/bin/tinygo GOROOT=/home/alban/programs/golang/go ../ig image build trace_open -l
make  trace_open GADGET_BUILD_PARAMS="-l" TINYGO=/home/alban/programs/tinygo/tinygo/bin/tinygo GOROOT=/home/alban/programs/golang/go
```
=> image build: allow alternative tinygo

docs/gadget-devel/program-types.md, docs/gadgets/builtin/profile/tcprtt.md
The broken link job fails often with elixir:
https://github.com/inspektor-gadget/inspektor-gadget/actions/runs/10391104393/job/28773219330
=> docs: Use GitHub instead of elixir

docs/gadgets/trace_lsm.mdx, docs/gadgets/trace_malloc.mdx, docs/gadgets/trace_signal.mdx, docs/gadgets/trace_ssl.mdx, docs/gadgets/trace_tcpconnect.mdx
Fixes: f609533acb47 ("gadgets/readmes: update all gadgets documentation")
=> docs: Add missing symlink to render gadget documentation

docs/gadget-devel/gadget-ebpf-api.md, docs/reference/operators/uidgidresolver.mdx
Is this the way we want to document the dataoperators?
=> docs/op: Add UidGidResolver documentation

docs/quick-start.md
Source for the Mermaid diagram:
```
flowchart TD
W{{Where to run Inspektor Gadget?}}
W -->|Linux system| L[How long?]
W -->|Kubernetes| K[How long?]
L --> |Just one command| ig1>ig run trace_exec]
L --> |Long running| ig2>ig daemon + gadgetctl]
K --> |Just one command| ku1>kubectl debug ...]
K --> |Long running| ku2>kubectl gadget]
```
[ describe the change in 1 - 3 paragraphs ]
=> docs: add diagrams for running modes

cmd/ig/containers/containers.go, docs/reference/ig.md, pkg/ig-manager/ig-manager.go, pkg/ig-manager/ig-manager_test.go, pkg/operators/localmanager/localmanager.go
Two new flags are added:
1. `--with-k8s-apiserver` to enable this optional enrichment
2. `kubeconfig` to point to a kubeconfig file if it isn't in the default path(s) (Split into #3370)
One has to supply a `kubeconfig` file with is allowed to query `DaemonSets`, ...
This works for builtin gadgets and image based gadgets.
```json
$ ig trace exec -o json --with-k8s-apiserver --kubeconfig /minikube.conf
{
"args": "/usr/sbin/iptables -w 5 -W 100000 -S KUBE-PROXY-CANARY -t mangle",
"comm": "iptables",
....
"k8s": {
"containerName": "kube-proxy",
"hostnetwork": true,
"namespace": "kube-system",
"node": "",
"owner": {
"kind": "DaemonSet",
"name": "kube-proxy"
},
"podName": "kube-proxy-9zf67"
},
....
}
{
"args": "/bin/gadgettracermanager -liveness",
"comm": "gadgettracerman",
....
"k8s": { …
```
=> ig: Add optional further K8s enrichment (Ownertype and Ownername in this PR)

docs/gadget-devel/metadata.md
Fixes: bd96ebeee690 ("columns: add support for displaying event data in Hex format")
=> docs: Add missing columns.hex annotation

examples/go.mod, examples/go.sum, go.mod, go.sum, pkg/gadgets/trace/dns/tracer/tracer.go
The google/gopacket package seems to be unmaintained, last commit was two years ago. Switch to the gopacket/gopacket fork which seems to be actively maintained.
This change also fixes as gopacket/gopacket has a new release including commit https://github.com/google/gopacket/commit/65a1dfb3db2ad85763f26417f8699486bc253369.
---
This was [reported](https://kubernetes.slack.com/archives/CSYL75LF6/p1724251867143229)1 in Slack by @amitschendel 
> Hey! we are using the dns tracer and we got this:
panic: runtime error: slice bounds out of range [:1435] with capacity 1434
> 
> ```
> goroutine 1992 [running]:
> github.com/google/gopacket/layers.(*DNSResourceRecord).decode(0xc02e8b3860, {0xc00b304e9a, 0x59a, 0x59a}, 0x2abf600?, {0x1?, 0xc022f98650?}, 0xc004551908)
> …
```
=> Switch to gopacket/gopacket

pkg/datasource/columns.go
Before this patch, a gadget could show the following:
```
$ sudo ig run mygadget --fields=pcomm,ppid,comm,pid,name
PCOMM                                                             PPID COMM                                                              PID NAME
sh                                                             1795261 wget                                                          2137524 www.wikipedia.org.
```
After this patch, it shows:
```
$ sudo ig run mygadget --fields=pcomm,ppid,comm,pid,name
PCOMM                  PPID COMM                    PID NAME
sh                  1795261 wget                2144726 www.wikipedia.org.
```
Tested while working on #2684.
=> columns template: add max size on some fields

.github/dependabot.yml
Update rules to match at the org level for docker and moby.
Hopefully this will fix this error message:
updater | 2024/08/28 03:32:00 WARN <job_875214778> Please check your configuration as there are groups where no dependencies match:
- docker
This can happen if:
- the group's 'pattern' rules are misspelled
- your configuration's 'allow' rules do not permit any of the dependencies that match the group
- the dependencies that match the group rules have been removed from your project
And actually group those PRs.
--- 
For instance, the following PRs should be grouped after this change:
- #3409  
- #3407 
- #3408
=> dependabot: Fix groups

cmd/common/oci.go, docs/reference/operators/limiter.md, gadget-container/gadgettracermanager/main.go, pkg/datasource/data.go, pkg/datasource/datasource.go, pkg/datasource/datasource_test.go, pkg/gadget-service/api-helpers/aphelpers_test.go, pkg/gadget-service/api-helpers/apihelpers.go, pkg/operators/limiter/limiter.go, pkg/operators/otel-metrics/otel-metrics.go
This PR introduces the `Limiter` data operator which operates on array data sources by limiting the number of entries in each batch of data. A great scenario for this operator is when you are already sorting data within an array of data and you want to filter out the top `X` entries. 
This operator has lower priority than combiner (if it's enabled) and sorted (to limit after things are sorted).
Notice this functionality was known as `max-rows` in built-in gadgets. However, it was changed to `max-entries` as it also limit the number of entries in the JSON or any other kind of output.
Refer https://github.com/inspektor-gadget/inspektor-gadget/issues/1924
=> pkg/operators: Add limiter

pkg/datasource/columns.go
After https://github.com/inspektor-gadget/inspektor-gadget/pull/3401, I propose to always set the maximum width to the maximum number of characters an integer and bool can use. 
This PR also adds support for "type" special value in the field annotations for the Width, MaxWidth and MinWidth field attributes.
Before and after this PR, the output for the following command is still the same:
```bash
$ go run --exec "sudo" ./cmd/ig/... run $MY_REPO/trace_exec --verify-image=false --insecure-registries=$LOCAL_REPO --pull always --fields=pcomm,ppid,comm,pid
PCOMM                  PPID COMM                    PID
```
=>  pkg/datasource/columns: Default MaxWith attribute based on field type (For int and bool)

gadgets/top_file/README.mdx, gadgets/top_file/gadget.yaml, gadgets/top_file/program.bpf.c, gadgets/top_file/test/top_file_test.go
- Modified the File parameter in `top_file` gadget to show the absolute file path
run top_file gadget, and create a pod and put some data into a file 
Just followed steps as mentioned in the [documentation](https://inspektor-gadget.io/docs/latest/gadgets/top_file)
- Before modifying the code, I ran the `top_file` gadget:
```bash
sudo -E ig run top_file:latest --containername test-top-file
```
> this would capture all the events running on the container with name test-top-file.
- Then I opened another terminal and ran the following commands to create a container named test-top-file and exec into it:
```bash
docker run --rm --name test-top-file -it ubuntu /bin/sh
```
- Then in the container, I ran the following command 
```bash
echo trail > /foo.txt & echo trail > /home/foo.txt
```
- and …
=> gadgets/top_file: Provide full file path

docs/reference/run.mdx, pkg/operators/cli/clioperator.go
Now able to remove fields,  when specified like this `sudo -E ./ig run trace_exec:latest --fields=-timestamp`
Yes, I've recreated ig binary and tested it locally.
fixes: #3267
=> clioperator: Add support for adding / removing fields with --fields

pkg/operators/otel-metrics/otel-metrics.go
Before this change, the operator would automatically flag every member of a map key as metrics.type=key. That however also affected types that were not suited for being a metrics key and thus led to an error. After this change, keys have to be explicitly set.
=> pkg/operators/otel-metrics: don't automatically apply metrics type based on role tag

pkg/datasource/data.go
Similar to https://github.com/inspektor-gadget/inspektor-gadget/pull/3293 and https://github.com/inspektor-gadget/inspektor-gadget/pull/3271, we are not using the `FullName` to look for fields. This prevents us from correctly annotating fields.
Try to annotate fields with parent like this:
```bash
diff --git a/gadgets/top_tcp/gadget.yaml b/gadgets/top_tcp/gadget.yaml
index d942a1aa51c6..dcd89c74c7bd 100644
--- a/gadgets/top_tcp/gadget.yaml
+++ b/gadgets/top_tcp/gadget.yaml
@@ -8,6 +8,9 @@ datasources:
annotations:
cli.clear-screen-before: "true"
fields:
+      runtime.containername:
+        annotations:
+          columns.hidden: true
mntns_id:
annotations:
description: Mount namespace inode id
```
Then, build and push the gadget:
```bash
$ go run ./cmd/ig/... image build -t …
```
=> pkg/datasource: Use FullName to look for fields in config

pkg/cachedmap/cachedmap.go, pkg/operators/common/kubeinventorycache.go
Checking pprof on big clusters (45k Pods) led to discover that a lot of CPU was wasted iterating over the map to run a func, which is the current method to match Pod IP addresses in the cache.
This PR proposes a second map indexed directly on IP addresses to fix that.
Was tried in kubescape's node-agent https://github.com/kubescape/node-agent/pull/362 and deployed on that huge cluster where we checked the better performance of the tracers.
=> Add a second map to get pods and svcs by IP without GetCmp

docs/spec/oci.md, pkg/oci/build.go
The documentation in [0] states we can set the artifactType in all cases, do it to simplify the logic.
[0]: https://github.com/opencontainers/image-spec/blob/main/manifest.md#guidelines-for-artifact-usage
See https://github.com/inspektor-gadget/inspektor-gadget/pull/2572#discussion_r1752171717
I still don't think `application/vnd.gadget.ebpf.program.v1+binary` is right. IMO it should be something like `application/vnd.gadget+binary` as the manifest refers to the whole gadget, not a single layer. 
See previous discussion on https://github.com/inspektor-gadget/inspektor-gadget/pull/2177#discussion_r1370713366 too.
=> oci: Set artifactType in all cases

gadgets/top_tcp/program.bpf.c
Given that the `sent` and `received` fields act already as counters, let's use the `gadget_counter__u32` type to make Inspektor Gadget manage them as metric counters. Doing so, we simplify the users' life because they will just need to select the key to make Inspektor Gadget start exporting the metrics for the `tcp` datasource.
Once we agree it's fine, I'll do the same for other top gadgets.
This change has no impact if metrics collection is disable.
All the testing was done on top of https://github.com/inspektor-gadget/inspektor-gadget/pull/3468.
Build gadget:
```bash
ig image build -t $CUSTOM_REPO/top_tcp:metrics-export gadgets/top_tcp
ig image push $CUSTOM_REPO/top_tcp:metrics-export
```
Start daemon with metrics listener enabled:
```bash
sudo ig daemon -H tcp://$IG_TARGET:9999 \ …
```
=> gadgets/top_tcp: Mark received and sent fields as metric counters

docs/gadgets/deadlock.mdx, gadgets/Makefile, gadgets/deadlock/README.md, gadgets/deadlock/README.mdx, gadgets/deadlock/artifacthub-pkg.yml, gadgets/deadlock/gadget.yaml, gadgets/deadlock/program.bpf.c, gadgets/fsnotify/README.mdx, gadgets/profile_blockio/README.mdx, gadgets/profile_tcprtt/README.mdx, gadgets/snapshot_process/README.mdx, gadgets/snapshot_socket/README.mdx, gadgets/top_file/README.mdx, gadgets/top_tcp/README.mdx, gadgets/trace_bind/README.mdx, gadgets/trace_capabilities/README.mdx, gadgets/trace_dns/README.mdx, gadgets/trace_exec/README.mdx, gadgets/trace_lsm/README.mdx, gadgets/trace_malloc/README.mdx, gadgets/trace_mount/README.mdx, gadgets/trace_oomkill/README.mdx, gadgets/trace_open/README.mdx, gadgets/trace_signal/README.mdx, gadgets/trace_sni/README.mdx, gadgets/trace_ssl/README.mdx, gadgets/trace_tcp/README.mdx, gadgets/trace_tcpconnect/README.mdx, gadgets/trace_tcpdrop/README.mdx, gadgets/trace_tcpretrans/README.mdx
Adds a basic gadget that traces mutex acquisitions and releases. This gadget will be extended to detect potential deadlocks.
1. Run the gadget using `ig`.
2. Run a simple script that uses the `pthread_mutex_lock` and `pthread_mutex_unlock` methods, in a container.
3. Observe trace.
Followed the above steps with the following `test` [script](https://github.com/iovisor/bcc/blob/master/tools/deadlock_example.txt#L187).
**Output**:
=> gadgets: add gadget to trace mutex locks/unlocks

gadgets/zz_daemon/daemon_test.go
The cosign key is not available when running the tests on the CI for external contributors or dependabot, it means that this test will fail because the signature can't be found.
Introduce logic to pass IG_FLAGS to "ig daemon" to disable the image verification when needed.
Fixes: c837450e4e4b ("add tests for ig --daemon in headless mode")
See #3514
cc @flyth @burak-ok
=> gadgets: Fix headless test

docs/gadgets/top_blockio.mdx, gadgets/Makefile, gadgets/top_blockio/README.md, gadgets/top_blockio/README.mdx, gadgets/top_blockio/artifacthub-pkg.yml, gadgets/top_blockio/gadget.yaml, gadgets/top_blockio/program.bpf.c, gadgets/top_blockio/test/top_blockio_test.go, gadgets/top_file/test/top_file_test.go, gadgets/top_tcp/test/top_tcp_test.go, gadgets/trace_capabilities/test/trace_capabilities_test.go, pkg/operators/ebpf/attach.go
This PR adds `top_blockio` as image based gadgets
Our builtin gadget supports kernel versions `<5.17` and `>6.5`. This is done through trying to attach the tracepoints/kprobes. Currently this can't be done with image based gadgets (#3274)
Fixes #2989
EDIT:
When having an encrpyted disk with `ig` it seems that the `--host` flag is needed. The event also shows up like the following:
```
RUNTIME.CONTAINERNAME      PID MAJOR        MINOR        COMM             BYTES              US                 IO                 RW   
485 259          0            dmcrypt_write/2  397312             8152               10                 write
0 259          0                             0                  2124               1                  read
```
=> Add top_blockio

pkg/operators/ebpf/ebpf.go
When running a faulty gadget containing ebpf code that gets rejected by the verifier, now the full 
verifier log is printed.
Fixes #3462
Pass `-v` flag to `ig run`. 
Run `sudo ig run -v ...` with a gadget rejected by the ebpf verifier.
=> feat: add verifier debug output when running faulty ebpf gadget

pkg/k8sutil/client.go, pkg/operators/common/kubeinventorycache.go
The kubeipresolver needs to watch ALL pods and services in the cluster to be able to enrich network events with the service / pod information. The memory usage can become critical in clusters with thousands of pods. This commit optimizes it by doing two different things:
- Use protobuf instead of json: The protobuf encoding is more efficient than json. It's supported by the kube-apiserver from 8 years ago, so compability is not an issue.
- Define a SlimPod and SlimService structures: We only need few fields from the pod/service, define smaller structs to avoid storing a lot of data we don't care about. This uses the Transform() support from the shared informer.
This is only relevant in clusters with a lot of pods, so let's create a minikube cluster with 40k pods. (don't worry, we don't …
=> operators/kubeipresolver: Improve memory consumption

cmd/common/oci.go, cmd/common/runwithspec_test.go, docs/reference/manifests.mdx, gadgets/trace_fsslower/gadget.yaml, gadgets/trace_fsslower/test/trace_fsslower_test.go, pkg/gadget-manifest/instance-spec.go
This allows specifying a manifest file using the "-f" flag.
Gadget instance specs can look like this:
```yaml
version: 1
kind: instance-spec
imageName: trace_exec
name: yoyo
tags:
- foo
- bar
paramValues:
operator.LocalManager.host: true
---
version: 1
kind: instance-spec
imageName: trace_exec
name: gagaga
tags:
- second
paramValues:
operator.oci.wasm.gadget_a: 1212
operator.oci.ebpf.gadget_a: 1212
operator.LocalManager.host: true
```
When defining multiple specs inside the file like that, this functionality can only be used in combination with `--detach`.
=> cmd/common: allow to specify gadget runtime configuration using "-f"

.github/workflows/inspektor-gadget.yml, gadgets/Makefile
This reverts commit 9f4cc8109141ef2d54734c0c8a4147034561321f.
"ig image build" doesn't work well on parallel, see issue #3554.
=> Revert "ci: Use -j$(nproc) with gadgets Makefile."

docs/reference/configuration.md, gadgets/trace_bind/README.mdx, gadgets/trace_capabilities/README.mdx, gadgets/trace_exec/README.mdx, gadgets/trace_mount/README.mdx, gadgets/trace_open/README.mdx, pkg/operators/localmanager/localmanager.go
In most of the cases users don't have all runtimes available, these warnings are very noisy. This commit updates the logic to avoid printing any warning if the runtime path is not set, if it's set then an error is returned.
```bash 
$ sudo ig run trace_open:latest --pull always
WARN[0000] Ignoring runtime "cri-o" with non-existent socketPath "/run/crio/crio.sock"
WARN[0000] Ignoring runtime "podman" with non-existent socketPath "/run/podman/podman.sock"
RUNTIME.CONTAINERNAME     COMM                 PID        TID        UID        GID  FD FNAME                    MODE          ERROR
$ sudo ig run trace_open:latest --pull always --docker-socketpath=nonexistingpath
WARN[0000] Ignoring runtime "docker" with non-existent socketPath "nonexistingpath"
WARN[0000] Ignoring runtime "cri-o" with …
```
=> operators/localmanager: Do not print warning if the runtime is not found

.github/workflows/release.yml
It seems the release workflow has been failing for past few release because of missing permissions:
- https://github.com/inspektor-gadget/inspektor-gadget/actions/runs/11211512604/job/31160543248#step:6:1720
- https://github.com/inspektor-gadget/inspektor-gadget/actions/runs/10664736937/job/29556607272#step:6:190
- https://github.com/inspektor-gadget/inspektor-gadget/actions/runs/10254676159/job/28369971796#step:6:188
This change fixes the permission issues that was introduced by https://github.com/inspektor-gadget/inspektor-gadget/pull/3197
cc: @burak-ok @alban
=> ci: Fix permission for release workflow

gadgets/audit_seccomp/artifacthub-pkg.yml, gadgets/deadlock/artifacthub-pkg.yml, gadgets/fsnotify/artifacthub-pkg.yml, gadgets/profile_blockio/artifacthub-pkg.yml, gadgets/profile_tcprtt/artifacthub-pkg.yml, gadgets/snapshot_process/artifacthub-pkg.yml, gadgets/snapshot_socket/artifacthub-pkg.yml, gadgets/top_blockio/artifacthub-pkg.yml, gadgets/top_file/artifacthub-pkg.yml, gadgets/top_tcp/artifacthub-pkg.yml, gadgets/trace_bind/artifacthub-pkg.yml, gadgets/trace_capabilities/artifacthub-pkg.yml, gadgets/trace_dns/artifacthub-pkg.yml, gadgets/trace_exec/artifacthub-pkg.yml, gadgets/trace_fsslower/artifacthub-pkg.yml, gadgets/trace_lsm/artifacthub-pkg.yml, gadgets/trace_malloc/artifacthub-pkg.yml, gadgets/trace_mount/artifacthub-pkg.yml, gadgets/trace_oomkill/artifacthub-pkg.yml, gadgets/trace_open/artifacthub-pkg.yml, gadgets/trace_signal/artifacthub-pkg.yml, gadgets/trace_sni/artifacthub-pkg.yml, gadgets/trace_ssl/artifacthub-pkg.yml, gadgets/trace_tcp/artifacthub-pkg.yml, gadgets/trace_tcpconnect/artifacthub-pkg.yml, gadgets/trace_tcpdrop/artifacthub-pkg.yml, gadgets/trace_tcpretrans/artifacthub-pkg.yml
Update the gadgets versions manually since the automated workflow is failing see: https://github.com/inspektor-gadget/inspektor-gadget/pull/3558.
I used the steps at https://github.com/inspektor-gadget/inspektor-gadget/blob/main/.github/workflows/release.yml#L24 to make the changes.
=> post-release[artifacthub]: update gadgets to 0.33.0

pkg/datasource/data.go, pkg/datasource/datasource_test.go, pkg/datasource/field.go, pkg/operators/ebpf/formatters.go, pkg/operators/ebpf/struct.go, pkg/operators/formatters/formatters.go, pkg/operators/uidgidresolver/uidgidresolver.go
Before this commit operators were creating the enriched field in the root of the data source. This commit fixes that by creating the enriched fields in the same node of the "raw" one.
I used the following gadget to test it:
```c
#include <vmlinux.h>
#include <bpf/bpf_helpers.h>
#include <gadget/buffer.h>
#include <gadget/macros.h>
#include <gadget/types.h>
enum myenum {
ONE = 1,
TWO = 2,
THREE = 3,
};
// Just to show inner fields
struct inner {
gadget_uid inner_user_raw;
gadget_gid inner_group_raw;
gadget_syscall inner_syscall_raw;
gadget_errno inner_errno_raw;
enum myenum inner_enum_raw;
};
struct event {
__u32 pid;
gadget_uid user_raw;
gadget_gid group_raw;
gadget_syscall syscall_raw;
gadget_errno errno_raw;
enum myenum enum_raw;
struct inner inner;
};
GADGET_TRACER_MAP(open_events, …
```
=> operators: Fix location of enriched fields

pkg/testing/gadgetrunner/gadgetrunner.go
Newly added unittest might be a little flaky due to json decoder out of sync error in gadgetrunner package see this:
https://github.com/inspektor-gadget/inspektor-gadget/actions/runs/11277713751/job/31365192850
Manual testing is done locally.
=> fix: json decoder out of sync error for gadgetrunner

pkg/container-utils/cri/cri.go, pkg/container-utils/cri/cri_test.go
The tests depends on github.com/google/go-cmp/cmp which is not necessary to include in ig. The dependency compiles regexp which cause 0.5MB to be permanently used by the ig process. This is visible in the pprof flamegraph as 'regexp.MustCompile'.
This patch was originally part of #3571 but that PR might not be merged, so I am submitting the patch separately.
cc @burak-ok
=> cri: move tests to separate package

docs/gadget-devel/output.md, docs/spec/operators/cli.md, docs/spec/operators/otel-metrics.md, gadgets/profile_blockio/gadget.yaml, gadgets/profile_tcprtt/gadget.yaml, pkg/operators/cli/clioperator.go, pkg/operators/otel-metrics/otel-metrics.go
Making the render datasource (used by the otel-metrics to print histograms on CLI side) visible to users provides some issues and unnecessary complexity:
- Gadget developer needs to apply some annotations to the datasource they created and some others to a datasource named `renderedmetrics` (which they didn't created). For instance, for the `trace_tcprtt` gadget:
```yaml
dataSources:
tcprtt:
annotations:
cli.output: "none"
metrics.print: "true"
fields:
latency:
annotations:
metrics.unit: µs
renderedmetrics:
annotations:
cli.clear-screen-before: "true"
```
- Available fields on help message is confusing:
```bash
--fields string                          Available data sources / fields
"tcprtt" (data source):
latency
unused
"renderedmetrics" (data source):
text
(default …
```
=> pkg/operators/otel-metrics: Hide render datasource from gadget users

pkg/operators/formatters/formatters.go
Fixes: d5e0f1198bd74c9ef66dea1c53a84ea94b40cecc
```
→ ./kubectl-gadget run trace_dns -n demo 
K8S.NODE           K8S.NAMESPACE      K8S.PODNAME        K8S.CONTAINERNAME  SRC                    DST                    COMM            PID QR QTYPE     NAME              RCODE    ADDRESSES SRC.PROTO DST.PROTO
minikube-docker    demo               mypod              mypod              10.244.0.12:47222      10.96.0.10:53          isc-net-…    630277 Q  A         google.com.                          UDP       UDP      
minikube-docker    demo               mypod              mypod              10.96.0.10:53          10.244.0.12:47222      isc-net-…    630277 R  A         google.com.       Success  142.250.… UDP       UDP  
```
```
→ ./kubectl-gadget run trace_dns -n demo 
K8S.NODE …
```
=> operators/formatters: Hide endpoint subfield proto

docs/spec/operators/kubeipresolver.md, gadget-container/gadgettracermanager/main.go, gadgets/trace_dns/test/integration/trace_dns_test.go, pkg/operators/common/datasource.go, pkg/operators/common/kubeinventorycache.go, pkg/operators/formatters/formatters.go, pkg/operators/kubeipresolver/kubeipresolver.go, pkg/testing/utils/types.go, pkg/testing/utils/utils.go
Allow using kubeipresolver for image-based gadgets:
```
→ ./kubectl-gadget run trace_dns -n demo  --fields=+src.k8s.kind,+src.k8s.name,+dst.k8s.kind,+dst.k8s.name
SRC                    DST                    COMM            PID QR QTYPE     NAME             RCODE    ADDRESSES K8S.NODE        K8S.NAMESPACE   K8S.PODNAME     K8S.CONTAINERN… SRC.K8S… SRC.K8S.NAME    DST.K8S… DST.K8S.NAME   
10.244.0.5:41390       10.96.0.10:53          isc-net-…    989183 Q  A         example.com.                        minikube-docker demo            mypod           mypod           pod      mypod           svc      kube-dns       
10.96.0.10:53          10.244.0.5:41390       isc-net-…    989183 R  A         example.com.     Success  93.184.2… minikube-docker demo            mypod           mypod …
```
=> operators: kubeipresolver for image-based gadgets

pkg/operators/wasm/testdata/dataarray/go.mod, pkg/operators/wasm/testdata/fields/go.mod
Missing bumping golang version to 1.22.8 on tests for wasm operators, which makes compilation fail:
```bash
$ make -C pkg/operators/wasm/testdata/ dataarray
make: Entering directory '/home/jose/go/src/inspektor-gadget/pkg/operators/wasm/testdata'
Building dataarray
Pulling builder image ghcr.io/inspektor-gadget/ebpf-builder:latest
latest: Pulling from inspektor-gadget/ebpf-builder
Digest: sha256:a79067988b121c64a6f14e22b19ad995bcc5c5c3425b1b1f550883999142a685
Status: Image is up to date for ghcr.io/inspektor-gadget/ebpf-builder:latest
Builder container logs start:
clang -target bpf -Wall -g -O2 -I /work/include/ -D __TARGET_ARCH_x86 \
-c /work/pkg/operators/wasm/testdata/dataarray/program.bpf.c -I /usr/include/gadget/amd64/ -o /out/amd64.bpf.o
clang -target bpf -Wall -g -O2 -I …
```
=> pkg/operators/wasm/testdata: Update go version

docs/gadget-devel/gadget-wasm-api-raw.md
As concluded in this [Slack discussion](https://kubernetes.slack.com/archives/CSYL75LF6/p1729110085017109), the documentation doesn't make clear that the handle returned by `dataSourceNewPacketSingle` and `dataSourceNewPacketArray` can be used as both a Data/DataArray and Packet handle.
=> docs/gadget-devel: How to use Data, DataArray and Packet in WASM API

Dockerfiles/ig.Dockerfile.dockerignore
The dockerignore file must be named after the Dockerfile with the ".dockerignore" suffix. It was ignored by docker-build because it didn't have the correct name.
The content was wrong. Add missing directory.
Fixes: d8e9d0f2774c ("ig/local-gadget: Rename local-gadget in docker images and containers")
cc @burak-ok
=> build: fix dockerignore file

go.mod, go.sum
This uses an unreleased version of cilium/ebpf.
The specific patches from cilium/ebpf are listed in a comment in go.mod.
This includes https://github.com/cilium/ebpf/pull/1590.
https://github.com/cilium/ebpf/pull/1588 was already picked up via [#3595](https://github.com/inspektor-gadget/inspektor-gadget/pull/3595).
cc @burak-ok
=> go.mod: update cilium/ebpf with more memory optimization

docs/spec/operators/oci.md, pkg/operators/oci-handler/oci.go
- Moved `authfile` and `pull-secret` to GlobalParams in `pkg/operators/oci-handler/oci.go`.
- Updated the corresponding documentation to reflect this change.
Closes [#3444](https://github.com/inspektor-gadget/inspektor-gadget/issues/3444).
=> Move authfile and pull-secret to GlobalParams and update documentation

pkg/operators/formatters/formatters.go, pkg/operators/kubeipresolver/kubeipresolver.go
This change allows improving format of endpoint field by including Kubernetes metadata:
```
→ ./kubectl-gadget run trace_dns -A
K8S.NODE               K8S.NAMESPACE          K8S.PODNAME           K8S.CONTAINERNAME     SRC                          DST                          COMM               PID QR QTYPE       NAME                  RCODE    ADDRESSES  
minikube-docker        demo                   mypod                 mypod                 p/demo/mypod:53574           s/kube-system/kube-dns:53    isc-net-00…     594477 Q  A           google.com.                               
minikube-docker                                                                           p/demo/mypod:53574           s/kube-system/kube-dns:53                         0 Q  A           google.com. …
```
=> operators/kubeipresolver: Improve how endpoint is displayed

Makefile
This allows me to optionally switch to another builder like depot: https://depot.dev/
```bash
DOCKER_BUILD='depot build' time make ig
```
=> 41 seconds
=> Makefile: make the 'docker build' command configurable

pkg/operators/ebpf/ebpf.go, pkg/operators/ebpf/params.go, pkg/operators/ebpf/params_defaults.go, pkg/operators/ebpf/types/types.go
- Made changes to params.go to label all parameters with prefix `ipaddr` as type TypeString
- Made changes to ebpf.go operator to convert all parameters with prefix `ipaddr_v4` from string to uint32 and
all parameters with prefix `ipaddr_v6` from string to struct uint128
- Defined uint128 as a struct with 2 members of uint64 and wrote a helper function `IPStringToUint128()` in helpers.go
This commit allows us to now specify IPv4 addresses as an input parameter in the cli. 
For example:
Let's assume we wanted to have a parameter of ipv4 and ipv6 address. We declare it as a u32 int and u128 in the kernel space as shown below:
```C
volatile const __u32 ipaddr_v4 = 3232235777;
volatile const u128 ipaddr_v6 =  {0x123456789ABCDEF0, 0x0FEDCBA987654321}; 
GADGET_PARAM(ipaddr_v4); …
```
=> feat: Accepting IPv4 and IPv6 parameters as command line input arguments

gadgets/snapshot_socket/test/integration/snapshot_socket_test.go
Fixes #3235 
- Defined `snapshotSocketEntry` struct with appropriate fields.
- Set up container with BusyBox and a listening TCP socket.
- Added validation logic to match expected output against actual gadget output.
- Added `TestSnapshotSocket` function in `tests/snapshot_socket_test.go`.
- Ensured compatibility with both local and Kubernetes test components.
- Included cleanup steps for stopping the test container.
-  Ran tests locally using `go test`.
-  `IG_EXPERIMENTAL=true go test -exec 'sudo -E' -v`
=> test: Added tests for gadgets/snapshot_socket

docs/gadgets/builtin/audit/seccomp.md, docs/legacy/crds/gadgets/audit-seccomp.md, gadgets/audit_seccomp/README.md, gadgets/audit_seccomp/README.mdx, pkg/gadget-collection/gadgets/audit/seccomp/gadget.go
runc v1.2.0 was released last week. It includes support for seccomp flag SECCOMP_FILTER_FLAG_LOG. The documentation of the audit-seccomp gadget can be updated accordingly.
See:
* https://github.com/opencontainers/runc/releases/tag/v1.2.0
* https://github.com/opencontainers/runc/pull/3390
=> docs: audit-seccomp: update runc requirement

docs/gadget-devel/gadget-intro.md, pkg/operators/ebpf/maps.go
Add types we currently support on Map Iterator data sources.
Ref discussion on Slack: https://kubernetes.slack.com/archives/CSYL75LF6/p1729093452941369?thread_ts=1729093112.369419&cid=CSYL75LF6
=> docs/gadget-devel/gadget-intro: Specify support of Map Iterators

pkg/operators/ebpf/ebpf.go, pkg/operators/ebpf/maps.go, pkg/operators/ebpf/tracer.go
The ebpf operator runs the logic that reads and emmits the events on a separated goroutine. This wasn't synchronized at all with the Stop() operation, what means the goroutine continued emitting events even after the operator was stopped. This caused an issue on the wasm operator as it was processing a data source callback **after** being stopped.
The timeline of this issue was:
```
goroutine 1        |       goroutine 2
-------------------------|-------------------------
| - ebpf op runTracer()
|   - ds.EmitData()
- Stop ebpf operator()   |
- Stop wasm operator()   |
- i.handles = nil      |
| - wasm op addHandle
|  - crash because i.handles is nil
```
crash log:
```
panic: assignment to entry in nil map
goroutine 3387 [running]: …
```
=> operators/ebpf: Fix race condition with wasm operator

Makefile
We have different golang modules in the repository, un fortunately there is a not an easy way to update all of them. This commit introduces a new target to the Makefile that runs `go mod tidy` in all the modules. This is useful to update all modules when the main one is updated by dependabot.
Useful to handle PRs like #3647
=> Makefile: Introduce target to run go mod tidy

examples/gadgets/operators/otel_metrics/main.go, pkg/operators/ebpf/ebpf.go, pkg/operators/ebpf/maps.go, pkg/operators/otel-metrics/otel-metrics.go
The previous logic was relying on the gadget context, but it was never being closed. This caused the map iterator to keep reading the map forever, producing the following error after a timeout:
```bash
sudo ig run mygadget:latest --verify-image=false -o json --timeout 2WARN[0001] image signature verification is disabled due to using corresponding option
WARN[0001] image signature verification is disabled due to using corresponding option
[]
[]
WARN[0004] error from map iterator: bad file descriptor
[]
WARN[0005] error from map iterator: bad file descriptor
[]
```
This logic switches to only rely on the Stop() operation and an internal channel.
This bug only appeared after 85b756c881d3 ("operators/ebpf: Fix race condition with wasm operator") as it introduced a waiting group, but the bug …
=> operators/ebpf: Fix map iterators waiting logic

integration/k8s/trace_network_test.go
This test is currently failing a lot of times and hinders us from merging and releasing without multiple attempts of re-runs
=> tests: Disable TestTraceNetwork on containerd

gadgets/trace_tcpconnect/README.mdx, gadgets/trace_tcpconnect/program.bpf.c
When an error happens in the connect call the src ip addr + port and the dst port is cleared in the kernel before returning. Therefore we need to save all the information at a point when it is available.
Edit: Actual source line is: https://elixir.bootlin.com/linux/v6.11/source/net/ipv4/af_inet.c#L738
~~See https://elixir.bootlin.com/linux/v6.11/source/net/ipv4/tcp_ipv4.c#L350~~
```bash
RUNTIME.CONTAINERNAME        SRC                                   DST                                   COMM                  PID        TID        UID        GID ERROR     
quizzical_cannon             172.17.0.2:34286                      142.250.185.131:80                    wget                41798      41798          0          0           
quizzical_cannon             172.17.0.2:35018 …
```
=> trace_tcpconnect: Fix missing src and dst ip and port on error

cmd/common/oci.go, pkg/eventgenerator/dns/generator.go, pkg/eventgenerator/http/generator.go, pkg/eventgenerator/types.go, pkg/operators/eventgen/operator.go, pkg/operators/eventgen/params.go
dns and http event generator. Creates pod and container using kubernetes and generate events from that pod when running gadget and delete pod after done. 
`sudo ./ig run trace_dns --filter name==example.com. --eventgen-enable=true --eventgen-params=type:dns,target:example.com,count:5,interval:2s`
`$ make ig`
`$ sudo ./ig run trace_dns --filter name==example.com. --eventgen-enable=true --eventgen-params=type:dns,target:example.com,count:5,interval:2s`
=> Eventgen k8s implementation

cmd/kubectl-gadget/version.go
kubectl-gadget version -o json
=> feat: enhance version command output to json format

.github/workflows/inspektor-gadget.yml, Makefile, gadgets/Makefile, gadgets/ci/inner_fields/test/unit/inner_fields_test.go, gadgets/snapshot_process/test/unit/snapshot_process_test.go, gadgets/testing/testing.go, gadgets/top_file/test/unit/top_file_test.go, gadgets/trace_open/test/unit/trace_open_test.go, gadgets/trace_tcp/test/unit/trace_tcp_test.go
fixes: #1343
cc @mauriciovasquezbernal @alban 
This PR provides a GitHub workflow job and a Makefile target to run unit tests for image-based gadgets. The workflow uses the Makefile target to run tests with different kernel versions passed as parameters. The Makefile first pulls gadget images from the repository where they were pushed during the build-and-push process. Then, it uses Vimto to pull the kernel image from the respective kernel image repository, as Vimto does not allow networking between the host and the VM.
TODO:
Testing is done both on fork and locally, summary for the test ran on fork can be found here: https://github.com/mastersans/inspektor-gadget/actions/runs/11517810558?pr=11 
the tests seems to pass on <= 5.10 tag kernel version. and fails on 5.4 and 4.19
=> ci: test image gadgets on different kernel versions

examples/container-collection/container-collection.go
There was a change done to access container PID and the field is no longer directly accessible from `Container` field. We need to access it through the new method `ContainerPid()`
This change is done as a part of examples in logging so review would be straightforward
=> Use `ContainerPid` method in example

docs/gadget-devel/gadget-wasm-api-raw.md, pkg/datasource/data.go, pkg/datasource/datasource.go, pkg/gadget-context/gadget-context.go, pkg/operators/combiner/combiner.go, pkg/operators/otel-metrics/otel-metrics.go, pkg/operators/wasm/datasource.go, wasmapi/go/datasource.go
- Updates naming from requested to referenced.
- Updates `SetRequested(bool)` to `Unreference()` and `IsRequested` to `IsReferenced` on dataSource
- Adds `Unreference` and `IsReferenced` methods on the datasource to the WASM api.
You can unreference a datasource from the WASM module now using `ds.Unreference`.
Ran it on a gadget and observed the output
=> datasource: refactor `SetRequested` to `Unreference` & add to WASM API

README.md
I've added some recent videos that were missing and removed to old videos which don't really describe how IG works now. There are probably some others to add which we should do in follow up commits.
I think we should have a dedicated file with all/old talks but I don't think they need to be in the Readme.
=> Readme: Update section to only show recent videos

pkg/operators/oci-handler/oci.go
This fixes an issue that could occur when merging `--annotate` flags into an existing `gadget.yaml` viper config. With the previous method it could happen that viper would place the key in an ambiguous way so that the older values got lost.
=> oci-handler: fix annotate param merge with prior config

pkg/container-hook/tracer.go, pkg/uprobetracer/ldcache_parser.go, pkg/utils/secureopen/secureopen.go
uprobetracer reads ld.so.cache, which is typically less than 200KiB. A 16MiB limit seems like a reasonable limit.
The pid file created by the container runtime should be a small regular file. Don't waste time reading it if it is not the case.
=> uprobe,container-hook: add coherence check on file sizes

gadgets/deadlock/README.mdx, gadgets/deadlock/build.yaml, gadgets/deadlock/gadget.yaml, gadgets/deadlock/go/digraph/cycles.go, gadgets/deadlock/go/digraph/digraph.go, gadgets/deadlock/go/go.mod, gadgets/deadlock/go/program.go, gadgets/deadlock/program.bpf.c
1. Builds edges of the graph in BPF code by tracing mutex locks/unlocks.
2. Sends events to user-space using `MAPITER`.
3. Added WASM modules that make a directed graph from the edges map and detects cycles in the `gadgetStop` callback (ie. when exiting the gadget).
1. Needs a way to run cycle detection every second (go routines?). A hack worth trying is to run a timer, and with each event check if it's time to run cycle detection.
2. Output formatting.. currently the output is just a trace of all edges in the graph as they are added.
1. Run the gadget using `ig`.
2. Run the following [script](https://github.com/iovisor/bcc/blob/master/tools/deadlock_example.txt#L187) (simulates mutex lock inversions) in a separate container.
3. Stop the gadget once you see the traces of the above script. …
=> gadgets/deadlock: add deadlock detection using cycles in mutex wait di-graph

cmd/common/oci.go, docs/reference/export-logs.mdx, gadget-container/gadgettracermanager/main.go, go.mod, go.sum, pkg/datasource/expr/expr.go, pkg/datasource/expr/expr_test.go, pkg/datasource/helpers.go, pkg/operators/otel-logs/otel-logs.go, pkg/operators/otel-metrics/otel-metrics.go
This adds support for [OpenTelemetry Logs](https://opentelemetry.io/docs/specs/otel/logs/) using the [otlp protocol](https://opentelemetry.io/docs/specs/otlp/). Fields of datasources can be configured to be exported as KeyValue pairs alongside the log body. The severity can also be read from a field. The message body can be composed using [expr-lang](https://expr-lang.org) (see below) to include fields from the datasource.
This also introduces support for [expr-lang](https://expr-lang.org) to be able to use filters and string composition with datasources. In this PR, the string composition feature will be used to create the actual log body message. If for example you have a datasource with a `StringField` and an `IntField` that you want to include in the log body, you could simply define …
=> introduce support for otel-logs

.github/dependabot.yml
Update github.com/containers dependency together to avoid multiple PRs like #3688 and #3708
=> dependabot: Add group for containers dependency

charts/gadget/templates/daemonset.yaml, cmd/kubectl-gadget/deploy.go, gadget-container/entrypoint/entrypoint.go, gadget-container/gadgettracermanager/main.go, pkg/resources/manifests/deploy.yaml
Use the version of the server instead of the client.
And easy PR to fix an old and annoying low handing fruit.
Fixes #1061
=> ig-k8s: Fix server version message

gadget-container/gadgettracermanager/main.go
Print the version only when running with -serve, otherwise it messes up some json output used by the advise network-policy gadget.
It turns out adding a new info log on the gadget tracer manager breaks something. I was too confident a simple message won't break anything and merged #3743 without waiting for the CI to finish.
Fixes: a46f5c2efc55 ("ig-k8s: Fix server version message")
---
=> ig-k8s: Fix fix server version message

.github/workflows/inspektor-gadget.yml, gadgets/snapshot_process/test/unit/snapshot_process_test.go, gadgets/top_file/test/unit/top_file_test.go, pkg/operators/ebpf/ebpf.go, pkg/operators/ebpf/tracer.go
Logic to fallback to a perf ring buffer when ring buffer is not supported
was introduced in ba2bfca2aa77 ("run: Add functions to use perf or ring
buffer."), however it wasn't ported in d28c76d0ef85
("pkg/operators/ebpf: ebpf layer operator").
```bash
$ make -C gadgets/ IG_VERIFY_IMAGE=false KERNEL_VERSION=5.4 test-unit
```
=>   operators/bpf: Fix perf ring buffer fallback logic

pkg/container-collection/k8s.go
In our node-agent I need to create and use a runtime.NewImageServiceClient for which it's very handy to make sure I have the same socket path as IG.
N/A
Works in my PR https://github.com/kubescape/node-agent/pull/384/
=> expose SocketPath in k8s.go

.github/dependabot.yml
Use this new key to update all directories containing a go.mod file. This fixes the issue that different gomodules weren't updated in a single PR.
See more information on: https://github.blog/changelog/2024-06-25-simplified-dependabot-yml-configuration-with-multi-directory-key-directories-and-wildcard-glob-support/
--- 
Hopefully it'll fix the issue described in [slack](https://kubernetes.slack.com/archives/CSYL75LF6/p1717097084440599?thread_ts=1716994391.199619&cid=CSYL75LF6) now that https://github.com/dependabot/dependabot-core/issues/1595#issuecomment-2189252273 is fixed. 
> I think I now understand what's going on:
> examples/go.mod uses inspektor-gadget through a [replace directive](https://github.com/inspektor-gadget/inspektor-gadget/blob/4662ce24870851d0231044eff7445e222f7d3195/exa …
=> dependabot: Use directories key

.github/workflows/check-artifacthub-tags.yml
We seem to be getting warning about missing permission for check-artifacthub: https://scorecard.dev/viewer/?uri=github.com/inspektor-gadget/inspektor-gadget. This change adds a top level permission similar to other workflows.
=> ci/check-artifacthub-tags: Add permissions

gadgets/snapshot_process/test/integration/snapshot_process_test.go, gadgets/snapshot_socket/test/integration/snapshot_socket_test.go
Snapshotter tests are failing a lot (see issue #3361). It seems to be that 1 second is too low for the message pump to send the information to the client, hence it's being dropped.
This commit increases the timeout to 5 seconds, however the final solution should be to fix #3033.
Fixes #3361
=> tests: Increase timeout for snapshotter tests

gadgets/audit_seccomp/test/integration/audit_seccomp_test.go, gadgets/fdpass/test/unit/fdpass_test.go, gadgets/snapshot_process/test/integration/snapshot_process_test.go, gadgets/snapshot_process/test/unit/snapshot_process_test.go, gadgets/snapshot_socket/test/integration/snapshot_socket_test.go, gadgets/top_blockio/test/integration/top_blockio_test.go, gadgets/top_file/test/integration/top_file_test.go, gadgets/top_file/test/unit/top_file_test.go, gadgets/top_tcp/test/integration/top_tcp_test.go, gadgets/trace_bind/test/integration/trace_bind_test.go, gadgets/trace_capabilities/test/integration/trace_capabilities_test.go, gadgets/trace_dns/test/integration/trace_dns_test.go, gadgets/trace_exec/test/integration/trace_exec_test.go, gadgets/trace_fsslower/test/integration/trace_fsslower_test.go, gadgets/trace_mount/test/integration/trace_mount_test.go, gadgets/trace_oomkill/test/integration/trace_oomkill_test.go, gadgets/trace_open/test/integration/trace_open_test.go, gadgets/trace_open/test/unit/trace_open_test.go, gadgets/trace_signal/test/integration/trace_signal_test.go, gadgets/trace_sni/test/integration/trace_sni_test.go, gadgets/trace_tcp/test/integration/trace_tcp_test.go, gadgets/trace_tcp/test/unit/trace_tcp_test.go, gadgets/trace_tcpconnect/test/integration/trace_tcpconnect_test.go, gadgets/trace_tcpretrans/test/integration/trace_tcpretrans_test.go, pkg/testing/utils/types.go, pkg/testing/utils/utils.go
- Updated utils package to alias ebpftypes.Process as Process.
- Refactored test files to use utils.Process instead of ebpftypes.Process.
- Modified utils.go functions to reflect the alias change.
=> Alias ebpftypes.Process as Process in utils package

.github/workflows/inspektor-gadget.yml
TL;DR: There are cases when we want to run the CI manually in case something bad has happened.
--- 
I used the `@dependabot merge` command to merge a PR in https://github.com/inspektor-gadget/inspektor-gadget/pull/3784#issuecomment-2536826436, this caused the GitHub Actions actor to be dependabot, since it doesn't have access to our private key, all signing related things failed: https://github.com/inspektor-gadget/inspektor-gadget/actions/runs/12277729656/attempts/1. 
This caused the CI to push images without signing. 
For gadgets the current "latest" images fail to be run without disabling image verification:
```bash 
$  sudo ig run trace_exec:latest --pull always
Error: fetching gadget information: initializing and preparing operators: instantiating operator "oci": ensuring image: …
```
=> ci: Enable workflow_dispatch

go.mod, go.sum
Bumped gopacket
Fixes: https://github.com/inspektor-gadget/inspektor-gadget/commit/1be3c7db7c8837d7d53bb64e580ea187785aad41 ("go: bump github.com/gopacket/gopacket from 1.2.0 to 1.3.1") https://github.com/inspektor-gadget/inspektor-gadget/pull/3698
=> Bumped gopacket to contain a fix for the panic of dns parsing

gadgets/trace_dns/gadget.yaml, gadgets/trace_dns/program.bpf.c
The cwd and exepath are already known by the socket enricher. This patch adds them in the events with --paths.
Since it makes the events bigger, it can no longer fit on the stack, so we use a temporary map.
Fixes https://github.com/inspektor-gadget/inspektor-gadget/issues/3804
```
$ sudo ig run ghcr.io/inspektor-gadget/gadget/trace_dns:latest --verify-image=false --paths=true -o yaml
...
cwd: /home
exepath: /bin/ping
```
=> trace_dns: add fields cwd & exepath (--paths)

Dockerfiles/gadget.Dockerfile, charts/gadget/templates/daemonset.yaml, gadget-container/Makefile, gadget-container/entrypoint/entrypoint.go, gadget-container/gadgettracermanager/main.go, pkg/resources/manifests/deploy.yaml
Updates the entrypoint logic of gadgettracermanager. The main function now directly handles the program's execution, eliminating the need for a standalone binary. This change simplifies the structure and improves maintainability.
=> Update entrypoint logic for gadget-container 

pkg/container-collection/k8s.go
Instead of just exporting RuntimeSocketPath it would be nice to have access to the whole config to reuse it for example in `containercollection.WithContainerRuntimeEnrichment()`
N/A
Currently in use in our node-agent https://github.com/kubescape/node-agent/pull/438/commits/70bc3b859403b43d5ffb51631ac239c43395c832
=> export the whole RuntimeConfig in K8sClient

cmd/common/oci.go, cmd/common/runwithspec_test.go, cmd/common/utils/http.go
This change allows getting manifest file remotely. It should help us host sample manifest files and share them with different use-cases:
```
$ go run ./cmd/kubectl-gadget run -f https://gist.githubusercontent.com/mqasimsarfraz/dcc1521afebdcc5708fb16efb9de2677/raw/f5b5a3d2737b44142c9f52792b170c8415a3e057/failed-dns-requests.yaml
K8S.PODNAME                                           SRC                                                  DST                                                  NAME                                                  RCODE
```
=> oci: remote manifest file

pkg/operators/ebpf/testdata/Makefile, pkg/operators/wasm/testdata/Makefile
This ensures the most up to date is used for building and exporting the images
=> wasm/testdata: Use in-tree ig to build the images

examples/gadgets/grpc/custom_operator/main.go, examples/gadgets/operators/local_manager/main.go, examples/gadgets/simple/trace_dns/main.go, pkg/operators/localmanager/localmanager.go
LocalManger operator caches k8s/container runtime information. This PR un-export LocalManger struct and instead introduces a package level variable, to be used by Golang users of IG platform. This will make sure, Golang users of localManager operator will share the localManger cache for all running gadgets.
Examples refactored to demonstrate usage
=> Refactor LocalManger to be used from package level variable only

pkg/gadget-service/service-oci.go
The previous logic was causing issues when running the gadget failed because the client was handing forever. This is because if `s.runtime.RunGadget` fails early the simple operator won't be initialized and hence the done <- true operation will block as there is not any goroutine reading from the channel.
This commit fixes that by closing the channel instead of writing to it.
Fixes first part of #3453.
Replaces #3863
=> oci-service: Fix closing logic

pkg/gadget-service/instance-manager/instance.go, pkg/gadget-service/instance-manager/manager.go
Uses a channel to signal completion of `Run` function in `instance.go` before returning gadgetinfo. Earlier this returned null, leading to a null pointer dereferencing error.
=> gadgetctl/kubectl-gadget: fixes crash when running attach right after run 

gadgets/trace_exec/gadget.yaml, gadgets/trace_exec/program.bpf.c, gadgets/trace_exec/test/integration/trace_exec_test.go
This PR adds three additional fields `dev_major`, `dev_minor` and `inode_no` in `trace_exec` gadget which can be accessed by `--fields` flag
```
$ sudo ./ig image build ./gadgets/trace_exec --local --tag trace_exec_local
$ sudo ./ig run trace_exec_local --verify-image=false  --paths --fields comm,args,error,exepath,file,dev_no,inode_no --host --ignore-failed=false
```
=> Adds dev and inode number field in trace_exec

gadgets/trace_exec/README.mdx, gadgets/trace_exec/gadget.yaml, gadgets/trace_exec/program.bpf.c, gadgets/trace_exec/test/integration/trace_exec_test.go
fupper_laer field provides an indication for whether the executable file of the process is in the upper layer of the overlay filesystem. This can be useful information when exepath != filepath, such as in a case of a script.
In response to https://github.com/inspektor-gadget/inspektor-gadget/issues/3838
* Unit tests
=> Adding fupper layer field for trace_exec image-based gadget

pkg/container-hook/runtime-finder/finder.go
Running a kubeadm cluster on Debian with upstream cri-o introduces this path to the runc binary. 
Install kubeadm cluster on Debian12 with crio from ```https://pkgs.k8s.io/addons:/cri-o:/stable:/v1.30/deb/```
Precondition is a working kubeadm cluster with cri-o from above.
I installed kubescape via helm
```
helm upgrade --install kubescape kubescape/kubescape-operator -n kubescape --create-namespace --set clusterName=`kubectl config current-context`
```
Immediately after installation the node-agent pods goes into CrashLoopBackOff
```
k -n kubescape get po | grep Crash
node-agent-25djz                  0/1     CrashLoopBackOff   2 (11s ago)   68s
node-agent-2p6fh                  0/1     CrashLoopBackOff   2 (7s ago)    68s
node-agent-f68pd                  0/1     CrashLoopBackOff   2 (8s …
```
=> Add runc path of kubeadm cluster running on Debian12 with upstream cri-o

pkg/container-collection/k8s.go
For some environments like k8s in openshift over cri-o and microk8s the socket path isn't prefixed with unix:// 
For example: [cri-o setup](https://docs.openshift.com/container-platform/3.11/crio/crio_runtime.html).
=> Adding support for non unix:// prefix in socket paths

pkg/oci/oci.go
Avoid crashing if the returned descriptor is nil.
0. Create a wrong index.json file (pointing to a non-existing index)
```json
{
"schemaVersion": 2,
"manifests": [
{
"mediaType": "application/vnd.oci.image.index.v1+json",
"digest": "sha256:b26f752fc5b5e2a15d8b5b90d87b036aa12e3a2715d1cf17e6c0d45b596b40d1",
"size": 728,
"annotations": {
"org.opencontainers.image.created": "2025-01-17T16:44:31-05:00",
"org.opencontainers.image.ref.name": "non-existing-foo"
}
}
]
}
```
Copy it to the index.json file of the ig oci store:
> [!WARNING]  
> This will destroy your oci-store, backup it first if you have anything important there
```bash
$ sudo cp index.json /var/lib/ig/oci-store/index.json
```
```bash 
$ sudo ig image list …
```
=> oci: Fix image list crash

cmd/kubectl-gadget/version.go
Before https://github.com/inspektor-gadget/inspektor-gadget/pull/3651, running `kubectl-gadget version` would still show the client version even if there was no server available -- we use this in nixpkgs CI to verify that the version passed by `ldflags` is used correctly [here](https://github.com/NixOS/nixpkgs/blob/5df43628fdf08d642be8ba5b3625a6c70731c19c/pkgs/by-name/ku/kubectl-gadget/package.nix#L33). 
Currently, `kubectl-gadget version` only returns an error when run with no server as
```
❯ kubectl-gadget version        
Error: getting running Inspektor Gadget instances: Get "http://localhost:8080/apis/apps/v1/daemonsets?fieldSelector=metadata.name%3Dgadget&labelSelector=k8s-app%3Dgadget": dial tcp [::1]:8080: connect: connection refused
```
This PR does not fail `version` when no …
=> kubectl-gadget: return client version when server not available

gadgets/trace_tcp/ebpf/accept.h, gadgets/trace_tcp/ebpf/common.h, gadgets/trace_tcp/ebpf/connect.h, gadgets/trace_tcp/gadget.yaml, gadgets/trace_tcp/program.bpf.c, gadgets/trace_tcp/test/integration/trace_tcp_test.go, gadgets/trace_tcp/test/unit/trace_tcp_test.go
Supersedes #3850.
Part of #3565
The fields are documented in gadget.yaml:
- The 'fd' field is the fd where the operation happened on (connect, accept)
- The 'accept_fd' field is the FD of the new connection returned by accept, or -1 for errors cases or other events
The gadget uses maps to store context. Map cleanup is always done in a tracepoint or a kprobe, avoiding kretprobe. This ensures it does not miss a cleanup because the kretprobe overflows the maxactive.
TCP close events don't include a fd because this is not always well-defined: a fd can be "renamed" with dup2() so it cannot be matched with the fd from connect or accept events.
```bash
$ nc -k -l -p 8080 &
[1] 588902
$ echo|nc 127.0.0.1 8080
```
```bash
$ sudo ./ig run ghcr.io/inspektor-gadget/gadget/trace_tcp:alban_trace_tcp_fd2 …
```
=> trace_tcp: Add fd (updated from Burak's #3850)

docs/reference/run.mdx, docs/spec/operators/filter.md, pkg/gadget-service/api/helpers.go, pkg/operators/filter/filter.go, pkg/operators/filter/filter_test.go
As discussed in the review: https://github.com/inspektor-gadget/inspektor-gadget/pull/3899#discussion_r1918914740 we need a way to escape commas in the filter values. This PR adds support for escaping commas in the filter values by using a backslash (`\`).
```bash
$ go run -exec sudo ./cmd/ig run trace_open --host -F 'fname==/tmp/a\,b'
RUNTIME.CONTAINERNAME                                                                COMM                    PID        TID  FD FNAME                                                                                    MODE                                         ERROR                            
cat                   13519      13519   3 /tmp/a,b                                                                                 ---------- …
```
=> filter: Allow escaping commas

.github/workflows/inspektor-gadget.yml
Adds a CI workflow that reports static analysis of ig binary size
Yes, tested on local fork. Attaching screenshot for reference:
=> CI: static analysis of ig binary size

pkg/gadgets/audit/seccomp/tracer/tracer.go, pkg/gadgets/trace/bind/tracer/tracer.go, pkg/gadgets/trace/capabilities/tracer/tracer.go, pkg/gadgets/trace/exec/tracer/tracer.go, pkg/gadgets/trace/fsslower/tracer/tracer.go, pkg/gadgets/trace/mount/tracer/tracer.go, pkg/gadgets/trace/oomkill/tracer/tracer.go, pkg/gadgets/trace/open/tracer/tracer.go, pkg/gadgets/trace/signal/tracer/tracer.go, pkg/gadgets/trace/tcp/tracer/tracer.go, pkg/gadgets/trace/tcpconnect/tracer/tracer.go, pkg/gadgets/trace/tcpdrop/tracer/tracer.go, pkg/gadgets/trace/tcpretrans/tracer/tracer.go, pkg/networktracer/tracer.go, pkg/operators/ebpf/tracer.go
As discussed in https://github.com/cilium/ebpf/issues/1633 we should continue reading the perf ring buffer in case of errors. Some examples from cilium/ebpf repository:
- https://github.com/cilium/ebpf/blob/main/examples/uretprobe/main.go#L96-L97
- https://github.com/cilium/ebpf/blob/9f201154004369b0bc1b99a06ee578aa46c6aab4/examples/fentry/main.go#L89-L90
=> perf/ring buffer: Continue reading in case of errors

pkg/gadgets/top/block-io/tracer/tracer.go, pkg/kallsyms/kallsyms.go, pkg/kallsyms/kallsyms_test.go, pkg/kallsyms/symbol-resolver.go
This implements kernel symbol lookups in /proc/kallsyms without unnecessary dynamic memory allocations.
This is 2x faster and almost completely removes dynamic memory allocations.
```
$ go test -exec=sudo -run=Benchmark -bench=. ./pkg/kallsyms/... -count 1
goos: linux
goarch: amd64
pkg: github.com/inspektor-gadget/inspektor-gadget/pkg/kallsyms
cpu: Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz
BenchmarkKernelSymbolAddressJITParsing-4               5         208193754 ns/op            4688 B/op         19 allocs/op
BenchmarkKernelSymbolAddressPreLoading-4               3         425194186 ns/op        105551938 B/op    639608 allocs/op
PASS
ok      github.com/inspektor-gadget/inspektor-gadget/pkg/kallsyms       4.746s
```
Once this PR is merged, I will make use of it in #3871.
No changes.
Let's …
=> kallsyms: implement just in time lookups without allocations

docs/reference/manifests.mdx, examples/instance-manifests/README.md, examples/instance-manifests/dns/failed-dns-requests-all.yaml, examples/instance-manifests/dns/failed-dns-requests-default.yaml, examples/instance-manifests/security/modified-files-all.yaml
Include example instance manifest files for running gadgets in the `examples/instance-manifests` directory.
```
$ kubectl gadget run -f https://raw.githubusercontent.com/inspektor-gadget/inspektor-gadget/fab472ddcf2268c061416b9b19f878f578ab2dc3/examples/instance-manifests/failed-dns-requests-all.yaml
$ kubectl gadget run -f https://raw.githubusercontent.com/inspektor-gadget/inspektor-gadget/fab472ddcf2268c061416b9b19f878f578ab2dc3/examples/instance-manifests/failed-dns-requests-default.yaml
$ kubectl gadget run -f https://raw.githubusercontent.com/inspektor-gadget/inspektor-gadget/fab472ddcf2268c061416b9b19f878f578ab2dc3/examples/instance-manifests/modified-files-all.yaml
```
After merge we can use the repository paths.
=> examples/instance-manifest: Add examples

.github/workflows/inspektor-gadget.yml, examples/go.mod, examples/go.sum, gadgets/Makefile, go.mod, go.sum, pkg/oci/build.go, pkg/oci/local_oci_store.go, pkg/oci/oci.go, pkg/oci/retry.go
Invoking multiple instances of the ig binary on parallel causes issues
as the oras library doesn't provide any multi process syncronization
guarantees on the index.json file. This commit fixes that by using a
file lock and some logic to detect when this file has been updated by
another process.
Specifically, this commit:
- Disables AutoSaveIndex to have control over when the index.json file
is written.
- Uses a file lock to be sure only one process is writing to the
index.json file at a time.
- Adds some logic to retry an operation when the index.json file has been
updated by another process.
Different alternatives were considered:
- big lock: It caused issues as the critical section was too big and
different instances of ig timeout while running gadgets.
- merge index: Instead of retry …
=> pkg/oci: Use a file lock to avoid concurrency issues

docs/gadget-devel/gadget-wasm-api-raw.md, gadgets/trace_dns/go/program.go, gadgets/trace_exec/go/program.go, gadgets/trace_exec/program.bpf.c, pkg/operators/wasm/fields.go, wasmapi/go/fields.go
Profiling of the wasm modules in the trace_exec and trace_dns gadgets revealed that more than 95% of the cpu time is spent in dynamic allocations done by the `Field.Bytes()` helper from the wasm API. See profiling in #3992.
This patch introduces an alternative way to get the bytes of a field without dynamic allocations for fields of type `string` or `[]byte`:
- `Field.BytesToSlice()` (wasm go API)
- `fieldGetToBuffer()` (underlying wasm helper)
No changes
See profiling in #3992.
```
sudo ig run ghcr.io/inspektor-gadget/gadget/trace_exec:alban_fieldGet --verify-image=false
sudo ig run ghcr.io/inspektor-gadget/gadget/trace_dns:alban_fieldGet --verify-image=false 
```
cc @mqasimsarfraz
=> trace_exec, trace_dns: remove dynamic allocations from wasm module

.github/workflows/inspektor-gadget.yml
Follow versions used in https://github.com/cilium/ci-kernels/
These are the new versions pushed on https://github.com/mauriciovasquezbernal/ci-kernels/actions/runs/13205395012.
=> ci: Update unit test kernel versions

pkg/factory/setk8sdefaults_test.go
This PR adds comprehensive unit tests for the `setk8defaults.go` file in the `pkg/factory` directory.This contribution is part of the larger effort to improve test coverage across the pkg/ directory (#3835).
1. Running the unit tests for the columns package:
```bash
go test ./pkg/factory -v
```
2. Verifying test coverage:
```bash
go test ./pkg/factory -v -coverprofile=coverage.out
go tool cover -html=coverage.out
```
=> [Tests]:Created Unit Test Coverage for setk8defaults.go in pkg/factory

internal/version/version.go, pkg/oci/build.go, pkg/operators/oci-handler/oci.go
Ideally Inspektor Gagget should allow running gadgets built with different ig versions. However, we haven't been able to implement this feature. To avoid user confusion, print a warning if the gadget is run with a different version of IG than the one it was built with.
1. Compile ig with a fake 0.98.0 version
```bash 
$ make VERSION=v0.98.0 
```
2. Build any gadget using this verison
```bash 
$ sudo ig image build . -t hello-world
```
3. Run the gadget
```bash 
$ sudo ig run hello-world --verify-image=false
WARN[0000] image signature verification is disabled due to using corresponding option
WARN[0000] image signature verification is disabled due to using corresponding option
RUNTIME.CONTAINERNAME                      PID COMM             FILENAME
```
No warning is printed on this case …
=> Add warning if gadget is run with a different IG version

gadgets/Makefile
The repository was transferred to the inspektor-gadget org.
=> gadgets: Update url of ci-kernels

gadgets/trace_dns/test/integration/trace_dns_test.go, pkg/container-utils/testutils/k8s.go, pkg/container-utils/testutils/options.go, pkg/testing/containers/options.go
Allow the use of existing namespaces by creating an option for the same rather than creating a namespace for each respective container when it is ran.
Tested the use of it in the trace_dns gadget test.
=> gadgets/trace_dns: Use same namespace for client and server

gadgets/fsnotify/test/unit/fsnotify_test.go, pkg/testing/utils/utils.go
Unit test to validate `inotify` event capture through `fsnotify` gadget.
Related to #3627
The test simulates event generation based on the example in the gadget’s [documentation](https://github.com/inspektor-gadget/inspektor-gadget/blob/main/gadgets/fsnotify/README.mdx). 
It uses the [fsnotify](https://github.com/fsnotify/fsnotify) Go package to watch the `/tmp` path and capture events.
Dependencies: [fsnotify package](https://github.com/fsnotify/fsnotify)
Tested with `gadgets-unittest` step of inspektor-gadget.yml workflow. [[successful run](https://github.com/4rivappa/inspektor-gadget/actions/runs/12074081422)]
[21st Dec 2024] Updated PR test [successful run](https://github.com/4rivappa/inspektor-gadget/actions/runs/12443836290/job/34743485124)
=> tests: added unit test to fsnotify gadget

gadgets/trace_exec/program.bpf.c
This resolves issue #4057.
This PR changes the eBPF maps in the `trace_exec` gadget from `BPF_MAP_TYPE_HASH` to `BPF_MAP_TYPE_PERCPU_HASH` and reduces their max_entries from `10240` to `1`. These modifications aim to lower memory usage by drastically shrinking the size of each map, which can help in resource-constrained environments or when the data stored in these maps is minimal.
```
sudo -E ig image build $IG_SOURCE_PATH/gadgets/trace_exec -t trace_exec
sudo -E ig run trace_exec:latest --host --verify-image=false
```
Built `ig` cli and the gadget program locally on a Linux environment with kernel version 6.8. I was able to successfully star the gadget using `ig run` (as described above):
I wrote a "benchmarking" program that calls `execve("/bin/true", args, envp);` to test exec …
=> trace_exec: reduce maps size

pkg/gadget-context/run.go, pkg/gadget-service/api-helpers/apihelpers.go, pkg/operators/oci-handler/oci.go
`InstantiateDataOperator` is called in three different situations:
- **Using the CLI**: The operators are instantiated twice with different parameters values, which creates two cases:
- Case 1: During the `GetGadgetInfo` call, operators are instantiated without parameters (`api.ParamValues` is empty)
- Case 2: During the `RunGadget` call, operators are instantiated with parameters (`api.ParamValues` contains all the operator's parameters with the values set by the user or the default value thanks to cobra/viper package in the CLI). 
- **Using the Go API**: 
- Case 3: Operators are instantiated only once during the `RunGadget` call and it is done only with the parameters passed by the caller. An example is the GadgetRunner for the unit-tests: …
=> pkg/gadget-service/api-helpers: Set default values for unset params

pkg/utils/protocols/protocols_test.go
Fixes #3835
This Test ``GetProtocolNameFromNumber``. It has Two cases :- 
1. If number was found in ``protoNumberToName = map[int]string``. It will give true and Name of protocol
2.  If number was found in ``protoNumberToName = map[int]string``. It will give false and empty array
Run
```
go test  ./... -v
```
```
=== RUN   TestGetProtocolNameByNumber
=== RUN   TestGetProtocolNameByNumber/number_was_found
=== RUN   TestGetProtocolNameByNumber/number_was_not_found
--- PASS: TestGetProtocolNameByNumber (0.00s)
--- PASS: TestGetProtocolNameByNumber/number_was_found (0.00s)
--- PASS: TestGetProtocolNameByNumber/number_was_not_found (0.00s)
PASS
ok      github.com/inspektor-gadget/inspektor-gadget/pkg/utils/protocols        0.002s
```
[Describe the testing you have done before submitting this …
=> [Tests]: Unit Test for pkg/utils/protocols

pkg/gadget-context/run.go
As discussed in [Slack](https://kubernetes.slack.com/archives/CSYL75LF6/p1739481635834429), it's superfluous to validate operators' global parameters [here](https://github.com/inspektor-gadget/inspektor-gadget/blob/f02cd39705574a628588338b919c86a8a866fbec/pkg/gadget-context/run.go#L52-L55) because the operators were already initialized in the [gadget-service](https://github.com/inspektor-gadget/inspektor-gadget/blob/f02cd39705574a628588338b919c86a8a866fbec/pkg/gadget-service/service.go#L388-L391) either when the [ig daemon](https://github.com/inspektor-gadget/inspektor-gadget/blob/f02cd39705574a628588338b919c86a8a866fbec/cmd/ig/daemon.go#L187) or the [gadgettracermanager](https://github.com/inspektor-gadget/inspektor-gadget/blob/f02cd39705574a628588338b919c86a8a866fbec/gadget-container/gad …
=> pkg/gadget-context/run: Remove superfluous global params validation

pkg/operators/oci-handler/oci.go
Do not print anything if parsing the version fails. It means the the gadget could have been built with a development version of Inspektor Gadget, hence it'll create a lot of noise when using the :latest version.
--- 
Annoying message is:
```bash 
$ sudo ig run trace_exec:latest  --pull always
WARN[0002] parsing builder version: Invalid character(s) found in major number "19bcf49"
WARN[0004] parsing builder version: Invalid character(s) found in major number "19bcf49"
```
Fixes: c04bab7e12e2 ("Add warning if gadget is run with a different IG version")
=> Improve gadget version skew warning

pkg/logger/logger_test.go
This PR adds comprehensive unit tests for the logger package to improve test coverage in the pkg/ directory. The changes include tests for both generic and dedicated logger implementations, ensuring all logging levels and methods are properly tested. This contribution is part of the larger effort to enhance test coverage across the codebase (#3835).
Reviewers can validate this PR by:
1. Running the unit tests:
```bash
go test ./pkg/logger -v -coverprofile=coverage.out
```
2. Examining the coverage report:
```bash
go tool cover -html=coverage.out
```
3. Verifying that all logging methods and levels are properly tested:
- Standard logging levels (Panic to Trace)
- Both formatted and unformatted logging methods
- Level getter/setter functionality
Added comprehensive test suite with the …
=> [Tests] : Add unit tests for logger.go in pkg/logger

docs/gadgets/profile_qdisc_latency.mdx, gadgets/Makefile, gadgets/profile_qdisc_latency/README.md, gadgets/profile_qdisc_latency/README.mdx, gadgets/profile_qdisc_latency/artifacthub-pkg.yml, gadgets/profile_qdisc_latency/gadget.yaml, gadgets/profile_qdisc_latency/program.bpf.c
In order to analyse network related issues, the qdisc_latency profiler tool has been added. It will visualise the amount a network packet spend in the network scheduler in an histogram. 
**Note:** The profiler requires at least kernel 5.14, as the tracepoints used were introduced in that kernel version. 
Run the new profiler via `ig profile qdisc-latency`. 
I tried running the gadget while performing various network tasks. One strange thing I could not get figured out though was, that I never managed to get a packet queued in my qdisc. Maybe somebody has an idea here? 
Fix #3118
=> gadgets: add qdisc_latency tracer

docs/spec/operators/oci.md, pkg/operators/oci-handler/oci.go
More explanations about the `pull-secret` parameter:
- It is a Kubernetes Secret
- The Kubernetes namespace is not configurable and is hardcoded to "gadget".
=> docs: pull-secret: more explanations

gadgets/profile_qdisc_latency/artifacthub-pkg.yml
See https://github.com/inspektor-gadget/inspektor-gadget/pull/3659#issuecomment-2671299658
> error getting package metadata (path: /tmp/artifact-hub1557883500/gadgets/profile_qdisc_latency): error validating package metadata file: 1 error occurred:
> invalid metadata: description not provided
Fixes: 76d79825e440 ("gadgets: add qdisc_latency tracer") #3659
cc @patrickpichler
=> artifacthub: add missing description for profile_qdisc_latency

.github/workflows/inspektor-gadget.yml, gadgets/Makefile, gadgets/trace_dns/README.mdx, gadgets/trace_dns/program.bpf.c, gadgets/trace_dns/test/integration/trace_dns_test.go, integration/ig/non-k8s/trace_dns_test.go, pkg/container-utils/testutils/docker.go, tools/dnstester/Dockerfile, tools/dnstester/dnstester.go
This change add support for TCP with per packet approach. It doesn't support to reassemble the segments but would be helpful since  nodelocaldns always uses TCP to resolve DNS on K8s nodes.
Ref: https://datatracker.ietf.org/doc/html/rfc7766#section-8
Related: https://github.com/inspektor-gadget/inspektor-gadget/issues/1416
```
/ # dig +tcp +short microsoft.com.
20.231.239.246
20.76.201.171
20.70.246.20
20.236.44.162
20.112.250.133
```
```
→ go run -exec sudo ./cmd/ig run trace_dns:qasim-dns-over-tcp --verify-image=false
WARN[0001] image signature verification is disabled due to using corresponding option 
WARN[0001] This gadget was built with ig v0.37.0-93-gf451011af-dirty and it's being run with v0.0.0. Gadget could be incompatible 
WARN[0002] image signature verification is disabled due …
```
=> trace_dns: TCP support w/o reassembly 

pkg/kallsyms/kallsyms_test.go
This PR adds several new test cases to improve code coverage for the kallsyms package. 
Reviewers can validate this PR by:
1. Running the full test suite: `go test ./pkg/kallsyms/`
2. Verifying the increased coverage: `go tool cover -func=coverage.out`
```bash
$ go test -coverprofile=coverage.out ./pkg/kallsyms/
ok  	github.com/inspektor-gadget/inspektor-gadget/pkg/kallsyms	0.482s
```
Part of [Feat:Improve Unit Test Coverage wherever required] #3835
=> [test]:improve coverage for kallsysms.go in pkg/kallsyms

pkg/datasource/formatters/json/options_test.go
Ref #3835
This PR add unit test for ``option.go``under ``pkg/datasource/formatters/json``. Covering ``withFields`` ``withShowAll`` ``withPretty`` ``withArray``.
This will give you brief idea about the test.
```
cd pkg/datasource/formatters/json
go test ./... -coverprofile=c.out  -v 
```
```
=== RUN   TestWithFields
=== RUN   TestWithFields/Testing_WithFields_with_custom_values
--- PASS: TestWithFields (0.00s)
--- PASS: TestWithFields/Testing_WithFields_with_custom_values (0.00s)
=== RUN   TestWithShowAll
=== RUN   TestWithShowAll/Testing_WithShowAll_with_custom_values
--- PASS: TestWithShowAll (0.00s)
--- PASS: TestWithShowAll/Testing_WithShowAll_with_custom_values (0.00s)
=== RUN   TestWithPretty
=== RUN   TestWithPretty/Testing_WithPretty_with_custom_values
--- PASS: TestWithPretty …
```
=> unit test pkg/datasource/formatters/json

pkg/operators/ebpf/ebpf_test.go, pkg/operators/oci-handler/oci.go
If loading an image operator fails, then make the whole thing fail.
Fixes: 83cb51de48f7 ("pkg/operators/oci: add OCI handler")
Create an image with an invalid wasm layer:
```diff
diff --git a/pkg/operators/wasm/testdata/badguest/program.go b/pkg/operators/wasm/testdata/badguest/program.go
index 6cd2e2b1..cc74b45c 100644
--- a/pkg/operators/wasm/testdata/badguest/program.go
+++ b/pkg/operators/wasm/testdata/badguest/program.go
@@ -109,7 +109,7 @@ func fieldGet(acc uint32, data uint32, kind uint32) uint64
func fieldSet(acc uint32, data uint32, kind uint32, value uint64) uint32
//go:wasmimport env getParamValue
-func getParamValue(key uint64) uint64
+func getParamValue(key uint64) uint32
//go:wasmimport env setConfig
func setConfig(key uint64, val uint64, kind uint32) uint32
```
```bash 
$ …
```
=> oci: Error out when handling wrong image

gadgets/fsnotify/program.bpf.c
Reduce max_entries of enriched_fsnotify_events map from 10240 to 1024. This reduces the size from 42 MiB to 4 MiB.
Part of #4069
No changes.
Before:
```
$ sudo bpftool map show -j | jq -r '.[] | {id: .id, type: .type, name: .name, bytes_memlock: .bytes_memlock, comms: (if .pids then (.pids | map(.comm) | unique | join(",")) else "" end)} | [.id, .type, .name, .bytes_memlock, .comms] | @tsv' | sort -k4n | column -t -s $'\t'|grep ig
19598  hash          ig_fa_pick_ctx   6368      ig
19605  hash          fsnotify_remove  6368      ig
19602  hash          fsnotify_insert  6912      ig
19608  array         .bss             8192      ig
19607  array         .rodata          12288     ig
19609  percpu_array  gadget_heap      41288     ig
19601  hash          mntnsset_f6e864  83168     ig
19604 …
```
=> fsnotify: reduce map size

docs/gadget-devel/gadget-wasm-api-raw.md, gadgets/deadlock/go/program.go, gadgets/trace_dns/go/program.go, gadgets/trace_exec/go/program.go, gadgets/trace_fsslower/go/program.go, gadgets/trace_mount/go/program.go, pkg/operators/wasm/fields.go, pkg/operators/wasm/helpers.go, pkg/operators/wasm/params.go, pkg/operators/wasm/perf.go, pkg/operators/wasm/syscalls.go, pkg/operators/wasm/testdata/badguest/program.go, pkg/operators/wasm/testdata/params/program.go, pkg/operators/wasm/testdata/perf/program.go, pkg/operators/wasm/wasm.go, wasmapi/go/config.go, wasmapi/go/datasource.go, wasmapi/go/fields.go, wasmapi/go/handle.go, wasmapi/go/helpers.go, wasmapi/go/kallsyms.go, wasmapi/go/log.go, wasmapi/go/map.go, wasmapi/go/params.go, wasmapi/go/perf.go, wasmapi/go/syscall.go
Malloc() was required to be able to allocate and write data into the
guest memory. This requirement was a bit strict as:
- malloc() is exposed when using tinygo by a obscure undocumented way
- This isn't exposed when using go 1.24
- It can be challenging to expose on another programming languages
This commit removes this requirement. The main change is that the guest
now has to pass a preallocated buffer where the host will write the data.
It can be suboptimal for some cases when the guest doesn't know the
size, but it can help to reduce the allocations if the guest passes a
static buffer in multiple calls. (As it was done in the trace_exec and
trace_dns gadgets).
After applying this change, we can use go 1.24 to compile our gadgets as experimented on …
=>  wasm: Remove malloc requirement for guest

.github/workflows/dockerhub-mirror.yml
Location should be ghcr.io/inspektor-gadget/ci/foo instead of ghcr.io/inspektor-gadget/inspektor-gadget/ci/foo.
Fixes: 3175b3db4bd6 ("ci: Mirror dockerhub images to our repo")
Ref https://github.com/inspektor-gadget/inspektor-gadget/pull/4122#discussion_r1969867592
=> ci: Fix location of ci images

.github/workflows/check-links.yml, .github/workflows/inspektor-gadget.yml, .github/workflows/mlc_config.json
The link check action was often failing due to repeatitive checks. This was annoying because it makes PRs fail due to links unrelated to the PR being tested.
This patch uses the check-modified-files-only parameter, so pull requests will only check the links that were modified in the PR.
This also adds a daily job to test all the links, so we learn about links that become broken.
=> ci: check links

gadgets/trace_capabilities/program.bpf.c
Before this patch, the trace_capabilities gadget didn't work on AKS and EKS. It failed with:
> rpc error: code = Unknown desc = starting operators: starting operator "oci": starting operator "ebpf": creating eBPF collection: program ig_trace_cap_x: load program: permission denied: 138: (85) call bpf_map_lookup_elem#1: R2 type=alloc_mem expected=fp, pkt, pkt_meta, map_value (232 line(s) omitted)
This is because of the following code pattern:
```c
event = gadget_reserve_buf(&events, sizeof(struct cap_event));
if (!event)
return 0;
gadget_process_populate(&event->proc);
sc_ctx = bpf_map_lookup_elem(&current_syscall, &event->proc.pid);
```
Arg2 is a pointer to a ringbuf allocated memory.
With that code pattern, we need Linux 6.1 for https://github.com/torvalds/linux/commit/894f2a8b1673a355a1a7 …
=> trace_capabilities: support for Linux < 6.1

gadgets/snapshot_process/test/unit/snapshot_process_test.go
The TestSnapshotProcessGadget/captures_events_with_no_filter is failing a lot because it's not able to capture the event. Increase the timeout to be sure sleep lasts long enough to be captured by the gadget.
=> snapshot_process: Increase timeout to fix test

Dockerfiles/ebpf-builder.Dockerfile
The workaround was introduced in a64e9228d3c6 ("ebpf-builder.Dockerfile: workaround to install software-properties-common") #4084.
---
Let's check the CI to see if the error described in #4084 is fixed.
=> ebpf-builder.Dockerfile: remove workaround on software-properties-common

cmd/ig/main.go, docs/spec/operators/env.md, gadget-container/gadgettracermanager/main.go, pkg/operators/env/env.go, pkg/operators/env/env_test.go
This operator lets you add new fields to datasources and fill it with contents of environment variables. For security reasons, environment variables that should be read by the operator need to be configured explicitly using the `--env-vars` parameter.
Annotations need to look like this:
```yaml
datasources:
myds:
annotations:
env.fields.my-new-field: ENV_VAR_1
```
=> operators/env: introduce operator to create new fields from environment variables

pkg/datasource/helpers.go, pkg/operators/otel-logs/otel-logs.go, pkg/operators/otel-metrics/otel-metrics.go
This allows properly overriding the keys of metrics/log fields with for example a name coming from an annotation.
This is only used for otel-logs currently, but might be added to otel-metrics in the future.
=> otel: allow overriding key/name

.github/actions/prepare-and-publish-test-reports/action.yml, .github/workflows/inspektor-gadget.yml, tools/store-test-reports.sh
As mentioned here https://github.com/actions/upload-artifact?tab=readme-ov-file#breaking-changes we shouldn't be using same artifact name for a workflow run. This change uses the suffix to ensure we don't use the same artifact name for all the reports.
Fixes: #3177
=> ci: Use different name for test-report artifacts

.github/actions/run-integration-tests/action.yml
Fixes: c6dda023212e1126f4715595140ac3f842a485a6
We want to run the integration tests for builtin gadgets and image based gadgets.
This PR fixes the part for the image based gadgets. It skips building the gadgets again in this testing step. Instead it will just use/pull the gadgets that were built in `Build and push gadgets`
=> CI/Integration tests: Skip building gadgets

docs/gadget-devel/gadget-wasm-api-raw.md, pkg/operators/wasm/fields.go, pkg/operators/wasm/helpers.go, pkg/operators/wasm/testdata/Makefile, pkg/operators/wasm/testdata/baderrptr/build.yaml, pkg/operators/wasm/testdata/baderrptr/go.mod, pkg/operators/wasm/testdata/baderrptr/program.go, pkg/operators/wasm/testdata/badguest/program.go, pkg/operators/wasm/wasm_test.go, wasmapi/go/fields.go
Before this commit it wasn't possible to distinguish between an error
and a field with value 0. This commit introduces a new error parameter
to report the error value instead of having the return value used for
both purposes.
Fixes #3071
Requires  #4097 to be merged first
=> wasm: Fix error ambiguity for fieldGetScalar

Dockerfiles/ebpf-builder.Dockerfile, cmd/common/image/helpers/Makefile.build, docs/gadget-devel/building.md, pkg/operators/wasm/testdata/baderrptr/program.go, pkg/operators/wasm/testdata/badguest/program.go, pkg/operators/wasm/wasm_test.go, wasmapi/go/doc.go
Fixes https://github.com/inspektor-gadget/inspektor-gadget/issues/4000
=> WASM: Use Go 1.24 for the wasmylayer instead of TinyGo

.github/actions/run-integration-tests/action.yml, .github/actions/set-container-repo-and-determine-image-tag/action.yml, .github/workflows/inspektor-gadget.yml, Makefile, cmd/common/image/build.go, docs/api/_golang/datasource/main.go, docs/api/_golang/from_file/main.go, docs/api/_golang/from_memory/main.go, docs/api/_golang/grpc/main.go, docs/api/_golang/operators/main.go, docs/api/_golang/trace_open/main.go, docs/api/golang.mdx, examples/gadgets/other/mutate/main.go, examples/gadgets/trace_dns/main.go, gadgets/trace_dns/test/integration/trace_dns_test.go, integration/components/image/integration_test.go, integration/ig/non-k8s/Makefile, integration/ig/non-k8s/integration_test.go, integration/k8s/Makefile, integration/k8s/integration_test.go, tools/image-tag
We're using latest on the wrong way, use main to indicate this is about the development version.
Part of #4049
=> ci: Use main instead of latest for container tags

Dockerfiles/ig.Dockerfile, docs/gadget-devel/building.md, docs/reference/verify-assets.mdx, gadgets/Makefile
Fixes: c192e6c241ac ("ci: Use main instead of latest for container tags")
Ref https://github.com/inspektor-gadget/inspektor-gadget/pull/4179#issuecomment-2704350522
cc @alban
=> tree-wide: Update ebpf-builder missing refs

pkg/gadget-context/run.go, pkg/operators/ebpf/ebpf.go, pkg/operators/ebpf/maps.go, pkg/operators/oci-handler/oci.go, pkg/operators/operators.go, pkg/operators/wasm/wasm.go
Add new hook that can be used by gadgets that need to print their output just before stopping as advise seccomp developed in #4089
=> operators: Add pre stop lifecycle

Dockerfiles/gadget.Dockerfile, Dockerfiles/ig-tests.Dockerfile, Dockerfiles/ig.Dockerfile, Dockerfiles/kubectl-gadget.Dockerfile
As per this [blog](https://www.docker.com/blog/containerize-your-go-developer-environment-part-2/), we can use incremental builds to improve building things locally. Currently if we make a single change entire build layer is invalidated but this change allows making use of Go’s compiler cache to ensuring we don't compile everything from scratch. Other projects using this:
- https://github.com/kedacore/keda/blob/main/Dockerfile#L29
- https://github.com/docker/buildx/blob/master/Dockerfile#L81
- https://github.com/containerd/containerd/blob/main/.github/workflows/release/Dockerfile#L50
Before testing clean everything using ` docker system prune -fa && docker builder prune -f`:
```
$ docker system prune -fa && docker builder prune -f
$ make ig
$  sed -i 's/gadgets for/awesome gadgets for/g' …
```
=> Dockerfiles: Use --mount-type=cache

.github/workflows/inspektor-gadget.yml, Makefile
The lint step in https://github.com/inspektor-gadget/inspektor-gadget/pull/4214 fails. While running `make lint` locally on that branch, the RAM usage just keeps rising (over 30GB) and then it gets OOM killed.
Updating `golangci-lint` resolves this issue.
=> golangci-lint: Update to v1.64.8

docs/gadget-devel/gadget-wasm-api-raw.md, pkg/operators/wasm/testdata/baderrptr/program.go, pkg/operators/wasm/testdata/badguest/program.go, pkg/operators/wasm/wasm.go, wasmapi/go/config.go, wasmapi/go/datasource.go, wasmapi/go/fields.go, wasmapi/go/handle.go, wasmapi/go/kallsyms.go, wasmapi/go/log.go, wasmapi/go/map.go, wasmapi/go/params.go, wasmapi/go/perf.go, wasmapi/go/syscall.go
We should name our module `ig` instead of `env`
=> wasm: Change module name from env to ig

gadgets/fsnotify/README.mdx, gadgets/fsnotify/gadget.yaml, gadgets/fsnotify/go/program.go, gadgets/fsnotify/program.bpf.c, gadgets/fsnotify/test/unit/fsnotify_test.go, gadgets/testing/testing.go
Linux had the following changes:
* The fanotify_event type changed in Linux 5.6 (https://github.com/torvalds/linux/commit/7088f35720a55b99624ea36091538baec7ec611f), so we need to use CORE functions to access it.
* Function `inotify_handle_inode_event` replaced `inotify_handle_event` in Linux 5.10 (https://github.com/torvalds/linux/commit/1a2620a99803ad660edc5d22fd9c66cce91ceb1c), so we need to enable/disable attachments appropriately in the WASM module.
No changes
```
make -C gadgets VIMTO=/home/alban/go/bin/vimto IG_DEBUG_LOGS=true IG_VERIFY_IMAGE=false GADGET_TAG=alban_fsnotify_linux5.4 KERNEL_VERSION=5.4 fsnotify/test-unit
make -C gadgets VIMTO=/home/alban/go/bin/vimto IG_DEBUG_LOGS=true IG_VERIFY_IMAGE=false GADGET_TAG=alban_fsnotify_linux5.4 KERNEL_VERSION=5.10 fsnotify/test-unit …
```
=> fsnotify gadget: add support for Linux 5.4

pkg/gadget-context/context_test.go, pkg/gadget-context/run.go
Just taking the priority of an operator is not enough to get a deterministic order of the operators. In case two operators have the same priority, the name should also be considered for the run order.
Non-deterministic ordering can mix up for example fields in data sources, when multiple nodes are running the same operators but in a different oder.
/cc @burak-ok
=> pkg/gadget-context: sort operators by priority and name to be deterministic

pkg/oci/oci.go
The updated OCI store didn't get written to disk after importing a gadget image, so that importing had no effect.
This fixes it.
Bug was introduced in #3842
Fixes #4208
=> oci: call `saveIndexWithLock` after importing gadget images

pkg/oci/oci.go
The updated OCI store didn't get written to disk after importing a gadget image, so that importing had no effect.
Fixes: 12453a012de6 ("pkg/oci: Use a file lock to avoid concurrency issues")
Fixes: #4208
cc @flyth
=> [Backport v0.38] oci: call `saveIndexWithLock` after importing gadget images

pkg/operators/common/datasource.go, pkg/operators/formatters/formatters.go, pkg/operators/formatters/formatters_test.go
This PR is an effort towards the issue #3835 and introduces unit tests for the **formatters operator** in `formatters_test.go`. These tests validate the formatting logic for various field types, ensuring that raw values are correctly converted into human-readable formats. Specifically, it includes tests for:  
- **General formatting cases** (timestamps, signals, errnos, bytes, durations, syscalls)  
- **L3 (Layer 3) formatter** for IP addresses  
- **L4 (Layer 4) formatter** for network endpoints, including IPs, ports, and protocols  
The tests verify the expected output for each case and ensure that the corresponding replacers function correctly.  
Note: These testcases are focused to be purely testing the formatters code. Like the tests of some other operators, these tests do not depend …
=> Implementing Formatters Operator Unit Tests

pkg/operators/limiter/limiter.go, pkg/operators/limiter/limiter_test.go
This PR introduces a set of unit test cases for the `limiter` operator, ensuring its correct behavior when applied to data sources of type array. The `limiter` operator restricts the number of entries in each batch of data, which is useful when sorting and filtering the top `X` entries.
The test cases cover various scenarios, including:
- Limiting a dataset to a smaller size.
- Applying a limit equal to the original dataset size.
- Using a limit greater than the dataset size.
- Handling negative limit values to ensure proper error handling.
Reviewers can validate this PR by running the test cases included in `limiter_test.go`. The tests ensure that the `limiter` function correctly modifies the dataset size or returns errors when given invalid input.
To run the tests, use:
```sh
go test -v …
```
=> Add Limiter Operator Unit Tests

pkg/container-collection/containers.go, pkg/container-collection/options.go, pkg/datasource/compat/wrapper.go, pkg/types/types.go
When the podLabels and ownerReference fields are requested in each event, it generates lots of allocations, which takes some cpu time directly and more cpu time indirectly with the Go GC.
This patch reduces those allocations by keeping a cache of the serialized podLabels string. Also, don't allocate the ownerReference field twice.
=> container-collection: reduce mem allocs for each event

docs/quick-start.md, docs/reference/install-kubernetes.md, docs/reference/install-linux.md
We received user feedback that the quick-start documentation does not make clear that the different installation methods must not all be used, but the user must choose one method instead.
This patch also add some filter flags to make the scenario more realistic.
cc @rata
=> docs: quick-start: clarify different options

docs/gadget-devel/gadget-ebpf-api.md, gadgets/trace_capabilities/README.mdx, gadgets/trace_capabilities/gadget.yaml, gadgets/trace_capabilities/program.bpf.c, gadgets/trace_capabilities/test/integration/trace_capabilities_test.go, gadgets/trace_malloc/README.mdx, gadgets/trace_malloc/gadget.yaml, gadgets/trace_malloc/program.bpf.c
The --print-ustack and --print-kstack flags didn't control whether the stacks are printed but whether they are collected (in ebpf code and in the ustack operator). Hence it makes sense to rename them.
To print the stacks, users must either include the stack fields in the column output with --fields, or use json/yaml output.
=> gadget params: rename print-*stack to collect-*stack

gadgets/trace_open/README.mdx, gadgets/trace_open/gadget.yaml, gadgets/trace_open/program.bpf.c
Example of output for a simple Go program opening a file:
```
sudo ig run ghcr.io/inspektor-gadget/gadget/trace_open:alban_trace_open_ustack \
--pull=never --verify-image=false \
--host --comm=gocat --collect-ustack -o yaml
...
ustack: '[0]internal/runtime/syscall.Syscall6; [1]syscall.Syscall6; [2]syscall.openat;
[3]os.open; [4]os.openFileNolog; [5]os.OpenFile; [6]main.main; [7]runtime.main;
[8]runtime.goexit.abi0; '
```
This is the same implementation as:
- trace_malloc in commit d33e3325b2c30ca0884b1d30028213f56a379b32
- trace_capabilities in commit 0b76243b4c6ae4cd1270324fdf3eea944d8e1397
=> gadget trace_open: add user stacks

integration/components/image/image_test.go
Add logic to check that the image was actually imported.
Fixes #4227
=> tests: Fix image export and import tests

cmd/common/image/inspect.go, docs/reference/images.md
adds flags oci flags to `inspect` command, mainly making pull policy and image verification configurable
```
$ sudo ./ig image inspect trace_dns:main --pull never --verify-image=false
WARN[0000] image signature verification is disabled due to using corresponding option 
{
"ebpf.maps": {
"content": "[{\"Name\":\"gadget_mntns_filter_map\",\"Type\":\"Hash\"},{\"Name\":\"tmp_events\",\"Type\":\"PerCPUArray\"},{\"Name\":\"query_map\",\"Type\":\"Hash\"},{\"Name\":\"events\",\"Type\":\"PerfEventArray\"},{\"Name\":\"gadget_sockets\",\"Type\":\"Hash\"}]",
"contentType": "application/json"
},
"ebpf.programs": {
...
```
Related to #4270
=> inspect: makes pull policy and verify-image configurable

docs/gadget-devel/gadget-ebpf-api.md, gadgets/trace_capabilities/gadget.yaml, gadgets/trace_capabilities/program.bpf.c, gadgets/trace_capabilities/test/integration/trace_capabilities_test.go, gadgets/trace_malloc/gadget.yaml, gadgets/trace_malloc/program.bpf.c, gadgets/trace_open/gadget.yaml, gadgets/trace_open/program.bpf.c, pkg/operators/ustack/ustack.go, pkg/symbolizer/symbolizer.go
For now, we have only one symbolizer: symtab. I am planning to add more symbolizers in future PRs for goresym and debuginfod.
The symtab symbolizer fills the new sub-field symbols:
```yaml
ustack:
addresses: '[0]0x000000000040332e; [1]0x00000000004771e6; [2]0x000000000047752e;
[3]0x000000000048250b; [4]0x00000000004829ae; [5]0x0000000000482a7e; [6]0x0000000000482afe;
[7]0x0000000000482b7e; [8]0x0000000000435a9d; [9]0x00000000004625a1; '
symbols: '[0]runtime/internal/syscall.Syscall6; [1]syscall.Syscall; [2]syscall.Syscall.abi0;
[3]golang.org/x/sys/unix.Chroot; [4]main.level3; [5]main.level2; [6]main.level1;
[7]main.main; [8]runtime.main; [9]runtime.goexit.abi0; '
...
```
Using --symbolizers=none means the ustack operator will not run the symbolizer, so the symbols sub-field will be empty: …
=> ustack: add --symbolizers parameter

pkg/container-collection/containers.go
Distinguish `c.K8s.PodLabels == nil` from an empty map. [IsEnriched](https://github.com/inspektor-gadget/inspektor-gadget/blob/48296c35caee65c8304ab13d7692c71e9f28c538/pkg/types/types.go#L171-L173) uses `if b.PodLabels != nil` to check if the PodLabels are already set.
Fixes: 8647f0e04eb5 ("container-collection: reduce mem allocs for each event")
See: https://github.com/inspektor-gadget/inspektor-gadget/pull/4237#discussion_r2021233164
Use `--enrich-with-k8s-apiserver`.
Test on Minikube. Prepare the permissions for `ig` to run:
```
kubectl create serviceaccount -n kube-system ig
kubectl create clusterrolebinding ig \
--clusterrole=cluster-admin \
--serviceaccount=kube-system:ig
```
Test on `main` branch:
```
kubectl debug -n kube-system \
--as system:serviceaccount:kube-system:ig \ …
```
=> container-collection: fix SetPodLabels

gadgets/trace_dns/README.mdx
As discussed https://github.com/inspektor-gadget/inspektor-gadget/pull/3951#discussion_r1974043709 we were displaying the host information as a bug. `trace_dns` documentation was using it in one of the example but since the reference PR has been merged we can remove it from the documentation.
=> trace_dns: Remove the section for OS level tracing

gadgets/audit_seccomp/README.mdx, gadgets/audit_seccomp/gadget.yaml, gadgets/audit_seccomp/program.bpf.c
This is done in the same way as other gadgets:
- trace_capabilities
- trace_malloc
- trace_open
Documentation added in the PR.
I used the following `profile.json`:
```json
{
"defaultAction" : "SCMP_ACT_ALLOW",
"syscalls" : [
{
"action" : "SCMP_ACT_KILL",
"names" : [
"unshare",
"chroot"
]
}
]
}
```
And the following Go program:
```go
package main
import (
"fmt"
"time"
"unsafe"
"golang.org/x/sys/unix"
)
func level3() {
fmt.Printf("level3: %v\n", level3)
err := unix.Chroot("/")
fmt.Printf("chroot: err=%v\n", err)
}
func level2() {
fmt.Printf("level2: %v\n", level2)
level3()
}
func level1() {
fmt.Printf("level1: %v\n", level1)
level2()
}
func main() {
fmt.Printf("main: %v\n", main)
level1()
time.Sleep(time.Second)
}
```
With the following command:
```
docker run --name test-audit-seccomp -v …
```
=> gadget audit_seccomp: add user stacks

docs/gadget-devel/gadget-wasm-api-raw.md, docs/gadgets/advise_seccomp.mdx, docs/gadgets/files/seccomp-confined.yaml, docs/gadgets/files/seccomp-unconfined.yaml, gadgets/Makefile, gadgets/advise_seccomp/README.md, gadgets/advise_seccomp/README.mdx, gadgets/advise_seccomp/artifacthub-pkg.yml, gadgets/advise_seccomp/build.yaml, gadgets/advise_seccomp/gadget.yaml, gadgets/advise_seccomp/go/go.mod, gadgets/advise_seccomp/go/program.go, gadgets/advise_seccomp/program.bpf.c, gadgets/advise_seccomp/test/unit/advise_seccomp_test.go, pkg/operators/wasm/filter.go, pkg/operators/wasm/testdata/Makefile, pkg/operators/wasm/testdata/filtering/build.yaml, pkg/operators/wasm/testdata/filtering/go.mod, pkg/operators/wasm/testdata/filtering/program.go, pkg/operators/wasm/wasm.go, pkg/operators/wasm/wasm_test.go, pkg/testing/gadgetrunner/gadgetrunner.go, wasmapi/go/filter.go
Implement the advise_seccomp as image-based
This is heavily based on #3718.  
- adds a PreStop() lifecycle hook to do things "last minute"
- fixes lifecycle of WASM instances
- adds "flush-on-stop" annotation for map fetching in PreStop()
- The eBPF code collects syscalls in a per mount namespace map. It's registered as a map-iter. 
- The wasm module subscribes to that map, and also creates a new text datasource with the seccomp policy output.
- When the gadget is stopped, the ebpf map is read and emitted, then the wasm module generates the seccomp policy
The gadget needs to be run with some specific params, when it's stopped, prints a seccomp policy for each container on the system that was allowed by the filtering options:
```bash 
$ sudo ig run advise_seccomp --verify-image=false …
```
=> gadgets: Implement advise_seccomp as image-based

gadgets/top_tcp/test/integration/top_tcp_test.go, gadgets/trace_bind/test/integration/trace_bind_test.go, gadgets/trace_tcp/test/integration/trace_tcp_test.go, gadgets/trace_tcpretrans/test/integration/trace_tcpretrans_test.go, pkg/operators/kubeipresolver/kubeipresolver.go, pkg/testing/utils/utils.go
operators/KubeIPResolver: Set kind to `raw` when its not a `pod` and `svc`
=> operators/KubeIPResolver: Set kind to raw when its not a pod and svc

cmd/common/image/list.go, cmd/common/image/remove.go
I'm used to calling the shorter aliases on Docker, this makes them also available on ig.
Before:
```bash
$ sudo ./ig image ls
Manage gadget images
Usage:
ig image [command]
Available Commands:
build       Build a gadget image
export      Export the SRC_IMAGE images to DST_FILE
import      Import images from SRC_FILE
inspect     Inspect a gadget image
list        List gadget images on the host
pull        Pull the specified image from a remote registry
push        Push the specified image to a remote registry
remove      Remove local gadget image
tag         Tag the local SRC_IMAGE image with the DST_IMAGE
...
```
After:
```bash
$ sudo ./ig image ls
REPOSITORY                                                                   TAG …
```
=> ig(UX): add aliases for image list (ls) and remove (rm)

cmd/kubectl-gadget/deploy.go, docs/gadgets/bpfstats.mdx, gadgets/Makefile, gadgets/bpfstats/README.md, gadgets/bpfstats/README.mdx, gadgets/bpfstats/artifacthub-pkg.yml, gadgets/bpfstats/gadget.yaml, gadgets/bpfstats/test/unit/bpfstats_test.go, pkg/bpfstats/bpfstats.go, pkg/config/gadgettracermanagerconfig/config.go, pkg/gadget-context/gadget-context.go, pkg/gadget-context/options.go, pkg/gadget-service/instance-manager/instance.go, pkg/gadgets/top/ebpf/tracer/tracer.go, pkg/operators/ebpf/ebpf.go, pkg/operators/ebpf/stats.go, pkg/operators/kubemanager/kubemanager.go, pkg/operators/operators.go, pkg/runtime/runtime.go, pkg/testing/gadgetrunner/gadgetrunner.go
This PR introduces support for exposing statistics (metrics) about the ebpf programs and gadgets running on the system. 
Check the individual commits to get more details on the implementation.
1. build the gadget
```bash 
$ sudo ig image build gadgets/bpfstats -t bpfstats
```
2. start ig on daemon mode 
```bash 
$ sudo ig daemon --verify-image=false --enable-bpfstats
```
3. Run some gadgets
```bash 
$ sudo gadgetctl run --name mytraceopen trace_open:latest --detach
$ sudo gadgetctl run --name mytraceexec trace_exec:latest --detach
```
4. Run the bpfstats gadget 
```bash 
$ sudo gadgetctl run bpfstats --sort -runtime
WARN[0000] local                | image signature verification is disabled due to using corresponding option
GADGETID    GADGETNAME           GADGETIMAGE          PROGID …
```
=> gadgets: Introduce bpfstats gadget

pkg/operators/common/common_test.go, pkg/operators/common/kubeinventorycache.go
This PR introduces a full suite of unit tests for the `inventoryCache` component in `pkg/operators/common/`. The tests cover the complete lifecycle of the cache, including `Start()`/`Stop()` reference counting, and all CRUD handlers (`OnAdd`, `OnUpdate`, and `OnDelete`) for both Pods and Services. Additionally, various edge cases are validated, such as handling invalid inputs, unknown types, and missing metadata that lead to expected logging of errors.
The new test cases improve confidence in the correctness of the cache implementation and its interactions with underlying Kubernetes objects. These tests validate behavior for lookup by name and IP, and also ensure correct log output when expected errors occur. Each test is isolated and uses the `cachedmap` with short timeouts to simulate …
=> Unit Tests for Inventory Cache

pkg/operators/ebpf/formatters.go, pkg/operators/ebpf/formatters_test.go
This PR introduces parameterized test cases for validating the `fetchAndFormatStackTrace` function and the `getFormattersForEnums` function. These tests ensure correct functionality for various stack trace scenarios and enum formatting conditions. (an effort towards #3835 )
For `fetchAndFormatStackTrace`, the test cases verify correct stack trace formatting for:
- A valid stack trace with multiple entries.
- An empty stack trace.
- A single valid entry.
For `getFormattersForEnums`, the test cases validate:
- Correct mapping of non-bitfield enums.
- Proper handling of bitfield enums with different separators.
- Handling of unknown enum values.
- Cases where multiple enums are present.
To validate this PR, reviewers should:
1. Run the tests using:
```sh
go test -run TestFetch -v …
```
=> Added unit tests for formmaters in ebpf operator

gadgets/bpfstats/README.mdx
`{}` in BPF_MAP_TYPE_{HASH,ARRAY}_OF_MAPS was making the website build to fail. I put backticks around it to fix the build.
Was hitting this issue on my PR: https://github.com/inspektor-gadget/inspektor-gadget/actions/runs/14404543472/job/40397739857
CI is [green](https://github.com/inspektor-gadget/inspektor-gadget/actions/runs/14405204745/job/40399967243?pr=4325).
=> docs: Fix website build

.github/workflows/inspektor-gadget.yml, docs/reference/install-kubernetes.md
This change publishes helm-charts for on `main` / `releases` to OCI registry. 
Note: For `main` the chart will have `1.0.0-dev` version. I am also fine if we want to skip publishing chart for `main`?
Fixes #2412
I pushed the changes to `main` on fork: https://github.com/mqasimsarfraz/inspektor-gadget/actions/runs/14403695873/job/40394987337
=> ci: Publish helm-charts to registry

cmd/common/image/image.go, cmd/gadgetctl/main.go, cmd/ig/main.go, cmd/kubectl-gadget/main.go
- extends the `NewImageCmd` to receive the new 'addCommands' param which can be used to add image commands optionally in `gadgetctl/kubectl-gadget` (only commands that are grpc-supported)
- adds inspect command in `kubectl-gadget`
Part of #3387
=> inspect: adds command to kubectl-gadget

cmd/common/utils/flags.go
Refer #4204 
The logic is currently working for in-built gadgets and I think the same will work for image based too but I am facing issues with running image based gadgets..I think there is  some version compatibility issue.
=> Remove panic when sort used incorrectly

pkg/operators/cli/clioperator.go, pkg/operators/cli/clioperator_test.go
This PR introduces a set of tests for the CLI operator functionality, covering various input field scenarios. The tests evaluate how the system handles different input values, such as single fields, multiple fields, empty fields, numbers as strings, and cases with a large number of fields. The tests ensure that the expected outputs are generated correctly in default, YAML, and JSON formats. (an effort towards #3835 )
The changes include the addition of two major test functions: `TestCliOperators` and `TestJsonArray`. Each test checks the correct output for different combinations of input values. This includes checking if the program formats single and multiple fields correctly in different serialization formats (default, YAML, JSON), and ensures proper handling of edge cases like empty …
=> Cli Operator Unit Tests

gadgets/trace_dns/program.bpf.c
Currently when build dns gadget I see following warning
```
$ export GADGET_BUILD_PARAMS=--verbose
$ make -C gadgets IG=$PWD/ig trace_dns
make: Entering directory '/home/qasim/work/cloud/github.com/inspektor-gadget/inspektor-gadget/gadgets'
Building trace_dns
Pulling builder image ghcr.io/inspektor-gadget/gadget-builder:main
main: Pulling from inspektor-gadget/gadget-builder
...
/work/gadgets/trace_dns/program.bpf.c:290:3: warning: label followed by a declaration is a C23 extension [-Wc23-extensions]
290 |                 struct tcphdr tcph;
|                 ^
/work/gadgets/trace_dns/program.bpf.c:290:3: warning: label followed by a declaration is a C23 extension [-Wc23-extensions]
290 |                 struct tcphdr tcph;
|                 ^
...
```
After this change we don't see the …
=> trace_dns: Handling warning during build

gadgets/trace_capabilities/program.bpf.c
The variable mntns_id is used without initialization. The bug was introduced after refactoring filters.
Compiler warnings:
```
/work/gadgets/trace_capabilities/program.bpf.c:206:16: warning: variable 'mntns_id' is uninitialized when used here [-Wuninitialized]
206 |                         .mntns_id = mntns_id,
|                                     ^~~~~~~~
/work/gadgets/trace_capabilities/program.bpf.c:174:14: note: initialize the variable 'mntns_id' to silence this warning
174 |         u64 mntns_id;
|                     ^
|                      = 0
```
Compiler warnings were not printed because of #4343.
Fixes 728b2eb59aa8 ("gadgets: Use filter helpers from last commit")
No changes.
Test workload:
```
for i in `seq 20` ; do docker run -d --env i=$i --privileged ubuntu sh -c "sleep 5 ; …
```
=> trace_capabilities: fix use of uninitialized variable

docs/reference/images.md, pkg/operators/oci-handler/extrainfo.go, pkg/operators/oci-handler/oci.go
This PR adds extra oci information in the inspect command
```
$ sudo ./ig image inspect trace_dns:main | jq 'with_entries(select(.key | startswith("oci")))'
"oci.created": {
"content": "2025-04-01T16:19:23Z",
"contentType": "text/plain"
},
"oci.digest": {
"content": "sha256:87de05648f4a380edc3b3187d875b47dd094f71e40dc76400918615705e3eb34",
"contentType": "text/plain"
},
"oci.manifest": {
"content": "{\"schemaVersion\":2,\"...,
"contentType": "application/vnd.oci.image.manifest.v1+json"
},
"oci.metadata": {
"content": "name: trace dns\ndescription: ...",
"contentType": "text/yaml"
},
"oci.repository": {
"content": "ghcr.io/inspektor-gadget/gadget/trace_dns",
"contentType": "text/plain"
},
"oci.tag": {
"content": "main",
"contentType": "text/plain"
}
}
```
Part of #3387
=> inspect: adds oci extra info

pkg/operators/ebpf/extrainfo.go
This PR aims to add ebpf relocations info in the `image inspect` subcommand.
Part of https://github.com/inspektor-gadget/inspektor-gadget/issues/3387
=> inspect: adds ebpf relocations in extraInfo

.github/workflows/release.yml, Makefile, gadgets/Makefile
This commit adds logic to update the latest tag for the container images to point to the latest release.
Fixes #4049
I did a release test on my fork: https://github.com/mauriciovasquezbernal/inspektor-gadget/actions/runs/14651783727/job/41119058541
`latest` and `v0.100.0` point to the same digest:
```bash 
$ docker pull ghcr.io/mauriciovasquezbernal/inspektor-gadget:v0.100.0
v0.100.0: Pulling from mauriciovasquezbernal/inspektor-gadget
Digest: sha256:e072440047636d2588a14b2038c6c632174a30c6135ccc528c5bb4acd8d5fd33
Status: Image is up to date for ghcr.io/mauriciovasquezbernal/inspektor-gadget:v0.100.0
ghcr.io/mauriciovasquezbernal/inspektor-gadget:v0.100.0
$ docker pull ghcr.io/mauriciovasquezbernal/inspektor-gadget:latest
latest: Pulling from mauriciovasquezbernal/inspektor-gadget
Digest: …
```
=> ci: Automatically update the latest tag on release

Makefile
Commit 9bd1f3e0aa08 ("Rename ebpf-builder to gadget-builder") renamed EBPF_BUILDER to GADGET_BUILDER, but commit a0ad5aab6b3d ("Makefile: Build ig for host architecture with go build instead of docker.") missed it and used the old EBPF_BUILDER.
This caused the builder image to be empty when ig was compiled with `make ig` producing an error when building a Gadget:
```bash
$ ig image build -h | grep builder
--builder-image string        Builder image to use
$ sudo ig image build .
Pulling builder image
Error: pulling builder image: invalid reference format
```
Fixes: a0ad5aab6b3d ("Makefile: Build ig for host architecture with go build instead of docker.") 
Link: https://kubernetes.slack.com/archives/CSYL75LF6/p1745944201173279
=> Makefile: Update missing reference of EBPF_BUILDER

docs/spec/operators/kubenameresolver.md, pkg/operators/kubenameresolver/kubenameresolver.go
This will be needed for `advise networkpolicy`
This Operator will now be always active for K8s deployments.
Is this okay? Should it be configurable instead? Or are we still waiting for the config to selectivly disable operators in general
=> KubeNameResolver: Add support for image based gadgets

pkg/operators/ebpf/maps.go
The current logic relies on the client to set the value for the parameters. This is done by kubectl-gadget, gadgetctl or ig by performing a call to GetGadgetInfo() to get the list of parameters and their default values. The issue here arises when using the headless mode, as in this case, the call to GetGadgetInfo() is not done, so the value for those parameters is missing if not explicitely set by the user in the gadget manifest file. This behavior causes all gadgets that depend on the "map-fetch-interval" param as it's set to 0.
The ideal solution for it should be something like 3c7f729e83ef ("pkg/gadget-service/api-helpers: Set default value for unset params"), but it doesn't work in this case these parameters are returned by the ExtraParams() method, hence they are not available when …
=> operators/ebpf: Fix missing parameter default value map-fetch-interval

Dockerfiles/gadget-builder.Dockerfile
This reduces the gadget-builder image by `1.3 GB`.
```bash
$ docker images -f reference=test
REPOSITORY   TAG                  IMAGE ID       CREATED                SIZE
test         bookworm-slim        bd8cc75cb312   51 seconds ago         1.1GB
test         base                 9776844636a0   About an 2 hours ago   2.43GB
```
Roughly were the sizes come from:
- `75MB`: `debian:bookworm-slim`
- `260MB`: `libc-dev lsb-release wget gnupg xz-utils software-properties-common make git`
- `470MB`: `clang-18 llvm-18 clang-format-18`
- `253MB`: Golang 1.24 tarball installation
This is a good base image IMO. And it can be taken to optimize the size even further if its needed by looking at specific files or more specific packages
ref https://github.com/inspektor-gadget/inspektor-gadget/issues/4345 …
=> gadget-builder: Switch to debian:bookworm-slim

pkg/params/params.go
Do not overwrite a param if it's already set on the destination map. This avoid issues when using gadget instance specs, as they params were being overwritten by the default values of the CLI, empty in many cases.
Fixes #3676 
Use the following manifest:
```yaml
apiVersion: 1
kind: instance-spec
image: trace_exec:main
paramValues:
operator.oci.annotate: wrong_annontation_should_break_the_gadget
```
```bash 
$ sudo ig run -f manifest.yaml
RUNTIME.CONTAINERNAME                             COMM                    PID        TID ARGS                         ERRO
```
Gadget runs fine, the annotation is not considered.
```bash
$ sudo ig run -f manifest.yaml
Error: initializing and preparing operators: instantiating operator "oci": annotation "wrong_annontation_should_break_the_gadget" must be …
```
=> params: Avoid overwritting params in CopyToMap()

pkg/container-hook/runtime-finder/finder.go
Added single line to point gadget to where runc is located
no change. But if you previously overwrote the RUNTIME_PATH variable for making k0s work, it should now work out fo the box
CI was run on my fork : please see https://github.com/entlein/inspektor-gadget/actions/runs/14821358374
=> Adding the path for gadget to find the runc of k0s in finder.go

pkg/kallsyms/kallsyms_test.go
Kallsyms test on symbol veth_init failed a lot, so it was disabled.
I believe this is due to using a function declared with "__init" because the memory holding the code can be lazily reclaimed when the kernel needs more memory,
This patch re-enables the test but uses a different symbol that does not use "__init".
Fixes: d25e2295d1e6 ("pkg/kallsyms: disable failing test")
Fixes: #4367
```
$ go test -exec sudo -v ./pkg/kallsyms/...
...
--- PASS: TestRealKAllSymsParsing (3.67s)
--- PASS: TestRealKAllSymsParsing/simple_symbol1 (0.46s)
--- PASS: TestRealKAllSymsParsing/simple_symbol2 (0.47s)
--- PASS: TestRealKAllSymsParsing/symbol_from_veth_kmod (0.49s)
--- PASS: TestRealKAllSymsParsing/symbol_from_netem_kmod (0.47s)
--- PASS: TestRealKAllSymsParsing/symbol_from_overlay_kmod (0.47s)
--- PASS: …
```
=> pkg/kallsyms: re-enable test for kernel module symbol

gadgets/trace_exec/test/unit/trace_exec_test.go
This PR introduces comprehensive unit tests for the `trace_exec` gadget, which verify its behavior under various scenarios such as executing simple commands, handling a large argument list, applying custom runner configurations (including user and group settings), and enforcing mount namespace filtering. The tests are implemented using a structured approach that leverages our internal testing utilities to simulate the gadget’s execution and capture resulting events for comparison.
These additions aim to improve the robustness of the gadget by ensuring that it appropriately processes command execution events, truncates argument lists when necessary, and correctly validates process credentials when custom configurations are provided. The test cases provide clear feedback on both successful …
=> Unit Tests for Trace Exec Gadget

pkg/container-hook/runtime-finder/finder.go
Adding the runtime paths of Bottlerocket OS (for both architectures)
https://bottlerocket.dev/
N/A
I have tested my fork with AWS nodes (AMD64 + Graviton ARM) running Bottlerocket OS 1.38.0.
=> Adding runc path of Bottlerocket OS

internal/version/version.go
Previously, when running gadgets using IG as a library, the version was not set. This leads to warning messages such as:
> WARN[0000] This gadget was built with ig v0.40.0 and it's being run
> with v0.0.0. Gadget could be incompatible
This patch detects when IG is used as a library and recovers the version of IG.
TODO
TODO
=> version: detect when IG is used as a library

gadgets/trace_dns/gadget.yaml, gadgets/trace_dns/program.bpf.c, gadgets/trace_dns/test/integration/trace_dns_test.go
As pointed out in the comment https://github.com/inspektor-gadget/inspektor-gadget/issues/3804#issuecomment-2551617018, we are missing `namesever` field. Also, in certain [troubleshooting steps](https://learn.microsoft.com/en-us/troubleshoot/azure/azure-kubernetes/connectivity/troubleshoot-dns-failures-across-an-aks-cluster-in-real-time#step-3-verify-the-health-of-the-upstream-dns-servers) in makes sense to be able to filter query/responses based on nameserver.
```
$ docker run --rm -it busybox sh
/ # nslookup google.com.
Server:         192.168.0.1
Address:        192.168.0.1:53
Non-authoritative answer:
Name:   google.com
Address: 142.250.181.206
Non-authoritative answer:
Name:   google.com
Address: 2a00:1450:4005:802::200e
/ # exit
→ docker run --rm -it busybox sh
/ # nslookup …
```
=> trace_dns: Add nameserver field

charts/gadget/templates/configmap.yaml, charts/gadget/values.yaml, cmd/kubectl-gadget/deploy.go, gadgets/bpfstats/README.mdx, gadgets/bpfstats/test/unit/bpfstats_test.go, pkg/config/gadgettracermanagerconfig/config.go, pkg/operators/ebpf/ebpf.go, pkg/operators/ebpf/stats.go, pkg/resources/manifests/deploy.yaml
The current implementation of the bpfstats gadget requires the daemon to be deployed with the --enable-bpfstats parameter to enable eBPF stats collection in the kernel. This UX is bad as users will need to enable it from the beginning, having a performance issue for all gadgets that are run, and by not being able to use this functionality on an existing IG deployment without having to restart it.
This PR changes the approach to enable the stats only when the bpfstats gadget is run, which is more practical as users don't need to change any configuration at deploy time and the stats collection is only enabled while the bpfstats gadget runs.
By changing this, we also fix an issue where stats collection wasn't disabled after running Inspektor Gadget.
Ref #4402
=> gadgets/bpfstats: Do not require --enable-bpfstats

.github/workflows/inspektor-gadget.yml, tools/store-test-reports.sh
It seems storing test reports was broken as part of https://github.com/inspektor-gadget/inspektor-gadget/pull/4157. It seems we were missing some error handling which resulted in broken file being committed. Also, this can be confirmed by https://github.com/inspektor-gadget/ig-test-reports since no new reports have been published. 
Fixes: bd82e6199bafa2d8faebd86e145a7e647f0d42d0
- Reports are now pushed fine: https://github.com/inspektor-gadget/inspektor-gadget/actions/runs/14996739819/job/42134141907#step:4:18
- https://github.com/inspektor-gadget/ig-test-reports/commits/main/
=> ci: Fix storing test reports

docs/reference/manifests.mdx, docs/reference/run.mdx, docs/spec/operators/filter.md
When specifying filters which contain special characters either on a shell or in a YAML document, it's easy to run into quoting issues. For example, specifying proc.comm~'^bash$' in a YAML document results in the single quotes being passed down to IG which in turn causes unexpected filtering behavior in user space.
Ensure the content makes sense and the docs are rendered correctly.
I ran
```
make docs
npm install docusaurus
npm run dev
```
under https://github.com/inspektor-gadget/website and ensured the documents render fine.
=> Document filter quoting

docs/reference/install-kubernetes.md
It seems the URL for OCI helm chart was incorrect. This PR fixes the URL for the OCI helm chart.
```
$ CHART_VERSION=$(curl -s https://api.github.com/repos/inspektor-gadget/inspektor-gadget/releases/latest | jq -r .tag_name | sed 's/^v//')
$ helm install gadget --namespace=gadget --create-namespace oci://ghcr.io/inspektor-gadget/inspektor-gadget/charts/gadget --version=$CHART_VERSION
Pulled: ghcr.io/inspektor-gadget/inspektor-gadget/charts/gadget:0.40.0
Digest: sha256:2518a01a989384a013a2b2528276a5c7db0e345a0cd19fdc49c8e8350e3559c4
W0512 17:55:03.989090  411655 warnings.go:70] spec.template.metadata.annotations[container.apparmor.security.beta.kubernetes.io/gadget]: deprecated since v1.30; use the "appArmorProfile" field instead
W0512 17:55:03.989135  411655 warnings.go:70] …
```
=> docs: Fix OCI helm chart URL

Dockerfiles/ig-tests.Dockerfile.dockerignore, cmd/common/version.go, examples/container-hook/Dockerfile.dockerignore, examples/container-hook/main.go, examples/kube-container-collection/Dockerfile.dockerignore, examples/kube-container-collection/main.go, gadget-container/gadgettracermanager/main.go, internal/version/version.go, internal/version/version_test.go, pkg/container-collection/containers.go, pkg/container-collection/k8s.go, pkg/container-collection/options.go, pkg/container-collection/podinformer.go, pkg/gadget-service/store/k8s-configmap-store/configmapstore.go, pkg/k8sutil/client.go, pkg/operators/common/kubeinventorycache.go, pkg/operators/oci-handler/oci.go
When investigating high network traffic to the Kubernetes API server, it is useful to have the user agent set with relevent information to find out where the requests are coming from.
No changes in the configuration or installation.
Users of Kubernetes can use the [Audit Logs](https://kubernetes.io/docs/tasks/debug/debug-cluster/audit/) to see the user agent in the requests to the API server.
With internal executables:
```
$ sudo ./ig version 
v0.40.0-61-g68cce8aa6-dirty
$ sudo ./ig version -v
v0.40.0-61-g68cce8aa6-dirty
DEBU[0000] Inspektor Gadget User Agent: ig/v0.40.0-61-g68cce8aa6-dirty (linux/amd64) kubernetes/v0.33.0 
```
```
$ kubectl logs -n gadget gadget-9jsh2|head -2
time="2025-05-15T12:26:46Z" level=info msg="Inspektor Gadget version: 0.40.0-61-g5eb92cb1a-dirty" …
```
=> k8s.io/client-go: add user agent

docs/reference/run.mdx
Some filter examples we have in the docs use outdated fields.
Check that the new filters are correct.
I used the modified filters locally using `ig` and ensured they work.
=> Update fields in filter examples

cmd/common/image/inspect.go, cmd/common/utils/flags.go, docs/reference/images.md, go.mod, go.sum
Currently, the output of `image inspect` command is very large and difficult to directly comprehend.
This PR adds improved formatting options to the command and improves the UX.
```bash
$ sudo ./ig image inspect trace_dns:latest --extra-info="ebpf.programs" --jsonpath="[0].Section" 
[
"socket1"
]
$ sudo ./ig image inspect trace_dns:latest --extra-info="ebpf.sections" --jsonpath="[2]" 
[
".text"
]
$ sudo ./ig image inspect trace_dns:latest --extra-info="ebpf.flowchart" --jsonpath="[1]"
Error: extra info "ebpf.flowchart" is not JSON
```
Part of #3387
=> inspect: improves utility and command ux

docs/gadget-devel/program-types.md, docs/gadgets/profile_cpu.mdx, gadgets/Makefile, gadgets/profile_cpu/README.md, gadgets/profile_cpu/README.mdx, gadgets/profile_cpu/artifacthub-pkg.yml, gadgets/profile_cpu/gadget.yaml, gadgets/profile_cpu/program.bpf.c, pkg/operators/ebpf/attach.go, pkg/operators/ebpf/ebpf.go
While converting the gadget was pretty straightforward, the actual program type allows many different settings to be applied. We need to discuss what and how we want to support those. I think it's wrong to just hardcode the values for our specific use-case (but I'm not familiar enough with the actual capabilities to decide).
The biggest question is: should we support just forwarding raw values (integers) from the configuration or abstract it with `count_sw_cpu_clock` etc. to always use the values defined in the `unix` package (for compatibility reasons)?
~~Also, this will make more sense after the addition of `flush-on-stop` in #4089.~~
The gadget now uses `flush-on-stop`, so it currently also needs `--map-fetch-interval 0s` set.
Fixes #3001
=> gadgets: port profile_cpu to image based gadget

gadgets/trace_bind/test/unit/trace_bind_test.go
This PR introduces a new set of unit tests for the `trace_bind` gadget in the Inspektor Gadget project. The tests are designed to validate the correct event capturing behavior of the gadget when various socket binding operations are performed. Specifically, the tests cover combinations of IPv4 and IPv6 with both TCP and UDP protocols, using both fixed and ephemeral ports.
Each test verifies that the captured bind event contains the expected address, protocol, and port (non-zero for ephemeral ports). The tests utilize the netcat (`nc`) utility to simulate socket bindings and ensure that the gadget emits one event per bind operation, with accurate protocol and address information.
an effort towards #3835 
To validate this PR, reviewers can run the unit tests using the following command from …
=> Add Trace Bind Unit Tetsts

gadgets/trace_capabilities/test/unit/trace_capabilities_test.go
This PR introduces a new set of unit tests for the `trace_capabilities` gadget to validate its ability to detect capability-related syscalls. These tests simulate various syscalls (`unshare`, `socket`, `chroot`, `nice`) that require specific Linux capabilities (`CAP_SYS_ADMIN`, `CAP_NET_RAW`, `CAP_SYS_CHROOT`, `CAP_SYS_NICE`) and assert that the gadget captures the corresponding events with the correct capability.
Each test case uses a minimal syscall invocation to trigger the gadget and then checks that exactly one event is captured, with the expected `Cap` field value. The tests are written using the standard Go `testing` package, along with helper utilities from `inspektor-gadget` for setting up the test environment and gadget runner.
an effort towards #3835 
To validate this PR, …
=> Unit Tests for Trace Capabilities Gadget

cmd/common/image/inspect.go, docs/reference/images.md
This PR adds additional info regarding datasources and their fields in the inspect subcommand.
```
$ sudo ./ig image inspect fsnotify --show-datasources
[
{
"name": "fsnotify",
"type": 1,
"fields": [
{
"name": "timestamp_raw",
"fullName": "timestamp_raw",
"size": 8,
"flags": 20,
"kind": 9,
"tags": [
"type:gadget_timestamp",
"type:__u64",
"type:unsigned long long",
"name:timestamp_raw",
"src:ebpf"
...
$ sudo ./ig image inspect advise_seccomp:latest --show-datasources -o yaml 
- annotations:
cli.supported-output-modes: none
ebpf.map.flush-on-stop: "true"
fetch-count: "0"
fetch-interval: 1s
fields:
- annotations:
columns.alignment: right
columns.ellipsis: end
columns.hidden: "true"
columns.width: "12"
description: Mount namespace ID
flags: 20
...
```
Part of #3387
=> inspect: adds datasources and fields

examples/container-hook/main.go, examples/kube-container-collection/main.go, gadgets/ci/datasource-containers/test/integration/datasource_test.go, integration/ig/non-k8s/list_containers_test.go, integration/k8s/enrichment_pod_label_test.go, integration/k8s/list_containers_test.go, pkg/container-collection/containers.go, pkg/container-collection/ocispec.go, pkg/container-collection/options.go, pkg/container-hook/tracer.go, pkg/container-hook/tracer_test.go, pkg/gadgettracermanager/gadgettracermanager.go, pkg/operators/common/containers-publisher.go
This PR is a first step for #4458.
The container-collection package detects when the container runtime starts a new container and reads the oci config (config.json from the container runtime spec). This config is used internally in the container-collection package for two purposes:
1. Look up the mount for the Kubernetes ServiceAccount token volume to distinguish several containers from the same pod.
2. Look up the annotations for Kubernetes enrichment (pod name, etc.)
This patch makes the config available in the containers data source as a string. It is now unmarshalled partially only when needed.
Before this patch, the config was completely unmarshalled using the opencontainers/runtime-spec package v1.2.1 (version specified in go.mod): …
=> container-collection: publish oci config as a string

cmd/kubectl-gadget/deploy.go
The legacy Prometheus implementation added the scrape annotations to make it possible to automatically scrap metrics
when using the service discovery on Prometheus. The port's value was hardcoded to 2223, so it doesn't work with the new
--otel-metrics-listen-address parameter.
Signed-off-by: ghinks <ghinks@yahoo.com>
```
=> deploy: Update prometheus annotation according to --otel-metrics-listen-address

pkg/testing/ig/ig.go
Changing the output mode will be needed by gadgets outputting a custom format like the `advise` category of gadgets.
This PR is a requirement for https://github.com/inspektor-gadget/inspektor-gadget/pull/4191
=> testing: Add WithOutputMode

pkg/gadget-context/gadget-context.go, pkg/runtime/grpc/oci.go, pkg/runtime/runtime.go
Before this PR both code paths listened on the same channel. So when a Ctrl+C comes in we do the two things in parallel:
1. Close all operators on the client side
2. Notify server side to close all operators
As an example problems always occur when one is using the `ebpf.map.flush-on-stop` annotation:
1. We are closing all operators on the client side. This is almost guaranteed to execute first and faster (no grpc communication, etc..)
2. We are notifying the server side that the gadget should stop
3. `ebpf.map.flush-on-stop` is seen and the map and events are flushed now to the client
4. Events are received by the client, but all operators are already stopped -> No further processing is done
5. The local CLI operator is still printing these though, since it doesn't do anything in its …
=> GadgetContext: Close local operators after remote operators are all closed

pkg/operators/combiner/combiner.go, pkg/operators/ebpf/ebpf.go
This combination only happens for the advise_networkpolicy gadget. There we have an array datasource and only want to get a packet at the end of the gadget, when it gets cancled/stopped.
This is done through setting count and interval to 0, while having flush-on-stop set to true
=> combiner: Disable timeout if interval and count is zero

pkg/gadget-service/api/helpers.go, pkg/operators/filter/filter_test.go, pkg/params/params.go, pkg/params/params_test.go
This allows strings to contain escaped commas (e.g. `abc\,def,ghi`) that are not considered delimiters (leading to `["abc,def", "ghi"` instead of `["abc\", "def", ghi"]`). Escape characters are only removed if used with a legal character (comma and backslash), and otherwise kept as is.
I also modified the already existing code in the api package to behave the same way (before it would always remove escape characters). I deliberately chose to duplicate code here to keep both packages fully self-contained.
This was reported as bug on [slack](https://kubernetes.slack.com/archives/CSYL75LF6/p1747680905544569).
=> pkg/params: allow escaping comma characters for string slices

cmd/common/image/build.go, gadgets/Makefile
- Move the pulling logic to a different step on the makefile to avoid pulling the gadget builder for each gadget.
- Fix a bug found while trying the above 
0. Be sure you have the latest gadget-builder image available:
```bash 
$ docker pull ghcr.io/inspektor-gadget/gadget-builder:main
main: Pulling from inspektor-gadget/gadget-builder
Digest: sha256:dac71c0de0d83ecc8e7785688548fc795a1e8c374e4dfa2827fe982dd99f8584
Status: Image is up to date for ghcr.io/inspektor-gadget/gadget-builder:main
ghcr.io/inspektor-gadget/gadget-builder:main
```
Building with a single core on my machine takes around 2 minutes 
```bash
$ time make -C gadgets
...
real    1m52,879s
user    0m0,411s
sys     0m0,458s
```
Building with a single core only takes around 1m20s.
```bash 
$ time make -C gadgets
real …
```
=> ci: Improve gadget building time 

pkg/gadget-service/store/k8s-configmap-store/configmapstore.go, pkg/operators/localmanager/localmanager.go
"ig run --enrich-with-k8s-apiserver" requires that $NODE_NAME is set. This patch ensures that nodeName is initialized correctly.
Without this patch, the function getPodByCgroups (which allows to distinguish different containers in a single pod) will not be able to fetch only the pods for the current node. The kube-apiserver will receive requests with this URL:
/api/v1/pods?fieldSelector=spec.nodeName%3D
On clusters with many nodes, this was a waste of resources.
=> ig, ig-k8s: ensure that $NODE_NAME is set

pkg/container-collection/ocispec.go, pkg/container-collection/options.go
When ig fails to get the OCI config, the error messages were confusing:
```
WARN[0001] kubernetes enricher: failed to get source mounts for container 0cae3a07a7f140e770c415d421d7ff641b46ca2bff898e2226d8069e6e086e5d: unexpected end of JSON input
WARN[0001] kubernetes enricher: failed to get source mounts for container 6a01354d1e6a0d7902b8cda9f3b15ab982d4915c62172a6ebecc197aa0131445: unexpected end of JSON input
WARN[0001] kubernetes enricher: failed to get source mounts for container 9b30e0412a63f36fbd959ffe913d8618b1bfec555cc9d322904991e723e20cae: unexpected end of JSON input
```
To reproduce:
```
$ minikube cp ig /bin/ig
$ minikube ssh sudo chmod +x /bin/ig
$ minikube ssh "sudo NODE_NAME=minikube-docker ig run trace_exec:main --enrich-with-k8s-apiserver …
```
=> container-collection: improve error messages

pkg/container-collection/k8s.go
Initial K8s containers set the PodLabels directly. This changed in https://github.com/inspektor-gadget/inspektor-gadget/pull/4237 where the PodLabels ***has to be set*** through the Method `SetPodLabels`, so it updates the `podLabelsAsString` which actually gets written to the events
Fixes: 8647f0e04eb51d15673325791de22f8324a436d9
=> container-collection/k8s: Set PodLabels with the method

gadgets/traceloop/go/program.go, wasmapi/go/datasource.go
Data source "containers" has a field EventType with the following possible values:
- CREATED
- DELETED
The maximum length is 7 characters. However, I am planning do add a new value, so the maximum length will increase.
This patch defines a constant for the maximum length with some spare room to ease future compatibility.
See also: https://github.com/inspektor-gadget/inspektor-gadget/pull/4458#discussion_r2086612875
Fixes: 3690cd4a066c ("gadgets: Convert traceloop to image-based gadgets.")
cc @eiffel-fl
=> wasmapi/go: define constants for "containers" datasource

cmd/common/oci.go, docs/gadgets/advise_networkpolicy.mdx, gadgets/Makefile, gadgets/advise_networkpolicy/README.md, gadgets/advise_networkpolicy/README.mdx, gadgets/advise_networkpolicy/artifacthub-pkg.yml, gadgets/advise_networkpolicy/gadget.yaml, gadgets/advise_networkpolicy/program.bpf.c, gadgets/advise_networkpolicy/test/integration/advise_networkpolicy_test.go, pkg/operators/generate_networkpolicy/generate_networkpolicy.go, pkg/operators/generate_networkpolicy/generate_networkpolicy_op.go
This PR adds the `advise_networkpolicy` gadget as an image-based gadget
The events are getting collected by a specific new operator, which has to be explicitly enabled. Anyway it is only useful to generate network policies
I tested with the Guide i created in `README.mdx`. Both the builtin `advise network-policy` and this new `run advise_networkpolicy` produced the same yaml.
Create test
Cherry-picked commands from other open PRs:
- https://github.com/inspektor-gadget/inspektor-gadget/pull/4168
- https://github.com/inspektor-gadget/inspektor-gadget/pull/4169
- https://github.com/inspektor-gadget/inspektor-gadget/pull/4396
- https://github.com/inspektor-gadget/inspektor-gadget/pull/4493
- https://github.com/inspektor-gadget/inspektor-gadget/pull/4492
- …
=> Add advise_networkpolicy as image based gadget

docs/gadgets/advise_networkpolicy.mdx
Fix link to ensure website builds fine.
Fixes: e9904075d92d ("Gadgets: Add advise_networkpolicy as ibg")
=> docs: Fix softlink for advise_networkpolicy

charts/gadget/templates/daemonset.yaml, pkg/resources/manifests/deploy.yaml
The daemon set currently has:
- an optional liveness probe controlled by the flag --liveness-probe
- a mandatory readiness probe, see commit 1af4130f59bc ("cmd/kubect-gadget: Add readiness probe")
When ig is slow to start, it can easily crash loop. It can be slow on large clusters with slow kube-apiservers to reply to the initial requests.
This patch adds a startup probe to wait up to 1 minute to initialize. Kubernetes will mark the pod as ready sooner if the initialization happens faster.
Both options are supported:
- kubectl-gadget deploy
- Helm charts
=> daemonset: add startup probe

docs/reference/export-metrics.mdx
Fix typo in docs/reference/export-metrics
=> docs/reference/export-metrics: Fix typo

gadgets/trace_exec/test/unit/trace_exec_test.go
For the trace exec unit tests, this commit cleans up the resources being used by the test process.
=> gadgets/trace_exec: cleaned up test process in unit tests

gadgets/trace_exec/gadget.yaml, gadgets/trace_exec/program.bpf.c
Fixes #4495
```
RUNTIME.CONTAINERNAME                                                                     COMM                    PID        TID TTY_INDEX   ARGS                                                      ERROR
happy_jackson                                                                             utempter              27564      27564 0                                                                          
happy_jackson                                                                             groups                27565      27565 1           /usr/bin/groups                                                
happy_jackson                                                                             locale-check          27566      27566 1           /usr/bin/locale-check …
```
=> Add tty field

gadgets/audit_seccomp/test/unit/audit_seccomp_test.go, gadgets/deadlock/test/unit/deadlock_test.go, gadgets/profile_blockio/test/unit/profile_blockio_test.go, gadgets/profile_cpu/test/unit/profile_cpu_test.go, gadgets/profile_qdisc_latency/test/unit/profile_qdisc_latency_test.go, gadgets/profile_tcprtt/test/unit/profile_tcprtt_test.go, gadgets/snapshot_socket/test/unit/snapshot_socket_test.go, gadgets/testing/testing.go, gadgets/top_blockio/test/unit/top_blockio_test.go, gadgets/top_process/test/unit/top_process_test.go, gadgets/top_tcp/test/unit/top_tcp_test.go, gadgets/trace_dns/test/unit/trace_dns_test.go, gadgets/trace_fsslower/test/unit/trace_fsslower_test.go, gadgets/trace_lsm/test/unit/trace_lsm_test.go, gadgets/trace_malloc/test/unit/trace_malloc_test.go, gadgets/trace_mount/test/unit/trace_mount_test.go, gadgets/trace_oomkill/test/unit/trace_oomkill_test.go, gadgets/trace_sni/test/unit/trace_sni_test.go, gadgets/trace_tcpdrop/test/unit/trace_tcpdrop_test.go, gadgets/trace_tcpretrans/test/unit/trace_tcpretrans_test.go, gadgets/traceloop/test/unit/traceloop_test.go
Add dummy unit tests to verify that at least those gadgets are running fine on different kernel versions. For sure, we need to extend them later on to verify the data provided by the gadget.
=> gadgets: Add dummy unit tests for all gadgets

.github/workflows/inspektor-gadget.yml, charts/gadget/templates/configmap.yaml, charts/gadget/values.yaml, pkg/resources/manifests/deploy.yaml
The helm installation keeps on failing with gadget-namespace not set. This change ensure we have the default namespace set. Also, it adds a job to test helm charts installtion to avoid such issues in future:
```
time="2025-06-12T10:45:31Z" level=info msg="Starting Pod controller"
time="2025-06-12T10:45:31Z" level=info msg="gadget tracermgr set in kubemanager"
time="2025-06-12T10:45:31Z" level=info msg="Serving on gRPC socket /run/gadgettracermanager.socket"
time="2025-06-12T10:45:31Z" level=fatal msg="gadget namespace must not be empty"
```
Fixes 1dcced3cc2f9b534f6f4a8d7c1da09af315c7460
Failing run on fork: https://github.com/mqasimsarfraz/inspektor-gadget/actions/runs/15608382968/job/43963570152#step:9:182
=> charts: Add default gadget namespace

gadgets/ci/datasource-containers/go/program.go, gadgets/ci/datasource-containers/test/integration/datasource_test.go, pkg/container-collection/container-collection.go, pkg/container-collection/options.go, pkg/container-collection/pubsub.go, pkg/container-hook/tracer.go, pkg/operators/kubemanager/kubemanager.go, pkg/operators/localmanager/localmanager.go, wasmapi/go/datasource.go
PreCreateContainer events happen before the container is created and include the OCI config. The event is included in the "containers" datasource, so gadgets have an opportunity to inspect the container id and container config.
The pid, namespaces and other fields are not available since they will be known only after the container is created.
---
This is part of #4458.
This patch does not allow gadgets to modify the container config yet. I intend to introduce that in a future PR.
```
$ sudo ig list-containers -w
...
2025-05-27T17:30:22… PRECREATE                      3888fa4ac0652b4…                                       0                                               1970-01-01T01:00:00.000000000+01:00
2025-05-27T17:30:22… CREATED    docker              3888fa4ac0652b4… keen_cartwright …
```
=> container-hook: introduce PreCreateContainer events

pkg/operators/combiner/combiner.go, pkg/operators/process/process.go
Array datasources need the the count and interval annotations for the combiner to work fine.
This issue was breaking the bpfstats and top_process gadgets when the combiner operator was used: in gadgetctl and kubect-gadget.
Fixes: f9febfbec8d4 ("combiner: Disable timeout if interval and count is zero")
---
Another option is to update the combiner to suppose the count annotation is 0 if empty.
=> operators/ebpf: Add missing annotations to ds

gadgets/bpfstats/test/unit/bpfstats_test.go, pkg/datasource/data.go, pkg/datasource/field.go, pkg/operators/ebpf/stats.go, pkg/operators/formatters/formatters.go, pkg/operators/process/process.go
Fixes https://github.com/inspektor-gadget/inspektor-gadget/issues/4321 (bpfstats/runtime and bpfstats/mapmemory) and same for top_process/memoryRSS, top_process/memoryVirtual.
```bash
GADGETID GADGETNAME       GADGETIMAGE      PROG… PROGNAME         PROGTYPE            RUNTIME    RUNCOUNT   MAPMEMORY MAP… COMMS           PIDS
2 hid_tail_call    Tracing                   0           0        8576    1
5                  CGroupDevice              0           0           0    0 systemd         1
6                  CGroupSKB                 0           0           0    0 systemd         1
7                  CGroupSKB                 0           0           0    0 systemd         1
8                  CGroupDevice              0           0           0    0 systemd         1
```
```bash …
```
=> bpfstats/top_process: Provide human readable format for bytes and duration fields

pkg/k8sutil/client.go
I found this issue by mistake when trying to run ig within a node-shell-pod and missed the `--kubeconfig` flag.
Setup the env to reproduce it:
```bash
$ kubectl node-shell aks-nodepool-41788306-vmss000002
spawning "nsenter-llpuop" on "aks-nodepool-41788306-vmss000002"
If you don't see a command prompt, try pressing enter.
root@aks-nodepool-41788306-vmss000002:/# export NODE_NAME=aks-nodepool-41788306-vmss000002
```
```bash
$ ig run trace_dns  --enrich-with-k8s-apiserver
[signal SIGSEGV: segmentation violation code=0x1 addr=0x1a8 pc=0x1c34557]
github.com/inspektor-gadget/inspektor-gadget/pkg/k8sutil.NewKubeConfig({0x0?, 0x10?}, {0x33aefe1, 0x2d}) …
```
=> pkg/k8sutil/client: Ensure config is there before using it

pkg/datasource/expr/expr.go, pkg/datasource/expr/expr_test.go
This improves performance of the expr-lang support for datasources, reducing cpu time by roughly 97%.
This is achieved by simplifying the way that fields of datasources are accessed and taking the `Data` object directly as environment.
Thanks to @alban for making me aware that the speed was not that great before by comparing it to the gval package.
```text
$ benchstat old.bench new.bench
goos: linux
goarch: arm64
pkg: github.com/inspektor-gadget/inspektor-gadget/pkg/datasource/expr
│   old.bench   │              new.bench              │
│    sec/op     │   sec/op     vs base                │
Expression/string_match_positive-4             2845.50n ± 3%   95.81n ± 1%  -96.63% (p=0.000 n=10)
Expression/string_match_negative-4             2836.00n ± 0%   95.29n ± 1%  -96.64% (p=0.000 n=10) …
```
=> pkg/datasource/expr: improve performance

pkg/container-hook/tracer.go, pkg/kallsyms/symscache/symscache.go, pkg/kfilefields/tracer.go, pkg/socketenricher/tracer.go
Introduce a new package pkg/kallsyms/cache used by:
- kfilefield
- container-hook
- kfilefields
The cost of loading many symbols at once is lower than loading few symbols multiple times for multiple ebpf collections. This is because most of the cpu time is used for reading /proc/kallsyms in the kernel function module_get_kallsym. So it is better to read /proc/kallsyms only one time.
https://github.com/torvalds/linux/blob/v6.15/kernel/module/kallsyms.c#L376
The cache package provides two separate functions:
- RegisterSymbolsFromSpec: to be called from init()
- PopulateKallsymsCache: to be called just before loading your ebpf collection
In this way, different users of the cache don't have to collaborate to collect the symbols they use.
This is a follow up to #4652.
Supersedes #4625
This …
=> kallsyms/cache: preload kallsyms that cilium/ebpf will need

.github/actions/run-integration-tests/action.yml, Makefile, charts/README.md, charts/gadget/templates/_helpers.tpl, charts/gadget/templates/configmap.yaml, charts/gadget/templates/daemonset.yaml, charts/gadget/values.schema.json, charts/gadget/values.yaml, cmd/kubectl-gadget/deploy.go, cmd/kubectl-gadget/deploy_test.go, docs/reference/disallow-pulling.mdx, docs/reference/insecure-registries.mdx, docs/reference/verify-assets.mdx, pkg/config/gadgettracermanagerconfig/config.go, pkg/resources/manifests/deploy.yaml
Currently, we have to add flag for each operator configuration resulting in the need to 
- Implement support in deploy.go whenever global operator's param is added.
- Limitation not able to specify nested configuration like
```
operator:
otel-metrics:
otel-metrics-listen: true
exporters:
grpc:
exporter: otlp-grpc
endpoint: "127.0.0.1:4317"
insecure: true
temporality: delta
interval: 30s
```
Additionally, as mentioned in https://github.com/inspektor-gadget/inspektor-gadget/issues/3168, having the Kubernetes and operators configs together can create a lot of confusion. We can already see it in the kubectl gadget deploy flags where we have things like liveness-probe, image and image-pull-policy (which are related to the gadget k8s daemonset) alongside things like insecure-registries, …
=> deploy: Add support for config file

charts/gadget/templates/daemonset.yaml, cmd/kubectl-gadget/deploy.go, gadget-container/entrypoint/entrypoint.go, gadget-container/gadgettracermanager/main.go, pkg/resources/manifests/deploy.yaml
This change removes the deprecated environment variables as part of https://github.com/inspektor-gadget/inspektor-gadget/pull/3150 (part of release `v0.31.0`).
```bash
$ make minikube-deploy
$ kubectl logs -n gadget ds/gadget | grep "Config:"
time="2025-06-27T07:38:28Z" level=info msg="Config: hook-mode=auto"
time="2025-06-27T07:38:28Z" level=info msg="Config: fallback-pod-informer=true"
time="2025-06-27T07:38:29Z" level=info msg="Config: events-buffer-length=16384"
time="2025-06-27T07:38:29Z" level=info msg="Config: gadget-namespace=gadget"
```
###: custom:
```yaml
events-buffer-length: 1024
hook-mode: "fanotify+ebpf"
fallback-pod-informer: false
```
```bash
$ ./kubectl-gadget deploy --liveness-probe=true  --image-pull-policy=Never --daemon-config=daemon-config.yaml
$ kubectl rollout …
```
=> gadgettracermanager: Remove deprecated environment variables

pkg/runtime/runtime_test.go
This PR adds comprehensive unit tests for error handling in `runtime.go`, focusing on the `CombinedGadgetResult` and `combinedErrors` types. The tests ensure proper error aggregation, formatting, and unwrapping functionality across different scenarios.
Reviewers can validate this PR by:
1. Running the unit tests:
```bash
go test ./pkg/runtime -v -coverprofile=coverage.out
```
2. Examining the coverage report:
```bash
go tool cover -html=coverage.out
```
Added test cases covering:
```bash
=== RUN   TestCombinedGadgetResult
=== RUN   TestCombinedGadgetResult/empty_result
=== RUN   TestCombinedGadgetResult/result_with_errors
--- PASS: TestCombinedGadgetResult (0.00s)
--- PASS: TestCombinedGadgetResult/empty_result (0.00s)
--- PASS: TestCombinedGadgetResult/result_with_errors (0.00s)
=== RUN …
```
=> [Tests]: Add unit tests for runtime.go in pkg/runtime

charts/gadget/templates/daemonset.yaml, charts/gadget/values.yaml
This change allows users to add custom environment variables to the Inspektor Gadget DaemonSet through the Helm chart values configuration. Previously, users had no way to
inject additional environment variables into the gadget container without modifying the chart directly.
The implementation adds a new `extraEnv` field to the values.yaml file that accepts an array of environment variable definitions, supporting both simple key-value pairs and
references to secrets or config maps. This provides flexibility for users who need to configure IG using `INSPEKTOR_GADGET_` prefixed env vars.
```bash
cat > test-values.yaml << EOF
additionalEnv:
- name: TEST_VAR
value: "test_value"
- name: SECRET_VAR
valueFrom:
secretKeyRef:
name: my-secret
key: secret-key
EOF
```
helm template gadget bin/gadget …
=> charts: Add support for extra environment variables in DaemonSet

pkg/operators/ebpf/snapshotter.go
When running the snapshotter in a containers network namespace it can happen that the container, and therefore the namespace, was deleted right before entering it.
Instead of returning an error in this case, the program should just "skip" this now removed container and continue executing.
---
This came from analysing a spurious CI failure. Specifically 
```
2025-07-04T15:37:50.6845404Z === RUN   TestSnapshotSocket
2025-07-04T15:37:50.6845930Z     docker.go:161: Container "test-snapshot-socket" output:
2025-07-04T15:37:50.6846523Z     command.go:92: Run command(Run_snapshot_socket):
2025-07-04T15:37:50.6847132Z     command.go:94: Command returned(Run_snapshot_socket):
2025-07-04T15:37:50.6849121Z         Error: starting operators: starting operator "oci": starting operator "ebpf": running …
```
=> ops/snapshotter: Don't error out when the NS path doesn't exist

go.mod
Remove the unused gopacket reference. Also, I included a PR which requires us to use our fork of cilium/ebpf.
Fixes: 3ba4e5500d1ad3ac43c70a9af303a6ebed19d945
=> go: remove unused gopacket

cmd/common/image/build.go, cmd/common/image/helpers/Makefile.build
When building in-tree gadgets, the $IG_SOURCE_PATH environment variable is set to use the header files from the IG sources rather than the builder container. This was done correctly for the headers in include/gadget/ such as mntns.h, but not for vmlinux.h.
This patch adds support for using vmlinux.h from the IG sources.
The problem was found out after updating vmlinux.h in #4680: the new types were not available for in-tree gadgets.
=> in-tree gadget build: use intree vmlinux

charts/gadget/templates/daemonset.yaml, pkg/operators/wasm/wasm.go, pkg/resources/manifests/deploy.yaml
This change fixes the wasm-cache in Kubernetes cluster. We weren't able to catch this error since logging wasn't configured correctly, and it doesn't happen on minikube (It seems `/var/run `is writeable in minikube but not in AKS). 
Fixes: ef09eaea2e445e393dbbf413d47e2e7918312e08
```bash
$ make kubectl-gadget
$ ./kubectl-gadget deploy --image=ghcr.io/mqasimsarfraz/inspektor-gadget:qasim-k8s-wasm-cache
$ kubectl logs -n gadget ds/gadget
Found 3 pods, using pod/gadget-s95sg
time="2025-07-16T16:13:36Z" level=warning msg="failed to setup wasm compilation cache, skipping cache: create directory /var/run/ig/wasm-cache: mkdir /var/run/ig: read-only file system"
$ time ./kubectl-gadget run trace_dns:main --timeout 1 --pull always
K8S.NODE                            K8S.NAMESPACE …
```
=> charts: Add mount for wasm-cache

charts/gadget/templates/clusterrole.yaml, charts/gadget/templates/clusterrolebinding.yaml, charts/gadget/templates/configmap.yaml, charts/gadget/templates/role.yaml, charts/gadget/templates/rolebinding.yaml, charts/gadget/templates/serviceaccount.yaml, cmd/kubectl-gadget/undeploy.go, docs/reference/install-kubernetes.md, pkg/resources/manifests/deploy.yaml
The namespace could have been created by the user beforehand, or the user deployed other resources into the namespace created by Inspektor Gadget.
By default we should not remove the namespace in order to keep other resources running in the namespace.
Another idea was to only remove the namespace if we created it. But I think its still safer to assume that we do not want to delete the namespace by default.
With Helm deleting the namespace is not even possible, while a namespace can be created the namespace when deploying a chart with `--create-namespace`. But there is no way from the Helm side to remove the namespace. The user has to do that manually with `kubectl delete <ns>`
Fixes #2692 and fixes #4624
=> kubectl-gadget/undeploy: Don't remove namespace

gadgets/ci/image_inspect/test/unit/image_inspect_test.go, pkg/operators/oci-handler/oci.go, pkg/testing/gadgetrunner/gadgetrunner.go
The same global Ocihandler was used in all the tests, this caused issues as they this object is not thread safe. Add an explicit error to avoid the same instance being initialized multiple times and create different instances for the tests around.
Fixes #4661
=> tests: Fix usage of same ocihandler instance

.github/workflows/release.yml
Resolves #4728 
Prevent `latest` tag tagging for containers and gadgets in a bug release.
The `gh` command requires GITHUB_TOKEN 
Tested the command locally and on a workflow.
=> Fix: Update release workflow to handle latest tag tagging

cmd/common/oci.go, cmd/common/runwithspec_test.go, pkg/gadget-context/gadget-context.go, pkg/gadget-context/options.go, pkg/operators/operators.go, pkg/operators/sort/sort.go, pkg/runtime/grpc/oci.go, pkg/runtime/local/oci.go, pkg/runtime/runtime.go
Some operators are used both server-side and client-side. Soon, the ustack operator will also be able to operator client-side and server-side.
The IsClient method allows to detect which side they are running and behave differently. This is similar to IsRemoteCall to detect if we are on a server.
Command           | IsClient | IsRemoteCall |
------------------|----------|--------------|
ig run            | false    | false        |
ig image inspect  | false    | false        |
ig daemon         | false    | true         |
gadgetctl run     | true     | false (*)    |
*: Note that gadgetctl can display logs from the server, so gadgetctl will print both lines:
```
client=true, remote_call=false
client=false, remote_call=true
```
Depending if the log was generated from the server or the …
=> gadgetCtx: add IsClient

gadgets/trace_exec/test/integration/trace_exec_test.go
nsenter from util-linux 2.38.1 used to be able to set some options like setuid and setgid without changing namespaces:
```
docker run --rm -ti --name gcctest ghcr.io/inspektor-gadget/ci/gcc:test nsenter --setuid 1000 --setgid 1111 /usr/bin/sh -c '/bin/echo OK'
OK
```
But it is not possible anymore with nsenter from util-linux 2.41:
```
docker run --rm -ti --name gcclatest ghcr.io/inspektor-gadget/ci/gcc:latest nsenter --setuid 1000 --setgid 1111 /usr/bin/sh -c '/bin/echo OK'
nsenter: no namespace specified
```
This patch changes the command line to change the ipc namespace. It does not really change since I use the "$$" target process.
Fixes: #4810
We use the new nsenter since #4804.
After this, the workaround from #4811 should no longer be necessary.
Let's run the CI.
=> trace_exec: fix test for nsenter from util-linux 2.41

docs/gadget-devel/parameters.md, gadgets/top_process/gadget.yaml, pkg/gadget-context/context_test.go, pkg/gadget-context/gadget-context.go, pkg/gadget-context/run.go, pkg/operators/oci-handler/oci.go, pkg/operators/operators.go, pkg/runtime/runtime.go
This adds support to create custom parameters in the manifest (`gadget.yaml`) that can then apply parameters, annotations and such to the base metadata. This allows easy creation of presets of configurations by the gadget author.
It uses [template/text](https://pkg.go.dev/text/template) for template logic and has access to the configuration (gadget params) and the metadata itself.
If the gadget developer needs even more logic, the fallback should be to use a WASM module for it (#3449, #3475), which will of course require the gadget author to be familiar with Go (or whatever language is used to compile to WASM in that case).
```
$ ig run mygadget --help
Run a gadget
Usage:
ig run [flags]
Flags:
...
--mycustomparam string                   Description for the param [option1] (default …
```
=> operators/oci: allow adding custom parameters from gadget.yaml

gadgets/top_process/gadget.yaml, pkg/operators/cli/clioperator.go, pkg/operators/process/helpers.go, pkg/operators/process/process.go, pkg/process-helpers/processhelpers.go
This PR contains some UX improvements for the top_process gadget and aligns it more with the `top` command on Linux.
* rename columns for CLI output to match those from 'top' command
* add some maxWidths to shrink output size
* increase width/max-width of `comm` (as it's not limited as usually) and add ellipsis
* add priority, nice, cpuTime / cpuTimeStr and shared memory information
* add first-interval for a faster start (shows first results after 250ms instead of 3s)
RSS & SHM values are said to be "inaccurate" in the man pages, but those values are still being used by the tools.
```
Some of these values are inaccurate because of a kernel-
internal scalability optimization.  If accurate values are
required, use /proc/pid/smaps or /proc/pid/smaps_rollup
instead, which are much slower but …
```
=> top_process: UX improvements

gadgets/top_process/gadget.yaml, pkg/operators/process/process.go
This adds a `--count` parameter and matching annotation to the top_process gadget / process operator to limit the number of times the operator fetches the metrics.
Requires #3485 
Partially implements #4595 (missing "closing" the output, which is out of scope here).
=> top_process: add count annotation / parameter

Makefile, docs/api/grpc.md, docs/design/002-containerized-gadgets.md, docs/devel/ci.md, docs/devel/contributing.md
See individual commits for details.
Broken links detected by the CI:
https://github.com/inspektor-gadget/inspektor-gadget/actions/runs/17391500787/job/49365920204
```
ERROR: 2 dead links found in ./docs/design/002-containerized-gadgets.md !
[✖] #socketfilter-programs → Status: 404
[✖] #inspektor-gadget-api → Status: 404
ERROR: 1 dead links found in ./docs/api/grpc.md !
[✖] https://github.com/inspektor-gadget/inspektor-gadget/blob/main/pkg/gadgettracermanager/api/gadgettracermanager.proto → Status: 404
ERROR: 1 dead links found in ./docs/devel/ci.md !
[✖] https://github.com/inspektor-gadget/inspektor-gadget/blob/main/internal/benchmarks/benchmarks_test.go → Status: 404
```
Fixes: fb0115c86df5 ("design: Add containerized gadgets design doc")
Fixes: 3e9f17e9d010 ("gadget-container: Use …
=> docs: fix various broken links

pkg/container-utils/testutils/k8s.go
There seems to be an update to the `kubectl delete` command which now includes the namespace in the output string.
This PR makes that optional, since we should support both versions.
```
Error:      	Not equal: 
expected: "pod \"test-advise-networkpolicy-client\" deleted\n"
actual  : "pod \"test-advise-networkpolicy-client\" deleted from test-advise-networkpolicy-6403532841951297483 namespace\n"
Diff:
--- Expected
+++ Actual
@@ -1,2 +1,2 @@
-pod "test-advise-networkpolicy-client" deleted
+pod "test-advise-networkpolicy-client" deleted from test-advise-networkpolicy-6403532841951297483 namespace
Test:       	TestAdviseNetworkpolicyGadget
Messages:   	output didn't match the expected string
```
=> deletePodCommand: Add regex to optionally include ns

cmd/common/oci.go, cmd/ig/containers/containers.go, cmd/ig/utils/flags.go, docs/reference/run.mdx, docs/spec/operators/kubemanager.md, docs/spec/operators/localmanager.md, gadgets/Makefile, gadgets/ci/container_filtering/program.bpf.c, gadgets/ci/container_filtering/test/integration/container_filtering_test.go, integration/k8s/list_containers_test.go, pkg/gadget-context/run.go, pkg/gadget-service/api-helpers/apihelpers.go, pkg/gadget-service/api/api.pb.go, pkg/gadget-service/api/api.proto, pkg/operators/common/container-selector.go, pkg/operators/kubemanager/kubemanager.go, pkg/operators/localmanager/localmanager.go, pkg/params/params.go, pkg/params/params_test.go
This change allows filtering by k8s resources in `ig`. Given `ig` works in the context of (container) runtime and `kubectl-gadget` in the context of Kubernetes, the idea here is to define fully qualified names for runtime/k8s so:
- `--runtime-containername`
- `--k8s-containername`
- `--k8s-podname`
- `--k8s-namespace`
- `--k8s-selector` 
- `--k8s-containername`
- `--k8s-podname`
- `--k8s-namespace`
- `--k8s-selector` 
- `--runtime-containername`
For ease of use / backward compatibility, we will be creating aliases for k8s specifix params in `kubectl-gadget` and runtime specific params in `ig` so complete list:
- `--runtime-containername` or `--containername` or `c`
- `--k8s-containername`
- `--k8s-podname`
- `--k8s-namespace`
- `--k8s-selector` 
- `--k8s-containername` or …
=> localmanager/kubemanager: Allow runtime/k8s filtering

.github/workflows/mlc_config.json
We use the GitHub Action markdown-link-check to check if links in markdown documents are still valid.
However, the underlying tool does not support URLs with %23. I reported the bug (https://github.com/tcort/link-check/issues/105). For now, this patch disables the test on that URL.
Symptoms:
```
ERROR: 1 dead links found in ./README.md !
[✖] https://img.shields.io/badge/slack-%23inspektor--gadget-brightgreen.svg?logo=slack → Status: 404
```
Let's check the CI...
=> docs: ignore link unsupported by github-action-markdown-link-check

.github/workflows/check-artifacthub-tags.yml, .github/workflows/check-links.yml, .github/workflows/scorecard-analysis.yml
Before this patch, forks would run daily github actions to check the links, check the artifact hub tags and run the scorecard analysis.
Most of the time, forks are just there to make pull requests. The main branch is unused and becomes stale. It is a waste of resources to run daily checks on it.
This patch disables these 3 cron jobs. Other cron jobs are left unchanged because they are already disabled by default (unless the fork configures environment variables to enable them).
=> github actions: disable some cron jobs on forks

pkg/process-helpers/processhelpers.go
Make it clearer what is stored in the variable.
Ref https://github.com/inspektor-gadget/inspektor-gadget/pull/4730/commits/e8af8b3813ec4669687002f723359f57157ac576#r2329524663
=> process-helpers: Put KB in variable name

pkg/operators/ustack/ustack.go, pkg/operators/ustack/ustack_linux.go, pkg/operators/ustack/ustack_others.go, pkg/symbolizer/symbolizer.go, pkg/symbolizer/symtab_linux.go, pkg/symbolizer/symtab_others.go
Before this patch, the ustack and symbolizer packages only build on Linux. In preparation for making the ustack operator work client-side, this patch moves part of the code in _linux.go files. It will make it easier for future patches.
Tested by adding the import in a cmd package:
```
+++ b/cmd/common/oci.go
+       _ "github.com/inspektor-gadget/inspektor-gadget/pkg/operators/ustack"
``` 
And running "make gadgetctl-all"
TODO, let's run the CI first.
=> ustack,symbolizer: refactor to build on different platform

pkg/symbolizer/symbolizer.go, pkg/symbolizer/symtab_linux.go
Before #4921:
|  | PIE | Non-PIE |
|---|---|---|
| C | ❌ | ✅ |
| Go | ❌ | ✅ |
After #4921, but before this patch:
|  | PIE | Non-PIE |
|---|---|---|
| C | ✅ | ✅ |
| Go | ❌ | ✅ |
After this patch:
|  | PIE | Non-PIE |
|---|---|---|
| C | ✅ | ✅ |
| Go | ✅ | ✅ |
To look up a symbol in the symbol table from its address, the correct formula is:
```
lookup_address := runtime_address - runtime_base_address + elf_base_address
```
Before this patch, the formula was only applied for PIE executable, and we had the following behaviour
- Usually fine with C non-PIE programs because C non-PIE programs have a elf_base_address of 0x400000 (unless chosen otherwise with compilation flag `-Wl,-Ttext=0x1234`) and the runtime_base_address is typically 0x400000 as well, so the two errors cancel out.
- Usually …
=> ustack: fix bias for Go PIE programs

gadgets/trace_exec/consts/consts.go, gadgets/trace_exec/go/program.go, gadgets/trace_exec/test/integration/trace_exec_test.go, gadgets/trace_exec/test/unit/trace_exec_test.go
The idea is to allow splitting back args into a []string that represents exactly the arguments (that might contain spaces) by using a different Unicode character that is also printable as a space.
Run the tracer with ig and see that the output remains the same.
Run the tracer with the Go API and split the args field with gadgets.ArgsSeparator
Works on my PC ;-p
The `args` field of the `trace_exec` gadget now uses the "non-breaking space" (unicode 00a0) character to join different arguments instead of the standard space (` `).
`trace_exec` users that parse and split the `args` field to get the list arguments list. 
Update the logic to use the "non-breaking space"  to split the field.
=> gadgets: trace_exec: use nbsp to join args

docs/gadgets/tcpdump.mdx, examples/go.mod, examples/go.sum, gadgets/Makefile, gadgets/tcpdump/README.md, gadgets/tcpdump/README.mdx, gadgets/tcpdump/gadget.yaml, gadgets/tcpdump/program.bpf.c, gadgets/tcpdump/test/integration/tcpdump_test.go, gadgets/tcpdump/test/unit/tcpdump_test.go, go.mod, go.sum, include/gadget/packetfilter.h, pkg/libpcap-compiler/cbpf.go, pkg/libpcap-compiler/ebpf.go, pkg/operators/cli/clioperator.go, pkg/operators/ebpf/ebpf.go, pkg/operators/ebpf/types.go
This adds support for generic packet filters compiled using libpcap (needs to present on the system).
Also introduces a new gadget `tcpdump` that allows capturing (filtered) packets on the system that can be written to pcap files.
```
$ cd gadgets/tcpdump
$ ig image build -t tcpdump:mine .
$ ig run --verify-image=false tcpdump:mine --pf "port 80" -o pcap-ng | tcpdump -nvr -
reading from file -, link-type EN10MB (Ethernet), snapshot length 65535
2025/06/06 13:00:45 failed to upload metrics: context deadline exceeded: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp 172.16.37.20:4317: connect: connection refused"
13:00:58.045870 IP (tos 0x0, ttl 64, id 9615, offset 0, flags [DF], proto TCP (6), length 60)
172.17.0.2.57098 > …
```
=> introduce generic packet filters and new gadget tcpdump

.github/workflows/check-artifacthub-tags.yml
Updated logic for filtering gadget names in `check-artifacthub-tags` workflow. Which checks for existence of offical and cncf flags set to true on images owned by inspektor-gadget.
Previously we were extracting gadget names from directory name. But to handle edge cases with naming convention, updating logic to extract names from artifacthub-pkg.yml file of each indivdual gadget.
The previous workflow will fail to validate the gadget `advise_networkpolicy`.
Which doesn't fit into prev filtering rule, with updated filtering logic - this gadget will also be validated correctly.
We need to discuss some kind of naming convention for gadget names to maintain consistency across gadgets.
This new edge case validation is done through [this …
=> Ref: Update filter-gadgets step logic in check-artifacthub-tags workflow

Makefile
It seems `minikube` changed table rendering and now we get following error when running `make minikube-deploy`:
```
Image in Minikube:
/home/qasim/work/cloud/github.com/inspektor-gadget/inspektor-gadget/bin/minikube/minikube-v1.37.0 image ls --format=table | grep "ghcr.io/inspektor-gadget/inspektor-gadget\s*|\s*main" || \
(echo "Image ghcr.io/inspektor-gadget/inspektor-gadget\s*|\s*main was not correctly loaded into Minikube" && false)
Image ghcr.io/inspektor-gadget/inspektor-gadget\s*|\s*main was not correctly loaded into Minikube
make: *** [Makefile:350: minikube-deploy] Error 1
```
```
|-------------------------------------------|----------|---------------|--------|
|                   Image                   |   Tag    |   Image ID    |  Size  | …
```
=> Makefile: Fix checking image in minikube
